### ISSUE TITLE
No boundaries set for cursor

### ISSUE THREAD

**Issue by bryo5363** [phetsims/calculus-grapher#10]
The cursor can be moved off of the page. Since there is no reset button, once the cursor is gone it is gone.

**Comment by amanda-phet** [comment]
We will definitely implement a boundary for the cursor (which will be called the "reference line").

**Comment by amanda-phet** [comment]
Unassigning and putting on hold until this sim is ported.

**Comment by veillette** [comment]
Although, we have not implement a cursor yet, (which we will refer to  as a  reference line for the html5 simulation) our DragListener has a DragBoundsProperty that allows it to remain within bounds. We will implement those on the reference line. We can therefore close this legacy issue.
