### ISSUE TITLE
Discontinuity display control in Preferences dialog

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#101]
This will be in the simulation tab of the preferences menu 

Let’s use two radio buttons with images (drawn in code) 

![image](https://user-images.githubusercontent.com/7633344/201947579-0a0e52ca-f8b0-4097-80fa-afa5964c792d.png)

**Comment by pixelzoom** [comment]
@amanda-phet @veillette ready for review.

The control currently looks like this in the _Simulation_ tab of the Preferences dialog. (Ignore the on/off switch above it, that's a work in progress for turning numerical values on/off.) I'm using the standard font size, as specified by `PreferencesDialog.CONTENT_FONT`.

<img width="735" alt="screenshot_1953" src="https://user-images.githubusercontent.com/3046552/202034672-ccc7ba13-1a56-4909-ad13-6f7e168c44e1.png">

This control appears in Studio with the following tandem name:
`calculusGrapher.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesPanels.simulationPreferencesPanel.simPreferences.discontinuitiesControl`.

Here's the Studio tree:

<img width="250" alt="screenshot_1956" src="https://user-images.githubusercontent.com/3046552/202035363-c9dee4c4-d460-4881-9aa5-adcb9d93a34f.png">

The associated Property is `connectDiscontinuitiesProperty`, and it has a boolean value. Here's how it looks in Studio:

<img width="640" alt="screenshot_1954" src="https://user-images.githubusercontent.com/3046552/202034983-89f52856-3bfc-4786-a217-865c3b994119.png">

The query parameter used to set the initial value of `connectDiscontinuitiesProperty` is defined in CalculusGrapherQueryParameters.ts like this:

```typescript
  // Whether to connect discontinuities with a dashed line (true) or leave a gap (false).
  connectDiscontinuities: {
    type: 'boolean',
    defaultValue: true,
    public: true
  }
```

Let me know what you'd like to change here.

**Comment by veillette** [comment]
THat looks good to me. I added the documentaion of the queryParameter in implementation-notes.md https://github.com/phetsims/calculus-grapher/commit/02369e37736d029427fde4ced7b4abe07b3a7be5

**Comment by veillette** [comment]
In the two commits above, I linked the visibility of connectDiscontinuitiesProperties to the discontinuousLinePlot and added  the property to  modelLinkables.

**Comment by veillette** [comment]
Assigning back to @amanda-phet  to review the work on  Discontinuity display control

**Comment by amanda-phet** [comment]
The names for things sound reasonable to me, but falseRadioButton and trueRadioButton weren't clear until you explained the connectDiscontinuitiesProperty. Could those radio buttons have different names? I understand why they are named as such, but on first glance they weren't as clear to me. I don't have a great idea though... 

I also would prefer that visually the two radio buttons are switched in their order, with `false` being the default state (for the query parameter as well as the radio button selection).

**Comment by veillette** [comment]
Assigning back to @pixelzoom to implement the suggestions above.

**Comment by pixelzoom** [comment]
> ... Could those radio buttons have different names? I understand why they are named as such, but on first glance they weren't as clear to me. I don't have a great idea though...

They can have any names you want :)  But I couldn't come up with anything better.  It's a boolean Property, and we typically name things based on their value, hence `falseRadioButton` and `trueRadioButton`.    We could change the value to a pair of descriptive names, but I'm at a loss for names ('connect' and ???).  So they will remain as-is until someone requests specific names.

> I also would prefer that visually the two radio buttons are switched in their order,

Done. Default state is shown below.

<img width="710" alt="screenshot_1978" src="https://user-images.githubusercontent.com/3046552/203425117-427e6840-50f2-4af3-a1ae-5ee6936e8454.png">

**Comment by pixelzoom** [comment]
@amanda-phet @veillette How about `discontinuitiesProperty` with values `'connected'` and `'gap'`. Would that be clearer?

**Comment by pixelzoom** [comment]
@amanda-phet @veillette How about `discontinuitiesProperty` with values `'gap'` and `'connected'`.   Or `gap` and `dashedLine`. Would that be clearer?

**Comment by pixelzoom** [comment]
@amanda-phet @veillette Some ideas for values other than `true` and `false`...

*  `'gap'` and `'connected'`
* `'gap'` and `'dashedLine'`
* 'noLine'` and `'dashedLine'`
 
Would any of those be clearer?

**Comment by amanda-phet** [comment]
>@amanda-phet @veillette How about discontinuitiesProperty with values 'gap' and 'connected'. Would that be clearer?

I actually think a boolean property is easiest to use as a query parameter, but in the studio tree something like connectedRadioButton and disconnectedRadioButton might be easier to understand. Is that OK, or should the value of the qp also be the name of the radio button?

**Comment by pixelzoom** [comment]
The name of the radio button typically matches the name of the query parameter value. But if you want to do something else, you're the designer.  And I don't feel strongly about it. 

We could also stick with `falseRadioButton` and `trueRadioButton`, and add `phetioDocumentation` (which I doubt that anyone will ever read).

**Comment by amanda-phet** [comment]
How about 'noLine' and 'dashedLine'. That seems clear to me! 

And the associated elements would be `noLineRadioButton` and `dashedLineRadioButton`, right?

**Comment by pixelzoom** [comment]
Yes, correct. I will make it so.

**Comment by pixelzoom** [comment]
Change requests completed in the above commit.  Back to @amanda-phet for review.

Summary of changes:

* The Preferences UI is unchanged.  It looks like this:

<img width="258" alt="screenshot_1982" src="https://user-images.githubusercontent.com/3046552/203431066-9a40fa3b-9847-4c41-9b62-aca5e89ade5d.png">

* Query parameter `connectDiscontinuities` now has values "noLine" (default) and "dashedLine".

* `connectDiscontinutiesProperty` looks like this in Studio:

<img width="597" alt="screenshot_1981" src="https://user-images.githubusercontent.com/3046552/203430916-a0d1d1c0-eff7-4a11-852d-13deb42c15ab.png">

* `discontinuitiesControl` looks like this in Studio:

<img width="285" alt="screenshot_1980" src="https://user-images.githubusercontent.com/3046552/203430701-6b3a649e-44a0-492f-b23b-cfaca1b725ab.png">

**Comment by amanda-phet** [comment]
Looks great to me. Thank you!

**Comment by pixelzoom** [comment]
👍🏻 closing.
