### ISSUE TITLE
Create a factory for curve buttons.

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#103]
The buttons will need to support the change in notation discussed in #98. 

![image](https://user-images.githubusercontent.com/7633344/201956209-7198ea09-289e-4ddc-96be-22061ea2df76.png)
![image](https://user-images.githubusercontent.com/7633344/201957278-44d9e89e-5ebf-49ac-9cbe-6a515997b965.png)
![image](https://user-images.githubusercontent.com/7633344/201957791-29dc9d29-284b-4e31-bb8b-aa191d3659bd.png)

**Comment by veillette** [comment]
See #63 for how to use them in the simulation

**Comment by pixelzoom** [comment]
I would start by using a horizontal colored line for all of these buttons. It will be a simpler implementation.  Then if that's not acceptable, consider adding different curves for each button icon.

**Comment by veillette** [comment]
The work in #98 is nearly completed. It led to a lot of changes to CurveLabelNode. The content of curveLabelNode automatically updates itself based on the derivativeNotationProperty and variableProperty.
The CurveButtonIcon should be composed of a curveLabelNode with an scenery/Path that takes an appropriate color.
We should think about how to deal with the change of bounds of the CurveLabelNode.

**Comment by veillette** [comment]
@pixelzoom will work on the GraphSetRadioButtons and we will work on the "PredictMode" Buttons in a separate issue.

**Comment by pixelzoom** [comment]
I addressed icons for the GraphSetRadioButtonGroup in https://github.com/phetsims/calculus-grapher/issues/106.  And icons for the f(x)/Predict buttons will presumably be addressed in https://github.com/phetsims/calculus-grapher/issues/100. So I'm going to close this issue.
