### ISSUE TITLE
Behavior of eraser button

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#105]
How should the eraser button behave when we're running a version that was saved via Studio?  Should erasing set all y values to zero (the default `initialY` of CurvePoint)?  Or should it restore the curve to what the instructional designer had saved? The latter would be difficult, maybe currently impossible, based on how PhET-io restores state and handles "reset all".

**Comment by amanda-phet** [comment]
Setting all y values to zero seems reasonable for this button. The user can always use reset-all to return to the state that was  saved via studio.

**Comment by pixelzoom** [comment]
@veillette Since this is the default behavior (as demonstrated using the Test button in Studio), I don't think there's anything that needs to be done for this.  If you agree, please close this issue.

**Comment by veillette** [comment]
In case anything changes, I will note that we could have restored the initial state with the eraser button with
```
  public static fromStateObject( stateObject: CurvePointStateObject ): CurvePoint {
    const curvePoint = new CurvePoint(
      stateObject.x,
      stateObject.y,
      stateObject.isDiscontinuous
    );
    curvePoint.isCusp = stateObject.isCusp;
```
