### ISSUE TITLE
Items in GraphSetRadioButtonGroup should support Lab and Advanced screens

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#106]
The items for the GraphRectangularRadioGroup are hardwired to the need of the Advanced (third) screen .
```
    // Item for integral radio button
    const integralRadioButtonItem = createItem(
      CurveLabelsNode.getIntegralLabel(),
      graphsChoices[ 0 ], {
        tandemName: 'integralRadioButton'
      } );

    // Item for integral radio button
    const derivativeRadioButtonItem = createItem(
      CurveLabelsNode.getDerivativeLabel(),
      graphsChoices[ 1 ], {
        tandemName: 'derivativeRadioButton'
      } );
```

As a result, the same buttons show up on the Lab (fourth) screen.

The tandemName, as well as their associated node/label should support both screens.

I haven't given any thought about the best way to address it but this should be done before #103.

**Comment by pixelzoom** [comment]
Remcommend to rename GraphsRectangularRadioButtonGroup.  It's definition is currently:

```
export default class GraphsRectangularRadioButtonGroup extends RectangularRadioButtonGroup<GraphChoice>
  public constructor( graphsSelectionProperty: Property<GraphChoice>,
```

We typically name subclasses based on the type of their associated Property, in this case `GraphChoice`.  So in this case, `GraphChoiceRadioButtonGroup` would be a more appropriate name. (The "Rectangular" part of the superclass name is also typical to drop.)

**Comment by veillette** [comment]
@pixelzoom volunteered to work on this issue.

**Comment by veillette** [comment]
Unassigning myself and @pixelzoom will work on the implementation.

**Comment by veillette** [comment]
On the 12/6 meeting, we discussed the use of `labelAlignGroup` as a way to align and size multiple objects. I noted that the creation of the `graphSetRadioButtonGroupItems` in the Screen (rather than the ScreenView) is unusual but given we create the `graphSets` is the Screen, since we need them for both model and view, and that the graphSetRadioButtonGroupItems takes the graphSets as an argument, it makes sense for them to be created  in proximity of one another. 

 About the use of different curve shape for each GraphType, I don't feel strongly about it but we can bring it to discussion during our design meeting. 

Since this issue was about supporting the lab and advanced screens rather than the look of the graphSet Radio buttons, we can close this issue.
