### ISSUE TITLE
Reconsider Curve Hierarchy 

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#108]
As we are discussing #100, we may want to reconsider the Curve  Hierarchy 

OriginalCurve --> TransformedCurve --> Curve

````
OriginalCurve

Instances
 - curveManipulationModeProperty
 - curveManipulationWidthProperty

Methods
- operatedCurve
- smooth
- undoToLastSave
- reset
````

```
TransformedCurve

Methods
- createHillAt
- createParabolaAt
- createPedestalAt
- createSinusoidalAt
- createTriangleAt
- drawFreeformToPosition
- freeformIconCurve
- interpolate
- isRegionZero
- positionManipulatedCurve
- reset
- saveCurrentPoints
- shiftToPosition
- tiltToPosition
- userManipulatedCurve
- widthManipulatedCurve
```

The OriginalCurve creates  the curveManipulationModeProperty and curveManipulationWidthProperty

The predict curve should be of the type 'Transformed" since there should be only one curveManipulationModeProperty and curveManipulationWidthProperty in the sim.

However, if we need to be able to smooth and undo the predicted curve, as suggested in #100, we will need to fold the smooth
and undoToLastSave methods from `OriginalCurve` into `TransformedCurve`.  At this point, the functionality of `OriginalCurve` is merely a container for  curveManipulationModeProperty and curveManipulationWidthProperty .  

I think it makes more sense to flatten the structure by hoisting the  curveManipulationModeProperty and curveManipulationWidthProperty to the CommonModel , and fold the entire class `OriginalCurve` into `TransformedCurve`. 
In this way, both instances of originalCurve and predictedCurve would be both of type `TransformedCurve`.

If we make these changes, this would simplify the view. 
On the view side, we would  replace the class  `OriginalCurveNode ( originalCurve, ....)`
with `TransformedCurveNode( someTransformedCurve, curveManipulationModeProperty, curveManipulationWidthProperty)`,
such that both instances of originalCurveNode and predictedCurveNode would be of the type `TransformedCurveNode`.

The base classes `Curve` and `CurveNode` would remain the same.

**Comment by veillette** [comment]
Assigning to @pixelzoom  to review this proposal.

**Comment by veillette** [comment]
Thinking about it, we can make the case for a counterproposal, to keep the same class structure for the Curve in the model , but instead to introduce an intermediate class in the view.

```
OriginalCurve --> TransformedCurve --> Curve
OriginalCurveNode--> TransformedCurveNode --> CurveNode
```

`TransformedCurveNode` would be like

````typescript
export default class TransformedCurveNode extends CurveNode 

  public constructor( transformedCurve: TransformedCurve,
                      curveManipulationWidthProperty: NumberProperty,
                      curveManipulationModeProperty: EnumerationProperty<CurveManipulationMode>,
                      chartTransform: ChartTransform,
                      providedOptions?: TransformedCurveNodeOptions ) {
````
and most of the current functionality of OriginalCurveNode , such as dragHandling would be transferred to TransformedCurveNode.

`OriginalCurveNode` would be like thin wrapper over TransformedCurveNode 

````typescript
export default class OriginalCurveNode extends TransformedCurveNode 

  public constructor( originalCurve: OriginalCurve,
                                         chartTransform: ChartTransform,
                      providedOptions?: TransformedCurveNodeOptions ) {

 super( originalCurve, originalCurve.curveManipulationWidthProperty, originalCurve.curveManipulationModeProperty, chartTransform, options)
````


I still prefer the first proposal but the second approach  would also work.

**Comment by pixelzoom** [comment]
@veillette and I discussed this issue in our meeting today.  The first approach (described in https://github.com/phetsims/calculus-grapher/issues/108#issue-1455569105) sounds very reasonable to me.

**Comment by veillette** [comment]
Lots of change in the commit above:
To summarize:
A new class `CurveManipulationProperties` was created, which host two curve Property:
```js
  widthProperty: NumberProperty,
  modeProperty: EnumerationProperty<CurveManipulationMode>,
```

The rest of the functionalities of the `OriginalCurve` were folded into `TransformedCurve`.

The class `OriginalCurveNode` was refactored to `TransformedCurveNode` and its signature was changed to accept an instance of a `TransformedCurve` and `CurveManipulationProperties`.  

Other changes were made to the signature of the ControlPanel in order to pass the CurveManipulationProperties.

No changes were made to add a predict curve yet but this sets the ground to tackle #100.

**Comment by veillette** [comment]
Overall, it cleans up nicely.

I'm assigning to @pixelzoom to review. It is a lot of changes which you are welcomed to look at .
One bit that would be worth discussing is in `OriginalGraphNode`, since attaching the new curveNode onto the graph was problematic.

For context, in `GraphNode`, we create an instance of `CurveNode` 

```js
    // curve associated with this graph
    this.curveNode = new CurveNode( curve, this.chartTransform, options.curveNodeOptions );
```
and attach it to the scene graph.

in `OriginalGraphNode` which extends 'GraphNode',  I create a TransformedCurveNode , detach the previous CUrveNode and replace it with the transformedCurve.

```js

    const transformedCurveNode = new TransformedCurveNode( curve,
      curveManipulationProperties,
      this.chartTransform,
      combineOptions<TransformedCurveNodeOptions>(
        { tandem: options.tandem.createTandem( 'originalCurveNode' ) },
        options.curveNodeOptions ) );

    this.replaceChild( this.curveNode, transformedCurveNode );
    this.curveNode = transformedCurveNode;
```
We can discuss it at our next meeting

**Comment by veillette** [comment]
We have reviewed the previous work and came to the conclusion that it would be better to pass it via a new createCurveNode option, which was done in the commit above.

**Comment by veillette** [comment]
Closing.
