### ISSUE TITLE
Occurances after clicking the origin

### ISSUE THREAD

**Issue by phet-steele** [phetsims/calculus-grapher#11]
Discovered while looking into #8 more; after forcing the graph into its straight vertical position, manipulating the origin does some interesting things (this is easiest with tilt):

![calcgra4](https://cloud.githubusercontent.com/assets/5863899/7865541/d336f174-0526-11e5-9d7f-bf38bda81f11.gif)

The line either becomes unchangeable, as seen above, or everything just becomes sharp peaks:

![calcgra5](https://cloud.githubusercontent.com/assets/5863899/7865624/4abe9382-0527-11e5-9451-971959086609.gif)

Tested on Win 8.1 FF 38.0.1

**Comment by phet-steele** [comment]
Here's another thing after the setup. Freeform is really the only thing that works, so after drawing some things then switching to hill, the graph returns to being flat when the hill is dragged past the end of the freeform drawing:

![calcgra6](https://cloud.githubusercontent.com/assets/5863899/7865812/97977934-0528-11e5-9f45-36a05aae02aa.gif)

**Comment by amanda-phet** [comment]
Unassigning and putting on hold until this sim is ported.

**Comment by brandonLi8** [comment]
From #26 we decided to disallow vertical curves (by enforcing a max tilting angle of 45). This scenario isn't possible anymore and can be closed. Closing.
