### ISSUE TITLE
derivatives should look for discontinuities or cusps in the base curve.

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#110]
The way to calculate the derivative should be dependent on the presence of discontinuities and cusps.

The current approach to determine the derivative is based on the y value of the left and right hand side of each  point.
It is also known as the symmetric difference quotient. It is numerically more stable, and is a  more accurate approximation to the derivative than a one-sided estimation. The estimation error goes (Dx)^2 as opposed of Dx.  This approach smooths out irregularities that may be present on the base curve (such as Freeform).

However, this very approach is counterproductive at cusps and discontinuities. 
![Calculus Grapher screenshot (13)](https://user-images.githubusercontent.com/7633344/203111953-b599c82e-dd63-4f88-9e3d-3761aa942c08.png)

At a cusp point, the derivative to the left and right is different, and the symmetric difference quotient averages these two results.
Technically speaking the derivative does not exist at a cusp point., and the value found by the symmetric difference quotient is a technical artefact. When we evaluate the second derivative, this technical artefact get propagated as seen in the image above.

**Comment by veillette** [comment]
On the 11/29 meeting, we talked that having two booleans to track the discontinuity and cusp status of a point is suboptimal . We discussed creating instead an instead that would track the PointType which would be  (similar to RayTypes in GO)
``
type PointTypeValues = [ 'smooth', 'cusp',  'discontinuous' ] as const;
type PointType = ( typeof PointTypeValues )[number];
```

**Comment by veillette** [comment]
Here is a patch that adds a pointType, but I didn't know how to implement the changed for CurvePointIO .

<details>
<summary>Patch</summary>
Subject: [PATCH] add pointType (see #110)
---
Index: js/common/model/Curve.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/Curve.ts b/js/common/model/Curve.ts
--- a/js/common/model/Curve.ts	(revision b86eff1df22afb0cbc36bf75e2b005ad6e80d257)
+++ b/js/common/model/Curve.ts	(date 1670102307253)
@@ -335,7 +335,7 @@
           // evaluate the difference in the angle of the left and right slope
           const K = Math.abs( ( Math.atan( leftSlope ) - Math.atan( rightSlope ) ) );
 
-          point.isCusp = ( K >= DERIVATIVE_THRESHOLD );
+          point.pointType = ( K >= DERIVATIVE_THRESHOLD ) ? 'cusp' : 'smooth';
         }
       }
     );
@@ -369,7 +369,7 @@
           // find jump
           const jump = Math.max( Math.abs( leftSideDifference ), Math.abs( rightSideDifference ) );
 
-          point.isDiscontinuous = ( jump >= 10 );
+          point.pointType = ( jump >= 10 ) ? 'discontinuous' : 'smooth';
         }
       }
     );
Index: js/common/model/DerivativeCurve.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/DerivativeCurve.ts b/js/common/model/DerivativeCurve.ts
--- a/js/common/model/DerivativeCurve.ts	(revision b86eff1df22afb0cbc36bf75e2b005ad6e80d257)
+++ b/js/common/model/DerivativeCurve.ts	(date 1670250004789)
@@ -82,31 +82,31 @@
     this.baseCurve.forEachAdjacentTrio( ( previousPoint, point, nextPoint, index ) => {
 
         let leftSlope: null | number = null;
-        let rightSlope: null | number = null;
+      let rightSlope: null | number = null;
 
-        // Compute the leftSlope and rightSlope.
+      // Compute the leftSlope and rightSlope.
 
-        // Take the slope of the secant line between the left adjacent Point and the current Point, where m = dy/dx.
-        if ( previousPoint && previousPoint.exists && !previousPoint.isDiscontinuous ) {
-          leftSlope = ( point.y - previousPoint.y ) / ( point.x - previousPoint.x );
-          assert && assert( Number.isFinite( leftSlope ), 'non finite slope' );
-        }
+      // Take the slope of the secant line between the left adjacent Point and the current Point, where m = dy/dx.
+      if ( previousPoint && previousPoint.exists && !( previousPoint.pointType === 'discontinuous' ) ) {
+        leftSlope = ( point.y - previousPoint.y ) / ( point.x - previousPoint.x );
+        assert && assert( Number.isFinite( leftSlope ), 'non finite slope' );
+      }
 
-        if ( nextPoint && nextPoint.exists && !point.isCusp ) {
-          // Take the slope of the secant line between the current Point and the right adjacent Point, where m = dy/dx.
-          rightSlope = ( nextPoint.y - point.y ) / ( nextPoint.x - point.x );
-          assert && assert( Number.isFinite( rightSlope ), 'non finite slope' );
-        }
-        //----------------------------------------------------------------------------------------
+      if ( nextPoint && nextPoint.exists && !( nextPoint.pointType === 'cusp' ) ) {
+        // Take the slope of the secant line between the current Point and the right adjacent Point, where m = dy/dx.
+        rightSlope = ( nextPoint.y - point.y ) / ( nextPoint.x - point.x );
+        assert && assert( Number.isFinite( rightSlope ), 'non finite slope' );
+      }
+      //----------------------------------------------------------------------------------------
 
-        if ( typeof leftSlope === 'number' && typeof rightSlope === 'number' && Number.isFinite( leftSlope ) && Number.isFinite( rightSlope ) ) {
-          // If both the left and right adjacent Points of the Point of the 'base' curve exist, the derivative is
-          // the average of the slopes if they are approximately equal. Otherwise, the derivative doesn't exist.
-          this.points[ index ].y = ( leftSlope + rightSlope ) / 2;
-        }
-        else if ( typeof leftSlope === 'number' && Number.isFinite( leftSlope ) ) {
+      if ( typeof leftSlope === 'number' && typeof rightSlope === 'number' && Number.isFinite( leftSlope ) && Number.isFinite( rightSlope ) ) {
+        // If both the left and right adjacent Points of the Point of the 'base' curve exist, the derivative is
+        // the average of the slopes if they are approximately equal. Otherwise, the derivative doesn't exist.
+        this.points[ index ].y = ( leftSlope + rightSlope ) / 2;
+      }
+      else if ( typeof leftSlope === 'number' && Number.isFinite( leftSlope ) ) {
 
-          // If only the slope of the left side exists, use that as the derivative.
+        // If only the slope of the left side exists, use that as the derivative.
           this.points[ index ].y = leftSlope;
         }
         else if ( typeof rightSlope === 'number' && Number.isFinite( rightSlope ) ) {
Index: js/common/model/CurvePoint.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/CurvePoint.ts b/js/common/model/CurvePoint.ts
--- a/js/common/model/CurvePoint.ts	(revision b86eff1df22afb0cbc36bf75e2b005ad6e80d257)
+++ b/js/common/model/CurvePoint.ts	(date 1670249899176)
@@ -1,36 +1,39 @@
 // Copyright 2020-2022, University of Colorado Boulder
 
 /**
- * CurvePoint is a single mutable point of a Curve at a given x-value. Inheriting from Vector2 was considered, but it
- * was decided to implement CurvePoints to be minimally invasive and lightweight for performance.
- *
+ * CurvePoint is a single mutable point of a Curve at a given x-value.
  * Each CurvePoint contains the following information:
- *   - The corresponding y-value of the Point.
- *   - Whether the Point exists. A Point that isn't defined means that the Curve has a hole or a discontinuity.
- *   - All of its previously 'saved' y-values. When the user finishes manipulating the TransformedCurve, the y-value of
- *     CurvePoints in the TransformedCurve are saved.
+ *   - The corresponding y-value and type of the Point.
+ *   - All of its previously 'saved' states. When the user finishes manipulating the TransformedCurve, the state of
+ *     CurvePoint in the TransformedCurve is saved.
  *
  * For the 'Calculus Grapher' simulation, CurvePoints are used inside of Curve (and its subtypes) to partition the curve
- * into a finite number of close points that map out the general shape and curvature. Adjacent CurvePoints are
- * considered to be infinitesimally close enough for derivative and integral computations. Thus, CurvePoints are created
- * at the start of the sim and are mutated when the Curve changes, meaning CurvePoints are never disposed.
+ * into a finite number of close points that map out the general shape and curvature. CurvePoints are created
+ * at the start of the sim and are mutated when the Curve changes. CurvePoints are never disposed.
  *
  * @author Brandon Li
  */
 
 import Vector2 from '../../../../dot/js/Vector2.js';
-import BooleanIO from '../../../../tandem/js/types/BooleanIO.js';
 import IOType from '../../../../tandem/js/types/IOType.js';
 import NumberIO from '../../../../tandem/js/types/NumberIO.js';
+import StringIO from '../../../../tandem/js/types/StringIO.js';
 import calculusGrapher from '../../calculusGrapher.js';
 import CalculusGrapherConstants from '../CalculusGrapherConstants.js';
 
+const PointTypeValues = [ 'smooth', 'cusp', 'discontinuous' ] as const;
+export type PointType = ( typeof PointTypeValues )[number];
+
+export type PointState = {
+  y: number;
+  pointType: PointType;
+};
+
 export type CurvePointStateObject = {
   x: number;
   y: number;
-  isDiscontinuous: boolean;
-  isCusp: boolean;
-  initialY: number;
+  pointType: PointType;
+  initialState: PointState;
 };
 
 export default class CurvePoint {
@@ -42,44 +45,37 @@
   // of all CurvePoints. See https://github.com/phetsims/calculus-grapher/issues/19
   public y: number;
 
-  public isDiscontinuous: boolean;
-
-  public isCusp: boolean;
-
-  // the initial y-coordinate passed into the CurvePoint, for resetting purposes.
-  private readonly initialY: number;
-
-  // an array of all of this Point's saved y-values.
-  private savedYValues: ( number )[];
-
   public static readonly CurvePointIO = new IOType<CurvePoint, CurvePointStateObject>( 'CurvePointIO', {
     valueType: CurvePoint,
     stateSchema: {
       x: NumberIO,
       y: NumberIO,
-      isDiscontinuous: BooleanIO,
-      isCusp: BooleanIO,
-      initialY: NumberIO
+      pointType: StringIO
     },
     toStateObject: ( curvePoint: CurvePoint ) => curvePoint.toStateObject(),
     fromStateObject: ( stateObject: CurvePointStateObject ) => CurvePoint.fromStateObject( stateObject ),
     documentation: 'describe the point on a curve'
   } );
+  public pointType: PointType;
+  // the initial y-coordinate passed into the CurvePoint, for resetting purposes.
+  private readonly initialState: PointState;
+  // an array of all of this Point's saved states.
+  private readonly savedStates: PointState [];
 
-  public constructor( x: number, y = 0, isDiscontinuous = false ) {
+  public constructor( x: number, y = 0, pointType: PointType = 'smooth' ) {
     assert && assert( Number.isFinite( x ) && CalculusGrapherConstants.CURVE_X_RANGE.contains( x ), `invalid x: ${x}` );
     assert && assert( y === null || Number.isFinite( y ), `invalid y: ${y}` );
 
     this.x = x;
     this.y = y;
-    this.isDiscontinuous = isDiscontinuous;
+    this.pointType = pointType;
 
-    // TODO: allow user to set state
-    this.isCusp = false;
+    this.initialState = {
+      y: y,
+      pointType: pointType
+    };
 
-    this.initialY = y;
-
-    this.savedYValues = [];
+    this.savedStates = [];
   }
 
   public toVector(): Vector2 {
@@ -87,7 +83,7 @@
   }
 
   /**
-   * Returns a boolean that indicates if the point exists.
+   * Returns a boolean that indicates if the y value of a point is finite.
    */
   public get exists(): boolean {
     return Number.isFinite( this.y );
@@ -99,7 +95,19 @@
    * Gets the most recently saved y-value.
    */
   public get lastSavedY(): number {
-    return ( this.savedYValues.length === 0 ) ? this.initialY : _.last( this.savedYValues )!;
+    return ( this.savedStates.length === 0 ) ? this.initialState.y : _.last( this.savedStates )!.y;
+  }
+
+  public static fromStateObject( stateObject: CurvePointStateObject ): CurvePoint {
+    const curvePoint = new CurvePoint(
+      stateObject.x,
+      stateObject.initialState.y,
+      stateObject.initialState.pointType
+    );
+    curvePoint.y = stateObject.y;
+    curvePoint.pointType = stateObject.pointType;
+
+    return curvePoint;
   }
 
   /**
@@ -109,16 +117,29 @@
    */
   public save(): void {
 
-    // Save the current y-value of the CurvePoint.
-    this.savedYValues.push( this.y );
+    // Save the current state of the CurvePoint.
+    this.savedStates.push( {
+      y: this.y,
+      pointType: this.pointType
+    } );
 
     // empty first element of array if the number of saved values exceed MAX_UNDO
-    while ( this.savedYValues.length > CalculusGrapherConstants.MAX_UNDO ) {
+    while ( this.savedStates.length > CalculusGrapherConstants.MAX_UNDO ) {
 
       // remove first value from array
-      this.savedYValues.shift();
+      this.savedStates.shift();
     }
+  }
 
+  /**
+   * Debugging string for the CurvePoint.
+   */
+  public toString(): string {
+    return `CurvePoint[ x: ${this.x}, y: ${this.y}, pointType: ${this.pointType} ]`;
+  }
+
+  public dispose(): void {
+    assert && assert( false, 'CurvePoint cannot be disposed (exists for the lifetime of the sim)' );
   }
 
   /**
@@ -129,41 +150,13 @@
 
     // Set the y-value of this CurvedPoint to the last saved state. The y-value is removed from our savedYValues
     // so the next undoToLastSave() call successively reverts to the state before this one.
-    this.y = ( this.savedYValues.length === 0 ) ? this.initialY : this.savedYValues.pop()!;
-  }
-
-  //----------------------------------------------------------------------------------------
-
-  /**
-   * Debugging string for the CurvePoint.
-   */
-  public toString(): string {
-    return `CurvePoint[ x: ${this.x}, y: ${this.y} ]`;
-  }
-
-  public dispose(): void {
-    assert && assert( false, 'CurvePoint cannot be disposed (exists for the lifetime of the sim)' );
+    this.y = ( this.savedStates.length === 0 ) ? this.initialState.y : this.savedStates.pop()!.y;
   }
 
   public reset(): void {
-    this.y = this.initialY;
-    this.savedYValues = [];
-
-    // TODO: save initial state
-    this.isDiscontinuous = false;
-    this.isCusp = false;
-  }
-
-  public static fromStateObject( stateObject: CurvePointStateObject ): CurvePoint {
-    const curvePoint = new CurvePoint(
-      stateObject.x,
-      stateObject.initialY,
-      stateObject.isDiscontinuous
-    );
-    curvePoint.y = stateObject.y;
-    curvePoint.isCusp = stateObject.isCusp;
-
-    return curvePoint;
+    this.y = this.initialState.y;
+    this.pointType = this.initialState.pointType;
+    this.savedStates.length = 0;
   }
 
   // the savedYValues of the curvePoint are purposefully not serialized (see https://github.com/phetsims/calculus-grapher/issues/65 )
@@ -171,9 +164,8 @@
     return {
       x: this.x,
       y: this.y,
-      isDiscontinuous: this.isDiscontinuous,
-      isCusp: this.isCusp,
-      initialY: this.initialY
+      pointType: this.pointType,
+      initialState: this.initialState
     };
   }
 }
Index: js/common/model/TransformedCurve.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/TransformedCurve.ts b/js/common/model/TransformedCurve.ts
--- a/js/common/model/TransformedCurve.ts	(revision b86eff1df22afb0cbc36bf75e2b005ad6e80d257)
+++ b/js/common/model/TransformedCurve.ts	(date 1670249175975)
@@ -399,7 +399,7 @@
 
       // update the y value of an intermediate point
       this.getClosestPointAt( xPosition ).y = ( 1 - W ) * position1.y + W * position2.y;
-      this.getClosestPointAt( xPosition ).isDiscontinuous = false;
+      this.getClosestPointAt( xPosition ).pointType = 'smooth';
     }
   }
</details>

**Comment by pixelzoom** [comment]
> Here is a patch that adds a pointType, but I didn't know how to implement the changed for CurvePointIO .

It looks like you're going in the correct direction.  Since `pointType` is a string union, you can treat it as StringIO. 

I see what you're doign with `initialState` -- you want to capture the entire state in one object, PointState.   But that's going to require another IOType, `PointStateIO`, to serialize `pointType`.   So 2 approaches:

(1) Replace `this. initialState` with `this.initialY` and `this.initialPointType`.  You loose the encapsulation of initial state, but this is the simplest/clearest approch.  And this is what I'd recommend.

(2) If loosing encapsualtion of initial state bothers you... Keep `this. initialState`, but serialize its fields separately, like:

```typescript
export type CurvePointStateObject = {
  x: number;
  y: number;
  pointType: PointType;
  initialY: number;
  initialPointType: PointType;
};
```

This is a little more complicated to implemented. And it's a little more confusing because we typically like the structure of the StateObject to match the structure of the core type (CurvePoint).

**Comment by veillette** [comment]
In the commit above, we opted for scenario 2, where we flattened the encapsulation of the pointState to serialize the curvePointState. In addition, we added some convenience function for testing the value of the pointType.

**Comment by veillette** [comment]
In #208,  we explicitly assign the type of a derivative point based on the original curve. 

The point type is "promoted" for the derivative such that a cusp in the original curve become a discontinuity in the derivative.
(A discontinuity remains a discontinuity)

```js
      if ( point.isCusp ) {
        this.points[ index ].pointType = 'discontinuous';
      }
      else if ( point.isDiscontinuous ) {
        this.points[ index ].pointType = 'discontinuous';
      }
      else {
        this.points[ index ].pointType = 'smooth';
      }
```

**Comment by veillette** [comment]
Our work is done here. We are tracking improvements in cusp tagging in #208. Closing

**Comment by marlitas** [comment]
From https://github.com/phetsims/calculus-grapher/issues/268

There is still a TODO referencing this issue in DerivativeCurve

**Comment by pixelzoom** [comment]
@veillette has been working on this, so I'll leave it to him to decide whether the TODO is vestigial or is something that needs to be addressed.

**Comment by veillette** [comment]
I added some documentation above and remove the TODO. 

This makes me think about what we need to really close this issue. I think the best way forward is to create an other issue :), that will remind us about informing QA about the `cuspPoints=true` queryParameter (as well as instructing them about what a cusp point). A behavior test is better than a code review to check all the corner cases that I may have missed.

**Comment by veillette** [comment]
The issue #292 is tracking the behavior test. Closing
