### ISSUE TITLE
Vertical Lines for PhET-iO

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#111]
From the design document:
Line/Label tool: 
Add vertical lines at certain locations

Instructional designer inputs x-coordinate, hex code, and a label in studio
Default hex code should be black 
1px, dashed, long dashes and small spaces (if dashed doesn’t work, try not dashed)  
Line spans multiple graphs
Sim displays a vertical dashed line and label above the vertical line
Limit this to 10 lines
Each line/label tool should have associated data for value for each of the curves at that x value (so four values - integral of f 0-x, f(x), f’(x), f’’(x)) 
if f’(x) is undefined, just say “undefined” or whatever you are using to indicate it.

**Comment by pixelzoom** [comment]
@veillette and I discussed. Notes:

* Do we really need this feature?  It's going to be a lot of work. How are we going to test this going forward? PhET has no process for testing PhET-iO-only features, and CT won't test this.  So it's likely to get broken in the future.

* The practical way to do this would be to create 10 instances of some class (e.g. `VerticalLabelLine`) that describes the x-coordinate, color, and string label (Properties).  Those would be invisible by default, instructional designer could make them visible as needed, and modify their x-coordinate, color, string label.

* All instances of `VerticalLabelLine` should be grouped under 1 parent tandem.

* Should VerticalLabelLines be in the model, view,  both?  Where do you want the visibleProperty?

* Do the string labels need to be translated? What are the default values? (A-J?)

**Comment by amanda-phet** [comment]
These are great questions. @kathy-phet should probably weigh in as the primary PhET-iO stakeholder. 

> Do we really need this feature? It's going to be a lot of work. How are we going to test this going forward? PhET has no process for testing PhET-iO-only features, and CT won't test this. So it's likely to get broken in the future.

We identified a lot of pedagogical value in having this in PhET-iO. For example, someone could set up a situation where they have lines in specific locations and they can ask students to build a graph with a specific quality at that location. 

I have no idea about how it relates to testing. 

> The practical way to do this would be to create 10 instances of some class (e.g. VerticalLabelLine) that describes the x-coordinate, color, and string label as Properties. Those instances would be invisible by default. The instructional designer could make them visible as needed, and modify their x-coordinate, color, and string label. Does that general approach sound acceptable?

That seems reasonable to me. 

> All instances of VerticalLabelLine should be grouped under 1 parent tandem. How should they be named? Typically we would number them, but that won't relate to the string label.

I think numbered is fine. While we expect someone to find a lot of use out of A-F as labels, they might use numbers or something else, so numbers seem logical to me. If you're going to ask about 1-10 or 0-9, I already forgot about how we're supposed to be numbering, but I think 1-10 is what we decided on for this kind of scenario? 

> Should VerticalLabelLines be in the model, view, both? Where do you want the visibleProperty?

This is something I don't feel qualified to answer. Most things I use in studio tend to be in the view, so that seems logical to me. 

> Do the string labels need to be translated? What are the default values? (A-J?) Will it be confusing to Rosetta users that these strings do not (by default) appear anywhere in the sim?

A-J as default values is good. Didn't consider the translation aspect at all, as I'm not sure how PhET-iO clients use translations.

**Comment by veillette** [comment]
@amanda-phet: Also we may need to push the graphs down if we put the labels above the vertical line. Is it possible to get a visual of what it would like with the label and the associated data for value for each of the curve?

**Comment by veillette** [comment]
![image](https://user-images.githubusercontent.com/7633344/209581081-30639f53-c704-4463-a9ab-bae6d2a011e4.png)

This is a first pass for this new features.

The general approach was outlined by @pixelzoom : 

> The practical way to do this would be to create 10 instances of some class that describes the x-coordinate, color, and string label as Properties. Those instances would be invisible by default. The instructional designer could make them visible as needed, and modify their x-coordinate, color, and string label. 

All instances of VerticalLineNode are grouped under the parent tandem `VerticalLinesLayer`.

The visible property of the VerticalLineNode appears in the view.
I used A-J as a tandem prefix for the labels, so that it matches the labels. 
The nominal values for the labels run from A through J, but the teacher/designer can override them.
The color of the dashed line is black  but the instructional designer can override it. The color only updates the dashed line, and not the label.

 I have also added linked elements in the view from the model, such as the X coordinate and the other properties (derivative, integral, etc) can also be seen.

**Comment by pixelzoom** [comment]
Similar to my comments in https://github.com/phetsims/calculus-grapher/issues/112#issuecomment-1366174708, it's odd to have "model" under `*Screen.view.graphsNode.verticalLinesLayer.*VerticalLineNode.model`.  If there is a model for each vertical line, those should be under `*Screen.model.verticalLines`, for example `derivativeScreen.model.verticalLines.AVerticalLine`.  Then those model elements should be linked under their associated node in the view, for exampe `derivativeScreen.view.graphsNode.verticalLinesLayer.AVerticalLineNode.AVerticalLine`.

**Comment by pixelzoom** [comment]
In our 1/10/2022 meeting, I volunteered to look at AncillaryTool issues. Self assigning because this is related to AncillaryTool.

**Comment by pixelzoom** [comment]
Here's what the model looks like in Studio:

<img width="369" alt="screenshot_2159" src="https://user-images.githubusercontent.com/3046552/213112866-3e66bb1a-c3e9-4167-b893-570744fd069f.png">

Here's what the view looks like in Studio:

<img width="374" alt="screenshot_2158" src="https://user-images.githubusercontent.com/3046552/213112914-49caa45a-ee0c-40d6-9c8a-167233d0bf91.png">

While `visibleProperty` is somewhat redundant in the view, it provides symmetric with labeled points (where `visibleProperty` is derived).   And getting rid of `visibleProperty` here is not striaghtforward, it's added by Node.

**Comment by veillette** [comment]
The model side of VerticalLine cleans up nicely.

We discussed having the layer verticalLines (in the view) be linked to verticalLines in the model. But thinking about it, maybe that's hard to do, because it is harder to link from the view to the model.

Also  we create an extra Tandem for VerticalLineNodes, but we have 
not instrumented verticalLineNodesLayer . Is `verticalLineNodesLayer` vestigial at this point?
```js
    const verticalLineNodesLayer = new Node( {
      children: verticalLineNodes
    } );
```
we could attach all the verticalLineNodes in this way instead
``js
    options.children = [ graphSetNode, ...verticalLineNodes, referenceLineNode ];
``

or maybe we prefer to keep the scenery node hierarchy in sync with the studio tree?

**Comment by pixelzoom** [comment]
> We discussed having the layer verticalLines (in the view) be linked to verticalLines in the model. But thinking about it, maybe that's hard to do, because it is harder to link from the view to the model.

It's difficult because `view.graphsNode.verticalLines` is not a PhetioObject, it's just a placeholder tandem. So we can't link anything to it, because we can't call `addLinkedElement`.   We could consider making it a Node and changing its name to `verticalLinesNode`.  That would also allow us to hide all vertical lines at once using `visibleProperty`.  Let's discuss.

**Comment by pixelzoom** [comment]
The other issue is that `visibleProperty` for each VerticalLineNode is a DerivedProperty (from  the tool model's `visiblePropert` and `predictModeEnabledProperty`).  So if we do not have each VerticalLineNode under `view.graphsNode.verticalLine` then the instructional design cannot discover how visibility is controlled.

**Comment by veillette** [comment]
> The other issue is that `visibleProperty` for each VerticalLineNode is a DerivedProperty (from the tool model's `visiblePropert` and `predictModeEnabledProperty`). So if we do not have each VerticalLineNode under `view.graphsNode.verticalLine` then the instructional design cannot discover how visibility is controlled.

This is a moot point as the visibility of verticalLineNode is never derived. Many ancillary tools have derived properties but not VerticalLines and referenceLine. 

>It's difficult because view.graphsNode.verticalLines is not a PhetioObject, it's just a placeholder tandem. So we can't link anything to it, because we can't call addLinkedElement. We could consider making it a Node and changing its name to verticalLinesNode. That would also allow us to hide all vertical lines at once using visibleProperty. Let's discuss.

`view.graphsNode.verticalLineNodesLayer` is a PhetIObject since it is a node. 

Let me look at it.

**Comment by veillette** [comment]
I think i understand, although I'm not 100$ sure. I think @pixelzoom is right and wrong at the same time.

I tried this

```js
    const verticalLineNodesLayer = new Node( {
      tandem: options.tandem.createTandem( 'verticalLines' )
    } );

    const verticalLineNodes = model.verticalLines.map( verticalLine =>
      new VerticalLineNode( verticalLine, this.originalGraphNode.chartTransform, {
        x: this.originalGraphNode.x,
        tandem: verticalLineNodesLayer.tandem.createTandem( `${verticalLine.labelProperty.value}VerticalLineNode` )
      } ) );

    verticalLineNodesLayer.setChildren( verticalLineNodes );
    verticalLineNodesLayer.addLinkedElement( model.verticalLines );
```

The last line fail because `model.verticalLines` is not a PhetioObject, it is an array of `VerticalLine`. Even though the VerticalLine are themselves `PhetioObject`, `model.verticalLines` has merely a placeholder tandem. So the comments are correct is we apply them to the model elements instead of the view elements.

**Comment by veillette** [comment]
Hmmm, after poking a bit in this, I realized that I dont have a very deep understanding of `addLinkedELement`. It would be better off pairing and discussing with @pixelzoom

**Comment by veillette** [comment]
I discussed with @pixelzoom to further my understanding of `addLinkedElement` on phetioObject. 
There is nothing more to do here wrt to phetIO. so closing.
