### ISSUE TITLE
Reference Line tool and PhET-iO

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#112]
Similar to data and line tools in #111, reference line tool should have have associated data for value for each of the curves at that x value (so four values - integral of f 0-x, f(x), f’(x), f’’(x)) 
if f’(x) is undefined, just say “undefined” or whatever you are using to indicate it.

**Comment by veillette** [comment]
Currently, the model is simply a xCoordinate. For the purpose of implementing this feature, we will need to create a reference line model that knows about the states of the four curves

**Comment by veillette** [comment]
As I read more on this, there is a lot of overlap with the line/label feature requested in  #111. We should try to understand the commonalities and differences of reference line and line/label before we start implementing this feature.

**Comment by veillette** [comment]
In addition, the scrubber needed for #97 and #99 shares many visual and functional similarities with the reference line tool ( DragListener on a sphere that is dragBounds by he x Range of the Graph, the sphere moves a line alongside)

**Comment by veillette** [comment]
The referenceline model needs to keep track of four values:  integral of f 0-x, f(x), f’(x), f’’(x)). As a result it will share the same model as AncillaryTools. Therefore we can create another instance of AncillaryTools for the referenceLine model.

**Comment by veillette** [comment]
In the commit above, I have deleted the ReferenceLine class and created an instance of referenceLine from the AncillaryTools class.

**Comment by veillette** [comment]
Here is the studio tree for the reference line tool
![image](https://user-images.githubusercontent.com/7633344/209720283-0b406c02-d069-4eb3-a358-dd0ef24e58af.png)

The four associated data and the x coordinate are linked in the view.

**Comment by veillette** [comment]
The work is done here. Assigning to @amanda-phet for review.

**Comment by pixelzoom** [comment]
@veillette I hope it OK for me to step in here and review before @amanda-phet does.

`integralScreen.referenceLineNode.model` is odd, not the way we typically structure things for PhET-iO.  Instead, there should be `integralScreen.model.referenceLine` which has elements as children that are related to the reference line. That model should then appear in the view as linked element `integralScreen.referenceLineNode.referenceLine`.

**Comment by veillette** [comment]
@pixelzoom : `integralScreen.view.graphsNode.referenceLineNode.model` is indeed a linked element and they do appear in `integralScreen.model.referenceLine`. I thought it would be neat to have a mini view-model for the referenceLineNode.

This is not so important for the referenceLineNode, but it becomes very convenient for other the verticalLineNode and PointLabel, since there are up to 10 of them.

**Comment by pixelzoom** [comment]
In our 1/10/2022 meeting, I volunteered to look at AncillaryTool issues. Self assigning because this is related to AncillaryTool.

**Comment by pixelzoom** [comment]
This issue is covered by #144, so I'm going to close.
