### ISSUE TITLE
Choose which manipulationCurveModes are visible in the radio button group with PhET-iO

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#114]
We currently have an option field which select which manipulation modes are displayed for each screen. 

```js
      curveManipulationModeChoices: [
        CurveManipulationMode.HILL,
        CurveManipulationMode.PEDESTAL,
        CurveManipulationMode.TILT,
        CurveManipulationMode.SHIFT
      ]
```

However, we would like to go further and expose it to PhET-IO.

**Comment by pixelzoom** [comment]
Here's a patch that demonstrates how to accomplish this.  Create radio button for ALL possible modes, set each radio button's `visible` based on whether it's in the initial set of mode choices. Then the instructional designer can visit `curveManipulationModeRadioButtonGroup` in Studio, and change the visibility of radio buttons as desired.

<details>
<summary>Patch</summary>

```diff
Index: js/common/view/CurveManipulationModeRadioButtonGroup.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/CurveManipulationModeRadioButtonGroup.ts b/js/common/view/CurveManipulationModeRadioButtonGroup.ts
--- a/js/common/view/CurveManipulationModeRadioButtonGroup.ts	(revision 63d078e4aa19d454d6b22cc00cc0bf2e7beb83bb)
+++ b/js/common/view/CurveManipulationModeRadioButtonGroup.ts	(date 1669135798250)
@@ -26,13 +26,20 @@
 
     const options = providedOptions;
 
+    const validModes = curveManipulationModeProperty.validValues!;
+    assert && assert( validModes );
+
     const rectangularRadioButtonGroupItems: RectangularRadioButtonGroupItem<CurveManipulationMode>[] =
-      curveManipulationModeProperty.validValues!.map(
+      CurveManipulationMode.enumeration.values.map(
         mode => {
           return {
             value: mode,
-            createNode: tandem => new CurveManipulationIconNode( mode,
-              { tandem: tandem.createTandem( `${mode.tandemPrefix}Icon` ) } ),
+            createNode: tandem => new CurveManipulationIconNode( mode, {
+              tandem: tandem.createTandem( `${mode.tandemPrefix}Icon` )
+            } ),
+            options: {
+              visible: validModes.includes( mode )
+            },
             tandemName: `${mode.tandemPrefix}${RectangularRadioButton.TANDEM_NAME_SUFFIX}`
           };
         }
```

</details>

**Comment by veillette** [comment]
As stated by CM:

> We create radio buttons for ALL possible modes, set each radio button's visible based on whether it's in the initial set of mode choices. Then the instructional designer can visit curveManipulationModeRadioButtonGroup in Studio, and change the visibility of radio buttons as desired.

Here are screenshots of Studio to show the tree to turn on a sine function button on the derivative screen.

![image](https://user-images.githubusercontent.com/7633344/204383449-13011a4c-0aab-43ee-a5f5-3a42af67f623.png)

![image](https://user-images.githubusercontent.com/7633344/204383046-59219d46-51e4-42d5-8e20-f30c6907192d.png)

I'm assigning @amanda-phet to review. Feel free to close if you think this issue has been addressed.

**Comment by amanda-phet** [comment]
I think this should work just fine. 

One potential issue: the "tangent" tool only works on completely differentiable curves. What if an instructional designer chooses to show triangleRadioButton. Should we decide how the tangent tool will behave at non-differentiable points, or should we change this PhET-iO decision?

**Comment by pixelzoom** [comment]
I went ahead an implemented what I suggested above.

For the Derivative and Integral screens, you have a subset of the buttons, and the Studio tree looks like this.  You can hide any of these buttons, but you cannot add buttons that are not shown in this tree.

<img width="228" alt="screenshot_2024" src="https://user-images.githubusercontent.com/3046552/206598981-4492d527-6da5-448c-b6eb-d9f74a3cc248.png">

For the Advanced and Lab screens, you have the full set of buttons, and any of them can be hidden. The Studio tree looks like this:

<img width="231" alt="screenshot_2025" src="https://user-images.githubusercontent.com/3046552/206599073-0ecdbc9b-f868-48d9-9dcb-c9aa9a7cd3c0.png">

@amanda-phet @veillette is this acceptable?

**Comment by amanda-phet** [comment]
That sounds perfect! Thank you for making that change.

**Comment by veillette** [comment]
This sounds like a satisfactorily solution to me. Since Ananda already weighted on this. I think it is safe to close this issue. Closing
