### ISSUE TITLE
Labeled Points for PhET-iO

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#115]
From design document.
Point/Label tool: 
Could use this to ask users to create a graph with certain conditions at certain points
- [x] Add labels/points at certain coordinates
- [x] Instructional designer inputs x-coordinate, hex code, and a label in studio and label
- [x] Sim displays a small filled circle and label at that coordinate location 
- [x] Default hex code should be blue to match the curve 
- [x] Label should be black text and have semi-transparent white background (see Number Line Integers as an example of this)
- [x] Label should be just above or below the curve (try to be “smart” about the label location) 
- [x] Point is not itself draggable horizontally (at a fixed x-value)
- [x] Limit this to 10 points 
- [x] Each point/label tool should have associated data for value for each of the curves at that x value (so four values - integral of f 0-x, f(x), f’(x), f’’(x)) 
- [x] if f’(x) is undefined, just say “undefined” or whatever you are using to indicate it.

**Comment by veillette** [comment]
Example of a label with black text and semi-transparent white background in Number Line
![image](https://user-images.githubusercontent.com/7633344/206761911-136e61b6-124c-4848-b53d-826cbf90fc53.png)

**Comment by veillette** [comment]
Question for @amanda-phet for the following requirements

> Add labels/points at certain coordinates

the labels are added to the originalGraph, correct?
and they should be invisible  if you toggle PredictMode


> each  point/label tool should have associated data for value for each of the curves at that x value (so four values - integral of f 0-x, f(x), f’(x), f’’(x))"

What does it mean to associate these curve values to the point? I think it means that the data should be read only in studio. Correct me if I'm wrong.

and should we make the data available for all curves, regardless of the set of graphs on the screen?

**Comment by veillette** [comment]
In the 12/22 meeting, we clarified that the associated data should be read only in studio.

**Comment by veillette** [comment]
I have implemented this feature as requested. 

Here is a screenshot in studio.
![image](https://user-images.githubusercontent.com/7633344/209717422-e62d8170-2f74-4f6c-a9e0-4e86be0019c1.png)

The label location is always above the curve but perpendicular to tangent of the curve, which makes it less likely to overlap the curve. 

The pointLabela are invisible in predictMode.

**Comment by veillette** [comment]
Assigning to @amanda-phet for review.

**Comment by veillette** [comment]
Unassigning @amanda-phet until some questions on #145 are addressed.

**Comment by pixelzoom** [comment]
In our 1/10/2022 meeting, I volunteered to look at AncillaryTool issues. Self assigning because this is related to AncillaryTool.

**Comment by pixelzoom** [comment]
PointLabel has been renamed LabeledPoint. 

Here's an example of the Studio tree for the model:

<img width="329" alt="screenshot_2156" src="https://user-images.githubusercontent.com/3046552/213112175-5b558f63-a204-4b95-87c2-fe5933863fc9.png">

Here's an example of the Studio tree for the view:

<img width="410" alt="screenshot_2157" src="https://user-images.githubusercontent.com/3046552/213112379-9b8092a3-027c-45c6-a6b0-72b878029fa8.png">

Over to @veillette for review. If this looks OK to you, feel free to close.

**Comment by veillette** [comment]
Here is a patch where you add the labelNode directly onto the plottedPoint, 
```js
    plottedPoint.addChild( labelNode );
```

in which case, you only  need to listen the yDerivativeProperty to position the label as it gets a free translation ride from plottedPoint. 

I'm not sure it is worth it, but it removes the need for the multilink  ( I also remove the labeledPoint.labelProperty dependency as the height of the label is not going to change) 

<details>
Subject: [PATCH] positioning of label relative to plottedPoint

````js
---
Index: js/common/view/LabeledPointNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/LabeledPointNode.ts b/js/common/view/LabeledPointNode.ts
--- a/js/common/view/LabeledPointNode.ts	(revision 65576d292bd972b898ef6fcd5961acc059bdd351)
+++ b/js/common/view/LabeledPointNode.ts	(date 1674077852135)
@@ -20,7 +20,6 @@
 import BooleanIO from '../../../../tandem/js/types/BooleanIO.js';
 import DerivedProperty from '../../../../axon/js/DerivedProperty.js';
 import PickRequired from '../../../../phet-core/js/types/PickRequired.js';
-import Multilink from '../../../../axon/js/Multilink.js';
 import LabeledPoint from '../model/LabeledPoint.js';
 
 type SelfOptions = EmptySelfOptions;
@@ -69,29 +68,28 @@
       }
     } );
 
+    // add label to plotted point
+    plottedPoint.addChild( labelNode );
+
     // update the positions of the label Node
     // we use some heuristic algorithm to prevent the label to overlap with the curve
-    const updateLabelPosition = () => {
-
-      // value of the tangent (slope) at the y point
-      const tangent = yDerivativeProperty.value;
+    yDerivativeProperty.link( yDerivative => {
 
-      // angle (with respect to x-axis) associated with the normal vector to the tangent
-      const modelPerpendicularTangent = Math.atan( tangent ) + Math.PI / 2;
+        // angle (with respect to x-axis) associated with the normal vector to the tangent
+        const modelPerpendicularTangent = Math.atan( yDerivative ) + Math.PI / 2;
 
-      // determine a distance between the label and plottedPoint (center to center) - put them as close as possible
-      const distance = ( labelNode.height / 2 ) + ( plottedPoint.height / 2 ) + 1;
+        // determine a distance between the label and plottedPoint (center to center) - put them as close as possible
+        const distance = ( labelNode.height / 2 ) + 5;
 
-      // vector perpendicular to the tangent in view (hence the minus sign for the angle, since y is inverted)
-      const perpendicularDisplacement = Vector2.createPolar( distance, -modelPerpendicularTangent );
+        // vector perpendicular to the tangent in view (hence the minus sign for the angle, since y is inverted)
+        const perpendicularDisplacement = Vector2.createPolar( distance, -modelPerpendicularTangent );
 
-      // position the label node perpendicular to the curve
-      labelNode.center = plottedPoint.center.plus( perpendicularDisplacement );
-    };
+        // position the label node perpendicular to the curve
+        labelNode.center = perpendicularDisplacement;
+      }
+    );
 
-    Multilink.multilink( [ labeledPoint.xProperty, yProperty, yDerivativeProperty, labeledPoint.labelProperty ], () => updateLabelPosition() );
-
-    options.children = [ plottedPoint, labelNode ];
+    options.children = [ plottedPoint ];
 
     super( options );
 
Index: js/common/view/PlottedPoint.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/PlottedPoint.ts b/js/common/view/PlottedPoint.ts
--- a/js/common/view/PlottedPoint.ts	(revision 65576d292bd972b898ef6fcd5961acc059bdd351)
+++ b/js/common/view/PlottedPoint.ts	(date 1674077312510)
@@ -39,7 +39,7 @@
 
       const x = xProperty.value;
       const y = yProperty.value;
-      this.center = chartTransform.modelToViewXY( x, y );
+      this.translation = chartTransform.modelToViewXY( x, y );
     };
 
     xProperty.link( updatePosition );

````
</details>

**Comment by pixelzoom** [comment]
@veillette and I worked on this together for a few minutes. We determined that the Multilink dependences could be refined (see above commit) and the patch in https://github.com/phetsims/calculus-grapher/issues/115#issuecomment-1396156360 is unnecessary.  

Closing.
