### ISSUE TITLE
Instrument only the curves and graphs that are relevant for a screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#116]
Currently, all screens have the full set of graphs instantiated and instrumented in the model and view. For example, for the _Derivative_ screen:

<img width="287" alt="screenshot_1975" src="https://user-images.githubusercontent.com/3046552/203393465-81a1ad05-29fc-4465-a0bb-a9ab86dd9ab0.png">

When we get closer to feature complete, we should prune what gets instrumented (and perhaps what gets instantiated) based on the `GraphSet[]` for each screen.

We should also verify that there is not some goal to be able to (for example) make the 2nd derivative and integral graphs visible on the _Derivatives_ screen.

**Comment by pixelzoom** [comment]
Here's the general idea of what I'd like to do to address this:

(1) Move GraphType and GraphSet from CalculusGrapherScreenView to GraphType.ts.

(2) Move options.graphSets to the Screen level, and pass to both the TModel and ScreenView subclasses.

(3) In CalculusGrapherScreenView, pass options.graphSets to GraphsNode.

(4) In GraphsNode, conditionally instrument each GraphNode instance, based on whether the GraphNode appears in options.graphSets.  For example:

```typescript
const derivativeGraphNode = new GraphNode( model.integralCurve,
...
        tandem: _.flatten( options.graphSets ).includes( 'derivative') ? 
                   options.tandem.createTandem( 'integralGraphNode' ) : Tandem.OPT_OUT
      } );
```

(5) In CalculusGrapherModel, also conditionally instrument the Curve instances based on whether they appear in options.graphSets.  For example:

```typescript
this.derivativeCurve = new DerivativeCurve( this.originalCurve, 
 _.flatten( options.graphSets ).includes( 'derivative') ? 
   options.tandem.createTandem( 'derivativeCurve' ) ) : Tandem.OPT_OUT;
```

For discussion at today's meeting with @veillette.

**Comment by veillette** [comment]
@pixelzoom volunteered to take on this issue.

**Comment by pixelzoom** [comment]
Done in the above commits. @veillette please review.  For each screen, verify that only the relevant curves and graph nodes are instrumented.  Also note that I did not conditionally instrument originalCurve, predictCurve, and originalGraphNode, since they should always be present.

**Comment by veillette** [comment]
That looks good and you also picked the copy-paste error in  `DerivativeScreenViewOptions` along the way  👍 .
