### ISSUE TITLE
Use of TModel and Screen<M,V>

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#117]
A couple of things related to TypeScript:

(1) Top-level model classes (like CalculusGrapherModel) are supposed to implement TModel.

(2) Screen is parameterized as Screen<M,V>, where M  is a TModel and V is a ScreenView. 

Unfortunately tsc currently can't help with this, because Screen.js is using IntentionalAny for the ScreenView params. I'm going to create a joist issue to address that.

**Comment by pixelzoom** [comment]
Addressed for Calculus Grapher in the above commit, and the more general issue has been reported in https://github.com/phetsims/joist/issues/886.

@veillette let me know if you'd like to discuss in our meeting today. Or if it's clear, feel free to close.

**Comment by veillette** [comment]
We have reviewed during the meeting. Closing
