### ISSUE TITLE
Name for f(x) curve

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#119]
We have several curves and graphs in the simulation. Since the name of the curves and graphs are exposed to PhET-IO, it is important to come up with names that encapsulate the nature of  the object. It has been pretty straightforward  to come up with such names for the curve that are related to f(x) such as 

```js
    this.predictCurve = new TransformedCurve( {
      tandem: options.tandem.createTandem( 'predictCurve' )
    } );

    this.derivativeCurve = new DerivativeCurve( this.originalCurve, options.tandem.createTandem( 'derivativeCurve' ) );
    this.secondDerivativeCurve = new DerivativeCurve( this.derivativeCurve, options.tandem.createTandem( 'secondDerivativeCurve' ) );
    this.integralCurve = new IntegralCurve( this.originalCurve, options.tandem.createTandem( 'integralCurve' ) );
```

However, we don't have a very good name for f(x) curve and f(x) graph itself. 
This issue tracks a new possible name for f(x). If I'm brainstorming a bit , I could come up with a few names:

- prototypalCurve
- archetypeCurve -> CM vetoed it as a very similar name appear in the studio tree
- primaryCurve
- fundamentalCurve
- primordialCurve
- mainCurve
- something else ??

Currently we used 'originalCurve' for f(x).

Assigning to @amanda-phet to think of an appropriate name, but @pixelzoom and @kathy-phet can weigh in as well.

**Comment by pixelzoom** [comment]
I originally (pun intended) thought that "original curve" might not be a great name.  But as I've been Google searching for a better term, I'm seeing hits like these:

* Finding the original function when given the derivative
* How do you find the original function and derivative of a graph?
* How does the second derivative relate to the original function?
* Given a Derivative Function, Integrate to Find the Original Function
* Derivative Graph vs Original Function

So "original function" seems to be the most common way to refer to f(x) in this content.  And I think it's fine to refer to "original curve" as the plot of the "original function".

**Comment by pixelzoom** [comment]
If we think that clarification of "original curve" is necessary, we might consider adding documentation to `originalCurve` in CalculusGrapherModel.ts:

```diff
    this.originalCurve = new TransformedCurve( {
      // originalCurve is always instrumented, because it should always be present.
      tandem: options.tandem.createTandem( 'originalCurve' ),
+     phetioDocumentation: 'curve that corresponds to the original function'
    } );
```

**Comment by veillette** [comment]
I added the documentation for PhET-IO. It is probably the right call to leave it as is but let's check with the other members of the team before closing.

**Comment by amanda-phet** [comment]
This sounds very appropriate to me!

**Comment by veillette** [comment]
I think we have a consensus to kept is as is. Closing.
