### ISSUE TITLE
Issues with the buttons

### ISSUE THREAD

**Issue by bryo5363** [phetsims/calculus-grapher#12]
I noticed that when selecting pedestal or freeform, the buttons extend out such that the buttons to the left of the two I mentioned will not be accessible. This isn't a huge issue but is something I noticed that should be cleaned up

![calculusgrapher3](https://cloud.githubusercontent.com/assets/7717368/7866012/ca8aea28-0529-11e5-97d7-0719a929932e.gif)

**Comment by amanda-phet** [comment]
It seems related to the tooltip text, like that text is extending the clickable region for that button.

**Comment by amanda-phet** [comment]
Closing this issue since we will not use tooltips in the HTML5 version.
