### ISSUE TITLE
Create separate Class named CueingArrowsNode

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#120]
OriginalGraphNode hosts a lot of logic to create and display an upAndDownArrow 
```js
      // set up and down arrow
    const centerX = CalculusGrapherConstants.CURVE_X_RANGE.getCenter();
    const tailX = this.chartTransform.modelToViewX( centerX );

    const downArrowTailY = 5;
    const downArrowTipY = CalculusGrapherConstants.ARROW_LENGTH + downArrowTailY;

    // property that track the visibility of the up and down arrow
    this.upAndDownArrowVisibleProperty = new BooleanProperty( true );

    // arrow options
    const arrowOptions = combineOptions<ArrowNodeOptions>( {
        fill: CalculusGrapherColors.arrowFillProperty,
        stroke: null,
        visibleProperty: this.upAndDownArrowVisibleProperty
      }, CalculusGrapherConstants.ARROW_NODE_OPTIONS
    );
    const downArrow = new ArrowNode( 0, downArrowTailY, 0, downArrowTipY, arrowOptions );
    const upArrow = new ArrowNode( 0, -downArrowTailY, 0, -downArrowTipY, arrowOptions );

    const upAndDownArrow = new Node( { children: [ upArrow, downArrow ], centerX: tailX } );

    // attach the up and down arrow to the curveNode to inherit its visibility.
    this.curveNode.addChild( upAndDownArrow );

    // set the visibility of up and down arrow to invisible if the curve has been touched once.
    originalCurve.curveChangedEmitter.addListener( () => {
      this.upAndDownArrowVisibleProperty.value = false;
    } );
```

This should be in its own class.

**Comment by veillette** [comment]
Also a better name would be DoubleHeadedArrow.

**Comment by pixelzoom** [comment]
The terminology that we've typically used for these arrows is "cueing arrows".  They cue the user that something can be dragged.  For example see CueingArrowsNode in geometric-optics, which renders these arrows:

<img width="1032" alt="screenshot_1989" src="https://user-images.githubusercontent.com/3046552/204656232-64c30576-a35b-4add-89d4-77941de98d86.png">

**Comment by pixelzoom** [comment]
See also SecondPointCueingArrowsNode in geometric optics, which is the red arrows shown in the screenshot below.

<img width="185" alt="screenshot_1990" src="https://user-images.githubusercontent.com/3046552/204656823-6ef3a8af-62fe-46bf-8b92-cd519d1a8674.png">

**Comment by pixelzoom** [comment]
In your implementation shown in https://github.com/phetsims/calculus-grapher/issues/120#issue-1468713262:

```typescript
const downArrow = new ArrowNode( 0, downArrowTailY, 0, downArrowTipY, arrowOptions );
const upArrow = new ArrowNode( 0, -downArrowTailY, 0, -downArrowTipY, arrowOptions );

const upAndDownArrow = new Node( { children: [ upArrow, downArrow ], centerX: tailX } );`
```

... I'd recommend simplifying by using a VBox:

```typescript
const upArrow = new ArrowNode( 0, 0, 0, -CalculusGrapherConstants.ARROW_LENGTH, arrowOptions );
const downArrow = new ArrowNode( 0, 0, 0, CalculusGrapherConstants.ARROW_LENGTH, arrowOptions );

const upAndDownArrow = new VBox( { 
  children: [ upArrow, downArrow ],
  spacing: 5
} );
```

**Comment by veillette** [comment]
SecondPointCueingArrowsNode is very similar to our need but CueingArrowsNode is a better name for our use case. So we will have CueingArrowsNode extends VBox using the simplification noted above.

**Comment by veillette** [comment]
All the logic about when to turn on/off the visibility of the cueingArrows still reside in OriginalGraphNode, but it still cleans up nicely. In any case it may prove to be very useful to have a separate class when we adressed #121.

**Comment by veillette** [comment]
We discussed in the 12/6 meeting if CueingArrowsNode should create its on visibility property, and passing the Emitter that control its visibility as an argument of the constructor of CueingArrowsNode. CM mentioned that this has been done previously but at this point I feel that the issue in #121 takes precedence and that we have already encapsulated a lot of the logic in creating a new CueingArrowsNode class. Closing
