### ISSUE TITLE
Layout of ControlPanel with additional curveManipulations buttons

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#122]
In #114 , we addressed how to instrument the curveManipulation buttons, such that we can make them (in)/visible.
As A result the controlPanel can expand to take into account extra buttons. However at some point, it starts to overlap with the tool checbkox and reset button. The layout of the controlPanel with respect to the other objects in the CGscreenView is set at the start of the sim and doesn't receive any update after initialization.

**Comment by pixelzoom** [comment]
Anything whose size changes (like CalculusGrapherControlPanel) need to be positioned dynamically via a boundProperty listener.   So in CalculusGrapherScreenView.js

```diff
Index: js/common/view/CalculusGrapherScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/CalculusGrapherScreenView.ts b/js/common/view/CalculusGrapherScreenView.ts
--- a/js/common/view/CalculusGrapherScreenView.ts	(revision 510f8df9a181e77955cfd03a1191bac3a62ba662)
+++ b/js/common/view/CalculusGrapherScreenView.ts	(date 1669913513528)
@@ -78,11 +78,14 @@
       this.predictModeEnabledProperty,
       this.visibleProperties,
       combineOptions<CalculusGrapherControlPanelOptions>( {
-        bottom: toolsCheckboxGroup.top - 20,
-        right: this.layoutBounds.right - 10,
         tandem: options.tandem.createTandem( 'calculusGrapherControlPanel' )
       }, options.controlPanelOptions ) );
 
+    controlPanel.boundsProperty.link( () => {
+      controlPanel.right = this.layoutBounds.right - 10;
+      controlPanel.bottom = toolsCheckboxGroup.top - 20;
+    } );
+
     toolsCheckboxGroup.left = controlPanel.left;
 
     this.graphsNode = new GraphsNode( model,
```

**Comment by pixelzoom** [comment]
I also think the overall layout would look better if `controlPanel` was top-aligned with the top graph.  See screenshot below for example. I realize that this may not match the mockups, but it's more consistent with other PhET sims.    And it gets controls away from the Reset All button, which we don't want users to hit accidentally.

Here's the patch:

```diff
Index: js/common/view/CalculusGrapherScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/CalculusGrapherScreenView.ts b/js/common/view/CalculusGrapherScreenView.ts
--- a/js/common/view/CalculusGrapherScreenView.ts	(revision 510f8df9a181e77955cfd03a1191bac3a62ba662)
+++ b/js/common/view/CalculusGrapherScreenView.ts	(date 1669913709546)
@@ -70,7 +70,6 @@
 
     const toolsCheckboxGroup = new ToolsCheckboxGroup( this.visibleProperties,
       {
-        bottom: resetAllButton.top - 10,
         tandem: options.tandem.createTandem( 'toolsCheckboxGroup' )
       } );
 
@@ -78,12 +77,15 @@
       this.predictModeEnabledProperty,
       this.visibleProperties,
       combineOptions<CalculusGrapherControlPanelOptions>( {
-        bottom: toolsCheckboxGroup.top - 20,
         right: this.layoutBounds.right - 10,
+        top: this.layoutBounds.top + 20,
         tandem: options.tandem.createTandem( 'calculusGrapherControlPanel' )
       }, options.controlPanelOptions ) );
 
-    toolsCheckboxGroup.left = controlPanel.left;
+    controlPanel.boundsProperty.link( () => {
+      toolsCheckboxGroup.left = controlPanel.left;
+      toolsCheckboxGroup.top = controlPanel.bottom + 20;
+    } );
 
     this.graphsNode = new GraphsNode( model,
       this.predictModeEnabledProperty,
```

<img width="1034" alt="screenshot_1995" src="https://user-images.githubusercontent.com/3046552/205113274-3138f971-646b-4821-add8-e0673da01dbb.png">

**Comment by veillette** [comment]
I committed the first patch suggested by @pixelzoom  where we listen to the bounds of the controlPanel and adjust its position relative to the toolCheckboxGroup. I also checked that it addresses the issue in Studio.

I'm going to assign to @amanda-phet to see if she would like me to apply the second patch (https://github.com/phetsims/calculus-grapher/issues/122#issuecomment-1334067843) where we top align the control panel. l recalled that we had discussions about the position of the control panel relative to the graphs. Another advantage of being top aligned, besides the ones mentioned above, is that it provide some visual continuity to all screens. 

Assigning to @amanda-phet

**Comment by pixelzoom** [comment]
> Another advantage of being top aligned, besides the ones mentioned above, is that it provide some visual continuity to all screens.

This is why we typically top-align control panels that are common to 2 or more screens -- so that the control panels don't jump around when switching screens.

**Comment by pixelzoom** [comment]
Regardless of whether we decided to top-align the control panel, there was still a potential dynamic-layout problem with `controlPanel` and `toolsCheckboxGroup`.  I addressed it in the above commit by putting them in a left-aligned VBox.  @veillette feel free to have a look.

**Comment by amanda-phet** [comment]
The panel should be top-aligned on all screens, yes. 

I've been holding off on what I call "pixel polishes" because things were still flux, but this was one of them.

**Comment by veillette** [comment]
I aligned the control panel in the above commit. Assigning to @amanda-phet for review.

**Comment by veillette** [comment]
The top of the referenceLineNode, although invisible, is determining the top of GraphsNode. We can reach inside GraphsNode, to find the top of the top graph

**Comment by veillette** [comment]
The value graphNode.y =0 is the top of the rectangle of the chart. Setting the top graphNode at y=0 in GraphsNode, ensures that we can easily align the top of the first graph with the control panel. Done in the commit above.

**Comment by veillette** [comment]
Assigning to @pixelzoom and @amanda-phet for review.

**Comment by veillette** [comment]
I also see that you set the rightVBox bound listener based on graphsNode,y, such that they always stay in sync even when the bounds of the rightVBox are changing. That looks better.

**Comment by veillette** [comment]
Assigning to @amanda-phet  to review.

**Comment by amanda-phet** [comment]
Alignment of the top graph and the panel looks good to me.

**Comment by veillette** [comment]
Our work is done here. Closing
