### ISSUE TITLE
Make it possible to set pdomOrder in CalculusGrapherScreenView

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#123]
So that this sim can easily support alternative input in the future....  

In CalculusGrapherScreenView.ts, replace this:

```typescript
    this.addChild( this.graphsNode );
    this.addChild( controlPanel );
    this.addChild( toolsCheckboxGroup );
    this.addChild( resetAllButton );
```

... with:

```typescript
    const screenViewRootNode = new Node( {
      children: [
        this.graphsNode,
        controlPanel,
        toolsCheckboxGroup,
        resetAllButton
      ]
    } );
   this.addChild( screenViewRootNode );
```

The reason for this is covered in detail in "Approach 2" of https://github.com/phetsims/phet-info/blob/master/doc/alternative-input-quickstart-guide.md#traversal-order.   But in a nutshell, focus traversal (aka "tab order") must to be set via the `pdomOrder` property of a Node, and it cannot be set directly on the ScreenView.  So (eventually, you don't need to do this now) the `pdomOrder` will be specified in CalculusGrapherScreenView.ts like this:

```typescript
screenViewRootNode.pdomOrder = [
  this.graphsNode,
  controlPanel,
  toolsCheckboxGroup,
  resetAllButton
];
```

Let me know if you have any questions.

**Comment by pixelzoom** [comment]
I see that `addChild( graphSetRadioButtonGroup )` is also called in subclasses AdvancedScreenView and LabScreenView.  So in CalculusGrapherScreenView, you'll need to add:

 `protected readonly screenViewRootNode: Node`

.. and in the subclasses:

`this.screenViewRootNode.addChild( graphSetRadioButtonGroup )`

**Comment by pixelzoom** [comment]
I'll do this while working on https://github.com/phetsims/calculus-grapher/issues/106.

**Comment by pixelzoom** [comment]
This was addressed in the above commit. @veillette ready for review.

Note that responsibility for creating `graphSetRadioButtonGroup` was moved to CalculusGrapherScreenView in https://github.com/phetsims/calculus-grapher/commit/305f35ecfd1b496b3affbfa8ed5b04d025dfba20 while working on https://github.com/phetsims/calculus-grapher/issues/106.

**Comment by veillette** [comment]
On 12/6, we discussed the PDOM and how we can test the PDOM in phetBrand . In #125, we will addressed the general question of how to support alternative input for the drag handler.  The work done here sets the stage to make it easier to set the PDOM in CalculusGrapherScreenView, without actually implementing a PDOM order. We can close this issue.
