### ISSUE TITLE
Create PredictModeRadioButtonGroup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#127]
Related to https://github.com/phetsims/calculus-grapher/issues/100 ...

I will create PredictModeRadioButtonGroup.  It controls `predictModeEnabledProperty`. The buttons should be inside the control panel, at the top.

**Comment by pixelzoom** [comment]
Done, see screenshot review.  @veillette ready for review.

<img width="175" alt="screenshot_2008" src="https://user-images.githubusercontent.com/3046552/206053566-27ee5d4b-43db-4c64-9d7c-9f9a1bf7bbad.png">

**Comment by pixelzoom** [comment]
Also note the tandem names of the radio buttons - `originalCurveRadioButton` and `predictCurveRadioButton`.   Since this property control `predictModeEnabledProperty: Property<boolean>`, the values are actually `false` and `true` respectively. But I know that @amanda-phet dislikes `falseRadioButton` and `trueRadioButton`.


<img width="270" alt="screenshot_2010" src="https://user-images.githubusercontent.com/3046552/206057550-f7825889-888c-4f9b-819c-eeba5c0cfea5.png">

**Comment by veillette** [comment]
I like the generalization of `LabelColorIcon`.  We can address the name and type of predictModeEnabledProperty in #100 if necessary. Closing
