### ISSUE TITLE
Review type of super class options 

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#128]
@pixelzoom shared that in general, if a class is responsible for a super class option, it should omit that super class option from its Options type. (Whew… that’s a mouthful.)  children is a common example.   But here’s the general pattern:
```js
type SelfOptions = ...;

// Omit options that Widget is responsible for setting, so they cannot be provided by callers.
type WidgetOptions = SelfOptions & StrictOmit<ParentOptions, 'something' | 'somethingElse'>;

export default class Widget extends Parent {

  public constructor( ..., providedOptions?: WidgetOptions ) {

    const options = optionize<WidgetOptions, SelfOptions, ParentOptions>()( {

      // sometimes the Parent option can be set here:
      something: ...
    }, providedOptions );
    ...

    // sometimes the Parent options needs to be set later:
    this.somethingElse = ...;
  }
}
```
The above is a bit more detailed explanation of guideline (3) in https://github.com/phetsims/phet-info/blob/master/doc/phet-software-design-patterns.md#options-typescript

It would be worth taking a look particularly for `options.children`.

**Comment by pixelzoom** [comment]
I was thinking that at some future point (closer to feature-complete?) that @veillette and I would go through all of the source files and review the options pattern.

**Comment by veillette** [comment]
and I mislabeled this relevant commit  https://github.com/phetsims/calculus-grapher/commit/16eb15ccb0875ee7013fa99c2642f0c6bee148fa

**Comment by veillette** [comment]
I did a search with regex for `\n    options\..*=`  which revealed 13 option assignments within a constructor (the vast majority of which where `options.children= ...`. This seems to take care of all of them at this point.

**Comment by veillette** [comment]
We can come back to this later. Assigning deferred for right now.

**Comment by pixelzoom** [comment]
I made a pass through all source files, and made 2 types of changes in the above commits:

* Where parameter `providedOptions` was being used only to pass `tandem`, I replaced it with parameter `tandem: Tandem`.
* When composing options types, I narrowed the parent options using `PickOptional` and `PickRequired`.

@veillette please have a look, see if I missed anything, or if you have questions. Also feel free to close.

**Comment by veillette** [comment]
I fixed some typos regarding  `GraphNodesOptions` -> `GraphsNodeOptions`.

Everything else looks good. Closing
