### ISSUE TITLE
@ts-expect-error in GraphNode.ts

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#129]
For https://github.com/phetsims/chipper/issues/1366 ...

In GraphNode.ts:

```typescript
      // @ts-expect-error, complains about number being the index of an array
      const spacing = Math.pow( 10, zoomMultiples ) * lookUpArray[ [ zoomModulo ] ];
```

Looks like there may be an extra set of brackets here. @veillette should it be `lookUpArray[ zoomModulo ]` ?

**Comment by veillette** [comment]
I thought that I needed the ts-expect-error because typescript didn't like the fact that I was using a number, and not just an integer as an index. It never occurred to me that I had the wrong number of brackets. Now, I can't understand how it could even work in the first place!!

**Comment by veillette** [comment]
The issue is addressed. Closing.
