### ISSUE TITLE
Discussion of appropriate data structure of CurvePoint and Curve to keep track of discontinuities

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#132]
Since we expose the model of the curve and curvePoint to the PhET-IO client, we should come up with a data structure that keep track of discontinuities.
For instance, for the following points, which points (if any should should be labelled a discontinuity).

![image](https://user-images.githubusercontent.com/7633344/207709829-7f2f800f-b7e5-4ac3-a016-69a474a53196.png)

Discussing on the 12/14 meeting with @pixelzoom.

Jotting some ideas about how to handle this.

|   | Model                       | View                                                      | Pro                                                                                                               | Cons                                |
| - | --------------------------------------------------------- | ----------------------------------------------------------------------- | ---------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------- |
| 1 | Tag point a discontinuity and add other curve Point with same X value (also labelled a discontinuity) | We can parse the curve to find pairs of discontinuities                                           | Very easy to handle in the view                                                                                   | What should the Y value of the newly added curvePoint? Hard to implement in the model. Very invasive               |
| 2 | Tag a point with a discontinuity and set y value to null        |  A model discontinuity point is replaced by a pair of point (t to the left and right of x value)    | curve made of segments, easy to handle mathematically easy to go from cusp to discontinuities with derivatives   |  Y value is a number or null.  Hard with typescript              |
| 3 | Tag pairs of adjacent x points as discontinuities,.     | Identify the pairs And draw vertical lines between y values                                      | Keep same structure for curve, merely a matter of tagging points in the model. Easy to implement                  | A bit dubious mathematically speaking.                               |
| 4 | Tag a curve point as discontinuity ,assume the y value belong to the right of the curve.         | Find the matching y value of a discontinuity to the right of a point and draw a line between them | Keep same structure for curve, merely a matter of tagging points in the model. Probably the easiest to implement. | As a model of a mathematical curve, it is the most dubious. Make assumptions that are very model dependent.         |
| 5 | Tag a point a discontinuity and “augment it” by saving the additional y value of the discontinuity. The addtional y value is the value to the right , whereas the nominal value, matches the curve to the left.   | A discontinuity has all the built in information to be drawn in the view                          | Model matches mathematical expectations of how discontinuities work       | What should newly Y value be?  Strange data structure for curvePoint Need to consider how to iterate over x values. Model as built in assumptions|

**Comment by veillette** [comment]
We discussed the costs and benefits of the five approaches outlined above in 12/14 meeting.
We agreed that solution (1) is a costly one and probably difficult to implement.

@pixelzoom volunteered to investigate solution (2)

**Comment by veillette** [comment]
At the heart of this discussion is what is a mathematically correct way to model a curve.
The curve in calculus-grapher is discretized into a series of points. 

For continuous curve, at a given point x=a, one would usually save the y value given by f(a).
For a continuous curve, the three following expressions would be the same 
- $f(a)$
- $\lim_{x \rightarrow a^+} f(x)$
- $\lim_{x \rightarrow a^-} f(x)$

However, if a curve is discontinuous, then the value $f(a)$ may not exist at this point, but the two other limits can be well defined. 
An example of this is the derivative of $f(x) = |x|$, where $df/dx$ is equal is well defined everywhere except at $x=0$. The $f'(0)$ is undefined but $f'(0^+)=1$ and $f'(0^-)=-1$

As we discretized a curve, should we keep track of only $f(a)$, or $\lim_{x \rightarrow a^+} f(x)$ and/or  $\lim_{x \rightarrow a^-} f(x)$. 

It is also important to keep in mind that discussion should not solely be based on mathematically "correctness" . It is important to consider how a PhET-IO client might want to use the data for rendering a curve as well as rendering discontinuities without having to know the details of the rendering in the view.

**Comment by pixelzoom** [comment]
Some additional notes from our 12/14/2022 meeting ...

The approach of setting y to `null` for discontinuities is more mathematically correct. It is not the case that there are 2 solutions for f(x) at a discontinuity.  There are no solutions for f(x) at a discontinuity. 

A goal/requirement is that a PhET-iO client should be able to plot set of CurvePoints in a wrapper. So usability and complexity of the PhET-iO data stream is a major consideration for which approach we choose. It needs to be something that we can easily explain in the Client Guide.  And ideally, the wrapper writer should not need to duplicate workarounds/Hollywooding that we used to make a curve look correct in the view.

**Comment by pixelzoom** [comment]
Over in https://github.com/phetsims/calculus-grapher/issues/145, we noted that decisions here affect what is displayed by the AncillaryTools (reference line, point labels, vertical lines, etc.).  They currently display a numeric y value, and have no information about whether a discontinuity exists. 

Options:

(1) Use `y: number | null` everywhere, where `null` indicates a discontinuity.  This is the recommended option, as long as it meets @amanda-phet's expectations.

(2) Use `y: number | null` only in AncillaryTool.  Relatively easy to implement. But CurvePoint and AncillaryTool would then have different representations for y values at discontinuitites.  So this option feels like it could be trouble for both PhET-iO clients and future maintainers.

(3) Show CurvePoints instead of y values in AncillaryTool.  This will provide all the information about y (discontinuity, cusp, etc.) but makes the Properties associated with AncillaryTool much more difficult for the PhET-iO client to parse. 

(4) Continue to use `y: number` everywhere. AncillaryTool will have no information about discontinuities. Maybe that's OK?

Before we proceed with this, we need to discuss the tradeoffs/implications with @amanda-phet. Labeling for design meeting.

**Comment by veillette** [comment]
We decided to opt for option number 1 at our 1/5/23 meeting.

**Comment by pixelzoom** [comment]
@veillette will document our decision here, then close.

**Comment by veillette** [comment]
After looking options (2) in  #133, we find that it involved very invasive choices to the model. 

After reflections we find the option (3) will be the way forward: that is all y values will be numbers.
A discontinuity will be tagged using a PointType. 
 
One way to understand/ justify this annotation is the following.
The blue curve below represents the real curve that we are trying to represent.
Our curve Model representation is a series of points at equally spaced intervals:

![image](https://user-images.githubusercontent.com/7633344/213014730-97a37f6e-0ea8-4571-91a9-b34f08ebdb63.png)

As you can see, in the image above, the discontinuity falls in between two adjacent points. (One can argue that the likelihood that a discontinuity falls exactly at a given curvePoint is a set of measure 0, since the x-space spanned by two adjacent curve contains in infinite number of real numbers). As a result, the yellow points above would be tagged as discontinuous, since they are adjacent to a discontinuity. The real discontinuity falls in between the two points tagged as a discontinuity. Although the curve points are tagged as discontinuous, there is a well defined y value that exists at that point, which a capture in their y field.

**Comment by veillette** [comment]
There is enough information here about the decision for our data-structure for future maintainers., We can close this issue at this point (pun ;)

**Comment by pixelzoom** [comment]
> After looking options (2) in https://github.com/phetsims/calculus-grapher/issues/133, we find that it involved very invasive choices to the model.
> 
> After reflections we find the option (3) will be the way forward: that is all y values will be numbers.
A discontinuity will be tagged using a PointType.

Minor correction, for posterity... The 3 options were enumerated in https://github.com/phetsims/calculus-grapher/issues/132#issuecomment-1370291607, not https://github.com/phetsims/calculus-grapher/issues/133.  We discovered that option (1) was too invasive, and chose (2) as the way forward.
