### ISSUE TITLE
Polish font sizes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#134]
Polish the font sizes used in this sim.

Before doing that... Factor out consistent font sizes for controls, labels etc.  Fonts and/or sizes should be in CalculusGrapher.ts, so they can be changed in one place.

As @veillette has noted previously, font sizes in GraphTypeLabelNode.ts are interdependent, and should be adjusted with care.

**Comment by pixelzoom** [comment]
Summary of above commits:

All fonts sizes are now controlled via these constants in CalculusGrapherConstants.ts. This will make it trivial to polish font sizes.  @amanda-phet please let us know if you'd like to change any of these values.

```typescript
  // fonts
  GRAPH_LABEL_FONT: new PhetFont( 16 ), // wherever graph labels like f(x), f'(x), etc. appear
  CONTROL_FONT: new PhetFont( 12 ), // for text on checkboxes, radio buttons, push buttons, etc.
  ACCORDION_BOX_TITLE_FONT: new PhetFont( 14 ) // for accordion box titles
```

@veillette FYI... For GraphTypeLabelNode, these additional options and default values were added. This makes it possible to simply change `GraphTypeLabelNodeOptions.fontSizeOptions.nominalFontSize`, and other font sizes will be computed proportionally.   Note the proportions used are identical to the font sizes that @veillette had previously implemented, so there is no change in the "look" of the sim.

```typescript
type FontSizeOptions = {

  // This value determines the size of the symbols 'f', 'd', 'x', and 't'. Typically, you'll want to set
  // nominalFontSize, and the sizes of other parts of the label will be computed proportionally.
  nominalFontSize?: number;

  // Leave these alone (use the defaults), unless you need to tweak for specific cases.
  integralSymbolFontSize?: number;
  limitsFontSize?: number;
  fractionFontSize?: number;
};
....
      fontSizeOptions: {
        nominalFontSize: NOMINAL_FONT_SIZE,
        integralSymbolFontSize: 1.5 * NOMINAL_FONT_SIZE,
        limitsFontSize: 0.5 * NOMINAL_FONT_SIZE,
        fractionFontSize: 0.75 * NOMINAL_FONT_SIZE
      }
```

**Comment by amanda-phet** [comment]
I'm more familiar with things being 16pt, but 14 looks ok to me. I think we should increase CONTROL_FONT to 14. 

Can we also change the height of the checkboxes to match the height of the text? We started doing this in recent sims and I think it looks better.

**Comment by pixelzoom** [comment]
> I'm more familiar with things being 16pt, but 14 looks ok to me. I think we should increase CONTROL_FONT to 14.

Done in 94660f04.

> Can we also change the height of the checkboxes to match the height of the text? We started doing this in recent sims and I think it looks better.

Done in the above commits.

**Comment by veillette** [comment]
TODO: @amanda-phet mentionned that all boxes of the checkboxes  should have the same uniform size, including the one with icons.

**Comment by amanda-phet** [comment]
We also discussed using 16pt font, so increasing CONTROL_FONT to 16, and adjusting the checkbox height accordingly.

**Comment by veillette** [comment]
CONTROL_FONT is set to 16.

**Comment by veillette** [comment]
Assigning to @amanda-phet to review the simulation and see if we need to change fonts or subclasses some font if needed.

**Comment by amanda-phet** [comment]
Ideally accordion_box_title_font is also 16, so we are consistent everywhere in the sim. Sorry I missed that one.

**Comment by veillette** [comment]
Done in the commit above. 
As a result this uncovers a problem with overlap when numerical values are visible. 
![Calculus Grapher screenshot (24)](https://user-images.githubusercontent.com/7633344/211401505-98df6746-7d37-4202-8216-3851d8b46f25.png

We have an issue in #135 for spacing and layout.

**Comment by veillette** [comment]
Reassigning to @amanda-phet to review and close if appropriate. We can tackle the overlapping accordion box with the graph in #135.

**Comment by veillette** [comment]
Reviewed a=in zoom meeting. CLosing.
