### ISSUE TITLE
QA testing of PhET-iO features.

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#137]
This issue is a placeholder to remind the QA team to test the PhET-IO features in #111, #112, and #113.

**Comment by pixelzoom** [comment]
I think we should close this issue.  Why not point QA to example.md (https://github.com/phetsims/calculus-grapher/issues/212) for this list of features?  That would eliminate duplicate documentation, and ensure that example.md is tested.

Labeling for discussion in design meeting.

**Comment by veillette** [comment]
We will include the phet-io features in examples.md to list the specific features in Phet-IO.

**Comment by veillette** [comment]
We can close this issue.
