### ISSUE TITLE
screen icons

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/calculus-grapher#139]
need to create these

**Comment by pixelzoom** [comment]
There's nothing like some really bad temporary screen icons to motivate creation of actual screen icons.  So in the above commit, I added these temporary icons:

<img width="878" alt="screenshot_2191" src="https://user-images.githubusercontent.com/3046552/214213547-6cd722f3-0703-4725-9738-83c28eeae63f.png">

**Comment by veillette** [comment]
I'll mention that it is possible to generate programmatically icons with a curve with areaUnderTool or tangentTool if we need to We can make theses tools "bolder" such that they stand out more.

**Comment by pixelzoom** [comment]
Adding "design-meeting" label here, so we can discuss at next design meeting. We'd like to have a general idea about what @amanda-phet has in mind.  Will screen icons, be artwork, code, or a combination?

**Comment by amanda-phet** [comment]
I think they will likely be made programmatically. I will plan to bring up the design of these next time I meet with @catherinecarter (Monday 2/6/23).

**Comment by amanda-phet** [comment]
@catherinecarter is going to take a first stab at these!

**Comment by catherinecarter** [comment]
@pixelzoom and @veillette, here is a pass at the screen icons. 
![Screenshot 2023-03-07 at 9 19 58 AM](https://user-images.githubusercontent.com/109630002/223483739-31c71494-a184-4e1b-bb04-17cada1b9230.png)
![Screenshot 2023-03-07 at 9 20 09 AM](https://user-images.githubusercontent.com/109630002/223483767-77ae3692-2b28-40f9-b6a4-a94d404d3d0e.png)

A question for the two of you is if it would be worth creating these icons programmatically? I was thinking of a PhET-iO client possibly changing the color of the curves, or the color of the tangent/area and wondering if the icons could possibly update as well? 
Before making any polished pngs, I'd love to hear whether this would be worth exploring.

**Comment by pixelzoom** [comment]
Since changing those colors has been made possible via the PhET-iO API, anything that needs to update when those colors are changed must be created programmatically.  And that would seem to include the screen icons. 

Before we dive into implementing them, I think we should have a design meeting. The icons in the above mockup are quite a bit more detailed than the typical screen icon.  I'm wondering if we could reduce their complexity a bit by identifying what you feel is most important in each icon.

**Comment by amanda-phet** [comment]
Let's have a design meeting to discuss. @catherinecarter and I talked about what we wanted each screen icon to communicate, and I think these are fairly simplified, but it would be good to hear what others think, and also show you some other iterations we considered that led to this set.

**Comment by catherinecarter** [comment]
03/07/23
CM: thinking about one piece of the curve with a giant tangent line to all the curve to highlight what's important on each screen.
Derivative
<img width="302" alt="image" src="https://user-images.githubusercontent.com/109630002/223502741-85a4af3c-6154-4462-98e5-04173351888d.png">
 
Integral
<img width="264" alt="image" src="https://user-images.githubusercontent.com/109630002/223502622-7c72fd4d-d239-4419-bef9-78ac65ce5dd1.png">

For advanced screen:
<img width="161" alt="image" src="https://user-images.githubusercontent.com/109630002/223501576-7d380d36-2791-4047-b1de-3c04b7afb5d2.png">

For Lab screen: 
<img width="290" alt="image" src="https://user-images.githubusercontent.com/109630002/223501491-ac7d1fc0-e2e1-4d8e-84eb-eb5751f86445.png">

**Comment by amanda-phet** [comment]
Had a mini meeting 3/7/23 and simplified the graphs so they could be drawn in code. 

Here are the functions we'd like to use 

1. Derivative 

![image](https://user-images.githubusercontent.com/7852916/223502905-d0b46902-db55-451e-8915-28a984d6df02.png)

3. Integral 

![image](https://user-images.githubusercontent.com/7852916/223502739-6adbf03e-e731-4e36-9300-4aacfbbd897c.png)

4. Advanced  

![image](https://user-images.githubusercontent.com/7852916/223501583-9f580c92-c793-4d87-8f2a-51497ae80a3d.png)

5. Lab 
![image](https://user-images.githubusercontent.com/7852916/223503067-ad445e7d-8198-4499-8980-3e8899f22e01.png)

**Comment by pixelzoom** [comment]
@veillette and I discussed.  I'll take a first stab at this.

Note to self: If drawing anything that needs to be clipped to ScreenIcon, https://github.com/phetsims/joist/issues/532 may be a problem and will require separate instances for navigationBarIcon.  See for example FocusAndDirectrixScreen.ts in graphing-quadratics.

**Comment by pixelzoom** [comment]
3/8/2023 design meeting: @amanda-phet @catherinecarter @kathy-phet @veillette @pixelzoom

As part of our discussion in #255, we decided to simplify the icons for the first 2 screens:

* Derivative: derivative expresssion, with a small red curve below it
* Integral screen: integral expression, with a small green curve below it

**Comment by pixelzoom** [comment]
@amanda-phet @catherinecarter screen icons are ready for review.  See screenshots of Home screen and navigation bar below.   Note that the icons for screens 1, 2, 4 share the same curve shapes for f(x), integral, and derivative.  And the icons for screens 1,2 update to match the "Variable" and "Notation" preferences.

Thanks to @veillette for pairing on creation of the curve shapes. 

<img width="868" alt="screenshot_2393" src="https://user-images.githubusercontent.com/3046552/223866211-ac1403cd-0768-4e16-869a-295674916f2f.png">

<img width="949" alt="screenshot_2394" src="https://user-images.githubusercontent.com/3046552/223866228-b9766f44-fba2-4954-bef8-30d2f3956ada.png">

**Comment by amanda-phet** [comment]
These look very nice!! 

I wonder how they would look if the graphs went edge-to-edge (so from left edge to right edge). I think the Advanced screen is the one that would look better that way, so we'd obviously need to do the same for all screens... but I'm not sure the effort involved.

**Comment by catherinecarter** [comment]
I think the extended lines look great, and while the symbols are smaller in the nav bar, they're great on the home screen. Seems if anyone really wanted to study the symbols, they could go back to the homescreen and click the icon to investigate larger. IMHO, they look really good.

**Comment by kathy-phet** [comment]
I can go either way, but have a slight preference for the first 3 icons from the top image and then for the 4th icon, something in between the top and lower image, where the lines extend closer to the edge similar to Advanced icon in the top image but they still have some whitespace before the edge.

**Comment by pixelzoom** [comment]
@amanda-phet your decision?

**Comment by pixelzoom** [comment]
@kathy-phet What do you mean by "the top image"?  Do you mean the image in https://github.com/phetsims/calculus-grapher/issues/139#issuecomment-1460972802? 

@amanda-phet your decision?

**Comment by amanda-phet** [comment]
Why did it make the symbols smaller? I was thinking the space to the right and left edges would just get filled with the strokes. I can see why screen 3 would have more of a change to fit both, but not sure why screens 1, 2 were so affected. 

I prefer v2 with the curves going edge-to-edge and would like to just make the symbols on screens 1,2 larger.

**Comment by amanda-phet** [comment]
Had a quick chat with @pixelzoom about some of the challenges with how the icons get created by common code, so I'd like to do this: Screens 1,2, 4 will be the "original" design (cropped curves with larger symbolic notation) and screen 3 will use the "new" design (edge-to-edge curve).

**Comment by pixelzoom** [comment]
Done in the commits above.  Here are revised screenshots. @amanda-phet please review, close if OK.

<img width="926" alt="screenshot_2405" src="https://user-images.githubusercontent.com/3046552/224170255-6271d82e-c8e6-4dcd-993b-3f974dda477f.png">

<img width="1000" alt="screenshot_2406" src="https://user-images.githubusercontent.com/3046552/224170280-c08bab75-cdd1-450f-86f1-bc9edf2bdc47.png">

**Comment by pixelzoom** [comment]
Since I suspect someone will ask...  Icons for screens 1,2,4 all use the same 3 curves. Making the curves wider for the Lab icon, without changing the shape of the curves, would take 30-60 minutes.  I'd need to parameterize all 3 curves, then fiddle with the parameters to make them look right.  I'm happy to do that if you really think it's worth the time.

**Comment by pixelzoom** [comment]
I've spent 5 hours on this issue so far.

**Comment by amanda-phet** [comment]
These look great to me. Thanks @pixelzoom !
