### ISSUE TITLE
Finalize Colors

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/calculus-grapher#140]
Played briefly because I couldn't resist. Two small design polishes to consider here ...

- For some reason, my brain would have an easier time if brighter green was positive and the darker was negative (subtracting) in the area integral screen.
- It might be nice if the brighter and darker area was also reflected in the bar graph so if it was negative it was darker and if it was positive it was the brighter green (assuming we switch the colors).

**Comment by veillette** [comment]
The switch in color was implemented above. I have moved the second suggestion about the Barometer to its own issue (see #147) since it requires to add some additional logic.

**Comment by amanda-phet** [comment]
@veillette can you add the integral colors to the color editor?

**Comment by veillette** [comment]
It is available at 
![image](https://user-images.githubusercontent.com/7633344/210283573-278a5574-d1f7-4b51-8e3d-e42099f2c8c8.png)

You probably already know this though. If I read between the lines, I think you may mean that you would like to have individual controls over some colors of the AreaUnderCurve.

In `AreaUnderCurveToolNode.js` I have
```
    function getColorShadeProperty( factor: number ): TReadOnlyProperty<Color> {
      return new DerivedProperty(
        [ CalculusGrapherColors.integralCurveStrokeProperty ],
        color => color.brighterColor( factor ) );

    // main color for scrubber
    const mainFillProperty = getColorShadeProperty( 1.0 );

    // colors for the shaded area charts, one for positive value and the other for negative values
    const positiveFillProperty = getColorShadeProperty( 0.8 );
    const negativeFillProperty = getColorShadeProperty( 0.6 );
```

So the positive and negative fill of the shaded area are "derived" from `integralCurveStrokeProperty`.
These number (0.8 and 0.6) could be changed to whatever you want. 

Or you would prefer to have completely customizable colors for the positiveFill and negativeFill?

**Comment by veillette** [comment]
I proactively promoted `IntegralPositiveFill` and `IntegralNegativeFill` to the `CalculusGrapherColors`, which should allow @amanda-phet to more easily explore different color palettes.

**Comment by pixelzoom** [comment]
These new colors violated the tandem naming convention for ProfileColorProperty:

> assert.js:28 Uncaught Error: Assertion failed: Property tandem.name must end with ColorProperty: calculusGrapher.global.view.colorProfile.integralPositiveFillProperty
    at window.assertions.assertFunction (assert.js:28:13)
    at new ProfileColorProperty (ProfileColorProperty.ts:65:15)
    at CalculusGrapherColors.ts:98:33

I think that convention is problematic - see https://github.com/phetsims/scenery/issues/1512.   Until that issue is resolved, do nothing.  In the meantime, I've changed the tandem names to satisfy the convention.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/scenery/issues/1512 has been addressed.  In addition to "ColorProperty", "FillProperty" and "StrokeProperty" are acceptable suffixes for ProfileColorProperty tandem name.  I've adjusted tandem names accordingly in the above commit.

**Comment by amanda-phet** [comment]
Yes, I meant area under the curve colors, sorry about that. Thanks for adding them to the color editor! That will make it easier to specify and see them in action.

**Comment by pixelzoom** [comment]
In today's design meeting, we change predictCurveStrokeProperty from  `rgb(128, 128, 128)` to '#ff00cf'.

**Comment by amanda-phet** [comment]
1. I had a discussion yesterday with @catherinecarter and @ariel-phet about colors, and we like the colors, but are leaning toward making the green darker. Please change `calculusGrapher.integralCurveStroke` to be `#00853E`. 

2. The graph backgrounds have a layer applied to them right now, but what we want is for them to be exactly the same as the sim background. So, `calculusGrapher.defaultChartBackgroundFill` needs to have 0 opacity to look the way I'd like it to look.

**Comment by pixelzoom** [comment]
@amanda-phet I've made your change requests in the above commit, please review. Note that `defaultChartBackgroundFill` still exists, but is initialized to the color of `screenBackgroundColor`, `rgb( 243, 252, 254 )`.

If this looks OK, please close.

**Comment by amanda-phet** [comment]
Colors look good. Closing.
