### ISSUE TITLE
Reset for PhET-iO only properties

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#141]
While working on #111 and #115, I noticed the the reset for the color, visibility and label of the pointLabel  does not work

**Comment by veillette** [comment]
In GraphsNode.s, we have, for instance,
```js
    const verticalLinesLayerTandem = options.tandem.createTandem( 'verticalLinesLayer' );
    const verticalLinesNode = model.labelledVerticalLines.map( ( verticalLine, index ) => {
        const label = CalculusGrapherModel.intToUppercaseLetter( index );
        const verticalLineNodeTandem = verticalLinesLayerTandem.createTandem( `${label}VerticalLineNode` );

        const colorProperty = new ColorProperty( new Color( 0x000000 ),
          { tandem: verticalLineNodeTandem.createTandem( 'colorProperty' ) } );
        const labelProperty = new StringProperty( label,
          { tandem: verticalLineNodeTandem.createTandem( 'labelProperty' ) } );
        const visibleProperty = new BooleanProperty( false,
          { tandem: verticalLineNodeTandem.createTandem( 'visibleProperty' ) } );

        const verticalLineNode = new VerticalLineNode( verticalLine, originalGraphNode.chartTransform, {
          x: originalGraphNode.x,
          cursor: null,
          dragListenerEnabled: false,
          lineOptions: {
            lineDash: [ 4, 2 ],
            stroke: colorProperty
          },
          sphereOptions: { visible: false },
          labelProperty: labelProperty,
          visibleProperty: visibleProperty,
          tandem: verticalLineNodeTandem
        } );

        return verticalLineNode;
      }
    );
```

but we never reset the colorProperty, the stringProperty and visibleProperty.

**Comment by pixelzoom** [comment]
In general, if something cannot be changed via the sim's UI, and can only be changed via PhET-iO, then we do not reset it when "Reset All" is pressed.

I'm not 100% certain that the things you've identified here can only be changed by PhET-iO.
But if the color is part of the sim's color profile, we do not reset it.  If the stringProperty is part of the sim's translated strings, we do not reset it. And it also looks like visibleProperty in this case may only be accessible via PhET-iO, in which case we do not reset it.

**Comment by pixelzoom** [comment]
@veillette I'm pretty sure there's nothing to do here, and that this issue can be closed.

**Comment by veillette** [comment]
Closing since we don't reset PhET-IO only properties.
