### ISSUE TITLE
Conditionally instrument visibleProperties

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#143]
visibleProperties.areaUnderCurveVisibleProperty and visibleProperties.tangentVisibleProperty need to be conditionally instrumented.   This can be done by passing CalculusGrapherModelOptions.hasTangentTool and hasAreaUnderCurveTool to CalculusGrapherVisibleProperties.

**Comment by veillette** [comment]
This may be moot due to the work in #142.

**Comment by veillette** [comment]
Assigning to @pixelzoom since he is doing work on ancillary tool.

**Comment by veillette** [comment]
The first half of this work has been done in the CalculusGrapherCommonModel
```typescript
type SelfOptions = {
  graphSets: GraphSet[];
  curveManipulationModeChoices?: CurveManipulationMode[];
  hasTangentTool?: boolean;
  hasAreaUnderCurveTool?: boolean;
};
```

but the conditional instrumentation remains to be done.

**Comment by pixelzoom** [comment]
I think I already handled the conditional instrumentation.  Here are the relevant parts of the Studio tree for each screen.

Derivative:
<img width="311" alt="screenshot_2151" src="https://user-images.githubusercontent.com/3046552/212211778-be51dbbc-1998-4aa2-be84-07955f39076f.png">

Integral:
<img width="309" alt="screenshot_2152" src="https://user-images.githubusercontent.com/3046552/212211799-8a076b36-a6d5-409b-966c-392050e3e16c.png">

Advanced:
<img width="313" alt="screenshot_2153" src="https://user-images.githubusercontent.com/3046552/212211818-ee66630e-6043-4b0c-9c57-7c10b294153d.png">

Lab:
<img width="311" alt="screenshot_2154" src="https://user-images.githubusercontent.com/3046552/212211831-fd3bfd75-88f2-436e-9889-6800e66e91b2.png">

`tangentVisibleProperty` and `areaUnderCurveVisibleProperty` are likely to be come DerivedProperties, but will remain conditionally instrumented.

@veillette can you check the above to verify? If it looks OK, please close.

**Comment by veillette** [comment]
Indeed, I stand corrected. Closing
