### ISSUE TITLE
Move all customization to the model for vertical lines and point labels.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#144]
For some of the PhET-iO only features, it wil be easier for the client to customize if everything customizable is in one place.  So let's think about how to move `colorProperty`, `labelProperty`, and `visibleProperty` to the model for vertical lines and point labels.  For example:

<img width="233" alt="screenshot_2099" src="https://user-images.githubusercontent.com/3046552/209732934-84cdbbdc-b688-4154-b48c-f713d146b5f6.png">

One way to do this would be to subclass AncillaryTool, add these Properties, and use that subclass for vertical lines and point labels.

For referenceLine, tangentTool and areaUnderTheCurveTool, these Properties do not really need to be exposed. And `visibleProperty` is derived from CalculusGrapherVisibleProperties.

**Comment by pixelzoom** [comment]
As part of our discussion in https://github.com/phetsims/calculus-grapher/issues/145, we noted that having visibleProperty in the model will allow us to optimize listener notifications, so that work is not being done by invisible tools. 

In AncillaryTool.ts, something like this for each DerivedProperty:

```typescript
    const yIntegralProperty = new DerivedProperty( [ this.xProperty, this.visibleProperty ],
      ( x, visible ) => visible && integralCurve.getYAt( x ), {
        tandem: options.tandem.createTandem( 'yIntegralProperty' ),
        phetioValueType: NumberIO
      } );
```

And `curveChangedEmitter` listeners can be conditionally added/remove like this (untested):

```typescript
    // When a curve is changed, update its associated y Property.
    const integralCurveListener = () => yIntegralProperty.recomputeDerivation();
    const originalCurveListener = () => yOriginalProperty.recomputeDerivation();
    const derivativeCurveListener = () => ySecondDerivativeProperty.recomputeDerivation();
    const secondDerivativeCurveListener = () => ySecondDerivativeProperty.recomputeDerivation();
    
    // When this tool is visible, listener to curveChangedEmitter for each curve.
    this.visibleProperty.link( visible => {
      if ( visible ) {
        integralCurve.curveChangedEmitter.addListener( integralCurveListener );
        originalCurve.curveChangedEmitter.addListener( originalCurveListener );
        derivativeCurve.curveChangedEmitter.addListener( derivativeCurveListener );
        secondDerivativeCurve.curveChangedEmitter.addListener( secondDerivativeCurveListener );
      }       
      else {
        if ( integralCurve.curveChangedEmitter.hasListener( integralCurveListener ) ) {
          integralCurve.curveChangedEmitter.removeListener( integralCurveListener );
        }
        if ( originalCurve.curveChangedEmitter.hasListener( originalCurveListener ) ) {
          originalCurve.curveChangedEmitter.removeListener( originalCurveListener );
        }
        if ( derivativeCurve.curveChangedEmitter.hasListener( derivativeCurveListener ) ) {
          derivativeCurve.curveChangedEmitter.removeListener( derivativeCurveListener );
        }
        if ( secondDerivativeCurve.curveChangedEmitter.hasListener( secondDerivativeCurveListener ) ) {
          secondDerivativeCurve.curveChangedEmitter.removeListener( secondDerivativeCurveListener );
        }
      }
    } );
```

**Comment by pixelzoom** [comment]
Before making this optimization, we should confirm that it's OK for invisible tools to contain stale information.  See https://github.com/phetsims/calculus-grapher/issues/154.

**Comment by pixelzoom** [comment]
At our 1/10/2022 meeting, I volunteered to look at moving this forward. 

I proposed a model class hierarchy something like this rough sketch:

```
AncillaryTool
   xProperty
   y*Property
   *.curveChangedEmitter
   visibleProperty

ScrubberTool extends AncillaryTool - tangent tool
  scrubberColorProperty

AreaUnderCurveTool extends ScrubberTool
  positiveAreaColorProperty
  negativeAreaColorProperty

LabelledAncillaryTool extends AncillaryTool — vertical lines, point labels
  labelProperty
  colorProperty
```

Notes about `visibleProperty`...


For the model, AncillaryTool has:

```
this.visibleProperty = new BooleanProperty( false, {
  tandem: options.tandem.createTandem( 'visibleProperty' )
} );
```

For the view, visibility of things related to an AncillaryTool depend on both the tool's `visibleProperty` and the state of `predictModeEnabledProperty`.  So like this, currently in AncillaryToolNode:

```
visibleProperty: new DerivedProperty(
  [ ancillaryTool.visibleProperty, predictModeEnabledProperty ],
  ( ancillaryToolVisible, predictModeEnabled ) => ancillaryToolVisible && !predictModeEnabled, {
    tandem: providedOptions.tandem.createTandem( 'visibleProperty' ),
    phetioValueType: BooleanIO
  } )
```

**Comment by pixelzoom** [comment]
In the above commits, I added `visibleProperty` to AncillaryTool.   

Instead of deleting the tool-related Properties from CalculusGrapherVisibleProperties, I made them references to the AncillaryTool visibleProperty instances. This was convenient because it required fewer code changes. I'm not sure if I'll keep this -- will reevaluate when I'm closer to "done".

TODO
- [ ] AncillaryTool y*Property instances are not currently updating in Studio when `visibleProperty` transitions from false to true.  If I add a console.log listener to these Properties, I see them change in the console. So I'm wondering if there's something about DerivedProperty`recomputeDerivation` that does not notify Studio.

**Comment by pixelzoom** [comment]
Notes on color customization via PhET-iO.  For the various ancillary tools, her are the things that have a color, and whether/how the color can be modified.  This list was complied in Zoom discussion with @veillette and @amanda-phet.

Reference Line
* sphere - NO
* line - NO
* value text - NO
* value background - NO

Vertical Line
* line - YES
* label text - NO
* label text background - NO

Labeled Point
* point — YES, initialized to color of the associated GraphType, then editable
* label text - NO
* label text background - NO

Tangent
* barometer - YES, via derivativeCurveStrokeProperty
* scrubber sphere - YES, via derivativeCurveStrokeProperty
* tangent arrow - YES, via derivativeCurveStrokeProperty
* point on curve - YES, via *CurveStrokeProperty of the associated GraphType

Area Under Curve 
* positive area (barometer and area plot) - YES, via integralCurveStrokeProperty
* negative area (barometer and area plot) - YES, via integralCurveStrokeProperty
* sphere - YES, via integralCurveStrokeProperty
* line - YES, via integralCurveStrokeProperty
* point on curve - YES, via *CurveStrokeProperty of the associated GraphType

**Comment by pixelzoom** [comment]
@veillette FYI...  In the above commits I moved forward with adding color Properties to the model for ancillary tools. I added model classes ReferenceLine, VerticalLine, and PointLabel.   There's some duplication noted for PointLabel.createMultiple that I plan to address.   I'll be tackling the Tangent and AreaUnderCurve next Wednesday.

**Comment by pixelzoom** [comment]
The model class hierarchy is:

```
AncillaryTool
  ReferenceLine
  TangentScrubber
  AreaUnderCurveScrubber
  LabeledAncillaryTool
    LabeledPoint
    VerticalLine
```

There is no view class hierarchy.  The view classes are:

```
ReferenceLineNode
ScrubberNode
TangentArrowNode
PlottedPoint
LabeledPointNodean
VerticalLineNode
```

Instances of the above classes are instrumented, and view elements link to model elements.  The instructional designer does all customization by visiting the model elements.  Colors are linked to ProfileColorProperties were appropriate.

@veillette please review. The best way to approach this is probably to browse the above classes, then inspect the Studio tree.   Or I can give you a tour, if that would be more effective.

**Comment by veillette** [comment]
This was reviewed at our 1/18 meeting. Closing
