### ISSUE TITLE
Things to discuss about AncillaryTool

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#145]
After working on AncillaryTool with @veillette, I had a few thoughts.  They may warrant separate issues, but I'll capture them here for now.  There's no need to do anything about these until we discuss.

---

(1) Is there a better name than AncillaryTool? @veillette brought this up a couple of times, I think it's worth thinking about a little more, even though the term does not appear in the UI or PhET-iO API.

---

(2) Related to https://github.com/phetsims/calculus-grapher/issues/133 ... If we change CurvePoint to have `y: number | null`, where `y = null` at discontinuities, then how will that affect these tools? The DerivedProperties in AncillaryTool will need to be `phetioValueType: NullableIO( NumberIO )`.  What else?

---

(3) Does current implementation of AncillaryTool impact responsiveness or performance?  We now have 23 AncillaryTool instances per screen: 1 `referenceLine`, 1 `tangentTool`, 1 `areaUnderCurveTool`, 10 `*VerticleLine`, and 10 `*PointLabel`.  And in AncillaryTool, we now have 4 `curveChangedEmitter` listeners per instance.  So that's 23 x 4 = 92 `curveChangedEmitter` listeners.   Some of those listeners are not really relevant for a specific screen -- e.g. `integralCurve.curveChangedEmitter` is not relevant for the Derivative screen.

Perhaps we should have 1 `originalCurve.curveChangedEmitter` listener for the entire set of `*VerticleLine`, and 1 for the entire set of  `*PointLabel`, then call a new `update` method on Ancillary tool when the `originalCurve` has changed.

---

(4) Related to (3), we currently have this in AncillaryTool, as a way of forcing the y-value DerivedProperties to update when the curves change:

```
    const curveChangedListener = () => this.xProperty.notifyListenersStatic();
    integralCurve.curveChangedEmitter.addListener( curveChangedListener );
    originalCurve.curveChangedEmitter.addListener( curveChangedListener );
    derivativeCurve.curveChangedEmitter.addListener( curveChangedListener );
    secondDerivativeCurve.curveChangedEmitter.addListener( curveChangedListener );
```

That seems like it's doing duplicate work. Wouldn't this be sufficient?  Why do we need to listen to all of the curves?

```
    originalCurve.curveChangedEmitter.addListener(  () => this.xProperty.notifyListenersStatic() );
```

---

(5) All of the AncillaryTool instances are doing work, whether they are visible or not. And for `*VerticleLine` and `*PointLabel`, they are only visible if made visible via Studio/PhET-iO.  This seems like a burden that should not be put on the general version of the sim. Should we only update an AncillaryTool when it's a visible (or becomes visible)?  It think that's certainly the case for `*VerticleLine` and `*PointLabel`.  But we'll need input from PhET-iO designers, since the AncillaryTool values would be stale when the tool is not visible.  This is motivation for putting `visibleProperty` in the AncillaryTool model, see https://github.com/phetsims/calculus-grapher/issues/144. 

---

(6) AncillaryTool currently has 4 DerivedProperties for the y values associated with the 4 curves:

```typescript
  public readonly yIntegralProperty: TReadOnlyProperty<number>;
  public readonly yOriginalProperty: TReadOnlyProperty<number>;
  public readonly yDerivativeProperty: TReadOnlyProperty<number>;
  public readonly ySecondDerivativeProperty: TReadOnlyProperty<number>;
```

We should verify with designers that this is acceptable.  Another way to do this would be to have 1 DerivedProperty that contains all 4 values, something like `yValuesProperty`, with a structure like:

```typescript
type YValues = {
  yIntegral: number;
  yOriginal: number;
  yDerivative: number;
  ySecondDerivative: number;
}
```

This would require an IOType. And we might not be able to inspect the value in Studio - I don't think that we have a way to present the value of a custom IOType in Studio.

We should also remind designers that the y-value for irrelevant curves will still be present, and will still be evaluated.

---

**Comment by pixelzoom** [comment]
(6) AncillaryTool currently has 4 separate DerivedProperties for the y values associated with the 4 curves:

```typescript
  public readonly yIntegralProperty: TReadOnlyProperty<number>;
  public readonly yOriginalProperty: TReadOnlyProperty<number>;
  public readonly yDerivativeProperty: TReadOnlyProperty<number>;
  public readonly ySecondDerivativeProperty: TReadOnlyProperty<number>;
```

We should verify with designers that this is acceptable.  Another way to do this would be to have 1 DerivedProperty that contains all 4 values, something like `yValuesProperty`, with a structure like:

```typescript
{
  yIntegral: number;
  yOriginal: number;
  yDerivative: number;
  ySecondDerivative: number;
}
```

This would require an IOType.  And we should remind designers that the y-value for irrelevant curves will still be present, and will still be evaluated.

**Comment by veillette** [comment]
I transferred item (4) to its own separate issue, #146.

**Comment by pixelzoom** [comment]
1/3/2023 meeting notes about the numbered items in https://github.com/phetsims/calculus-grapher/issues/145#issue-1512891201 ...

(1) AncillaryTool is fine. If we think of something better great, but not necessary to change.

(2) We'll continue this dicussion in #133. But we're leaning towards going "all in" and changing CurvePoint to have `y: number | null`.  But we're going to wait until we've discussed #133 with @amanda-phet.

(3) Having a `curveChangedEmitter` listener for a collection of AncillaryTools doesn't work well in the general case.  For example, there is no "collection" for the reference line.  So do nothing here, and we think we'll probably improve performance enough via (5).

(4) @veillette previously moved this to https://github.com/phetsims/calculus-grapher/issues/146.  It has been addressed and closed.

(5) As part of https://github.com/phetsims/calculus-grapher/issues/144, we'll move visibleProperty to AncillaryTool model, and limit updates to visible tools.  We'll continue discussion of this in #144.

(6) Having a single `yValuesProperty` for each AncillaryTool is not a viable solution, becuase the curves all update at different times, and `yValuesProperty` would go through invalid intermediate states.  We could probably introduce some new Emitters to address this, but it feels like a lot of work for diminishing returns. So if this kind of "single structure" is brought up again, we'll recommend against it.

I think we've covered everything here, or move things to their own issues.   So I'm going to close this issue. @veillette feel free to re-open if I missed anything.
