### ISSUE TITLE
Duplicate work done by curve listeners in Ancillary Tools

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#146]
Moving item (4) of #145, to a separate issue. 

> we currently have this in AncillaryTool, as a way of forcing the y-value DerivedProperties to update when the curves change:

    const curveChangedListener = () => this.xProperty.notifyListenersStatic();
    integralCurve.curveChangedEmitter.addListener( curveChangedListener );
    originalCurve.curveChangedEmitter.addListener( curveChangedListener );
    derivativeCurve.curveChangedEmitter.addListener( curveChangedListener );
    secondDerivativeCurve.curveChangedEmitter.addListener( curveChangedListener );
> That seems like it's doing duplicate work. Wouldn't this be sufficient? Why do we need to listen to all of the curves?

    originalCurve.curveChangedEmitter.addListener(  () => this.xProperty.notifyListenersStatic() );

Yes that seems excessive, and it may explain the unresponsiveness in studio that was observed but I am not sure if the proposed solution is robust.

The emitter on originalCurve is being listened to by derivativeCurve:

```js
// Observe when the 'base' Curve changes and update this curve to represent the derivative of the 'base' Curve.
    // Listener is never removed since DerivativeCurves are never disposed.
    baseCurve.curveChangedEmitter.addListener( this.updateDerivative.bind( this ) );
```
 which prompts it to update itself, and then send its own emitter.

```js

 private updateDerivative(): void {
    // Loop through each trio of adjacent Points of the base Curve.
    this.baseCurve.forEachAdjacentTrio( ( previousPoint, point, nextPoint, index ) => {
     ...
    } );

    // Signal once that this Curve has changed.
    this.curveChangedEmitter.emit();
  }
```
The emitter on derivativeCurve is  being listened to by secondDerivativeCurve, which then updates itself. 

By triggering the xProperty.notifyListener on originalCurve, we may run into a race condition, where we force a recalculation of 
```js
this.ySecondDerivativeProperty = new DerivedProperty( [ this.xProperty ],
      x => secondDerivativeCurve.getYAt( x ), {
        tandem: options.tandem.createTandem( 'ySecondDerivativeProperty' ),
        phetioValueType: NumberIO
      } );
```
but the `secondDerivateCurve` has not been updated yet.   

 
I think it would be safer to add the listener to ` secondDerivativeCurve` instead. 
```js
   secondDerivativeCurve.curveChangedEmitter.addListener(  () => this.xProperty.notifyListenersStatic() );
```

This ensures that the `originalCurve`, and the `derivativeCurve` have been updated. However, this ignores `integralCurve` altogether. We may want to assume that it would take half the time to update itself than the secondDerivative, since it is not a double step process, but that's just an assumption, so it may be safer to have 

```js
   secondDerivativeCurve.curveChangedEmitter.addListener(  () => this.xProperty.notifyListenersStatic() );
   integralCurve.curveChangedEmitter.addListener(  () => this.xProperty.notifyListenersStatic() );
```

I'm assigning to @pixelzoom as you may have more tricks up your sleeve for these cases.

**Comment by pixelzoom** [comment]
Ah, right...  Curve `getYAt` will not return a correct value until all CurvePoints have been updated.

**Comment by pixelzoom** [comment]
DerivedProperty has method `recomputeDerivation` that lets you force its value to be derived.  So in the above commit, I replaced the `curveChangedEmitter` listeners like this:

```typescript
    // When a curve is changed, update its associated y Property.
    integralCurve.curveChangedEmitter.addListener( () => yIntegralProperty.recomputeDerivation() );
    originalCurve.curveChangedEmitter.addListener( () => yOriginalProperty.recomputeDerivation() );
    derivativeCurve.curveChangedEmitter.addListener( () => yDerivativeProperty.recomputeDerivation() );
    secondDerivativeCurve.curveChangedEmitter.addListener( () => ySecondDerivativeProperty.recomputeDerivation() );
```

I inspected in Studio, and it looks OK to me, so this seems like an improvement. Let's discuss if you have questions.

**Comment by veillette** [comment]
Closing.
