### ISSUE TITLE
Review of AncillaryToolNode and sub classes

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#153]
On the 1/3/2023 meeting, CM briefly reviewed AncillaryToolNode and its sub classes.

Some comments:
- There are too many responsibilities assigned to `AncillaryToolNode`.
- We can pull out the barometer and the ancillaryTool checkbox of the controlPanel and create them into the `derivativeScreenView` and `IntegralScreenView`.
-  `The derivativeScreenView` and `IntegralScreenView` should attach its children to the `screenViewRootNode`  (see #152)
-  Ideally the creation of the checkbox should be done by instantiating the super class CGScreenView.

**Comment by pixelzoom** [comment]
I looked at what has been done, and this is looking much nicer.   But I think there's still some work to be done.

AncillaryToolNode and its subclasses (TangentToolNode, AreaUnderCurveToolNode) are a bit odd. They are Nodes with no children, and exist to add things (scrubber, "focus circle", area curve) to GraphNode instances.

A more typical approach would be to have the parent Nodes responsible for adding things related to the tools. So I would break up AncillaryToolNode by doing this:

* Make originalGraphNode (or DerivativeScreenView and IntegralScreenView) responsible for adding ScrubberNode
* Make GraphNode responsible for adding FocusCircle
* Make originalGraphNode (or DerivativeScreenView) responsible for adding TangentArrowNode
* Make originalGraphNode (or IntegralScreenView) responsible for adding ShadedAreaChart
* Delete AncillaryToolNode

Let's discuss in our meeting this week.

**Comment by pixelzoom** [comment]
Before creating this issue, I did a bit of cleanup in AncillaryToolNode.  And I'd like to review that with @veillette.  

One significant change is that I replaced `getAncillaryToolVisibleProperty` with a DerivedProperty for `visibleProperty`. Then I used the AncillaryToolNode's `visibleProperty` wherever `getAncillaryToolVisibleProperty` was previously called.

The definition of `getAncillaryToolVisibleProperty` was:

```typescript
  public getAncillaryToolVisibleProperty( graphType: GraphType ): TReadOnlyProperty<boolean> {
    return new DerivedProperty( [
        this.ancillaryToolCheckboxProperty, this.predictModeEnabledProperty ],
      ( ancillaryToolCheckbox, predictModeEnabled ) => {

        // if graphType is original and in predictMode
        const mustHideTool = predictModeEnabled && graphType === 'original';

        return ancillaryToolCheckbox && !mustHideTool;
      } );
  }
```

And that was replaced with the much simpler:

```typescript
      visibleProperty: new DerivedProperty(
        [ ancillaryToolCheckboxProperty, predictModeEnabledProperty ],
        ( ancillaryToolCheckbox, predictModeEnabled ) => ancillaryToolCheckbox && !predictModeEnabled, {
          tandem: providedOptions.tandem.createTandem( 'visibleProperty' ),
          phetioValueType: BooleanIO
        } )
```

I tested before/after, and behavior seems to be the same. But I want to verify with @veillette that I didn't miss something.

**Comment by pixelzoom** [comment]
At our 1/10/2022, I volunteered to move this forward. Specifically, I'm going to investigate what I proposed in https://github.com/phetsims/calculus-grapher/issues/153#issuecomment-1376692491.

**Comment by pixelzoom** [comment]
AncillaryTool and its subclasses have been replaced by these methods in GraphsNode:

* `addTangentView` - called by DerivativeScreenView
* `addAreaUnderCurveView` - called by IntegralScreenView
* `addPlottedPoint` - private

@veillette please review. Let me know if this needs more explanation.

**Comment by veillette** [comment]
@pixelzoom gave me a tour of the changes. It also make sense to add these methods onto the OriginalGraphNode class in this context.  Also it is correct that we can simplify the visibleProperty when we attach the tools solely to the originalGraphNode.
Well done. Closing
