### ISSUE TITLE
Is it OK to update tools only when they are visible?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#154]
The sim has a bunch of features that we refer to as "tools", with base class AncillaryTool.  This includes the reference line, tangent scrubber, area-under-the-curve scrubber, vertical lines, and point labels.

In https://github.com/phetsims/calculus-grapher/issues/145, bullet (3), we noted that we currently have 23 instances of such tools:

> We now have 23 AncillaryTool instances per screen: 1 `referenceLine`, 1 `tangentTool`, 1 `areaUnderCurveTool`, 10 `*VerticleLine` (A-J), and 10 `*PointLabel` (A-J). 

The vertical lines and point labels are for PhET-iO only, and not visible in the sim unless they are made visible by the instructional designer. 

Updating all of these tools can affects responsiveness/performance when manipulating with the original curve.  So in #144, we plan to update AncillaryTool instances only when they are visible.  This means that their associated Properties will contain stale data when they are not visible.  @amanda-phet Is this OK?   If so, this is something to note in the Client Guide.

@veillette FYI.

**Comment by veillette** [comment]
at our meeting 1/5, we decided that it is OK not to update. We will note this in the Phet-IO guide.

**Comment by amanda-phet** [comment]
Is this still assigned to me so I note it in the client guide?

**Comment by veillette** [comment]
No, there is some internal work to be done by me before we make this change. I'll assign it back to you once it is over.

**Comment by veillette** [comment]
The work on this has been done in the model.
Assigning to @amanda-phet to ensure that this is indicated in the PhET-IO guide.

**Comment by pixelzoom** [comment]
> ... Assigning to @amanda-phet to ensure that this is indicated in the PhET-iO guide.

I noted this in https://github.com/phetsims/calculus-grapher/issues/212, so closing this issue.
