### ISSUE TITLE
Do we need 10 vertical lines and 10 point labels?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#155]
As noted in https://github.com/phetsims/calculus-grapher/issues/154, vertical lines and point labels are PhET-iO-only features.  10 of each are created at startup, labeled A-J.  It's not possible to create them on demand, since they have no associated controls in the sim.

Here's how they currently look in the Studio tree:

<img width="238" alt="screenshot_2100" src="https://user-images.githubusercontent.com/3046552/210453874-33462f16-db65-4692-8694-28667d0ddd6a.png">

We can reduce the amount of work done by only updating when these tools are visible, see #154. But we're wondering... Do we really need 10 of each tool? 

@veillette FYI.

**Comment by veillette** [comment]
Brought up today during a zoom meeting : @amanda-phet and @catherinecarter concurred that 5-6 lines  and point labels is probably  sufficient for pedagogical purposes.

**Comment by veillette** [comment]
We picked 6 as a sufficient number.

**Comment by veillette** [comment]
In `CalculusGrapherConstants.js` we have
````js
  // PhET-io ONLY constants
  MAX_VERTICAL_LINES: 6,
  MAX_LABEL_POINTS: 6
````
and the `CalculusGrapherCommonModel` instantiates only the appropriate number of tools

````js
    this.labelledPoints = this.createAncillaryTools( CalculusGrapherConstants.MAX_LABEL_POINTS,
      options.tandem.createTandem( 'points' ), 'Point' );

    this.labelledVerticalLines = this.createAncillaryTools( CalculusGrapherConstants.MAX_VERTICAL_LINES,
      options.tandem.createTandem( 'verticalLines' ), 'VerticalLine' );
````

Closing
