### ISSUE TITLE
Should Tanget/Area checkbox disappear when "Predict" radio button is selected? 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#156]
In the _Derivative_ screen, pressing the "Predict" radio button causes the "Tangent" checkbox to disappear from the control panel.   And similarly for the "Area Under Curve" checkbox in the _Integral_ screen.

A few problems with this:

(1) PhET does not typically hide controls in control panels. We typically disable controls when they are not relevant. See for example the "Solvent" checkbox in Acid-Base Solutions:

<img width="307" alt="screenshot_2102" src="https://user-images.githubusercontent.com/3046552/210454982-57eca43d-c3b8-4097-8f0f-f7c309a590a0.png">

(2) Hiding the checkbox causes the control panel to resize, and the checkboxes below the panel to move up.  This is distracting.  For example in the _Derivative_ screen:

<img width="155" alt="screenshot_2103" src="https://user-images.githubusercontent.com/3046552/210455316-9e0fff6f-0539-419f-8841-5529e4ac8127.png">   <img width="148" alt="screenshot_2104" src="https://user-images.githubusercontent.com/3046552/210455321-34474767-e3ad-469d-970e-b3c403583423.png">

(3) Since the sim is controlling whether the checkbox is visible, this makes it problematic/complicated to allow the PhET-iO client to control whether this checkbox is visible.  If the client hides it, the sim will make it visible as soon as the the user switches from Predict to f(x) radio button.  See `calculusGrapher.derivativeScreen.view.controlPanel.tangentToolCheckbox` in Studio. It currently does not have its `visibleProperty` instrumented, so the client cannot hide this feature.

@amanda-phet Did you really want the checkbox to disappear when Predict radio button is pressed?   I recommend keeping it visible, but disabling it.

**Comment by pixelzoom** [comment]
@veillette FYI.

**Comment by veillette** [comment]
The distraction noticed in Problem (2) could be addressed by positioning their y- value of the checkboxes below the panel relative to the reset all button instead, which is what the design document suggested at first. So that might be a red herring in the discussion.

**Comment by amanda-phet** [comment]
There are lots of good reasons to keep this checkbox visible: consistent with other sims, easier to access in the studio tree, and likely the best user experience.

**Comment by veillette** [comment]
Done in the commit above. Assigning to @amanda-phet to review the change.

**Comment by amanda-phet** [comment]
This is working well and looks good to me.
