### ISSUE TITLE
Polish tick marks on barometer

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/calculus-grapher#159]
Discussed 1/5/23 
* Sum of area could go by 50s instead of 40s
* Consider reducing weight (or number) of intermediate tick marks
* Consider only having tick marks on the left side and not overlapping with the bar

**Comment by veillette** [comment]
There are numerous changes below
<img src="https://user-images.githubusercontent.com/7633344/211432816-be93d832-2877-4678-8b0e-c2d389b2bce0.png" width="300">

The minor tick marks are set to gray, and I halved their linewidth. There are fewer major tick marks. I also reduced the font size of the values.

**Comment by veillette** [comment]
I created an issue to support non-symmetric tick marks in Bamboo (our common charting library) as it is not possible to do at present time.

**Comment by pixelzoom** [comment]
Looking good!

**Comment by catherinecarter** [comment]
Looks great! I'm wondering if using fewer minor tick marks would be sufficient. With three tick marks between major tick marks of size 50 makes it challenging to calculate the increment. Perhaps one minor tick mark to mark 25 would be sufficient. I'd have to see it, but I suspect it might be ok.

**Comment by pixelzoom** [comment]
Here's what I see in master...

For Slope, major tick spacing of 5 seems nice. But the minor tick spacing is currently 2.5, and that doesn't feel useful. Recommended to change to minor tick spaving to some integer, like 5 or 2.
<img width="89" alt="screenshot_2138" src="https://user-images.githubusercontent.com/3046552/211625690-20cd955f-9f85-4896-90bc-0f7c18843b3b.png">

For Area, I'm not sure what @catherinecarter is reporting. I see major tick spacing of 100 (not 50), and the minor tick spacing of 25 seems fine.
<img width="102" alt="screenshot_2137" src="https://user-images.githubusercontent.com/3046552/211625705-d1692422-d9b4-430b-908c-2cd5acbddcd9.png">

**Comment by catherinecarter** [comment]
Oh! Great! I think Martin may have changed it between me looking and then having meetings and now. Looks great :)

**Comment by amanda-phet** [comment]
What you have in screenshots here @pixelzoom looks great to me.
