### ISSUE TITLE
Is "Area Under Curve" barometer behaving correctly?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#161]
Is there a problem with the "Area Under Curve" barmeter?  When I have the scrubber in an area that is below the y-axis, the bar is still positive.  Example:

<img width="452" alt="screenshot_2134" src="https://user-images.githubusercontent.com/3046552/211455776-d5acf081-8ecc-4c2d-bef7-13229904a112.png">

**Comment by veillette** [comment]
No that's the correct behavior, the barometer value track the integral curve instead of the original function.

**Comment by pixelzoom** [comment]
Ah, right. Closing.

**Comment by pixelzoom** [comment]
Reopening. I'm still confused and want to discuss at today's meeting.

**Comment by pixelzoom** [comment]
Discussed in a meeting with @amanda-phet @catherinecarter @veillette.  I now understand what "Accumulated Area" means.  We considered other possible labels for this (including "Net Area") but decided to leave it as is.  And @amanda-phet  will watch for confusion in interviews.

Closing.
