### ISSUE TITLE
Cueing arrows problems

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#164]
A few problems in TransformedCurveNode.ts related to the cueing arrows:

---

(1) This bit of code is going is not really checking to see if the curve was "touched once". When PhET-iO state is restored, `curveChangedEmitter` will fire, and the cueing arrows will incorrectly disappear.

```
    // set the visibility of cueingArrowsNode to invisible if the curve has been touched once.
    curve.curveChangedEmitter.addListener( () => {
      this.undraggedProperty.value = false;
    } );
```

How about handling this in the DragListener's `start` function?

---

(2) This would be clearer if the value was inverted and it was renamed `hasBeenDraggedProperty`:

```
  // has this node ever been userDragged, used for tracking the visibility of the cueingArrows
  private readonly undraggedProperty: BooleanProperty;
```

---

(3) undraggedProperty should be `phetioReadOnly: true`.

---

**Comment by pixelzoom** [comment]
I took care of these in the above commit. @veillette please review.

**Comment by veillette** [comment]
That is much cleaner, particularly for addressing point (1), where we don't need to assume that only the DragListener is responsible for the changing the curve.

Closing
