### ISSUE TITLE
Cursor problem with TransformedCurveNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#165]
When I mouse over the original curve, I don't see the cursor change.  For example, in this initial state, there is no cursor change:

<img width="431" alt="screenshot_2140" src="https://user-images.githubusercontent.com/3046552/211743379-6944c23b-f02f-4bca-a3d7-c475e85a648f.png">

If I manipulate the curve like this, then mousing anywhere between the curve and x-axis shows the cursor (anywhere in the area under the curve).  But there is still no cursor when I mouse over any location where y = 0.

<img width="429" alt="screenshot_2141" src="https://user-images.githubusercontent.com/3046552/211743727-fa7708bc-5ad9-4041-a7c2-c16c271fbb7e.png">

**Comment by veillette** [comment]
The problem lies with the DragListener which is attached to the entire TransformedCurveNode (which includes say the CueingArrows). It would be more appropriate to attach it only to the continuousLinePlot, which would prevent this behavior.

**Comment by veillette** [comment]
It is behaving correctly now.
It is a small change, but I think it may be worth a review. Assigning back to @pixelzoom

**Comment by pixelzoom** [comment]
The commit looks nice, and it's behaving as expected.  Done, closing.
