### ISSUE TITLE
Can we derive the positive/negative colors for "Area Under Curve" feature.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#166]
For the "Area Under Curve" feature, we currently have 3 color in the color profile (CalculusGrapherColors.ts):

* `integralCurveStrokeProperty`
* `integralPositiveFillProperty`
* `integralNegativeFillProperty` 

All of these Properties are instrumented. And if you change one of them, you must adjust all of them - and that's problematic.

It would be preferrable to collapse these to 1 Property, `integralCurveStrokeProperty`, and derive `integralPositiveFillProperty` and `integralNegativeFillProperty`.   This of course will be a tradeoff, since you won't be able to tweak the derived colors.  But it seems necessary if we are indeed going to expose any of these colors in Studio/PhET-iO.

Deriving colors by adjusting alpha is the simplest solution, and looks pretty nice. For example:

```
// Fill for integral curve (when area is positive)
integralPositiveFillProperty: new DerivedProperty( [integralCurveStrokeProperty],
  integralCurveStroke => integralCurveStroke.withAlpha( 0.4 ) ),

// Fill for integral curve (when area is negative)
integralNegativeFillProperty: new DerivedProperty( [integralCurveStrokeProperty],
  integralCurveStroke => integralCurveStroke.withAlpha( 0.6 ) ),
```

@amanda-phet let's discuss.

**Comment by pixelzoom** [comment]
@amanda-phet and I collaborated on this, and decided that the alpha/opacity approach proposed in https://github.com/phetsims/calculus-grapher/issues/166#issue-1529683098 works well.  We settled on alpha values of 0.3 (positive area) and 0.5 (negative area).   Because we're using opacity, the grid lines are a bit less visible through the negative area, but they are still clearly visible.

@amanda-phet over to you for review, since you were viewing this on Zoom when we collaborated.

**Comment by amanda-phet** [comment]
This is looking really good to me. I'd like to try 0.25 for the positive area though, so there's a bit more contrast between the two. If it's easier to do this over zoom I can do that too, but it was hard to see clearly over zoom, so could you make the change and let me know when it's on main? Then I'll review. Thanks!

**Comment by pixelzoom** [comment]
Even better, I added query parameters so that you can fine-tune the alpha for these colors.

* `positiveAlpha` - default=0.25, range=[0,1]
* `negativeAlpha` - default=0.5, range=[0,1]

Note that I did change `positiveAlpha` from 0.3 to 0.25. 

Back to you @amanda-phet. Let me know if you'd like to change the defaults. Otherwise feel free to close.

**Comment by amanda-phet** [comment]
I think these look great, but I could see someone wanting a bit more contrast. So, please change it to `negativeAlpha=0.55`.

**Comment by pixelzoom** [comment]
> ... So, please change it to `negativeAlpha=0.55`.

Done in the above commit. Screenshot below. Closing.

<img width="697" alt="screenshot_2219" src="https://user-images.githubusercontent.com/3046552/215875117-23ec3466-3316-45cf-9307-221e732de8af.png">
