### ISSUE TITLE
TangentTools are not updating properly.

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#169]
Noticed while playing the sim that the tangentArrowNode, the tangent barometer, and the focus circle are not updating properly.
![Calculus Grapher screenshot (25)](https://user-images.githubusercontent.com/7633344/212124315-b2d11b0d-63f7-4c01-ba59-5465aaf32cda.png)

This suggests that the tangentTool model is not updating properly. However, when I looked at the Integral Screen, I don't come across this buggy behavior. I'm confused!!

**Comment by veillette** [comment]
Steps to reproduce.
- Turn on Tangent Checkbox
- Move original curve nearby the scrubber x value

Noticed how the tangent arrow node, slope of tangent barometer and derivative focus circle never updates.

What is very puzzling is that the AreaUnderCurve tools do not exhibit this behavior, but they share the same underlying model.

**Comment by veillette** [comment]
Moving the scrubber updates the tangent correctly. The problem lies with the curve update.

**Comment by pixelzoom** [comment]
Yes, I've noticed this behavior while working on the ancillary tools, and I should have created this issue.  It's almost certainly due to changes that I've made. I'll circle back to this issue when I'm done making changes.

**Comment by veillette** [comment]
I got it: 
    const derivativeCurveListener = () => ySecondDerivativeProperty.recomputeDerivation();
```
 // When a curve is changed, update its associated y Property.
    const integralCurveListener = () => yIntegralProperty.recomputeDerivation();
    const originalCurveListener = () => yOriginalProperty.recomputeDerivation();
    const derivativeCurveListener = () => ySecondDerivativeProperty.recomputeDerivation();
    const secondDerivativeCurveListener = () => ySecondDerivativeProperty.recomputeDerivation();
```

**Comment by veillette** [comment]
That explains why it was specific to tangentTool and not areaUnderCurve.

**Comment by veillette** [comment]
In the process of testing this (with the previous commit), I confirmed that (with the above fix) toggling the visibility on/off of the checkbox updates the tangentTool, so the optimization set by the visibleProperty is working properly.

**Comment by veillette** [comment]
I also checked manually `AncillaryTool` to see if there was other mismatch pairs, but this was the only one.
We can close this.

**Comment by pixelzoom** [comment]
Good 'ol copy-paste error.  Thansk for the fix!
