### ISSUE TITLE
Create curve model

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/calculus-grapher#17]
Create the model for each curve. At this point, I'm not sure what this will look like as the flash simulation is practically unreadable.

**Comment by brandonLi8** [comment]
I spent some time looking into the flash source code. 

Essentially, it works by storing a finite (but large) number of y-values in an array for every type of curve (integral, original, derivative).

The model then applies a series of algorithms for when the user manipulates the original curve or when the 'smooth' button is pressed. The derivative curve is updated using the definition of a slope for two points and the integral is updated using a trapezoidal riemann sum.

This seems like a reasonable starting point (and I don't envision any other approaches). In addition, we will probably want to port the algorithms for updating the original curve (which are unreadable) to the html5 version.

**Comment by brandonLi8** [comment]
Keeping https://github.com/phetsims/calculus-grapher/issues/18 in mind (and the design in mind), our curve points will need to store whether or not it is a sharp point (a cusp) and whether or not it exists. Sharp points and points that don't exist aren't differentiable.

However, because the HTML5 version has a second derivative (which will be implemented as the derivative of the derivative curve), we cannot just update the first derivative curve using the definition of a slope for two points. Instead, we have to use the limit definition of a derivative to determine if it exists.

**Comment by brandonLi8** [comment]
In the commit above, I added a CurvePoint model. Now its time to add the curve models. I've created a general plan:

## Curve hierarchy

RootCurve 
    - Creates an array of points for every x value
    - Stores the 'type'
    - Convenience method to get closest point given a x value
    - Other Convenience methods 
    - Reset

OriginalCurve
    - Implements all the algorithms for manipulation from the flash versions

IntegralCurve
    - takes a OriginalCurve and observes when any of the points changes and update the points

DerivativeCurve 
    - takes a parentCurve (or baseCurve) and observes when any of the points changes and updates the points


## View

Mirrors the model hierarchy.

**Comment by veillette** [comment]
This hierarchy works well for us. Closing.
