### ISSUE TITLE
Consider changing the x-range of Curve

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#173]
In issue #170, @kathy-phet raise the issue of usability of the integral graph without zooming. However I think the solution proposed is a red herring as the problems lies in the choice of the x-range.

To illustrate my proposal, we imagine for a second the very plausible scenario that a teacher uses a linear function to demonstrate the effect of it on the integral and the derivative.
The teacher wants to show that the derivative of a linear function is a constant but the integral is quadratic. 
  
(I decided to use the lab screen so that one can see the integral and the derivative at the same time, but the results are similar using the derivative and integral screens) 

Without zooming, we get the following.
![Calculus Grapher screenshot (26)](https://user-images.githubusercontent.com/7633344/212344275-0a564949-1678-4290-ad38-86f4df2fa319.png)

As you can see it one can barely detect that the derivative change from zero and the integral gets clipped very rapidly. It would take about 4 zoom out clicks to bring all of the integral function within the view. 

----

If instead we decrease the max x-range to a much **smaller** value, say 5, then even without zooming, it is readily apparent that the derivative is non-zero, and most of the integral is already in the nominal viewport.

![Calculus Grapher screenshot (28)](https://user-images.githubusercontent.com/7633344/212351207-978703b3-11cf-471a-939b-f6c49bf522c5.png)

Notice that the grid is the same for all three graphs. I think we should aim to give the user a best possible user interactions with the simulation, without having to tweak the zoom buttons.

If one turns on the values (which is not a very likely interaction user interaction unless if it is set by a teacher through a queryParameter) , then one could see something like this. 
![Calculus Grapher screenshot (27)](https://user-images.githubusercontent.com/7633344/212344845-5e0b1b66-17f5-401c-8b12-509d814e40a9.png)

**Comment by kathy-phet** [comment]
I see how this is working for keeping things on scale, but I do feel like there is value in the "values", and these small decimal values on y-axis feels quite difficult to work with. And we know we want to keep x and y scales the same, so that we have 45 degrees for x=y tangent. 

So I would not want to go this direction, myself.

**Comment by veillette** [comment]
It is still isometric such that a 45 degree angle is still a slope of 1.

**Comment by kathy-phet** [comment]
I know, but then the y-axis is values like 0.1 and 0.2, which is much harder to digest for students.

**Comment by amanda-phet** [comment]
I think a major consideration for both of these issues (y-axis zooming and the overall scale) is to go back to the learning goals.

> - Access the relationship between a function, its derivative, and its integral, in a context that is divorced from equations
> - Predict what the derivative or integral of a function will look like based on the graph of the function
> - specific goals could include: predict whether the integral will be increasing or decreasing 
> - Identify critical points and compare that x-value across multiple graphs using the cursor tool
> - Use critical points to make predictions 
> - Identify where slope is changing, constant, zero
> - Relate the graphical representation of a function and its derivative or integral to an equation, but see them as independent. 
> - Compare different types of curves and the appearance of their derivatives/integrals. 
> - Apply the inverse relationship between the derivatives and integrals (the derivative of the integral function is the function itself).
> - Draw the velocity and/or acceleration  graph given a position graph.
> - Draw the position and/or velocity graph given an acceleration graph.
> - Draw the position and/or acceleration graph given a velocity graph.

The goals here are addressed without having values on. We are adding a "values" option to address the potential user request to see them, but not to achieve the learning goals. 

With that said, I'm not sure what I think is the right direction for the x-range. On the one hand, the proposed change solves a few problems that are directly tied to the learning goals. On the other hand, we are providing a values option as a preference, and that needs to be usable as well.

**Comment by amanda-phet** [comment]
@veillette demonstrated a graph with an x-axis to 10 and y-axis that is -2 to 2. We like this compromise! It addresses #170 and also the concern in this issue about the scale being decimals. Having integers on the axes is really nice, if someone does turn on values. 

The grid checkbox needs to be updated to reflect the new scale. Let's try grid lines only at the integers, but also experiment with adding intermediate grid lines so it doesn't look too sparse.

**Comment by veillette** [comment]
The x-range curve has been reduced to 
```js
CURVE_X_RANGE = new Range( 0, 10 );
```
also

```js
  NOMINAL_GRID_LINE_SPACING: 1,
  NOMINAL_VERTICAL_TICK_MARK_SPACING: 1,
  NOMINAL_VERTICAL_TICK_LABEL_SPACING: 1,
  NOMINAL_HORIZONTAL_TICK_MARK_SPACING: 1,
  NOMINAL_HORIZONTAL_TICK_LABEL_SPACING: 1,
```

As a result the nominal y-axis goes from -2 to 2 on the first three screens.

FYI, the Curve x-range is a very foundational part of the calculus-grapher model. Even though we have tried in #171, to make the model more resilient to such a change of scale, it is hard for any model to be able to sustain a change by a factor of 5, without having some side effects.

I have remove 2 zoom levels on the zoom-in side, as the change of scale removes the need for those.
I increased the edgeSlopeFactor, so that it makes the pedestal smoother.

**Comment by veillette** [comment]
Here is a screenshot.

![Calculus Grapher screenshot (30)](https://user-images.githubusercontent.com/7633344/213788212-a8f309a5-5373-448d-93ad-a14c14e6a24a.png)

**Comment by veillette** [comment]
I removed two additional zoom levels such that we have
```js
  // zoom level ranges
  ZOOM_LEVEL_RANGE: new RangeWithValue( 1, 6, 4 ),
```
so there is four additional zoom out and two zoom in.

To understand the effect, consider that the nominal y Range is (-2,2).
The maximum y-range is (-20,20) and the minimum is (-0.4,0.4).
So you can zoom out with a factor of 10 and zoom in with a factor of 5.

These are reasonable numbers. The maximum value of the integral is 2*10 = 20, therefore at the maximum y range we can always see the function. In addition, there is not a good reason to zoom in as much as the nominal value is 2 (rather than 10).

**Comment by veillette** [comment]
We are creating separate issues to track the result of changing the x-Curve such as #194, and #200. We can close this issue.
