### ISSUE TITLE
Change 'Accumulated Area' to 'Net Signed Area'

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#175]
In a Slack thread, @catherinecarter  and @amanda-phet discussed changing the barometer title:  'Accumulated Area' to 'Net Signed Area'.

@amanda-phet said :
> I really like that it includes the word "signed" to completely disambiguate the area we are referring to. And once we get the positive/negative colors worked out it seems like it will be nice and clear.

We should change the string associated with the barometer. In addition, we should also refactor the classes and option Fields that refer to AccumulatedArea.

**Comment by veillette** [comment]
The name of the string and all the classes and options fields were replaced.
I did a regex search on `accumulated` to ensure that there are no more instances of it in the code.

Assigning to @pixelzoom to review and also put on his radar as it affects some of the work on ancillaryTools.

**Comment by pixelzoom** [comment]
Looks good. There are one rename that was missing, and I handled it in the above commit: `ACCUMULATED_AREA_MODEL_RANGE` to `NET_SIGNED_AREA_MODEL_RANGE`.

Closing.
