### ISSUE TITLE
Consider migrating AreaPlot to Bamboo

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#177]
The website (https://www.tibco.com/reference-center/what-is-an-area-chart) defines an area chart as

> An area chart is a graph that combines a [line chart](https://www.tibco.com/reference-center/what-is-a-line-chart) and a bar chart to show changes in quantities over time. It’s similar to a line graph in that data points are plotted and connected by line segments. However, the area below the line is colored in or shaded. Then, other values are plotted below the lines and shaded in a different color, resulting in a chart with layers.
![image](https://user-images.githubusercontent.com/7633344/209971807-afae34ed-917e-456c-a026-055c7cae22de.png)

In calculus grapher, we needed an area chart to show the area under the curve of a function. 
![image](https://user-images.githubusercontent.com/7633344/209971453-5fc495c8-0807-474b-b98d-6a63c0c82d0e.png)

The requirement for Calculus-grapher were to have the area under the curve change color, for negative area.  
![image](https://user-images.githubusercontent.com/7633344/209972127-3c0fe427-774c-4991-8f5b-b8a707a55ed3.png)

As a result we invoked two AreaCharts that parses a curve.
In Calculus Grapher

```typescript
/**
 * AreaChart is a chart that combines a line chart and a bar chart.
 * An area chart is distinguished from a line chart by the addition of shading between
 * lines and a baseline, like in a bar chart.
 *
 * Null values are skipped and allow you to create separate shaded regions.
 *
 */
```
The Area chart extends a path and follow a similar construct as LinePlot 
```typescript
export default class AreaChart extends Path {

  public constructor( chartTransform: ChartTransform,
                      dataSet: AreaChartDataSet,
                      providedOptions?: AreaChartOptions ) {
}
}
```
where the type of dataSet is

```typescript
type AreaChartDataSet = ( Vector2 | null )[];
```

The AreaChart takes a baseline as an options, which may differ from 0. 
```typescript
type SelfOptions = {

  // y-value representing the foundation of the chart
  baseline?: number;
};
```

See AreaChart in CalculusGrapher for more details.

**Comment by pixelzoom** [comment]
AreaPlot has been migrated to bamboo. DemoAreaPlot was added to the bamboo demo application, screenshot below.

@veillette please review, close if OK.

<img width="1003" alt="screenshot_2190" src="https://user-images.githubusercontent.com/3046552/214210696-77a7d66e-d1bd-4943-8422-a180cfa351c0.png">

**Comment by veillette** [comment]
In https://github.com/phetsims/calculus-grapher/issues/177#issuecomment-1386560595, it was suggested that we try to consolidate AreaPlot with LinePlot. Although they look superficially the same, you do need 2 different shapes for them. It is not possible to think of the AreaPlot as the fill and the linePlot as the outline. Therefore, I think we are following the correct course here.

**Comment by veillette** [comment]
I reviewed the `AreaPlot.ts` and the `DemoAreaPlot.ts`. The change to support a default fill is appropriate.
Closing
