### ISSUE TITLE
ToolsCheckboxGroup name clashes with AncillaryTool

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#178]
The name of ToolsCheckboxGroup clashes with the "tools" concept for AncillaryTool.  Since both of these "tools" meanings are exposed in PhET-iO, this could be confusing.

**Comment by pixelzoom** [comment]
The class is now CalculusGrapherCheckboxGroup (very creative of me, eh?) and the tandem is "checkboxGroup".  Assigning to @veillette as an FYI, or in case he had a better name.  The tandem name is the important thing, and it seems to work just fine in the Studio tree.   @veillette feel free to close or modify.

**Comment by veillette** [comment]
Now that I think about it, we had two ChechboxGroups at some point, so we had to find them different names. With only one such group, the generic CalculusGrapherCheckboxGroup  is unambiguous.

**Comment by veillette** [comment]
I refactored the `ToolsCheckboxGroupOptions` in the commit below.

**Comment by veillette** [comment]
Closing
