### ISSUE TITLE
Organize GraphNode into layers based on visibility and clipping requirements

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#179]
In our meeting today, @veillette and I discussed the possibility of introducing additional "layers" in GraphNode, so that we can control the visibility of layers instead of individual parts of a graph.

This may also clean up the Studio tree, since we wouldn't need so many instrumented `visibleProperty` elements and links.

We also need to consider clipping requirements.  Plots, tangent line, and plotted points should be clipped to the chart bounds. (Plotted points would look slightly better if not clipped.)

I'll investigate.

**Comment by veillette** [comment]
FYI, the original curve visibility is

```
    // original curve is visible if not in predictMode or allOriginalCurveVisible is true
    const originalCurveNodeVisibilityProperty = new DerivedProperty( [ predictModeEnabledProperty, visibleProperties.allOriginalCurvesVisibleProperty ],
      ( predictModeEnabled, allOriginalCurvesVisible ) =>
        !predictModeEnabled || allOriginalCurvesVisible );
```

which is different than the visibility of the ancillaryTools since they have no dependency on allOriginalCurvesVisible. However, I think we could make a case to the designers that they should, or at least that it would greatly simplify the logic of the visibility of ancillaryTools.

**Comment by pixelzoom** [comment]
Noting there that visibility of LabeledPoints is currently buggy.   They are visible (and should not be visible) when originalCurveNodeVisibilityProperty === false:

<img width="441" alt="screenshot_2186" src="https://user-images.githubusercontent.com/3046552/214170980-85e50551-bd50-4c6b-b07a-8bc0ba9be8f4.png">

<img width="438" alt="screenshot_2187" src="https://user-images.githubusercontent.com/3046552/214171013-95cb94eb-28b2-4bdc-a60c-03f76319c64b.png">

**Comment by pixelzoom** [comment]
I'll note here that there's a bug with LabeledPoints. They are still visible when the "eye" toggle is off, see below.  And we don't want to put them in `curveLayer` because we don't want them to be clipped to the chart bounds.

<img width="441" alt="screenshot_2186" src="https://user-images.githubusercontent.com/3046552/214174275-e2ad04b0-f289-4a5f-83f4-515385d2f292.png">

<img width="438" alt="screenshot_2187" src="https://user-images.githubusercontent.com/3046552/214174281-95cbaf3f-3aac-490b-9730-0f5693bee74f.png">

**Comment by pixelzoom** [comment]
@veillette mentioned that it's a little unclear what is desired when "Predict" is selected and "Show f(x)" is checked.  Currently the tangent line and LabeledPoints are not shown, for example see below.  So whatever we do here for layering should (ideally) make it easy to move things between layers to satisfy change requests. 

<img width="693" alt="screenshot_2188" src="https://user-images.githubusercontent.com/3046552/214175241-88b4c361-9666-4a07-8bdf-9b1ee5f237c3.png">

<img width="685" alt="screenshot_2189" src="https://user-images.githubusercontent.com/3046552/214175249-9394143e-781d-40b4-a9a1-97267e570250.png">

**Comment by pixelzoom** [comment]
I went way down the rathole on this issue, got into a lot of trouble, and ended up reverting.  I ultimately made only 2 minor changes:

(1) Fixed the visibility bug with LabeledPointNode reported in https://github.com/phetsims/calculus-grapher/issues/179#issuecomment-1401142423

(2) Rename CalculusGrapherVisibleProperties `allOriginalCurvesVisibleProperty` to `showOriginalCurveProperty` throughout, to match the name of things like `showOriginalCurveCheckbox`.

I'm going to leave this issue open while I ruminate. I might have another go at it, or I might recommend leaving it mostly "as is".

**Comment by veillette** [comment]
At our previous design meeting,  we agreed that the visibility of the original curve is 
```
  const originalCurveNodeVisibilityProperty = new DerivedProperty(
      [ predictEnabledProperty, visibleProperties.showOriginalCurveProperty ],
      ( predictEnabled, showOriginalCurve ) => !predictEnabled || showOriginalCurve );
```
whereas the tools should have visibility something similar to
```
    // Tangent features are visible if the TangentScrubber is visible, and we are not in predict mode.
    this.tangentVisibleProperty = new DerivedProperty(
      [ tangentScrubberVisibleProperty, predictEnabledProperty ],
      ( tangentScrubberVisible, predictEnabled ) => tangentScrubberVisible && !predictEnabled, {
        tandem: tandem.createTandem( 'tangentVisibleProperty' ),
        phetioValueType: BooleanIO
      } );
```
So the tool visibility is not the same as the originalCurve, so this may impede the effort to organize the tools into layers.

**Comment by pixelzoom** [comment]
@veillette noted that one of the reasons for doing this was to clean up the Studio tree, especially under `view.graphsNode.verticalLinesNode` and `view.graphsNode.originalGraphNode.labeledPointsNode`.  But since the subtree under those elements was replaced by a link to the model, that reason is now moot.

**Comment by pixelzoom** [comment]
I've been trying to wrap my head around all of the Properties that affect visibility, and all of the Nodes that are affected.  It's a lot to keep track of.  So here's my summary.

## Properties that determine visibility, and how they are controlled by the user

* `curveLayerVisibleProperty` is controlled by `eyeToggleButton`
* `predictEnabledProperty` is controlled by `predictCurveRadioButton`
* `referenceLine.visibleProperty` is controlled by the `referenceLineCheckbox`
* `tangentScrubber.visibleProperty` is controlled by `tangentCheckbox`
* `areaUnderCurveScrubber.visibleProperty` is controlled by AreaUnderCurveCheckbox
* `showOriginalCurveProperty` is controlled by “Show f(x)” checkbox
* `*VerticalLine.visibleProperty` is controlled only via Studio/PhET-iO (e.g. `AVerticalLine.visibleProperty`)
* `*LabeledPoint.visibleProperty` is controlled only via Studio/PhET-iO (e.g. `APoint.visibleProperty`)

## Nodes whose visibility is affected by the above Properties:

* GraphNode.curveLayer, children: [ curveNode, predictCurveNode, tangentArrowNode, areaUnderPlotNode, plottedPoints]: 
```typescript
visibleProperty: curveLayerVisibleProperty
```

* originalGraphNode.originalCurveNode:
```typescript
visibleProperty: new DerivedProperty(
  [ predictEnabledProperty, showOriginalCurveProperty ],
  ( predictEnabled, showOriginalCurve ) => !predictEnabled || showOriginalCurve )
```

* originalGraphNode.predictCurveNode: 
```typescript
visibleProperty: predictEnabledProperty
```

* originalGraphNode.highlightRectangle: 
```typescript
visibleProperty: curveLayerVisible
```

* originalGraphNode.labelNode.predictText:
```typescript
visibleProperty: model.predictEnabledProperty
```

* tangentScrubberNode, tangentPointNode, tangentArrowNode:
```typescript
visibleProperty: new DerivedProperty(
  [ tangentScrubberVisibleProperty, predictEnabledProperty ],
  ( tangentScrubberVisible, predictEnabled ) => 
    tangentScrubberVisible && !predictEnabled
```

* areaUnderCurveScrubberNode, areaUnderCurvePointNode, areaUnderCurvePlot:
```typescript
visibleProperty: new DerivedProperty(
  [ areaUnderCurveScrubberVisibleProperty, predictEnabledProperty ],
  ( areaUnderCurveScrubberVisible, predictEnabled ) => 
    areaUnderCurveScrubberVisible && !predictEnabled,
```

* graphsNode.referenceLineNode: 
```typescript
visibleProperty: referenceLine.visibleProperty
```

* graphsNode..verticalLinesNode.verticalLineNode: 
```typescript
visibleProperty: verticalLine.visibleProperty
```

* originalGraphNode.labeledPointsNode.labeledPointNode: 
```typescript
visibleProperty: new DerivedProperty(
  [ labeledPoint.visibleProperty, curveLayerVisibleProperty, predictEnabledProperty ],
  ( labeledPointVisible, curveLayerVisible, predictEnabled ) => 
    labeledPointVisible  && curveLayerVisible && !predictEnabled
```

**Comment by pixelzoom** [comment]
Lots of work on this in the above commits, and I'm much happier with the results.

Summary of changes:

* GraphsNode `addTangentView` is now responsible for deriving `tangentVisibleProperty`.  It's not currently instrumented until someone asks for it. `tangentVisibleProperty ` was removed from CalculusGrapherViewProperties.
* GraphsNode `addAreadUnderCurveView` is now responsible for deriving `areaUnderCurveVisibleProperty`.  It's not currently instrumented until someone asks for it. `areaUnderCurveVisibleProperty ` was removed from CalculusGrapherViewProperties.
* `referenceLineVisibleProperty` was redundant, so it was removed from CalculusGrapherViewProperties.
* `gridLinesVisibleProperty` was moved to CalculusGrapherModel, since it was the sole Property remaining in CalculusGrapherViewProperties.
* CalculusGrapherViewProperties was deleted.
* Improved the documentation for GraphNode `curveLayer`, so it's clear what Nodes are affected by `curveLayerVisibleProperty`

@veillette this one may be difficult to review, but I encourage you to have a look around.  We can discuss at our next pairing session if you'd like.  Or feel free to close if it looks good to you and you don't have questions.

**Comment by veillette** [comment]
If I sum up the approach used here, the primary visibility properties are moved from the view to the model and the derived property for the node visibility are not instrumented.

I took a look at Studio tree and it looks well organized . Also good documentation for
`showOriginalCurveProperty` and `curveLayerVisibleProperty`.

Closing.
