### ISSUE TITLE
ReferenceLineNode has duplicated code

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#180]
In our meeting today, @veillette identified some duplication in ancillary tools:

- [x] ReferenceLineNode  and VerticalLineNode both have `setLineTop` and `setLineBottom` methods
- [x] ReferenceLineNode and ScrubberNode have similar DragListeners

I'll investigate.

**Comment by pixelzoom** [comment]
In the above commit, I addressed the duplication between ReferenceLineNode and VerticalLineNode.  @veillette FYI here is a summary of changes:

* Factored out base class `LineToolNode` that is responsible for the line, its x coordinate (via `xProperty`) and its y coordinates (via `setLineTopAndBottom`).
* Fixed a bug where the DragListener in ReferenceLineNode was being added to more than just the drag handle (ShadedSphere).
* Polished the extents of the VerticalLineNodes. They now extend the same amount above and below the graphs.
* Polished the extents of ReferenceLineNode.  It extends above the graphs the same as VerticalLineNodes, below the graphs a bit more to avoid overlapping scubbers.

**Comment by pixelzoom** [comment]
In the above commits, I addressed the duplication between ReferenceLineNode and ScrubberNode.  I factored out `XDragHandleNode`, which is responsible for the ShadedSphere and DragListener.   

@veillette I believe that this issue is ready for your review.   These were some worthwhile changes, thanks for identifying the duplication.

**Comment by veillette** [comment]
I reviewed the changes above. In summary, the hierarchy is :

- `VerticalLineNode` extends `LineToolNode`
- `ReferenceLineNode` extends `LineToolNode`
- `ScrubberNode` extends `Node` 

However `ReferenceLineNode` and `ScrubberNode`each add a `XDragHandleNode` (ShadedSphere with DragListener) by composition.

This seems like a nice way to remove duplicate responsibilities. Closing
