### ISSUE TITLE
Review of slider snap to values

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#182]
If we change the range of the x-curve, in #173, this must also affect the range of width of the curve manipulation mode.

In `CurveManipulationWidthSlider.js`, we used to have
```js
 // Snap to the nearest whole number.
      constrainValue: ( value: number ) => WIDTH_RANGE.constrainValue( Utils.roundSymmetric( value ) )
````

From the point view of the slider, it doesn't make sense to round the value of the range. It is also very limiting if the range is smaller.

Below I attempted to constrain the values to the ticks themselves. Although it works, it got a bit complicated, maybe there is a simpler way. I feel that I am reinventing the wheel for a functionality that may already exist.

Asking to @pixelzoom to review and comment.

**Comment by pixelzoom** [comment]
@veillette and I paired on this.  The overall approach to snapping is correct.   We made some refinements about how the ticks are created, so that we're not duplicating major and minor ticks at the same values.  

This is in good shape, so closing.
