### ISSUE TITLE
GraphTypeLabelNode problems with superscripts

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#185]
In GraphTypeLabelNode.ts:

```
  // string for d^2 f , we need a hairspace to prevent the superscript to overlap with d
  const numeratorStringProperty = new DerivedProperty(
    [ CalculusGrapherSymbols.dStringProperty, CalculusGrapherSymbols.fStringProperty ],
    ( d, f ) => `${d}${HAIR_SPACE_STRING}<sup "style="font-size:10pt; font-family:Times>2</sup>${f}`
  );

  // string for dx^2 , the superscript is downsized but in the same Family at the math symbols
  const denominatorStringProperty = new DerivedProperty(
    [ CalculusGrapherSymbols.dStringProperty, variableStringProperty ],
    ( d, x ) => `${d}${x}<sup style="font-size:10pt; font-family:Times">2</sup>`
  );
```

There are 3 problems here:

(1) WebStorm is flagging `font-family:Times` with "Font property font-family does not have generic default".   There needs to be a generic default, in case "Times" font is not available.

(2) Since the intent is "the same Family at the math symbols", this should be using `MathSymbolFont.FAMILY`.  And it should probably be using `MathSymbolFont.getRichTextMarkup`.

(3) Hard-coding `font-size:10pt` will not be adjusted when the font sizes in CalculusGrapherConstants are changed.

I'll investigate.

**Comment by pixelzoom** [comment]
This line also has typos, so is the style is likely being ignored:

```
    ( d, f ) => `${d}${HAIR_SPACE_STRING}<sup "style="font-size:10pt; font-family:Times>2</sup>${f}`
```

There's an extra `"` before the `style` attribute.  And there's a missing `"` at the end of the `style` value.

**Comment by veillette** [comment]
Ideally, in math notation, we don't want number to be italicized, which I think means that we don't want `MathSymbolFont.FAMILY`.

**Comment by pixelzoom** [comment]
MathSymbolFont.FAMILY does not include italics. It's simply:

```
  public static readonly FAMILY = '"Times New Roman", Times, serif';
```

**Comment by veillette** [comment]
That could work then.

If you zoom in you can see that the styling of the superscript is indeed different in the denominator and numerator.
![image](https://user-images.githubusercontent.com/7633344/213800469-bbcc4a50-2d79-4d3a-87ee-3309f3583a70.png)

**Comment by pixelzoom** [comment]
Fixed in the above commits, see screenshot below.  @veillette please review.

Summary of changes in GraphTypeLabelNode.ts:

* Added `FontSizeOptions.superscriptSize`, so that superscript size will be adjusted if CGConstants are changed.
* Factored out `function getSuperScript`, which is used wherever a superscript is needed. It uses the `FontSizeOptions.superscriptSize` and `MathSymbolFonts.FAMILY`, and the superscript is NOT in italics.
* I reformatted some calls to `new DerivedProperty` to improve readability.

You can test by doing something like this in GraphTypeLabelNode.ts:

```diff
-        superscriptSize: 0.625 * NOMINAL_FONT_SIZE
+       superscriptSize: 5
```

<img width="191" alt="screenshot_2171" src="https://user-images.githubusercontent.com/3046552/213801496-8ee76751-a267-4eee-ad62-c0469f7d2ea2.png">

**Comment by veillette** [comment]
I think it is good to have a superscript font size that is relatively large (as it is in this case) as it emphasizes the difference between the first and second derivative.

It scales up nicely, even for ridiculous large sizes 
```
GRAPH_LABEL_FONT: new PhetFont( 56 )
``` 
![image](https://user-images.githubusercontent.com/7633344/213802931-aa95ca36-c7b9-44a0-b9d0-b53783a6c2e2.png)

**Comment by veillette** [comment]
The commits look good too. Closing
