### ISSUE TITLE
Reset all does not reset some ancillary tools

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#187]
Noted in https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.8/phet/calculus-grapher_en_phet.html

Reset all does not reset the referenceLine as well as the checkbox associated with the tangentTool and areaUnderTheCurveTool.

Most likely the result of the recent refactoring of visibility.

**Comment by veillette** [comment]
It is mostly due to the fact that 'ancillaryTool' owns a `visibleProperty` but does not have a reset function on it.

It could be readily added to `ancillaryTool` but i'm uncertain about the effect on the "PhET-IO only" sub classes of ancillaryTools.

**Comment by veillette** [comment]
OK I think I see a way forward. We should add visibleProperty to the base class and rely on the fact that we dont call reset in the firstplace on `verticalLines` and `labeledPoints`  as indicated below. 

```js
  /**
   * Reset all
   */
  public reset(): void {
    this.originalCurve.reset();
    this.predictCurve.reset();
    this.curveManipulationProperties.reset();
    this.predictModeEnabledProperty.reset();

    // Reset tools
    this.referenceLine.reset();
    this.tangentScrubber.reset();
    this.areaUnderCurveScrubber.reset();
    // Do not reset this.labeledPoints, because they are configured only via PhET-iO.
    // Do not reset this.verticalLines, because they are configured only via PhET-iO.
  }
```

**Comment by pixelzoom** [comment]
Sorry about that. The fix to AncillaryTool.ts would be:

```diff
  public reset(): void {
+   this.visibleProperty.reset();
    this.xProperty.reset();
  }
```

**Comment by veillette** [comment]
Work done. Closing.
