### ISSUE TITLE
Create allPointsScatterPlot and cuspsScatterPlot conditionally

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#189]
In CurveNode.ts:

```typescript
    this.allPointsScatterPlot = new ScatterPlot( chartTransform, allPointsScatterPlotDataSet, options.allPointsScatterPlotOptions );
    this.cuspsScatterPlot = new ScatterPlot( chartTransform, cuspsScatterPlotDataSet, options.cuspsScatterPlotOptions );
...
    if ( CalculusGrapherQueryParameters.allPoints ) {
      this.addChild( this.allPointsScatterPlot );
    }
    if ( CalculusGrapherQueryParameters.cuspsPoints ) {
      this.addChild( this.cuspsScatterPlot );
    }
```

So there are 2 scatter plots that are always created/update, but are only added if query parameters are present.  That seems like a significant amount of work that doesn't need to be done, and might impact responsiveness.  

Self-assigning to create/update these scatter plots conditionally.

**Comment by pixelzoom** [comment]
Correction... These scatter plots are always created, but they are conditionally updated.

**Comment by pixelzoom** [comment]
Done in the above commit. @veillette please review.

**Comment by veillette** [comment]
It never occurred to me that you could optionally create instances. Noted. Closing
