### ISSUE TITLE
Architectural Discussion

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/calculus-grapher#19]
@ariel-phet, @pixelzoom  and I discussed a plan for the architecture of calculus grapher on 6/30. This is a placeholder issue to document what was discussed.

1. Current plan for using CurvePoints that are close together, like the flash sim, seemed like an appropriate starting point.
2. Current hierarchy for curves looks good.
3. In terms of performance, it might not be a good idea for DerivativeCurve and IntegralCurve to listen to all yProperties of CurvePoints of their 'base' Curve. This will introduce 360 dependencies in a Multilink, which will likely introduce performance issues. I'll monitor performance, but the alternative solution would be to use an emitter that emits when the 'curve' has changed. I'll start with the emitter strategy for now.
4. For holes (https://github.com/phetsims/calculus-grapher/issues/18), @pixelzoom suggested doing something similar to my original plan:
> Another solution specific to calculus grapher would be to render the curve normally with a single Path and ignoring the discontinuity, then going over it and using separate dashed lines on top of the curve with a different line-dash and line-width. Unsure at this point how this would impact memory/performance.

5. I asked the question of how the view would know where to draw the holes in this picture (since technically in the model, the yProperty is null).
![image](https://user-images.githubusercontent.com/42391580/86152716-d6969700-babd-11ea-9441-cce7978e3922.png)

My initial thought was draw the holes at the same y values as the point on the left and the point on the right, but it might look weird if the points aren't close together. @pixelzoom said an alternative could be to find the slope on both sides and find what would be the y value at the hole's x-value. 

6. As far as the curve manipulation algorithms go, a good starting point would be to use the same algorithms that the flash simulation uses.

**Comment by veillette** [comment]
I read over this issue and we can safely close it as we have a pretty good handle on the architecture of calculus grapher
