### ISSUE TITLE
Should we support graphSets that have a different number of graphs

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#190]
One question we should address before tackling #95: Should we support graphSets that have a different number of graphs

such as 
```js
  const graphSets: GraphSet[] = [
      [ GraphType.INTEGRAL, GraphType.ORIGINAL, GraphType.DERIVATIVE ],
      [ GraphType.ORIGINAL, GraphType.DERIVATIVE ]
    ];
```

At some point in time, we had to handle such possibility and there is some code to handle this.

```js
    // determine the (view) height of the graph based on the number of visible graphs.
    const graphHeightProperty = new DerivedProperty( [ graphSetProperty ], graphsSelected => {
      const numberOfVisibleGraphs = graphsSelected.length;
      return CalculusGrapherConstants.GRAPH_VERTICAL_HEIGHT[ numberOfVisibleGraphs - 1 ];
    } );
```

However, at this point it is not leveraged, not tested, and it will complicate the implementation of #95.

**Comment by veillette** [comment]
@pixelzoom : We should resolve before tackling #95.

**Comment by veillette** [comment]
Doing a simple test on the `AdvancedScreen` with

```
    const graphSets: GraphSet[] = [
      [ GraphType.INTEGRAL, GraphType.ORIGINAL, GraphType.DERIVATIVE ],
      [ GraphType.ORIGINAL, GraphType.DERIVATIVE ]
    ];
```

reveals that
![Calculus Grapher screenshot (31)](https://user-images.githubusercontent.com/7633344/214611812-dd49b9f7-f85d-41c1-94f0-a8920ef0de9d.png)

The cueingArrowNode is not centered Properly, the yRange of the two graphSet remains the same (it shouldn't be).

**Comment by pixelzoom** [comment]
@veillette and I discussed. We're not going to support this.  But there is some work to do, which I'll handle:

* Add an assertion in GraphsNode that graphSets contain sets of the same length.
* Delete GraphsNode `graphHeightProperty` and related things can go away.  Change `graphHeightProperty` to `option.graphHeight`, and propagate where appropriate.

**Comment by veillette** [comment]
I'll note that in the process of removing ` graphHeightProperty`, there will be some incidental properties that can be cleaned up.

```js
    graphHeightProperty.link( height => {

      // TODO : too much repetition
      this.curveNode.dragBoundsProperty.value.setMaxY( height );
      this.predictCurveNode.dragBoundsProperty.value.setMaxY( height );

      // TODO: find a way to update touch/mouse area without resorting to this: https://github.com/phetsims/calculus-grapher/issues/74
      this.setCurvePointerAreas();
    } );
````

The dragBoundsProperty exists on `CurveNode` (which is odd because CurveNode does not have a drag handler, but I digress).
If we remove `graphHeightProperty`, we only need to create a local variable  `dragBoundsProperty` on the dragHandler of `TransformedCurveNode` and not an  instance on `CurveNode`.

**Comment by pixelzoom** [comment]
@veillette ready for review.  Summary:

* GraphsNode `graphHeightProperty` was replaced with GraphNodeOptions.graphHeight.

* CurveNode `dragBoundsProperty` was eliminated, and replaced with this in TransformedCurveNode:
```typescript
    this.continuousLinePlot.addInputListener( new DragListener( {
      dragBoundsProperty: new Property( new Bounds2( 0, 0, chartTransform.viewWidth, chartTransform.viewHeight ) ),
```

**Comment by veillette** [comment]
This turned out to be a welcomed clean up that removes a few TODO at the same time. Closing.
