### ISSUE TITLE
Lab screen has no tick marks at y-axis min/max

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#192]
Is it expected and OK that there are no tick marks at the min/max of the y-axis in the Lab screen? 

<img width="696" alt="screenshot_2197" src="https://user-images.githubusercontent.com/3046552/214641248-7f3cc0d2-b955-4663-b68b-55ee7bf535c7.png">

**Comment by veillette** [comment]
Short answer: It is not expected. Although it is not clear why it is the case.

**Comment by pixelzoom** [comment]
Discussed with @veillette.  The motivation was to keep the grid cells square.   We could put ticks at y min and max.  But this may introduce "special case" code, so avoid if possible?

**Comment by pixelzoom** [comment]
Design meeting: @amanda-phet wants to think about this some more. It might be less of an issue if we have minor grid lines.

**Comment by pixelzoom** [comment]
Minor gridlines were added in https://github.com/phetsims/calculus-grapher/issues/194.  As I said in https://github.com/phetsims/calculus-grapher/issues/194#issuecomment-1404411345:

> One other major change I should mention... The lookup table is the same _regardless of the number of graphs_.   So in the Lab screen (3 graphs), the grid cells are not square.  This seemed like an acceptable way to address https://github.com/phetsims/calculus-grapher/issues/192, and it doesn't bother me as much as I thought it would.  Your mileage may vary... 

This feels like an acceptable tradeoff to me.  @amanda-phet please have a look.

**Comment by amanda-phet** [comment]
This seems like it's no longer relevant, since we decided the Lab screen would go from -2 to 2.
