### ISSUE TITLE
Create Functional tests for curves

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#193]
In order to check that the Curve model of Calculus-Grapher works properly, I propose that we create a host of mathematical functions of preset curves that can readily "loaded" onto the simulation.
These functions would be hidden behind a (private) queryParameter.

**Comment by veillette** [comment]
@pixelzoom  suggested the following pattern to load the functions

```js
// ... in CalculusGrapherModel.ts

    if ( CalculusGrapherQueryParameters.presets ) {
      let presetIndex = 0;
      window.addEventListener( 'keydown', event => {
        if ( event.keyCode === 37 ) {
          // left arrow: apply previous preset to this.originalCurve
        }
        else if ( event.keyCode === 39 ) {
         // right arrow: apply next preset to this.originalCurve
        }
      } );
    }
```

**Comment by veillette** [comment]
In the commit above, I introduced a new Boolean (private) queryParameter `presetFunctions`:

This is invoked in `CalculusGrapherModel.js` 
``
    // debug functionality to cycle through preset curves
    if ( CalculusGrapherQueryParameters.presetFunctions ) {
      this.cyclePresetCurves();
    }
``

The ` cyclePresetFunction` method adds a keyboard listener to the Left and Right arrow keys. Using the left and right arrow functions, one can cycle through 10 PresetFunctions, that have been created in `PresetFunctions`.

Assigning to @pixelzoom to review.

**Comment by veillette** [comment]
I'll note that I did not bother addressing an issue with the cueing arrow (which assumes the curve is at y=0) as this is supposed to be an internal query parameter.

**Comment by veillette** [comment]
Hmm, I was wondering was it so unresponsive. I think that since we add the keyboard listener on window

```js
 // add a keyboard listener to ArrowLeft and ArrowRight
    window.addEventListener( 'keydown', event => {

      const isLeft = event.code === 'ArrowLeft';
      const isRight = event.code === 'ArrowRight';

      if ( isLeft || isRight ) {

        if ( isLeft ) {

          // decrease index value
          index--;
        }
        else if ( isRight ) {

          // increase index value
          index++;
        }

        // making sure the cycledIndex lies between 0 and length-1, even if index is negative
        const cycledIndex = ( index % length + length ) % length;

        // apply the math function to the original curve
        this.originalCurve.applyMathFunction( presetFunctions[ cycledIndex ] );
      }
```

then this is invoked four times (on the 4 screens), which makes it unresponsive.

**Comment by pixelzoom** [comment]
Nice feature!

Performance has been addressed in the above commits, along with a bit of cleanup.

Summary:

* Moved CalculusGrapherModel `cyclePresetCurves` to PresetFunctions `addKeyboardEventListener`, so that the entire implementation for `?presetFunctions` is in one place.

* Call `addKeyboardEventListener` from CalculusGrapherScreenView instead of CalculusGrapherModel, so that we have access to the Screen's `visibleProperty`.  This allows us to process events only for the visible Screen.  And since keyboard input is a "view" thing, it's more appropriate to wire this up in the view.

* In `addKeyboardEventListener`, process key events only when the screen is visible.

* ... plus a bit of cleanup and renaming in PresetFunctions.ts.

Back to @veillette for review. Close if OK.

**Comment by pixelzoom** [comment]
A question related to this...  Curve has option `mathFunction?: MathFunction`, which is evaluated by `getFromMathFunction`.   This is entirely different code than what is used to evaluate the MathFunctions in PresetFunctions. Should the same code be used?  Can we replace `getFromMathFunction` with `applyPresetFunction`?

**Comment by veillette** [comment]
Nice clean up above!!.

To answer the question in https://github.com/phetsims/calculus-grapher/issues/193#issuecomment-1407114426, the main difference is that one initialize the curve by creating new CurvePoints whereas the other is merely updating the y value of the CurvePoints.

I'm not sure how to combine the two. In some ways, the `getFromMathFunction` in`Curve` has two responsibilities: Creating an array of CurvePoints and initializing the CurvePoints.  On one hand, this is nice feature such that you could reset the curve to its initial math function. Initializing the curve to have y=0 and then applying the function would not reset properly. On the other hand, the `getFromMathFunction` is never leveraged anywhere, the only math function passed is the default `x=>0` .  So we could remove the functionality to set a math function in `Curve` instead. What do you think?

**Comment by pixelzoom** [comment]
My vote would be to remove the `mathFunction` option from Curve, and initialize to `f(x) = 0` in a more straightforward manner.  Like this patch:

<details>
<summary>patch</summary>

```diff
Subject: [PATCH] doc
---
Index: js/common/model/Curve.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/Curve.ts b/js/common/model/Curve.ts
--- a/js/common/model/Curve.ts	(revision e1ccff7a5b6ae7b8405a9a9baa90fcb1e3a54a6e)
+++ b/js/common/model/Curve.ts	(date 1674934323806)
@@ -32,7 +32,6 @@
 import optionize from '../../../../phet-core/js/optionize.js';
 import Property from '../../../../axon/js/Property.js';
 import ArrayIO from '../../../../tandem/js/types/ArrayIO.js';
-import { MathFunction } from './PresetFunctions.js';
 
 // constants
 const CURVE_X_RANGE = CalculusGrapherConstants.CURVE_X_RANGE;
@@ -43,7 +42,6 @@
 type SelfOptions = {
   xRange?: Range;
   numberOfPoints?: number;
-  mathFunction?: MathFunction;
   pointsPropertyReadOnly?: boolean;
 };
 
@@ -71,7 +69,6 @@
       // SelfOptions
       xRange: CURVE_X_RANGE,
       numberOfPoints: NUMBER_OF_POINTS,
-      mathFunction: () => 0,
 
       // PhetioObjectOptions
       phetioState: false,
@@ -84,8 +81,13 @@
     this.xRange = options.xRange;
     this.numberOfPoints = options.numberOfPoints;
 
-    // the Points that map out the curve within the domain. See the comment at the top of this file for full context.
-    const initialPoints = this.getFromMathFunction( options.mathFunction );
+    // Initial points, with equally spaced x values, and y=0
+    const initialPoints: CurvePoint[] = [];
+    for ( let i = 0; i < this.numberOfPoints; i++ ) {
+      const xNormalized = i / ( this.numberOfPoints - 1 ); // in the range [0,1]
+      const x = this.xRange.expandNormalizedValue( xNormalized );
+      initialPoints.push( new CurvePoint( x, 0 ) );
+    }
 
     this.pointsProperty = new Property( initialPoints, {
       isValidValue: points => isValidPoints( initialPoints, points ),
@@ -196,26 +198,6 @@
     }
   }
 
-  private getFromMathFunction( mathFunction: MathFunction ): CurvePoint[] {
-    // Populate the points of the curve with CurvePoints that are close together. CurvePoints are created at the
-    // start of the simulation here and are never disposed.
-
-    const points: CurvePoint[] = [];
-
-    const numberOfPoints = this.numberOfPoints;
-
-    for ( let i = 0; i < numberOfPoints; i++ ) {
-
-      // a value ranging from 0 to 1, inclusive;
-      const normalizedValue = i / ( numberOfPoints - 1 );
-
-      const x = this.xRange.expandNormalizedValue( normalizedValue );
-
-      points.push( new CurvePoint( x, mathFunction( x ) ) );
-    }
-    return points;
-  }
-
   private assignType(): void {
 
     // Loop through each trio of adjacent Points of the curve.
```

</details>

**Comment by veillette** [comment]
👍

**Comment by pixelzoom** [comment]
Cool. I'll apply the patch.

**Comment by pixelzoom** [comment]
Cool. Patch applied in the above commit. 

Anything else here @veillette? If not please close.

**Comment by veillette** [comment]
That all looks good. Closing
