### ISSUE TITLE
Add minor grid lines

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#194]
At 1/25/2023 design meeting with @amanda-phet @catherinecarter @veillette, there was a request to add minor grid lines to the graphs.   They should be lighter in color and thinner in lineWidth that the majhor grid lines.

**Comment by pixelzoom** [comment]
Oh boy, this sure got complicated!  The problem was that it was impossible to choose a minor gridline spacing, because the tick mark spacing varies between 1, 0.5, and 0.2 -- those last 2 spacings having no possible gridline spacing in common.

So this required some relatively major  changes. @veillette please review before having @amanda-phet review.

Summary of changes in the above commit:

* CalculusGrapherColors.ts are has 2 gridline colors: `majorGridlinesStrokeProperty` and `minorGridlinesStrokeProperty`.  They can be adjusted in the phetmarks Color Editor.

* The gridline spacing is currently defined in GraphNode.ts as:
```typescript
const MAJOR_GRID_LINE_SPACING = 1;
const MINOR_GRID_LINE_SPACING = 0.25;
```

* In GraphNode.ts, the `zoomProperty` listener had a fairly complicated algorithm for computing the y-axis range and tick spacing.  I replace that algorithm with a lookup table, an approach I've used in all of my sims.  It's a bit brute force, but so much easier to understand/change/maintain.  See `Y_ZOOM_INFO` in GraphNode.ts.  You can just look at it and quickly see if it meets the requirements for y-axis range and tick marks:

```typescript
const Y_ZOOM_INFO: ZoomInfo[] = [
  { max: 20, tickSpacing: 10 },
  { max: 10, tickSpacing: 5 },
  { max: 4, tickSpacing: 2 },
  { max: 2, tickSpacing: 1 },
  { max: 1, tickSpacing: 0.5 },
  { max: 0.5, tickSpacing: 0.25 }
];
```

* The problematic y-axis range was [-0.4,0.4] with tick spacing 0.2.   In case there is something pedogocially special about that range... To be compatible with `MINOR_GRID_LINE_SPACING `, I changed that to [-0.5,0.5] with tick spacing 0.25.  For example:

<img width="125" alt="screenshot_2201" src="https://user-images.githubusercontent.com/3046552/214726265-2ca9096b-c73d-482d-8b52-6ed676d10784.png">

If that's not acceptable, then we'll need to change the [-1,1] range to have tick spacing 0.2, and change MINOR_GRID_LINE_SPACING to 0.2 -- which looks like too many ticks imo, for example:

<img width="123" alt="screenshot_2200" src="https://user-images.githubusercontent.com/3046552/214726032-07195639-0af3-4c4b-8e5a-d540b5c21ece.png">

* When the major tick marks get close together, the minor grid lines result in a visual mess. So see this line in GraphNode.ts:
```typescript
// Hide the y-axis minor grid lines if they get too close together.
yMinorGridLines.visible = ( Math.abs( this.chartTransform.modelToViewDeltaY( MINOR_GRID_LINE_SPACING ) ) > 5 );
```

**Comment by pixelzoom** [comment]
One other major change I should mention... The lookup table is the same _regardless of the number of graphs_.   So in the Lab screen (3 graphs), the grid cells are not square.  This seemed like an acceptable way to address https://github.com/phetsims/calculus-grapher/issues/192, and it doesn't bother me as much as I thought it would.  Your mileage may vary...

**Comment by pixelzoom** [comment]
One other major change I should mention... The zoom lookup table is the same _regardless of the number of graphs_.   So in the Lab screen (3 graphs), the grid cells are not square.  This seemed like an acceptable way to address https://github.com/phetsims/calculus-grapher/issues/192, and it doesn't bother me as much as I thought it would.  If this is not acceptable, we can customize the zoom lookup table for the Lab screen.

**Comment by pixelzoom** [comment]
Are you not fond of the lookup table approach, or the fact that the lookup table is the same regardless of the number of graphs?

I get it that computing the y-axis range and tick spacing is more general. And it assumes that there's a general algorithm for computing y-axis range and ticks, which (in my experience) is not always the case -- someone inevitably askes for a range/spacing that doesn't fit the algorithm, which I think we're going to end up seeing in this sim too.  And secondarily, I had a lot of trouble making changes to the algorithm without unintentionally changing something.

**Comment by veillette** [comment]
Mostly that the zoom lookup table is the same regardless of the number of graphs, but since we decided that it is fine and it resolves #192. I'm not very fond of the look up tale per say but since we only have have a handful of zoom levels (instead of 10) and keep the same zoom levels for all screens, I think the convenience of making custom levels outweighs the need for a  general (but rigid ) algorithm. 

However, we should document (perhaps in `CalculusGrapherConstants` ?) that if one changes the x-range, they should modify the zoom levels as well.

**Comment by pixelzoom** [comment]
> However, we should document (perhaps in `CalculusGrapherConstants` ?) that if one changes the x-range, they should modify the zoom levels as well.

That's an excellent idea. Would you mind adding that comment @veillette? I was not very involved in the refinement of the x and y ranges, and you have a better understanding of how they are related.

**Comment by veillette** [comment]
Yes, will do.

**Comment by veillette** [comment]
I added some documentation in `CalculusGrapherConstants` about the side effects to be aware if one changes `CURVE_C_RANGE`.

**Comment by veillette** [comment]
Our work is done here. Closing.
