### ISSUE TITLE
Zero tick should be labeled '0', not '0.0'

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#195]
We don't usually show zero with decimal places.  On the charts:

<img width="516" alt="screenshot_2199" src="https://user-images.githubusercontent.com/3046552/214721877-2c36169f-f012-4e8c-a9b7-636e2c800180.png">

**Comment by pixelzoom** [comment]
Done in the above commit. @amanda-phet please sign off on this change, close if OK.

@veillette FYI, because I factored out private `function createYTickLabelSet`.

**Comment by veillette** [comment]
At the 1/30 meeting, we agree that this was a welcome change.

**Comment by veillette** [comment]
Closing
