### ISSUE TITLE
Instrument graphSetProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#196]
In CalculusGrapherScreenView.ts, this Property needs to be instrumented:

```typescript
 this.graphSetProperty = new Property( options.graphSets[ 0 ]
```

And ideally, the valid values should be displayed as radio buttons in Studio.

**Comment by pixelzoom** [comment]
I instrumented `graphSetProperty` in the above commit - a little tricky.  Unfortunately the `validValues` are not showing up as radio buttons in Studio, see screenshot below.  I'm not sure why this is, but perhaps they need to be PhET-iO elements to be presented as radio buttons. I'll disucss with the PhET-iO team.

<img width="851" alt="screenshot_2204" src="https://user-images.githubusercontent.com/3046552/214878017-54f4e088-7305-4a68-aca5-583bd4d3644c.png">

**Comment by pixelzoom** [comment]
There were no radio buttons for the above case (`derivativeScreen.view.graphSetProperty`) because that screen has only 1 choice.   That presented a new problem - why are Get/Set UI buttons provided when there is only 1 valid value? Reported in https://github.com/phetsims/studio/issues/291.  In the meantime, I worked around this by setting `validValues: ( options.graphSets < 2 )` to hid the Get/Set UI buttons.

In the Advanced and Lab screen, we do indeed see radio buttons.  But the radio buttons results in a failure.  This seems like a general problem, and is reported in https://github.com/phetsims/studio/issues/291.  Further work on this issue is blocked until that issue is addressed.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/studio/issues/290 (Get/Set UI) was resolved and working nicely. 

https://github.com/phetsims/studio/issues/291 (failure when choosing radio button) is still unresolved and blocking.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/studio/issues/291 is no longer failing when selecting radio buttons in Studio.  But now the rectangular radio button in the sim, for selecting values of graphSetProperty, or permanently disabled after making a selection in Studio.  I suspect that validation is someone changing the validValues. See https://github.com/phetsims/studio/issues/291#issuecomment-1412924563.

So still blocked.

**Comment by pixelzoom** [comment]
Over in https://github.com/phetsims/calculus-grapher/issues/196, we concluded that we'll need a custom IOType for graphSetProperty values, probably GrapSetIO.

**Comment by zepumph** [comment]
Please wait on this until @samreid can commit the new IOType we are working on for this application.

**Comment by pixelzoom** [comment]
In the above commit, I added class `GraphSet`, with IOType `GraphSetIO`.   It uses reference type serialization, but overrides `toStateObject` so that the GraphTypes that are members of the set will be visible in the Studio UI.

It seems to be working OK. But the presentation in Studio is ugly. For example, shown below is the Lab screen, which has 2 GraphSets.  I can certainly grok this, but it's not exactly friendly for instructional designers. 

<img width="749" alt="screenshot_2258" src="https://user-images.githubusercontent.com/3046552/216526304-c00d1e61-135e-4670-bb8d-2234db2f927d.png">

I'm also not wild about the values cluttering up the Studio tree.  For example, for the Lab screen:

<img width="302" alt="screenshot_2259" src="https://user-images.githubusercontent.com/3046552/216526485-b99e220e-8a94-4389-9c72-7d3d4fca6ae1.png">

@zepumph @samreid questions:

* Any suggestion to improve this?  Is this what you had in mind during today's meeting about https://github.com/phetsims/studio/issues/291?

* Labeling radio buttons with the full state object is a really ugly UX. Have you considered adding an IOType method for specifying how a value is presented in Studi as (for example) the label on radio buttons?

**Comment by pixelzoom** [comment]
In the above commit, I added `phetioDocumentation` to the GraphSet instances.  For example:

<img width="712" alt="screenshot_2262" src="https://user-
images.githubusercontent.com/3046552/216657393-1a324b7c-4ac9-4b19-a92a-2e800b2ee1de.png">

Now that all GraphSet instances have documentation describing which graphs they show, I reconsidered the value that should be shown next to radio buttons in Studio. In the screenshot in https://github.com/phetsims/calculus-grapher/issues/196#issuecomment-1415099825, we had:

<img width="656" alt="screenshot_2261" src="https://user-images.githubusercontent.com/3046552/216657425-fe2f3666-a1db-4d6a-88ce-607107251901.png">

I suspect that this will look scary to the instructional designer, and not really convey useful information. And I don't think that showing `"graphTypes": [ "INTEGRAL", "ORIGINAL", "DERIVATIVE" ]` is particularly helpful, since we don't expose (or describe) these GraphType enumeration values elsewhere.  So I removed  the `"graphTypes"` field from GraphSetIO, and the radio button display now looks like this:

<img width="741" alt="screenshot_2263" src="https://user-images.githubusercontent.com/3046552/216658073-6106d923-2ee8-45f6-8514-98b52c9904fd.png">

Since we now have `phetioDocumentation` for each GraphSet instance, the user can go to (for example) `model.graphSet0` to find out more about that value choice.

**Comment by pixelzoom** [comment]
Notes from Zoom call with @samreid ...

Over in https://github.com/phetsims/tandem/issues/292, @samreid and @zepumph are creating a new IOType, `ReferenceDataTypeIO`, for use with JavaScript's Array type. That looks useful for other situations, but the current instrumentation of `graphSetProperty`(using GraphSetIO) looks appropriate for Calculus Grapher.  So no futher changes are needed and this issue can be close.
