### ISSUE TITLE
Instrument various Text and RichText elements

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#197]
Searching for `new Text` and `new RichText`, I see that there are quite a few of these that are not instrumented for PhET-iO.

**Comment by veillette** [comment]
Question: Does 
``
   // no PhET-iO instrumentation
``
mean that we intentionally don't want to instrument or is it a tag to identify missing instrumentation?

**Comment by pixelzoom** [comment]
It's to indicate that we do not want to (and do not intend to) instrument it.  Maybe I should rework that comment?

For things that still need to be instrument and have been identified, I've been adding a TODO like

```
//TODO https://github.com/phetsims/calculus-grapher/issues/197
```

**Comment by veillette** [comment]
Thanks for the clarification. I think we can leave as is.

**Comment by pixelzoom** [comment]
I think it would improve the message to change it as shown below, and I'll do this now.

```diff
- // no PhET-iO instrumentation
+ // no PhET-iO instrumentation is desired
```

**Comment by pixelzoom** [comment]
Comment refined in the above commits, including 1 in equality-explorer.

**Comment by pixelzoom** [comment]
This issue has been completed.  All occurrences of `new Text` and `new RichText` have either been instrumented, or have a comment like this:

```
// No PhET-iO instrumentation is desired.
```

If there are any changes to be made, they will be identified as part of general PhET-iO review.

Closing.
