### ISSUE TITLE
Remove CurveNode `setPointerAreas`?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#199]
It would be nice if we didn't need this in CurveNode.ts, but I understand why it's currently needed:

```typescript
  public setPointerAreas(): void {
    throw new Error( 'Set Pointer Areas not handled on base class' );
  }
```

Self assigning to investigate.

**Comment by veillette** [comment]
Agree!

**Comment by pixelzoom** [comment]
Also noting a problem with this in OriginalGraphNode.ts:

```typescript
    this.yZoomLevelProperty.link( () => {

      // TODO: find a way to update touch/mouse area without resorting to this: https://github.com/phetsims/calculus-grapher/issues/74
      this.setCurvePointerAreas();
    } );
```

First, `yZoomLevelProperty` never changes for the original graph.  But if it did, there's an ordering problem here.  If this listener is called before the CurveNodes are updated, then their poitner areas will be incorrect.

**Comment by pixelzoom** [comment]
In the above commits, I addressed 2 issues:

* First GraphNode `yZoomLevelProperty` and `yZoomButtonGroup` were showing up in PhET-iO for the Original graph. So I conditionally instrumented them.

* Because they are conditionally instrumented, I could remove the fault `yZoomLevelProperty` listener (identified in https://github.com/phetsims/calculus-grapher/issues/199#issuecomment-1407299239) from OriginalGraphNode.

* Because the yZoomLevelProperty  `yZoomLevelProperty` listener was the only thing calling OriginalGraphNode `setCurvePointerAreas`, I could remove that method, as well as CurveNode `setPointerAreas`.

@veillette please have a look, close if OK.

**Comment by veillette** [comment]
Question:
Do we even need a dependency on `chartRectangle.boundsProperty` below?
```js
    // Adjust button positions if the chartRectangle is resized or ticks change visibility.
    Multilink.multilink( [ chartRectangle.boundsProperty, ticksParent.visibleProperty ],
      ( bounds, visible ) => {
        const rightNode = visible ? ticksParent : chartRectangle;

        // eyeToggleButton at bottom-left of chart rectangle
        eyeToggleButton.rightBottom = rightNode.leftBottom.addXY( -BUTTON_SPACING, 0 );

        // yZoomButtonGroup at left-center of chart rectangle
        if ( yZoomButtonGroup ) {
          yZoomButtonGroup.rightCenter = rightNode.leftCenter.addXY( -BUTTON_SPACING, 0 );
        }
      } );
```

I think listeners on `chartRectangle.boundsProperty` are vestigial as nothing can change the bounds of the `ChartRectangle` at this point.  Am i right?

**Comment by pixelzoom** [comment]
You are correct. I forgot that we made that simplification last week.  

In the above commit:

* Removed the observers of `chartRectangle.boundsProperty`
* Add an observer to `labelNode.boundsProperty`, because it's size changes.  Since `labelNode` is in the left-top of chartRectangle, it's not strictly necessary.  But I think it's a good habit to dynamically position things that change.

**Comment by pixelzoom** [comment]
Doh! It was noted in the design meeting today that my changes above broke the initial range of the original chartTransform.  This is because I removed yProperty from the orginal graph, and it's listener was responsible for setting chartTransform.modelYRange.  Fix coming...

**Comment by pixelzoom** [comment]
` chartTransform.modelYRange` fixed in the above commit.  The default is now [-2,2].

**Comment by veillette** [comment]
It turns out that removing the zooming in Original graph removes a lot of cruft!
I think we had forgotten the observers of `chartRectangle.boundsProperty` in a previous issue. It is a good riddance.
Yes I agree, it is fine to keep the listener on `labelNode.boundsProperty` in case a future maintainer would like to position it by something else than top left. 

This looks good. Closing.
