### ISSUE TITLE
Review existing unfuddle ticket 2660

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/calculus-grapher#2]
@amanda-phet please see if this unfuddle ticket has any relevant suggestions to the redesign

https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/2660

**Comment by amanda-phet** [comment]
Here are the issues that Mike wanted fixed: 
1. mapquest style zoom control that indicates zoom level
2. change cursor to indicate curve type
3. user controlled smoothing for freeform drawing, including velocity regulated smoothing
4. file save/load

I don't understand 2 and don't recall discussing 4. I will bring them up in design meeting.

**Comment by amanda-phet** [comment]
Discussed in design meeting 5/28. Closing.
