### ISSUE TITLE
Some polishes for curve manipulations model width

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#200]
This issue will keep track behavior of the various curve manipulation mode and their interaction with curve manipulation width.

**Comment by veillette** [comment]
![image](https://user-images.githubusercontent.com/7633344/214950039-b92225a5-24a1-4dbf-a1f6-5513b0f578a5.png)
One issue that was noted @amanda-phet was that the pedestal was unusually wide compare to the other curve mode.

**Comment by amanda-phet** [comment]
Yes. Can you make the default pedestal width (at that second tick mark on the slider) equivalent to the width that is currently the narrowest pedestal? I think it would be nice to be able to go even more narrow, and also be able to fit these three all by default.

![image](https://user-images.githubusercontent.com/7852916/215847966-7e01cfe8-81b0-4928-8b8c-2e7c44e26a00.png)

**Comment by veillette** [comment]
I modified the pedestal function such that the curve manipulation width no longer sets the width of the plateau, bur rather the width of the base. This lead to a narrower pedestal for a given "width".

**Comment by veillette** [comment]
Here are some screenshot with the narrow width and default width curve manipulation.

The four modes shown are parabola, triangle, pedestal and hill.

**Narrowest width setting:**
![image](https://user-images.githubusercontent.com/7633344/216396636-3eb92cfd-f414-41e7-a376-cbc256951eac.png)

**Width the default width:**
![image](https://user-images.githubusercontent.com/7633344/216397191-4414d8b3-d3cf-42f4-bca3-de5c113aa263.png)

**Comment by veillette** [comment]
We didn't get to it today, but assigning to @amanda-phet to review and comment.

**Comment by amanda-phet** [comment]
The widths look good. Closing.
