### ISSUE TITLE
Credits for 1.0 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#202]
All credits except QA can be filled in at any time.

QA credits should be filled in during the QA process, after each dev-test and RC-test cycle.

**Comment by amanda-phet** [comment]
Lead Designer: Amanda McGarry
Team: Catherine Carter, Michael Dubson, Brandon Li, Ariel Paul, Kathy Perkins,

**Comment by pixelzoom** [comment]
I added https://github.com/phetsims/calculus-grapher/issues/202#issuecomment-1410848535 to the credits. I also took an initial stab at "softwareDevelopment", see below. @veillette does this seem correct to you?

<img width="511" alt="screenshot_2220" src="https://user-images.githubusercontent.com/3046552/215875799-f36e99f7-9eee-40f7-88ba-2c18df8c9428.png">

**Comment by amanda-phet** [comment]
If Brandon is listed in development I don't think he needs to be in team. I
wasn't sure how we are handling large development teams so I put him in
team, but please go ahead and delete him from team.

**Comment by pixelzoom** [comment]
Thanks for noticing that @amanda-phet. I confirmed with @veillette: Brandon made a significant contribution to the early software development, so it's appropriate that he is listed in Software Development. So I've removed him from Team in the above commit.

**Comment by veillette** [comment]
Yes, that looks correct to me for the software development team.

**Comment by veillette** [comment]
Unassigning until we circle back to it for the QA credits.

**Comment by pixelzoom** [comment]
In the above commit, I added @Nancy-Salpepi and @KatieWoe for their role in https://github.com/phetsims/qa/issues/921.

**Comment by Nancy-Salpepi** [comment]
Jaron Droder also did QA testing.

**Comment by pixelzoom** [comment]
Jaron Droder has been added for https://github.com/phetsims/qa/issues/921.

**Comment by pixelzoom** [comment]
Jaron Droder has been added for https://github.com/phetsims/qa/issues/921.

**Comment by pixelzoom** [comment]
The 1.0 release branch has been created.  So any additional credits changes will need to be pushed to master, then cherry-picked to calculus-grapher 1.0 branch.

**Comment by veillette** [comment]
For https://github.com/phetsims/calculus-grapher/issues/202, QA should confirm that the credits are up to date.

**Comment by veillette** [comment]
In https://github.com/phetsims/qa/issues/933, QA confirmed that the QA credits are up to date.

**Comment by veillette** [comment]
The simulation has been published. Closing

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
