### ISSUE TITLE
Draw attention to the interactive graph 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#204]
In today design meeting, we decided to put a "glow" around the interactive graph, color-code to whether f(x) or "Prefict" is selected. This was suggested by @ariel-phet.

**Comment by pixelzoom** [comment]
Done in the above commits, example screenshot below.  Opacity of the highlight is currently 0.25.

I'd like to hear what the team thinks of this, including @ariel-phet who suggested this a highlight.

<img width="934" alt="screenshot_2214" src="https://user-images.githubusercontent.com/3046552/215593601-ca44bdef-5d25-41d2-aeb9-4ff6f5cc87a9.png">

<img width="926" alt="screenshot_2215" src="https://user-images.githubusercontent.com/3046552/215593620-7b22bf84-c282-4521-86a4-a998ae5972a7.png">

**Comment by catherinecarter** [comment]
I like it as it does a nice job of highlighting the graph that's manipulatable while simultaneously letting the user know if they're in f(x) or predict mode. One thing I wonder is whether the outline should disappear once the graph has been interacted with, but reappear each time the user switches between f(x) and predict mode. Not sure if that's feasible or desirable, but I'd be curious what others think.

**Comment by pixelzoom** [comment]
> ...  One thing I wonder is whether the outline should disappear once the graph has been interacted with, but reappear each time the user switches between f(x) and predict mode. ...

This will be complicated.  What about when the user switches screens? Do they need a reminder when they come back to a screen.

**Comment by veillette** [comment]
Another question is should the graph highlight be present if we use the eyeToggle to make the curve disappear.

**Comment by pixelzoom** [comment]
I think it would be fine for the highlight to remain when the eyeToggle is set to "off".

**Comment by amanda-phet** [comment]
I am looking at this behavior on PhET test and like the current faint color-coded stroke ("highlight") quite a bit.

I think the highlight should go away when the eyeToggle is off. The highlight does a great job of helping us see where we should interact, but we don't necessarily want that graph to always be highlighted above all other graphs. If eyeToggle is being used, it's likely because we _don't_ want that graph to be the main focus at that moment.

**Comment by pixelzoom** [comment]
In the above commit, the highlight is hidden when the eyeToggle is off.

**Comment by ariel-phet** [comment]
I think all is looking nice -- the highlight appears to do the intended job and is not too heavy handed. I think it does an especially nice job on the lab screen drawing your eye to the interactive graph.

**Comment by veillette** [comment]
This looks good. The design team agrees (2/2 meeting) Closing
