### ISSUE TITLE
Find a more precise way to detect cusp points. 

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#208]
The most common way to generate curves in this simulation is to add piecewise functions from the curve manipulation modes. For some of these modes, this lead to the formation of cusps at the edge of the function. In #110, we are attempting to calculate the derivative based on the presence of such points in the base curve. 

Our current approach to detect cusp points is too local, and it lead to some false positive and false negative cusp points. 
Below, the cusps are shown in green circles. Note that the cusps are only visible with a private queryParameter: `cuspsPoints=true`
![image](https://user-images.githubusercontent.com/7633344/215818778-58b8b5d6-1c11-475f-9578-1d05df8f8fde.png)

**Comment by pixelzoom** [comment]
3/7/2023 @veillette and I discussed in pairing.  He's going to investigate using info about what shape is being drawn to create known cusps for that shape.  This would be ultimately more reliable than the current ad hoc method, and would likely be more maintainable too.

**Comment by veillette** [comment]
I have made several commits but I can see that this new approach is clearly the way to go. 
There is more work to be done on the second derivative and the sinusoid function, but based on the work on Triangle, parabola, and the freeform, it looks very promising.
There is some more clean up and documentation to add as well.

**Comment by veillette** [comment]
The commit, https://github.com/phetsims/calculus-grapher/commit/51a34daecfc76692ff1abedd089c058626a2853e, address how to add cusps to the sinusoid function.

**Comment by veillette** [comment]
All the curve Manipulation methods are assigning type when needed. 
There is still report of problem for the freeform mode, which is tracked in #276. 
I'm going to close this issue. 
I created an issue (#292) to let the QA team know to look for problems associated with cusps.
