### ISSUE TITLE
Improve drag performance of curves

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#210]
During the 1/31 meeting, we noted that dragging the original curve leads to garbage collections.  Potentially related to #74.

**Comment by pixelzoom** [comment]
From our meeting today:

* Search out allocations (like new Vector2) that could be eliminated in critical code
* Improve performance by instantiating (or at least updating) only the curves and tools that are relevant for a screen
* Verify that Tangent and Area Under Curve are updated only when visible
* TransformedCurve.ts: Replace ‘new Vector2’ with passing x & y components to methods

**Comment by pixelzoom** [comment]
Reminder that we should test the responsiveness of a built version, to see if assertions in critical code are impacting responsiveness.

**Comment by pixelzoom** [comment]
Also a reminder that we need to instantiate all curves in CalculusGraphModel, regardless of whether they appear in the screen, because we want to see their y values in the AncillaryTools.

**Comment by pixelzoom** [comment]
> Reminder that we should test the responsiveness of a built version, to see if assertions in critical code are impacting responsiveness.

I tested a build version on my 2019 MacBook Pro. Dragging feels a bit smoother. But GC is still a problem -- it pauses frequently, and frame rate drops as low as 6fps.

**Comment by veillette** [comment]
Here is a comparison of heap between two snapshots. The only difference is that I played with the dragged the curve for the second snapshot. This shows the new objects we created.

![image](https://user-images.githubusercontent.com/7633344/216092206-be2fe8f8-4157-416b-ae69-5c04a39beb61.png)

**Comment by veillette** [comment]
One thing we have not looked at are allocations generated by `setPointerAreas`.

**Comment by pixelzoom** [comment]
Inspecting occurrences of "= new" in all calculus-grapher files, I can safely say that `new Vector2` seems to be the only dynamic allocation that we're explicitly doing.

In bamboo (e.g. LinePlot `update`), I see `new Vector2` and `new Shape`.

In Shape `getStrokedShape`, I see many allocations.  Here's the implementation, and I've added the "// allocates" comments:

```
  getStrokedShape( lineStyles ) {
    let subpaths = [];
    const bounds = Bounds2.NOTHING.copy();  // allocates Bounds2
    let subLen = this.subpaths.length;
    for ( let i = 0; i < subLen; i++ ) {
      const subpath = this.subpaths[ i ];
      const strokedSubpath = subpath.stroked( lineStyles ); // allocates SubPath[], and other things internally
      subpaths = subpaths.concat( strokedSubpath ); // allocates SubPath[]
    }
    subLen = subpaths.length;
    for ( let i = 0; i < subLen; i++ ) {
      bounds.includeBounds( subpaths[ i ].bounds );
    }
    return new Shape( subpaths, bounds );
  }
```

**Comment by pixelzoom** [comment]
Brainstorming here... Instead of putting the DragListener and pointer areas on the TransformedCurveNodes, how about putting them on OriginalGraphNodes's `chartRectangle`.   Only one of the 2 curves is interactive at any given time. You could still attempt to drag the curve directly. But you could also click somewhere above/below the curve - Pointer down anywhere in the chartRectangle would move change the curve to have the pointer's y value.

**Comment by pixelzoom** [comment]
@veillette and I discuss the idea in https://github.com/phetsims/calculus-grapher/issues/210#issuecomment-1412310749.  If clicking anywhere in the chartRectangle is not desirable, we could dynamically change the chartRectangle to `cursor: 'pointer'` when it is "close" to an interactive curve, and only drag the curve when we're within that closeness.

**Comment by pixelzoom** [comment]
Below is a quick patch that allows you to click or click-and-drag anywhere in the chartRectangle to modify the interactive curve.   It was committed, published in [1.0.0-dev.9](https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.9/phet/calculus-grapher_all_phet.html), then reverted.

I really like the way this feels.  It's SO much easier to quickly create curves by just clicking in the chartRectangle.  And you can still drag curves like you could before.

<details>
<summary>patch</summary>

```diff
Subject: [PATCH] fix itemsPerPage for Carousel, https://github.com/phetsims/number-suite-common/issues/37
---
Index: js/common/view/TransformedCurveNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/TransformedCurveNode.ts b/js/common/view/TransformedCurveNode.ts
--- a/js/common/view/TransformedCurveNode.ts	(revision 0b685c07004fa1d20e28107cc01e340fc7b60a2a)
+++ b/js/common/view/TransformedCurveNode.ts	(date 1675269189760)
@@ -11,24 +11,16 @@
  * @author Martin Veillette
  */
 
-import { DragListener } from '../../../../scenery/js/imports.js';
 import calculusGrapher from '../../calculusGrapher.js';
 import TransformedCurve from '../model/TransformedCurve.js';
 import CurveNode, { CurveNodeOptions } from './CurveNode.js';
 import optionize, { EmptySelfOptions } from '../../../../phet-core/js/optionize.js';
 import ChartTransform from '../../../../bamboo/js/ChartTransform.js';
-import { LineStyles } from '../../../../kite/js/imports.js';
-import Vector2 from '../../../../dot/js/Vector2.js';
 import CurveManipulationProperties from '../model/CurveManipulationProperties.js';
 import CalculusGrapherConstants from '../CalculusGrapherConstants.js';
 import CueingArrowsNode from './CueingArrowsNode.js';
 import BooleanProperty from '../../../../axon/js/BooleanProperty.js';
 import DerivedProperty from '../../../../axon/js/DerivedProperty.js';
-import Property from '../../../../axon/js/Property.js';
-import Bounds2 from '../../../../dot/js/Bounds2.js';
-
-// For use with Shape getStrokedShape
-const LINE_STYLES = new LineStyles( { lineWidth: 10 } );
 
 type SelfOptions = EmptySelfOptions;
 
@@ -37,7 +29,8 @@
 export default class TransformedCurveNode extends CurveNode {
 
   // has this node ever been userDragged, used for tracking the visibility of the cueingArrows
-  private readonly wasDraggedProperty: BooleanProperty;
+  public readonly wasDraggedProperty: BooleanProperty;
+  public readonly transformedCurve: TransformedCurve;
 
   public constructor( curve: TransformedCurve,
                       curveManipulationProperties: CurveManipulationProperties,
@@ -54,6 +47,8 @@
 
     super( curve, chartTransform, options );
 
+    this.transformedCurve = curve;
+
     this.wasDraggedProperty = new BooleanProperty( false, {
       tandem: options.tandem.createTandem( 'wasDraggedProperty' ),
       phetioReadOnly: true
@@ -73,54 +68,6 @@
     } );
 
     this.addChild( cueingArrowsNode );
-
-    //----------------------------------------------------------------------------------------
-    // Add a DragListener to the linePlot for manipulating the TransformedCurve model. Listener is never removed since
-    // TransformedCurveNodes are never disposed.
-
-    let penultimatePosition: Vector2;
-    let antepenultimatePosition: Vector2 | null = null;
-
-    this.continuousLinePlot.addInputListener( new DragListener( {
-      dragBoundsProperty: new Property( new Bounds2( 0, 0, chartTransform.viewWidth, chartTransform.viewHeight ) ),
-      applyOffset: false,
-      start: () => {
-
-        // Indicate that we've touched the curve, and hide the cueing arrows.
-        this.wasDraggedProperty.value = true;
-
-        // Save the current values of the Points for the next undoToLastSave call.
-        // This must be called once at the start of dragging (and not on each micro drag-position change).
-        curve.saveCurrentPoints();
-
-        // set the second to last position to null, since it is a new drag.
-        antepenultimatePosition = null;
-      },
-      drag: ( event, listener ) => {
-
-        // current modelPosition
-        const modelPosition = chartTransform.viewToModelPosition( listener.modelPoint );
-
-        // previous (model) position the drag
-        penultimatePosition = chartTransform.viewToModelPosition( listener.modelPoint.minus( listener.modelDelta ) );
-
-        // update curve based on mode and width
-        curve.userManipulatedCurve(
-          curveManipulationProperties.mode,
-          curveManipulationProperties.width,
-          modelPosition,
-          penultimatePosition,
-          antepenultimatePosition );
-
-        // update antepenultimatePosition
-        antepenultimatePosition = penultimatePosition;
-
-      },
-      tandem: options.tandem.createTandem( 'dragListener' )
-    } ) );
-
-    // Initialize pointer areas. They will be updated as the curve changes.
-    this.setPointerAreas();
   }
 
   /**
@@ -133,19 +80,6 @@
 
   protected override updateCurveNode(): void {
     super.updateCurveNode();
-    this.setPointerAreas();
-  }
-
-  /**
-   * Sets the pointer areas for manipulating the curve.
-   */
-  private setPointerAreas(): void {
-
-    // create a dilated shape based on the continuous line plot shape
-    const dilatedCurveShape = this.continuousLinePlot.shape!.getStrokedShape( LINE_STYLES );
-
-    this.continuousLinePlot.touchArea = dilatedCurveShape;
-    this.continuousLinePlot.mouseArea = dilatedCurveShape;
   }
 }
 
Index: js/common/view/CurveNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/CurveNode.ts b/js/common/view/CurveNode.ts
--- a/js/common/view/CurveNode.ts	(revision 0b685c07004fa1d20e28107cc01e340fc7b60a2a)
+++ b/js/common/view/CurveNode.ts	(date 1675269189779)
@@ -63,7 +63,7 @@
   private readonly allPointsScatterPlot?: ScatterPlot;
   private readonly cuspsScatterPlot?: ScatterPlot;
 
-  protected readonly curve: Curve;
+  public readonly curve: Curve;
 
   public constructor( curve: Curve, chartTransform: ChartTransform, providedOptions?: CurveNodeOptions ) {
 
Index: js/common/view/OriginalGraphNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/OriginalGraphNode.ts b/js/common/view/OriginalGraphNode.ts
--- a/js/common/view/OriginalGraphNode.ts	(revision 0b685c07004fa1d20e28107cc01e340fc7b60a2a)
+++ b/js/common/view/OriginalGraphNode.ts	(date 1675269636124)
@@ -16,7 +16,7 @@
 import CalculusGrapherColors from '../CalculusGrapherColors.js';
 import TReadOnlyProperty from '../../../../axon/js/TReadOnlyProperty.js';
 import GraphNode, { GraphNodeOptions } from './GraphNode.js';
-import { HBox, Rectangle, TColor, Text } from '../../../../scenery/js/imports.js';
+import { DragListener, HBox, PressedDragListener, Rectangle, TColor, Text } from '../../../../scenery/js/imports.js';
 import CalculusGrapherConstants from '../CalculusGrapherConstants.js';
 import ChartTransform from '../../../../bamboo/js/ChartTransform.js';
 import CalculusGrapherModel from '../model/CalculusGrapherModel.js';
@@ -34,6 +34,9 @@
 import ShowOriginalCurveCheckbox from './ShowOriginalCurveCheckbox.js';
 import LabeledPointsNode from './LabeledPointsNode.js';
 import PickRequired from '../../../../phet-core/js/types/PickRequired.js';
+import Property from '../../../../axon/js/Property.js';
+import Bounds2 from '../../../../dot/js/Bounds2.js';
+import Vector2 from '../../../../dot/js/Vector2.js';
 
 type SelfOptions = EmptySelfOptions;
 
@@ -141,6 +144,56 @@
       options.tandem.createTandem( 'labeledPointsNode' )
     );
     this.addChild( labeledPointsNode );
+
+    const originalCurveNode = this.curveNode as TransformedCurveNode;
+    assert && assert( originalCurveNode instanceof TransformedCurveNode ); // eslint-disable-line no-simple-type-checking-assertions
+    const interactiveCurveNodeProperty = new DerivedProperty( [ model.predictModeEnabledProperty ],
+      predictModeEnabled => predictModeEnabled ? this.predictCurveNode : originalCurveNode
+    );
+
+    let penultimatePosition: Vector2;
+    let antepenultimatePosition: Vector2 | null = null;
+
+   const updateCurve = ( listener: PressedDragListener ): void => {
+
+      // current modelPosition
+      const modelPosition = this.chartTransform.viewToModelPosition( listener.modelPoint );
+
+      // previous (model) position the drag
+      penultimatePosition = this.chartTransform.viewToModelPosition( listener.modelPoint.minus( listener.modelDelta ) );
+
+      // update curve based on mode and width
+      interactiveCurveNodeProperty.value.transformedCurve.userManipulatedCurve(
+        curveManipulationProperties.mode,
+        curveManipulationProperties.width,
+        modelPosition,
+        penultimatePosition,
+        antepenultimatePosition );
+
+      // update antepenultimatePosition
+      antepenultimatePosition = penultimatePosition;
+    };
+
+    this.chartRectangle.cursor = 'pointer';
+    this.chartRectangle.addInputListener( new DragListener( {
+      dragBoundsProperty: new Property( new Bounds2( 0, 0, this.chartTransform.viewWidth, this.chartTransform.viewHeight ) ),
+      applyOffset: false,
+      start: ( event, listener ) => {
+
+        // Indicate that we've touched the curve, and hide the cueing arrows.
+        interactiveCurveNodeProperty.value.wasDraggedProperty.value = true;
+
+        // Save the current values of the Points for the next undoToLastSave call.
+        // This must be called once at the start of dragging (and not on each micro drag-position change).
+        interactiveCurveNodeProperty.value.transformedCurve.saveCurrentPoints();
+
+        // set the second to last position to null, since it is a new drag.
+        antepenultimatePosition = null;
+        updateCurve( listener );
+      },
+      drag: ( event, listener ) => updateCurve( listener ),
+      tandem: options.tandem.createTandem( 'dragListener' )
+    } ) );
   }
 
   public override reset(): void {
```

</details>

**Comment by pixelzoom** [comment]
Calls to `chartTransform` are also allocating Vector2 instances in the DragListener:

```
 // current modelPosition
      const modelPosition = this.chartTransform.viewToModelPosition( listener.modelPoint );

      // previous (model) position the drag
      penultimatePosition = this.chartTransform.viewToModelPosition( listener.modelPoint.minus( listener.modelDelta ) );
``

**Comment by veillette** [comment]
As 2/2/2023, we decided we will add a drag handler directly onto the original graph node rather than the curveNodes.

**Comment by pixelzoom** [comment]
@veillette I'll go ahead and apply the patch from https://github.com/phetsims/calculus-grapher/issues/210#issuecomment-1412397987, after I clean it up a bit to make it "production worthy".

**Comment by pixelzoom** [comment]
Patch applied in the commits above, after some cleanup. @veillette feel free to have a look.

Notes:
* `TransformedCurveNode.wasDraggedProperty` moved to `TransformedCurve.wasManipulatedProperty`.
* I'm not particularly happy with this bit in OriginalGraphNode.ts, but I can live with it if you can:

```typescript
    // We need to know that this.curveNode is of type TransformedCurveNode, as created by createCurveNode above.
    const originalCurveNode = this.curveNode as TransformedCurveNode;
    assert && assert( originalCurveNode instanceof TransformedCurveNode ); // eslint-disable-line no-simple-type-checking-assertions
```

And I see that you opened https://github.com/phetsims/calculus-grapher/issues/218 to address 'Free Form' manipulation. Excellent.

**Comment by pixelzoom** [comment]
In the above commit, I converted several methods in TransformedCurve to have parameters `x: number, y: number` instead of `position: Vector2`.  This eliminated a handful of Vector2 allocations, especially in `freeformIconCurve`.  The number of allocation saved is admittedly small compared to what bamboo is doing, but it was "low hanging fruit" and I suspect that to squeeze out as much performance as possible.   (And I triple checked my work on this commit.)

**Comment by pixelzoom** [comment]
I discovered that PressListener "field" `modelPoint` and `modelDelta` are actually ES5 getters that allocate a Vector2 as a "defensive copy".  So in the above commit, I minimized their use in OriginalGraphNode like this:

```typescript
      // These listener 'fields' are actually ES5 getters that allocate a Vector2, so call them only once.
      const modelPoint = listener.modelPoint;
      const modelDelta = listener.modelDelta;
```

Another source of Vector2 allocation is `chartTransform.viewToModelPosition`.  We might consider replacing these occurences in OriginalGraphNode with `viewToModelX` and `viewToModelY`.   That would also require changing the signature of TransformedCurve `manipulateCurve` to take x,y values instead of Vector2.

```typescript
      // Current modelPosition
      const modelPosition = this.chartTransform.viewToModelPosition( modelPoint );

      // Previous (model) position the drag
      penultimatePosition = this.chartTransform.viewToModelPosition( modelPoint.minus( modelDelta ) );
```

**Comment by pixelzoom** [comment]
In the above commit, I added conditional creation of GraphNodes, based on whether they appear in model.graphSet.  This results in 2 less GraphNodes to update in the _Derivation_ and _Integral_ screens, 1 less GraphNode is _Advanced_ screen.  The _Lab_ screen did not benefit from this optimization, because it involves all 4 screens.  We can get some additional optimization by only updating GraphNode when it's visible.

**Comment by pixelzoom** [comment]
In the above commits, I set `pickable: false` for various things that are displayed on a GraphNode.  This should improve hit testing a bit. These are the important ones, in OriginalGraphNode:

```
    // Performance optimization, see https://github.com/phetsims/calculus-grapher/issues/210
    this.curveNode.pickable = false;
    this.predictCurveNode.pickable = false;
    this.labelNode.pickable = false;
```

**Comment by pixelzoom** [comment]
@veillette @jonathanolson and I had a Zoom meeting to review performance.  These are my notes on what we discovered.

* The biggest contributor to GC appears to be LinePlot, specifically `new Shape` and `lineToPoint`.

* Setting LinePlot `boundsMethod = 'unstroked'` improves performance noticeably, apparently because we're adding a listener to `this.graphsNode.boundsProperty` in CalculusGrapherScreenView.ts. (We ultimated used `boundsMethod = 'none'` -- we do not care at all about plot bounds, because plots are clipped to ChartRectangle.  And we may reeevaluate `graphsNode.boundsProperty` in the future.)

* When Chrome dev tools are closed, the large GC pauses that we're seeing do not occur. This pause occurs in Chrome 109 (latest), but not in Chrome 100 (old version on @jonathanolson's machine), 112 (Canary), or 110 (soon to be released).

* @veillette and I added `boundsMethod: 'none'` to plots that are clipped to ChartRectangle (LinePlot, ScatterPlot, TangetArrowNode, AreaUnderCurveNode,...) Search for `CalculusGrapherConstants.PLOT_BOUNDS_METHOD`.

* @veillette and I added`pickable: false` to more chart decorations that are not interactive (tick marks, grid lines, axes,... )  This optimization is probably relatively tiny, but it was easy, and may have a cummulative payoff on performance-challenged platforms.

As a snapshot of where we're at, I published [1.0.0-dev.10](https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.10) (phet & phet-io). Performance feels exceptionally smooth on my 2019 MacBook (macOS 13.2) and 2018 iPad6 (iPadOS 16.2).   So I think we're in good shape here, ready for a preliminary "performance dev test" by QA.  I'll create a QA issue for that shortly.   Closing this issue.

**Comment by pixelzoom** [comment]
QA performance testing has been requested in https://github.com/phetsims/qa/issues/898.

Closing.

**Comment by pixelzoom** [comment]
A note that our `boundsMethod` optimizations had some unintended consequences for the icons on the curve-manipulation radio buttons, see https://github.com/phetsims/calculus-grapher/issues/226.   So we added `CurveNodeIOptions.plotBoundsMethod`,  defaulted it to `'accurate'`, with override of `'none'` only where performance optimization is needed -- that is, in GraphNode and OriginalGraphNode.  See https://github.com/phetsims/calculus-grapher/commit/9d1da332cef634fa0ba4001c0ba5f365c7f4c813.
