### ISSUE TITLE
Document options and fields

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#211]
Make a pass through all files, document all options and fields whose semantics are not obvious.

**Comment by veillette** [comment]
@pixelzoom: FYI, in WebStorm, if one adds add an inline comment within types  such as

```js
type SelfOptions = {
  x: number; // initial value of xProperty
  visible?: boolean; // initial visibility of the tool
};
```
then the tool tip assigns the correct type, but the comment from the previous type. 
<img src="https://user-images.githubusercontent.com/7633344/216180139-f3acee92-dc66-4e67-b5fe-da4eefafbaae.png" width=400>

While it seems a limitation from WebStorm ,we should be mindful of it when adding inline comments.

**Comment by pixelzoom** [comment]
I went through all source files and added missing documentation for options and fields.  @veillette have a look, feel free to close.

**Comment by veillette** [comment]
That looks good. Closing.
