### ISSUE TITLE
GraphNode: use graphType to opt-out of zoom feature

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#214]
In GraphNode.ts, instead of `GraphNodeOptions.hasYZoom`, use `graphType === GraphType.ORIGINAL` to opt out of creating `yZoomProperty` and `yZoomButtonGroup`.

**Comment by pixelzoom** [comment]
Done in the above commit. @veillette want to have a look? Feel free to close.

**Comment by veillette** [comment]
That looks good. 

We may ultimately put a comment in line 146 about how to enable zoom in originalGraph if we decide that it is worth it. We are tracking this in #215.
