### ISSUE TITLE
OriginalGraphNode: document how to add zoom feature

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#215]
From 1/31/2022 pairing with @veillette ...

Document what needs to be done (pointer areas, zoom) if a future PhET team wants to add the zoom feature to OriginalGraphNode.

**Comment by veillette** [comment]
Although the design team decided include the zoom buttons to all graphs but the original graph
Since `OriginalGraphNode` extends `GraphNode`, one might naively think that it should be relatively easy to turn on the zoom buttons.
However, there would be more work to do in `OriginalGraphNode`, namely to have a listener to the `chartTransform` emitter such that it would recalculate the `pointerAreas` of the curve.

**Comment by veillette** [comment]
This previous comment may not apply if we go ahead with adding the dragListener directly to the originalGraph instead of the individual curves.

**Comment by veillette** [comment]
Let's set to deferred until we come to a conclusion on #210.

**Comment by veillette** [comment]
As a result of your decision in #210, where we added the drag listener to the chartRectangle (https://github.com/phetsims/calculus-grapher/commit/4509d08acea8ad2d93a3bd209d7cf34badd5d2d9), there is, in principle no documentation that needs to be added  if one would like to add a zoom button. I tested that it would work fine, so it is merely a design decision.

@pixelzoom: should we revert #214 or leave as is?

**Comment by pixelzoom** [comment]
I think we should leave #214 as is.  We do not want yZoomProperty or yZoomButtonGroup to be showing up in the Studio tree for the original graph.

@veillette But perhaps this comment in GraphNode.ts (which I added in the above commit) is sufficient?  If so, feel free to close.  If not, point me to other code locations that would benefit from a comment.

```typescript
    // The original graph does not have the zoom feature for the y-axis. If you'd like to add the zoom feature
    // to the original graph in the future, remove the if statement that surrounds this block.
    if ( graphType !== GraphType.ORIGINAL ) {
      this.yZoomLevelProperty = new NumberProperty( DEFAULT_ZOOM_LEVEL, {
        range: new Range( 0, Y_ZOOM_INFO.length - 1 ),
        tandem: options.tandem.createTandem( 'yZoomLevelProperty' )
      } );
    }
```

**Comment by veillette** [comment]
That looks good. Closing
