### ISSUE TITLE
Undo and Erase buttons should be disabled when there's nothing to undo or erase.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#219]
This is a bit of a nit, and we could probably leave it as is.  But technically, these buttons should be disbled if there's nothing to undo or erase.

This gets a little tricky because originalCurve and predictCurve each have their own undo list.  So there might be a bit of reworking the undo history to make this easier. 

@veillette Let's check with @amanda-phet before doing anything here. Can we simplify development and live with this as is? Or do we need to address it? (It's not going to be an insignificant amount of work.)

**Comment by veillette** [comment]
As a parallel, we can think our handling of the reset all button for simulations. We don't disable the reset button at the start of the sim, even though there is nothing to reset. We can do something similar. 
My vote is to do nothing.

**Comment by pixelzoom** [comment]
+1 for doing nothing.

**Comment by pixelzoom** [comment]
@amanda-phet are you OK with "do nothing" for this issue?

**Comment by amanda-phet** [comment]
Sounds fine to me.
