### ISSUE TITLE
TranformedCurveNode overloads the semantics of enabledProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#220]
In scenery, it has a specific meaning, and often results in a visual change to the Node.  For TranformedCurveNode, we're lucky that our anscetor class is Node, so there is no pre-defined visual change.

I'm guessing that @veillette may have used `enabledProperty` because he thought that would disable input listener.  That's no longer relevant, because we are putting the DragListener on the chartRectangle, not on TranformedCurveNode. 

Finally, seeing  enabledProperty here has also confused me more than once when reading the code.

So I think we should consider replacing this overload of `enabledProperty` with a Property that is specific to TranformedCurveNode, perhaps something like `isInteractiveProperty`. 

@veillette let me know if you ideas. Self-assigning to think about it more.

**Comment by pixelzoom** [comment]
I went with `isInteractiveProperty`. @veillette close if that's OK with you.

**Comment by veillette** [comment]
Noted. That looks good. CLosing

**Comment by veillette** [comment]
I think it may worth to use similar terminology for `interactiveCurveNodeProperty` in the `CurvePushButtonGroup`.
Self-assigning.

**Comment by veillette** [comment]
Let's track in a separate issue instead. Tracking in #221.
