### ISSUE TITLE
Refactor curveToTransformProperty to interactiveCurveProperty

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#221]
Following work in #220, I think it may worth to use 'isInteractive' terminology throughout the sim.

**Comment by veillette** [comment]
FYI, I mangled the reference tagging in the commits above.  Only the last commit is relevant to this issue.

The initial change  starts in `CalculusGrapherModel` and then all the other places it cropped up.
````diff
-  this.curveToTransformProperty = new DerivedProperty( [ this.predictEnabledProperty ],
+  this.interactiveCurveProperty = new DerivedProperty( [ this.predictEnabledProperty ],
      predictEnabled => predictEnabled ? this.predictCurve : this.originalCurve
    );
````
Assigning to @pixelzoom to review.

**Comment by pixelzoom** [comment]
Looks great. Closing.
