### ISSUE TITLE
Refactor PredictModeRadioButtonGroup to PredictEnabledRadioButtonGroup

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#222]
The name of the button group should follow the name of the associated property.

**Comment by pixelzoom** [comment]
Good catch.

**Comment by veillette** [comment]
Done in the commits above.

I searched for 'predictmode' throughout the code base I found some vestigial usages in the process.

After this, I cant find any more mentions of `predictMode` in the code or in strings.

@pixelzoom:  feel free to close.

**Comment by pixelzoom** [comment]
👍🏻 Looks great. Closing.
