### ISSUE TITLE
Order of GraphNodes is not determined by order of GraphSet.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#223]
While making a changes described in https://github.com/phetsims/calculus-grapher/issues/210#issuecomment-1416057543, I discovered a problem that should be corrected in GraphsNode.   The relevant code is:

```typescript
    model.graphSetProperty.link( graphSet => {

      // Gets the GraphNode instances that correspond to graphSet.
      const graphNodes = this.graphNodes.filter( graphNode => graphSet.includes( graphNode.graphType ) );
      assert && assert( graphNodes.length > 0 );
      graphSetNode.setChildren( graphNodes );
```

The problem is that the order of `const graphNodes` is not determined by the order of `graphSet`.  It's dependent on the order of `this.graphNodes`.  That should be fixed; the order of `this.graphNodes` should not be relevant.

I'll investigate. @veillette FYI.

**Comment by veillette** [comment]
It took me a while to process. Our graphSets always have the same order as the GraphNodes, so it was never a problem.  Good find.

**Comment by pixelzoom** [comment]
Addressed in the above commit.  Note that I am purposely testing this by having `this.graphNodes` in an order that does not typically match graphSets order.

@veillette want to have a look? Close if OK.

**Comment by veillette** [comment]
That looks good. Closing
