### ISSUE TITLE
phetioFeatured overrides

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#225]
Use Studio to feature/unfeature elements, and generate `calculus-grapher-phet-io-overrides.js`. If you're clear on the process for this, contact @arouinfar.

Because this sim does not yet have an API, you can safely commit changes to `calculus-grapher-phet-io-overrides.js` without having to regenerate the API.

This should be completed after https://github.com/phetsims/calculus-grapher/issues/224 (PhET-iO design review).

**Comment by pixelzoom** [comment]
From https://github.com/phetsims/phet-io/issues/1873#issuecomment-1460709508:

> ...
> @pixelzoom will experiment with this new process in Calculus Grapher.
> @amanda-phet will decide whether it is synchronous or asynchronous. @arouinfar is requested to join, and @catherinecarter will probably join
> ...
> Consensus: We will start with Calculus Grapher and see how it goes first to see if we want adjustments or discussion before we go "all in". If that goes well, we can go to Beer's Law Lab. Having @arouinfar @amanda-phet @catherinecarter and @pixelzoom collaborate synchronously will hopefully be very clear & straightforward.

**Comment by pixelzoom** [comment]
@amanda-phet asked about the relative priority of this issue at today's "team entropeas" status meeting.  Having the overrides specification is higher priority than reviewing issues that are currently assigned to @amanda-phet.  It would be great if overrides could be completed by end-of-day Wed 3/15, because I only have Thu and Sun available to complete the merge into code, and we're still shooting for QA to being on Mon.

Repeating what I posted in Slack#phet-io yesterday:
> ... The new process that we’ll be test driving is currently described in https://github.com/phetsims/phet-io/issues/1873#issuecomment-1460709508.  (At some point it will make its way into the official PhET-iO docs.)   It’s unlikely that I can participate in the design synchronously. If you have any questions, please comment in the CG issue https://github.com/phetsims/calculus-grapher/issues/225 (phetioFeatured overrides) or ask in Slack#calculus-grapher.   I should be available  to handle the merging of overrides into code, but have briefed 
[@veillette](https://phetsims.slack.com/team/U6D0VLH96)
 on the process just in case. If there are any design decisions that you’d like to appear in code comments when I do the merge, please note them in https://github.com/phetsims/calculus-grapher/issues/225. Thanks,

**Comment by amanda-phet** [comment]
I took a first pass at establishing a feature set by just doing the Derivative screen, and have enough questions I'd like to discuss before proceeding. I asked these to @arouinfar on slack but thought I'd put them here too since I'm working late at night. 

1. It seems like even if I feature a property, it doesn't show up in the tree where it's linked when I only view Featured. Here is one example of linked properties in the tree, but if I have the Featured radio button selected they don't appear in the tree. 

2. Should I feature all of the `StrokeProperty`s and `ColorProperty`s? We decided it would be in studio, but I’m not sure it’s an important feature for clients. 

3. Should I feature a checkbox group's visibleProperty in addition to individual checkboxes? I assume we want to feature visibleProperty for most everything in the view, but I can’t figure out the obvious answer to this.

4. (for @pixelzoom ) I think featuring that you can make the labeledLines visible and set the x-value is useful. I’d like all of the lines (A-F featured). Is this obvious from what I did for Aline and APoint? 

```
/* eslint-disable */
window.phet.preloads.phetio.phetioElementsOverrides =
  {
    "calculusGrapher.derivativeScreen.model.curves.originalCurve.pointsProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.curves.predictCurve.pointsProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.gridVisibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.predictEnabledProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.predictSelectedProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.labeledLines": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.labeledLines.ALine.visibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.labeledLines.ALine.xCoordinateProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.labeledPoints.APoint.visibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.labeledPoints.APoint.xCoordinateProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.referenceLine.visibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.referenceLine.xCoordinateProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.referenceLine.yDerivativeProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.referenceLine.yIntegralProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.referenceLine.yOriginalProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.referenceLine.ySecondDerivativeProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.tangentScrubber.visibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.tangentScrubber.xCoordinateProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.tangentScrubber.yDerivativeProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.tangentScrubber.yOriginalProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.view.checkboxGroup.visibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.view.controlPanel.curveManipulationControls.visibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.view.controlPanel.curveManipulationControls.widthControl.visibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.view.controlPanel.pushButtonGroup.visibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.view.controlPanel.visibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.view.graphsNode.derivativeGraphNode.curveLayerVisibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.view.graphsNode.derivativeGraphNode.curveNode.visibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.view.graphsNode.originalGraphNode.curveLayerVisibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.view.slopeOfTangentAccordionBox.featureVisibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.global.model.preferences.connectDiscontinuitiesProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.global.model.preferences.derivativeNotationProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.global.model.preferences.functionVariableProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.global.model.preferences.hasShowOriginalCurveCheckboxProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.global.model.preferences.predictFeatureEnabledProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.global.model.preferences.valuesVisibleProperty": {
      "phetioFeatured": true
    }
  };
```

**Comment by pixelzoom** [comment]
> 1. It seems like even if I feature a property, it doesn't show up in the tree where it's linked when I only view Featured. Here is one example of linked properties in the tree, but if I have the Featured radio button selected they don't appear in the tree.

I don't have time right now to investigate or reproduce. But this sounds like a question for @zepumph and @samreid.  Is Studio working correctly when in admin mode? If the designer set something to `phetioFeatured: true`, shouldn't it appear in the tree when the "Featured" radio button is selected?

**Comment by amanda-phet** [comment]
I should clarify. It was difficult to explain. If I feature a **linked** property, it doesn't seem to show up in it's linked location.

**Comment by pixelzoom** [comment]
> 2. Should I feature all of the StrokePropertys and ColorPropertys? We decided it would be in studio, but I’m not sure it’s an important feature for clients.

I think the default is "no".  But colors that serve some important instruction design purpose could be featured.  

> 3. Should I feature a checkbox group's visibleProperty in addition to individual checkboxes? 

I don't think the answer is always "yes" or always "no".  It depends on whether you think that hiding the specific checkbox group facilitates the kinds of instructional designs that PhET wants to encourage.

> I assume we want to feature visibleProperty for most everything in the view, but I can’t figure out the obvious answer to this.

I strongly disagree with this. We should be featuring only things that we think are more useful for the the kinds of instructional designs that PhET wants to encourage.  Featuring everything dilutes the usefulness of "featured".

**Comment by pixelzoom** [comment]
I still don't understand https://github.com/phetsims/calculus-grapher/issues/225#issuecomment-1469273149.

**Comment by pixelzoom** [comment]
I still don't understand https://github.com/phetsims/calculus-grapher/issues/225#issuecomment-1469273149.  Perhaps a set of steps and screenshots to reproduce, if it's not too complicated?

**Comment by amanda-phet** [comment]
1. Select a property to be featured that is also linked elsewhere in the tree. 
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/7852916/225202110-9f9bd031-dd7a-4559-a364-ff979d691ac3.png">

2. Change the view from All to Featured. Blue linked property isn't in the tree in the linked location.
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/7852916/225202188-14c754ad-a1b0-44b5-86ad-8c2cfddf6ed9.png">

**Comment by pixelzoom** [comment]
What @amanda-phet has shown in the comment above looks like a Studio bug to me. @zepumph @samreid please comment. If it's indeed a bug, please create a Studio issue.

**Comment by amanda-phet** [comment]
Thanks for confirming @pixelzoom. I figured it would get answered tomorrow during normal working hours, but it's helpful to know I was encountering something unexpected.

**Comment by pixelzoom** [comment]
> 4. (for @pixelzoom ) I think featuring that you can make the labeledLines visible and set the x-value is useful. I’d like all of the lines (A-F featured). Is this obvious from what I did for Aline and APoint?

Yes, will do.

**Comment by amanda-phet** [comment]
Just to clarify where I'm at in the process.. I've gone through just the Derivative screen so far and had enough questions I felt like I should wait to proceed. 

My next steps (tomorrow) will be to go through the remaining screens and complete the process, and also meet with @arouinfar and @kathy-phet to address other questions that arise relating to design patterns I should follow. By the end of Wednesday I should have a complete featured list ready to paste into this issue for @pixelzoom to implement, with comments.

**Comment by pixelzoom** [comment]
I attempted to start merging the overrides that  @amanda-phet provided above.  But I ran into problems into problems with git-hooks -- common code changes had been made, and API files were not regenerated.  So I'm going to wait until you have a more complete overrides.

**Comment by samreid** [comment]
Is https://github.com/phetsims/calculus-grapher/issues/225#issuecomment-1469282884 the same problem as described in https://github.com/phetsims/studio/issues/176?

**Comment by arouinfar** [comment]
I agree with @pixelzoom's comments in https://github.com/phetsims/calculus-grapher/issues/225#issuecomment-1469275471. 

> 1. It seems like even if I feature a property, it doesn't show up in the tree where it's linked when I only view Featured. Here is one example of linked properties in the tree, but if I have the Featured radio button selected they don't appear in the tree.

The behavior @amanda-phet describes in https://github.com/phetsims/calculus-grapher/issues/225#issuecomment-1469282884 is expected. Checking "Featured" will automatically make that element appear in the tree when viewing featured elements. However, if that element is linked somewhere else, the link will not show up until the overrides are committed (or the phetioFeatured behavior is internalized). 

Thanks @samreid for linking https://github.com/phetsims/studio/issues/176. That is exactly what @amanda-phet is running into here. I suppose I've just lived with it for these last few years, but it would be a quality of life improvement.

> 2. Should I feature all of the StrokePropertys and ColorPropertys? We decided it would be in studio, but I’m not sure it’s an important feature for clients.

I don't think it's necessary to feature the `colorProfile` contents. I would feature it if I thought the colors were pedagogically important or if a client had explicitly asked to change the colors, but otherwise, I wouldn't.

> 3. Should I feature a checkbox group's visibleProperty in addition to individual checkboxes? I assume we want to feature visibleProperty for most everything in the view, but I can’t figure out the obvious answer to this.

I would say `visibleProperty` is often (but not always) featured, and the decision is always situational. Normally I see a group of checkboxes like this in the panel. I usually feature `panel.visibleProperty` for convenience, but also because panels don't necessarily disappear when empty (though recently they do). Here, there isn't a visual container grouping these checkboxes, so I think it's really up to you whether or not to feature `checkboxGroup.visibleProperty`. 

Personally, I don't think it's necessary to feature it in CG unless there is some instructional reason to hide the entire group. There are only 2-3 checkboxes in the group, so it's not saving much time.

**Comment by amanda-phet** [comment]
Thanks everyone for all of your support through this process! 

@pixelzoom I'm ready for you to implement the following changes to the phetioFeatured set. I'm hoping you can figure out from the list (ie. read my mind) which properties exist on all screens and make them consistent across screens. For example, the set of properties relating to the reference line should be applied to all screen. 

If you can do that, the next step I'd like to take is doing a review of the featured set across all screens and then submit final changes (for example, I'll probably make some Integral screen adjustments). 

```
/* eslint-disable */
window.phet.preloads.phetio.phetioElementsOverrides =
  {
    "calculusGrapher.derivativeScreen.model.curves.derivative.pointsProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.curves.originalCurve.pointsProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.curves.predictCurve.pointsProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.gridVisibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.predictEnabledProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.predictSelectedProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.labeledLines": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.labeledLines.ALine.visibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.labeledLines.ALine.xCoordinateProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.labeledPoints.APoint.visibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.labeledPoints.APoint.xCoordinateProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.referenceLine.visibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.referenceLine.xCoordinateProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.referenceLine.yDerivativeProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.referenceLine.yIntegralProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.referenceLine.yOriginalProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.referenceLine.ySecondDerivativeProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.tangentScrubber.visibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.tangentScrubber.xCoordinateProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.tangentScrubber.yDerivativeProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.model.tools.tangentScrubber.yOriginalProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.view.controlPanel.curveManipulationControls.visibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.view.controlPanel.curveManipulationControls.widthControl.visibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.view.controlPanel.visibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.view.graphsNode.derivativeGraphNode.curveLayerVisibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.view.graphsNode.derivativeGraphNode.yZoomButtonGroup.visibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.view.graphsNode.originalGraphNode.curveLayerVisibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.derivativeScreen.view.slopeOfTangentAccordionBox.featureVisibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.archetype.preferencesPanels.simulationPreferencesPanel.content.discontinuitiesControl.visibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.archetype.preferencesPanels.simulationPreferencesPanel.content.notationControl.visibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.archetype.preferencesPanels.simulationPreferencesPanel.content.predictControl.visibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.archetype.preferencesPanels.simulationPreferencesPanel.content.valuesControl.visibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.archetype.preferencesPanels.simulationPreferencesPanel.content.variableControl.visibleProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.global.model.preferences.connectDiscontinuitiesProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.global.model.preferences.derivativeNotationProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.global.model.preferences.functionVariableProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.global.model.preferences.hasShowOriginalCurveCheckboxProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.global.model.preferences.predictFeatureEnabledProperty": {
      "phetioFeatured": true
    },
    "calculusGrapher.global.model.preferences.valuesVisibleProperty": {
      "phetioFeatured": true
    }
  };
```

**Comment by pixelzoom** [comment]
In the above commits, I merge overrides into code.  This consisted exclusively of `phetioFeatured: true` overrides. Back to @amanda-phet for review, and I'll be meeting with her on 3/16/2023.

Some notes:

(1) All of the tools share the same base class, which has 6 instrumented Properties: `visibleProperty`, `xProperty`, `yOriginalProperty`, `yDerivativeProperty`, `yIntegralProperty`, `ySecondDerivativeProperty`.   You asked to feature `visibleProperty` and `xProperty` for all tools, so no problem there.  But for the other 4 Properties, you had specific requested for each tool. For example, for `tangentScrubber`, you wanted to only feature `yOriginalProperty` and `yDerivativeProperty`.  That's not doable without introducing a whole bunch of options to the base class (cluttering up the API for AncillaryToolOptions).  So I featured all Properties, for all tools. @amanda-phet let's discuss if that's OK.  @samreid @zepumph @arouinfar @kathy-phet note that this type of requirement is a case where overrides.js is superior to merging into the code. And there will certianly be cases where it's _not_ OK to do what I've done here.

(2)  The process for verifying that I correctly merged overrides.js into code, as described in https://github.com/phetsims/phet-io/issues/1873#issuecomment-1460709508, was not at all practical. @amanda-phet gave me a partial overrides.js, for one screen, and asked me to "do the same for other screens".   So regenerating the API file after doing the merge resulted in a ton of changes. There's no way I was going to spend the time to manually review the diff, and even if I did, I would be likely to miss something.  @samreid @veillette @arouinfar @kathy-phet FYI: Short of manual review, we do not have a viable way of verifying that overrides were correctly merged. So expect the design to have to do a manual review.

**Comment by pixelzoom** [comment]
> (1) ... That's not doable without introducing a whole bunch of options to the base class (cluttering up the API for AncillaryToolOptions). So I featured all Properties, for all tools.

I ended up adding the options to AncillaryToolOptions, and customizing for `tangentScrubber` and `areaUnderCurveScrubber`.  So those tools now feature a subset of the tool Properties.

**Comment by amanda-phet** [comment]
I did my manual review today and talked about a couple final things with @pixelzoom . Everything should be good to go after he features the zoom button group!

**Comment by amanda-phet** [comment]
Looks great!
