### ISSUE TITLE
Side effects on Curve Manipulation Buttons

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#226]
While addressing some performance issues #210, we have introduces some changes to the curve manipulation buttons. Notice below the changes from version 9 to version 10.

https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.9/phet/calculus-grapher_en_phet.html

<img src='https://user-images.githubusercontent.com/7633344/217578135-94d81a2b-1fc7-4f07-acec-c3d489ca582d.png' width =300>

vs
https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.10/phet/calculus-grapher_en_phet.html

<img src='https://user-images.githubusercontent.com/7633344/217578302-8ead0ddb-66ab-4175-95cf-232018675517.png' width=300>

**Comment by veillette** [comment]
I confirmed that it is related to the change of  `boundsMethod` in `CurveNode`.

**Comment by veillette** [comment]
I think I understand what is going on. The chartRectangle in icon is sometimes smaller than the icon, such that by having BoundsMethod to none, the size of the curve gets clipped.

**Comment by pixelzoom** [comment]
Or better... Let's set `boundsMethod: 'accurate'` for the CurveNode instances used in the these buttons.

**Comment by veillette** [comment]
Yes, We can create an option field to `CurveNode` is set it to `CalculusGrapherConstants.PLOT_BOUNDS_METHOD` by default, but we can override it as necessary.

**Comment by pixelzoom** [comment]
Fixed in the above commit.  I added CurveNodeOptions.plotBoundsMethod, and set it to 'accurate' for instances of CurveNode created by CurveManipulationIconNode.

@veillette please review.

**Comment by pixelzoom** [comment]
Searching for `new CurveNode`.... Perhaps we should also use `plotBoundsMethod: 'accurate'` for the CurveNode instance created by CurveManipulationDisplayNode?

**Comment by veillette** [comment]
Yes that would be preferable.

**Comment by pixelzoom** [comment]
Even more preferrable... No not set `plotBoundsMethod: 'none'` as the default in CurveNode.  Set the default to `'accurate'`, then override it to `'none'` for CurveNode and TransformedCurveNode instances that are children of GraphNode.

I'm on it...

**Comment by pixelzoom** [comment]
Done in the above commit.  

The default in CurveNode is now `plotBoundsMethod: 'accurate'`.  That is overridden to `plotBoundsMethod: CalculusGrapherConstants.PLOT_BOUNDS_METHOD` in GraphNode and OriginalGraphNode, the places where performance is an issue.

@veillette ready for review, close if OK.  And good catch!

**Comment by veillette** [comment]
Yes, having the boundsMethod to be accurate as the default seems the most logical choice.
This way we can override it where performance is needed. 
It works well. Closing
