### ISSUE TITLE
Refactor CurveManipulationMode.SINE to CurveManipulationMode.SINUSOIDAL

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#227]
The function created uses a cosine function, so it is misleading. The name SINUSOIDAL is more generic and less prone to minute changes of implementation.

**Comment by veillette** [comment]
The curve manipulation method is already generic: `createSinusoidalAt`

**Comment by veillette** [comment]
Thinking aloud, all the other curve manipulation modes are nouns: HILL, PARABOLA, LINE.
We should use a noun rather than an adjective, so SINUSOID.

**Comment by veillette** [comment]
Assigning to @pixelzoom to review. Feel free to close.

**Comment by pixelzoom** [comment]
👍🏻 closing.
