### ISSUE TITLE
Discontinuity points are not at the edges of the discontinuity.

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#228]
![image](https://user-images.githubusercontent.com/7633344/218114715-713d8bd9-297b-4e18-a7d8-c74ceba4a1ed.png)

**Comment by veillette** [comment]
I think I have a good idea of the cause of this artefact.

Below I limited the number of points to 51 to magnify the problem and highlighted all the points.
`numberOfPoints=51&screens=3&allPoints=true`

![image](https://user-images.githubusercontent.com/7633344/218186795-25c31474-9ee2-4edd-b07d-428332d877fe.png)

On the right, in green, I attempted to show where the "real" intersections of the parabola and the line should be.
This intersection does not lie on a point, but between two points. As a result, it creates a small shoulder on the original curve. In turn, the small shoulder creates a non zero derivative.

**Comment by veillette** [comment]
WIth the work in #208, this is working much better.

![image](https://user-images.githubusercontent.com/7633344/223901105-98d86391-8637-42f2-9b31-2809ca562aee.png)

However, there is still some work to be done with the second derivative.

![image](https://user-images.githubusercontent.com/7633344/223901398-e02769dd-e3da-4880-b741-959e3e88b706.png)

**Comment by pixelzoom** [comment]
Very nice!

**Comment by veillette** [comment]
The work on the second derivative is being tracked in #275

**Comment by veillette** [comment]
Since we are tracking the work of the second derivative in #275, we can close this issue.
