### ISSUE TITLE
Polish the Simulation tab in the Preferences Dialog

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#231]
@amanda-phet asked me to open this issues.

The current implementation looks like this:

<img width="765" alt="screenshot_2304" src="https://user-images.githubusercontent.com/3046552/218817872-e8c3758c-29c7-4681-9df8-b768a4ca3c79.png">

Things that @amanda-phet would like to consider:

* Order of controls. Definitely move "Values" to the bottom.

* Labels should be in bold font, with no colon suffix. E.g. **"Values"**, not "Values:"

* Do we want to add descriptions to any of these controls?  Keep in mind that there is currently no common-code support for layout of controls that involve radio buttons.

Finally...  Keep in mind that the Preference dialog design is being addressed as part of a larger, more general effort.  Layout and common-code support are likely to change significantly.  So we should not be trying to match the current layout, or anticipate the future layout.  We should be providing a UI that is usable until common-code support is provided.

**Comment by pixelzoom** [comment]
Summary of above commits:
* moved "Values" control to the bottom
* changed all control labels to 16-pt bold font, with not ":" suffix
* all controls are subclasses of common-code PreferencesControl, so that they will (hopefully) migrate to revised layout when changes are made to Preferences in the future

Here's what the Simulation tab looks like now.  I have no control over the layout of each control, or the fact that all labels are left-justified, and all controls are right-justified.  All of those layout details are handled by common-code PreferenceControl. 

<img width="788" alt="screenshot_2305" src="https://user-images.githubusercontent.com/3046552/218832421-fa845dad-f9a7-42fa-8476-8e837baa32d5.png">

If you'd like to add description for each control, here's how the layout willl look. Again, unless we make common-code changes, I have no control over this layout.  And the layout for radio buttons is less-than ideal.

<img width="773" alt="screenshot_2306" src="https://user-images.githubusercontent.com/3046552/218832948-9a0ccb2b-afb8-4f62-88dc-2d86d1296e9e.png">

We could make the above a little less ugly by using a horizontal layout for the Notation radio buttons. For example:

<img width="766" alt="screenshot_2307" src="https://user-images.githubusercontent.com/3046552/218833405-9f35f31a-3868-4442-8efb-62f83138c705.png">

@amanda-phet let me know what other changes you'd like to make.

**Comment by pixelzoom** [comment]
Note that we added a "Predict" switch in #232.  It's currently at the bottom of the panel.

**Comment by amanda-phet** [comment]
I think it would be valuable to have a brief discussion with some design team members (doesn't have to be the entire team, but at least @veillette) to determine the best sequence for the preferences. I think a description is unnecessary for discontinuities, notation, and variable, since those are self-explanatory with the radio button options. Values and predict should have descriptions. 

Here is my initial stab at a logical order and descriptions. 

* Variable
* Notation
* Discontinuities
* Predict
_Adds a mode for users to predict f(x)._ 
* Values
_Shows values on graph axes, reference line, slope of tangent line, and area under the curve._

**Comment by pixelzoom** [comment]
> * Values
> _Shows values on graph axes, reference line, slope of tangent line, and area under the curve._

This description is a bit incorrect/incomplete.  Did you mean this?:

_Shows values on graph axes, reference line, "Slope of Tangent", and "Net Signed Area".

**Comment by pixelzoom** [comment]
Make changes from https://github.com/phetsims/calculus-grapher/issues/231#issuecomment-1440935939 before Wed 3/1/2023 interview.

**Comment by pixelzoom** [comment]
Changes have been completed and are present in [1.0.0-dev.17](https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.17/phet/calculus-grapher_all_phet.html)  See screenshot below.  Note that I modifed the Predict description slightly; "the user" is not appropriate language to use during design, but not in a UI.

Back to @amanda-phet for review and next steps.

<img width="803" alt="screenshot_2322" src="https://user-images.githubusercontent.com/3046552/221690658-c5556836-a3c4-4a52-a2c9-be53a5e1de61.png">

**Comment by veillette** [comment]
@amanda-phet : The sequence for the preferences dialog looks appropriate to me.

**Comment by pixelzoom** [comment]
After https://github.com/phetsims/calculus-grapher/issues/252, the order has now changed to:

<img width="700" alt="screenshot_2356" src="https://user-images.githubusercontent.com/3046552/223204149-df96f0d6-26d9-43cc-b1b2-3e955cf687d2.png">

**Comment by amanda-phet** [comment]
I think this can be closed now.
