### ISSUE TITLE
Changes for the Predict feature

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#232]
In Slack#calculus-grapher, @amanda-phet said:
> We have feedback from three teachers about the “predict” feature, pasted in to the design doc [here](https://docs.google.com/document/d/1yt4ykdjF8EYAv9GdxmM3Y-_9kYeudW7gKth-nEleygk/edit?pli=1#heading=h.p2jvyfjccucx). Please have a look before we have a brief design meeting Thursday to discuss.

**Comment by pixelzoom** [comment]
I discussed briefly with @amanda-phet today, and the 2 options that she is considering are:

(1) Do nothing.

(2) Mak the 'Predict' feature optional, via a query parameter and/or Preference, off by default.

I was happy to hear that moving/adding 'Predict' to graphs other than f(x) was not being considered. That would be very problematic at this stage, for both the UI design and implementation.

**Comment by amanda-phet** [comment]
Discussed 2/16/23

Another option between 1-2 that is hidden a "medium" amount. 

(1.5) Checkbox within the sim to show extra/advanced features

Preferences menu is a good place to put "global" preferences- things that impact multiple screens. 

We like option (2), with a preference toggle AND query parameter.

**Comment by amanda-phet** [comment]
Let's name it `predict`. 

Need to consider PhET-iO, so this might take a little more time than 30 minutes.

**Comment by pixelzoom** [comment]
We did not discuss whether the user's Predict curve should be reset if they toggle the Predict preference on/off.   I don't see any harm in keep whatever Predict curve they had most recently set up.  And doing nothing involves less code, and avoid problems when restoring PhET-iO state.  So I'm going to leave the Predict curve unaffected by the state of the Predict preference.

If for some reason we want to reset the Predict curve when the Predict preference is toggled, add this to CalculusGrapherModel.ts:

```ts
    // If the Predict feature is enabled via Preferences, and we're not restoring PhET-iO state, then
    // reset the predictCurve.
    CalculusGrapherPreferences.predictPreferenceEnabledProperty.link( predictPreferenceEnabled => {
      if ( predictPreferenceEnabled && !phet.joist.sim.isSettingPhetioStateProperty.value ) {
        this.predictCurve.reset();
      }
    } );
```

**Comment by pixelzoom** [comment]
@amanda-phet this is ready for review in master.   

Here' the query parameter:

```ts
  /**
   * Whether the 'Predict' feature is available
   */
  predict: {
    type: 'boolean',
    defaultValue: false,
    public: true
  },
```

Below is a screenshot of the Preferences dialog.

And as noted in https://github.com/phetsims/calculus-grapher/issues/232#issuecomment-1433840013... If you turn on the Predict preference, makes changes to the Predict features (select the radio button, select the "Show f(x)" checkbox, etc.), turn off the Predict features, then turn the Predict features back on, you'll see that any state related to the Predict feature has been preserved.  This is the default behavior, and is compatible with PhET-iO.  If this is not acceptable, then we need to have a design discussion.

![screenshot_367](https://user-images.githubusercontent.com/3046552/219513419-4c75db8c-d597-46d8-ab82-0966b9de6bd3.png)

**Comment by amanda-phet** [comment]
I am fine with the predict state being preserved. If that's the only thing needed for review here, I will close this issue.
