### ISSUE TITLE
Visible tools are not updating when f(x) is changed.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#233]
Reported by @kathy-phet in [the PhET-iO Design Doc](https://docs.google.com/document/d/1M7th-Lanv9tS7O7SPOcpR2cn10nu0IbciQqex25Go_Q/edit#):
> calculusGrapher.derivativeScreen.model.tools.labeledPoints.APoint.yOriginalProperty - It looks like this point property isn’t updating any values (original, derivative, integral) when the “Original curve” changes, it always say 0. It does update when I change the x-value setting of the point. (Perhaps set it so it updates only if “visible”, so don’t need to constantly listen unless visible.)

I asked for clarification, and @kathy-phet reported that it's not updating when the tool is visible, only updates when x-position is changed for the point, line, or reference line. It isn't updating as you change f(x) curve.

**Comment by pixelzoom** [comment]
This was definitely working for a long time. But CT and the sim team have not been exercising this feature because it’s not accessible in the general sim. Now that it’s broken, we have no idea when it broke or how long it’s been broken, and it will be relatively expensive to resolve.

This is an example of a fundamental problem with features that are available only through PhET-iO.  PhET is entirely unprepared to test them via CT.

Mentioning @samreid @zepumph.

**Comment by kathy-phet** [comment]
Wondering if this the kind of place to elevate the unit test approach used in extreme programming?Sent from my iPhoneOn Feb 25, 2023, at 8:25 AM, Chris Malley ***@***.***> wrote:﻿
This was definitely working for a long time. But CT and the sim team have not been exercising this feature because it’s not accessible in the general sim. Now that it’s broken, we have no idea when it broke or how long it’s been broken, and it will be relatively expensive to resolve.
This is an example of a fundamental problem with features that are available only through PhET-iO.  PhET is entirely unprepared to test them via CT.
Mentioning @samreid @zepumph.

**Comment by pixelzoom** [comment]
> Wondering if this the kind of place to elevate the unit test approach used in extreme programming?

Yes, unit tests would be the way to go.  But I have no idea how we'd write unit tests for something that must be controlled through Studio, and verified by looking at the UI.

**Comment by pixelzoom** [comment]
The problem is the cleverness that add to AncillaryTool.js to make discontinuties appear as `null` y values. In `createProperties`:

```ts
  const curvePointProperty = new DerivedProperty( [ xProperty ],
    x => curve.getClosestPointAt( x )
  );

  const yProperty = DerivedProperty.deriveAny( [ curvePointProperty ], () => curvePointProperty.value.y );

  // We are creating this Property solely for PhET-iO, to present the y value. And the difference here is that
  // we present discontinuities as null. This Property persists because it is referenced by the tandem registry.
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const yPhetioProperty = new DerivedProperty( [ curvePointProperty ],
    curvePoint => curvePoint.isDiscontinuous ? null : curvePoint.y, {
      tandem: tandem,
      phetioValueType: NullableIO( NumberIO )
    } );
```

`yProperty` is indeed updating properly.  But because we're mutating CurvePoint instances, the value of `curvePointProperty` does not change, and `yPhetioProperty` does not update. 

Since this cleverness is also costing us performance (see https://github.com/phetsims/calculus-grapher/issues/243#issuecomment-1453263020) perhaps we should reevaluate this approach.

**Comment by pixelzoom** [comment]
The cleverness in AncillaryTool.ts had to go. In the above commit, I made major changes to AncillaryTool's Properties, with the following benefits:

* Easier to understand. No more confusion/obfuscation due to the cleverness in `function createProperties`.
* The response to `curveChangedEmitter` is now a call to `notifyListenersStatic` instead of `recomputeDerivation`. This is a much more typical approach.
* There are 4 fewer DerivedProperties per tool, which should improve performance -- see https://github.com/phetsims/calculus-grapher/issues/243#issuecomment-1453263020.

@veillette please have a look. Or wait until our next meeting and I'll give you a quick tour, and explain my design choices.

**Comment by veillette** [comment]
During our 3/7 meeting, we discussed why `yPhetioProperty` was not updating itself.  @pixelzoom and I reviewed is approach which becomes more computationally efficient and is less obfuscating. CLosing
