### ISSUE TITLE
Add a translucent background to "Show f(x)" checkbox.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#236]
In https://docs.google.com/document/d/1M7th-Lanv9tS7O7SPOcpR2cn10nu0IbciQqex25Go_Q/edit#, @kathy-phet requested:

>  Make the Show f(x) checkbox have a white semi-transparent background so its easier to read when f(x) goes behind it.

**Comment by pixelzoom** [comment]
2/27/2023 design meeting: Do it.

**Comment by amanda-phet** [comment]
Looks great.
