### ISSUE TITLE
Rename "Vertical Lines" to "Labeled Lines" throughout

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#237]
Related to #52.

From https://docs.google.com/document/d/1M7th-Lanv9tS7O7SPOcpR2cn10nu0IbciQqex25Go_Q/edit#heading=h.nuk4ozqbti54:

> `calculusGrapher.derivativeScreen.model.tools.verticalLines`
> AM: I wonder if this should be named labeledVerticalLines to be consistent with labeledPoints. 
> KP:  Suggest labeledLines or labeledVerticalLines.
CM: Let’s rename to  labeledLines. Many things in the code will need to be renamed, so this is not as simple as just changing the tandem name.

**Comment by pixelzoom** [comment]
2/27/2023 design meeting:  Do it.

**Comment by pixelzoom** [comment]
Done in the above commits.  In addition to revised tandem name, terminology is now consistent within the code.

@amanda-phet please review, close if OK.  The PhET-iO elements to inspect in Studio are:

* `model.tools.labeledLines`
* `graphsNode.labeledLinesNode`

**Comment by amanda-phet** [comment]
Looks good to me. Thanks!
