### ISSUE TITLE
Make it possible to permanently hide the "Slope of Tangent" and "Net Signed Area" accordion boxes.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#239]
Related to #52.

From https://docs.google.com/document/d/1M7th-Lanv9tS7O7SPOcpR2cn10nu0IbciQqex25Go_Q/edit#:

> `calculusGrapher.derivativeScreen.view.slopeOfTangentAccordionBox.visibleProperty`
> `calculusGrapher.integralScreen.view.netSignedAreaAccordionBox.visibleProperty`
> AM: I think this should not be read only
> CM:  It must be read-only. It’s controlled by the sim, via the “Tangent” checkbox and “Predict” selection.
> KP: Would like to be able to hide the accordion box when tangent is checked
> CM: This will require an additional Property. How do you want the Studio tree to look?

**Comment by pixelzoom** [comment]
2/27/2023 design meeting:

Add: `slopeOfTangentAccordionBox .hasSlopeOfTangentAccordionBox`

with `phetioDocumentation: 'Setting this to false will permanently hide the "Slope of Tangent" accordion box.'`

**Comment by amanda-phet** [comment]
This was easy to find and use. I'm curious if `featureEnabledProperty` is a convention, or something we made up just for this sim? If we are making it up, would `featureVisibleProperty` be more appropriate, and consistent with how we use enabled vs. visible?

**Comment by pixelzoom** [comment]
`featureEnabledProperty` is not a convention.  I was at a loss for a name, and it's what I came up with.  I'll change it to `featureVisibleProperty`.

**Comment by pixelzoom** [comment]
Renamed to `featureVisibleProperty`, see screenshots below.  Closing.

<img width="818" alt="screenshot_2332" src="https://user-images.githubusercontent.com/3046552/222546505-b4c89ea1-ca3b-4b0d-9c3d-89f48da66616.png">
<img width="810" alt="screenshot_2333" src="https://user-images.githubusercontent.com/3046552/222546517-915661f2-6ada-4148-8e16-ae2002ba49a1.png">
