### ISSUE TITLE
Instrument `originalGraphNode.inputEnabledProperty`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#240]
2/27/2023 design meeting, @kathy-phet requested:

Instrument `originalGraphNode.inputEnabledProperty`

**Comment by pixelzoom** [comment]
Done in the above commit. @amanda-phet please review, close if OK.

**Comment by kathy-phet** [comment]
I took a quick look, and the inputEnabledProperty is applying to both f(x) and Predict f(x). Ideally, it would only apply to f(x), so you could still interact with the Predict f(x) curve, but could not change the original f(x) curve if you flipped back to the f(x) mode. I know that is more complex, requiring a conditional or a combo situation for that property.

**Comment by pixelzoom** [comment]
That's exactly what I asked todat when I said that inputEnabledProperty could not apply to a curve, it had to apply to the entire graph.  Self assigning to start over.

**Comment by pixelzoom** [comment]
There's a bug in Node that is preventing me providing a custom `inputEnabledProperty`, see https://github.com/phetsims/scenery/issues/1540.  This issues is blocked until that is resolved.

**Comment by pixelzoom** [comment]
When https://github.com/phetsims/scenery/issues/1540 has been addressed, here's the patch for creating a custom `inputEnabledProperty`:

<details>
<summary>patch</summary>

```diff
Subject: [PATCH] convert to TypeScript
---
Index: js/common/view/GraphNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/GraphNode.ts b/js/common/view/GraphNode.ts
--- a/js/common/view/GraphNode.ts	(revision e2a3512d3977ad3622575451a4d60ada70aecca2)
+++ b/js/common/view/GraphNode.ts	(date 1677545206622)
@@ -100,7 +100,7 @@
 };
 
 export type GraphNodeOptions = SelfOptions &
-  PickOptional<NodeOptions, 'phetioInputEnabledPropertyInstrumented'> &
+  PickOptional<NodeOptions, 'inputEnabledProperty'> &
   PickRequired<NodeOptions, 'tandem'>;
 
 export default class GraphNode extends Node {
Index: js/common/view/OriginalGraphNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/OriginalGraphNode.ts b/js/common/view/OriginalGraphNode.ts
--- a/js/common/view/OriginalGraphNode.ts	(revision e2a3512d3977ad3622575451a4d60ada70aecca2)
+++ b/js/common/view/OriginalGraphNode.ts	(date 1677545635706)
@@ -86,6 +86,11 @@
                            'The value of this Property can be changed by toggling showOriginalCurveCheckbox.'
     } );
 
+    const originalCurveInputEnabledProperty = new BooleanProperty( true, {
+      tandem: providedOptions.tandem.createTandem( 'originalCurveInputEnabledProperty' ),
+      phetioDocumentation: 'Use this Property to disable interactivity of the original curve.'
+    } );
+
     const originalCurveNodeTandem = providedOptions.tandem.createTandem( 'originalCurveNode' );
 
     const options = optionize<OriginalGraphNodeOptions, SelfOptions, GraphNodeOptions>()( {
@@ -112,7 +117,10 @@
         stroke: CalculusGrapherColors.originalChartBackgroundStrokeProperty
       },
       labelNode: labelNode,
-      phetioInputEnabledPropertyInstrumented: true // see https://github.com/phetsims/calculus-grapher/issues/240
+      inputEnabledProperty: DerivedProperty.or( [ predictEnabledProperty, originalCurveInputEnabledProperty ], {
+        tandem: providedOptions.tandem.createTandem( 'inputEnabledProperty' ),
+        phetioValueType: BooleanIO
+      } )
     }, providedOptions );
 
     super( graphType, originalCurve, model.gridVisibleProperty, options );
```

</details>

**Comment by pixelzoom** [comment]
So that I could proceed, I resolved https://github.com/phetsims/scenery/issues/1540 myself and assigned to @jonathanolson for review.

Ready for review by @amanda-phet and @kathy-phet.  The screenshot below shows the relevant part of the Studio tree.

* `originalGraphNode.originalCurveInputEnabledProperty` is used to enabled/disable input for f(x).
* `originalGraphNode.inputEnabledProperty` is derived from `originalGraphNode.originalCurveInputEnabledProperty` and `predictModeEnabledProperty`.  It's true if either of those Properties is true.

Note that it is NOT possible to disable input for the Predict curve. That's not what you asked for, but I wanted to point that out.

<img width="941" alt="screenshot_2323" src="https://user-images.githubusercontent.com/3046552/221726190-48304a69-10e2-416f-9fd7-50ad7da683dc.png">

**Comment by pixelzoom** [comment]
Thinking about this more... The current solution doesn't change the state of the cueing arrows, should it?  And perhaps `originalGraphNode.originalCurveInputEnabledProperty` should be relocated to `originalGraphNode.originalCurveNode.inputEnabledProperty`.

And I'm still not entirely sure on the requirements. @kathy-phet with high-priority, could you please confirm that this is what you're expecting:
* Be able to premanently disable f(x) interactivity.
* Hide the cueing arrows when f(x) interactivity is disabled.
* No such need for the Predict curve.

**Comment by kathy-phet** [comment]
> I'm also not entirely sure that I have all the requirements. @kathy-phet with high-priority, could you please confirm that this is what you're expecting:

>Be able to premanently disable f(x) interactivity.
Hide the cueing arrows when f(x) interactivity is disabled.
No such need for the Predict curve.

Yes - that is what I was thinking of as the requirements. Nice catch on the cuing arrows. I hadn't thought about that - but it makes complete sense to hide those if input is disabled.

**Comment by kathy-phet** [comment]
Assigning back to you Chris. Since it sounded like the above still needed to be implemented.

**Comment by pixelzoom** [comment]
> Note that https://github.com/phetsims/scenery/issues/1541 is a serious problem, and affects all sims. I could work around in this sim, but I don't think we want to have to apply a workaround everywhere that Node Properties are used (visibleProperty, enabledProperty, inputEnabledProperty, etc.) So if there are no additional change requests for this issue, I'll be marking this issue on-hold/blocked.

Another option would be to uninstrument `originalCurveNode.inputEnabledProperty` and `originalCurveNode.cueingArrowsNode.visibleProperty`.  I seriously doubt that they are useful, or that anyone will ever look at them.  And they could be added in a future release, after addressing https://github.com/phetsims/scenery/issues/1541.

**Comment by pixelzoom** [comment]
Another option would be to uninstrument `originalGraphNode.inputEnabledProperty` and `cueingArrowsNode.visibleProperty`.  

3/2/2023 PhET-iO meeting: @kathy-phet and @arouinfar said to do this.

**Comment by pixelzoom** [comment]
The screenshot below shows the part of the Studio tree under `view.graphsNode`.   @amanda-phet if this looks OK, please close.

<img width="414" alt="screenshot_2329" src="https://user-images.githubusercontent.com/3046552/222544445-cf392113-b672-4160-91a5-790474eeb51e.png">

**Comment by amanda-phet** [comment]
Looks good to me!
