### ISSUE TITLE
Can we improve performance further? 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#243]
https://github.com/phetsims/qa/issues/898 was a performance test by QA.

In https://github.com/phetsims/qa/issues/898#issuecomment-1437631257, @liammulh reported:

> These notes apply to:
> 
> ```
>Tester = LM
>Device =
>    (Seemingly has no name. Also has no cart sticker. Black with black case. Lion logo on the case.)
>    iPad Model MR7F2LL/A
>    iPadOS 16.3
>    Safari 16.3 Mobile
>Time = 1.5 hour
>```
>
> **Specific Things**
>
> > In the Derivative screen, compare responsiveness with 'Tangent' checkbox checked and unchecked.
>
> Not noticeably worse with tangent checkbox checked.
>
> > In the Integral screen, compare responsiveness with 'Area Under Curve' checkbox checked and unchecked.
>
> Not noticeably worse with area under curve checkbox checked.
>...
> The performance on the derivative, integral, and advanced screens was fine. The lab screen's performance is slightly worse.
>...
>**Lab Screen** Initially, with no configuration, the performance is noticeably worse than the other screens. However, if you click the button that allows you to create a piecewise function, the performance degrades to the point where the curve being drawn is well behind where your finger is on the screen.

In https://github.com/phetsims/qa/issues/898#issuecomment-1439075060, @stemilymill reported:

> ```
> Tester = E2 
> Device = Lenovo 100e Chromebook gen 2 MTK
> ChromeOS Version 110.0.5481.112 (32-bit)
> Time = 1.5 hr{max 2 hours} 
> ```
>
> Testing with the chromebook I had the same experience as Liam, ...
>
>  On the Lab screen, the performance is significantly worse (mostly with piecewise function) but I would still consider it usable. This chromebook is not touchscreen, and the lag might just be less obtrusive with trackpad input than touch input.

The statement "I would still consider it usable" for the worst case (Lab screen) is encouraging.  But we should investigate whether there's anywhere else that we might improve performance. Assigning to @veillette and myself for discussion.

**Comment by pixelzoom** [comment]
Also note that we need to do another round of QA performance testing with `labeledLines` and `labeledPoints` turned on, because those PhET-iO-only features will impact performance.  From https://github.com/phetsims/qa/issues/898#issuecomment-1450396035:
> In 2/27/2023 Calculus Grapher design meeting, we decided that we need further performance testing with some PhET-iO-only features enabled (`labeledLines`, `labeldPoints`).  I polled @emily-phet and @liammulh, and we decided to continue with this issue for futher testing, since that testing should involve the same devices.  I’ll assign this issue back to @emily-phet and @liammulh, with specific instructions, when it’s ready for further testing.

**Comment by amanda-phet** [comment]
Do you mean @stemilymill ? (emily-phet is Emily Moore)

**Comment by pixelzoom** [comment]
In AncillaryTool, each of the y Properties (yOriginalProperty, et.al.) is actually 3 DerivedProperties.  See `function createProperties`.  This is because we want to present discontinuties as `null` in Studio.   If we dropped that requirement, we would only need 1 DerivedProperty, and would likely see some performance improvement for the tools.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/calculus-grapher/issues/233#issuecomment-1454153946, I rewrote AncillaryTool and noted:
> * There are 4 fewer DerivedProperties per tool, which should improve performance -- see #243.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/calculus-grapher/issues/259 reminded me that the canvas version of bamboo classes have better performance.  We should consider switching to them.

**Comment by pixelzoom** [comment]
@veillette and I discussed during weekly pairing.  I'm going to experiment with using the Canvas versions of bamboo classes. We probably only need to do this for CanvasLinePlot.  There currently is no Canvas implementation for ScatterPlot, but it's not much performance burden.

**Comment by pixelzoom** [comment]
I spent ~30 minutes investigating what it would take to convert uses of LinePlot to CanvasLinePlot.  Summary:

* Most of the changes would be in CurveNode.ts.  
* We'd need to add a ChartCanvasNode, and add both `continuousLinePlot` and `discontinuousLinePlot` to it. 
* Where we're using LinePlotOptions in CurveNodeOptions, we'd need to switch to CanvasLinePlotOptions, which are not the same.  The `stroke` option is particularly problematic because CanvasLinePlot only supports `Color | string | null`, and not color Properties.  So we'd have to handle color updates ourselves, by listening to the color Property and calling CanvasLinePlot `setStroke` and `update`.

So it's probably another couple of hours to convert to Canvas.  I'm incline to do the conversion, since Canvas had such better performance in Fourier.  But defer the decision until we get performance results from https://github.com/phetsims/qa/issues/898.

**Comment by pixelzoom** [comment]
A lot of redunant calls to `curveChangeEmitter.emit` were identified and addressed in https://github.com/phetsims/calculus-grapher/issues/278.

**Comment by pixelzoom** [comment]
Closing, and ready for sign-off in #266.
