### ISSUE TITLE
Ancillary tool dashed line visible in predict mode

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#244]
There has been a bit of churn with the predict mode and I think this is a bug that result from it.
This was noticed on https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.17/phet/calculus-grapher_en_phet.html

To reproduce, on the integral screen
- turn on the predict mode under preference menu
- check the area under curve
- toggle the predict mode button
 
All the tools associated with the area under the curve disappear except the dashed vertical line.
You can do something similar with the derivative screen.

![image](https://user-images.githubusercontent.com/7633344/222227172-27d30830-653f-4a85-ab5e-0682db864dea.png)

Assigning to @pixelzoom, since he can isolate/locate the problem more easily than me.

**Comment by pixelzoom** [comment]
Fixed in the above commit.  I decided to fix this in the current implementation, so that it doesn't get report multiple times between now and when I refactor the scrubber code.
