### ISSUE TITLE
MAX_TILT is not respected.

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#245]
In tilt mode, the maximum tilt of the line should be 45 degrees. However the max tilt is not respected if the curve at at x=0 is not y=0. 

![image](https://user-images.githubusercontent.com/7633344/222556470-ecfaa51d-2432-474b-b76a-00d077406133.png)

**Comment by veillette** [comment]
This was noted while trying to reproduce https://github.com/phetsims/calculus-grapher/issues/241.

**Comment by veillette** [comment]
The tilt mode makes an assumption that the curve at x=0 is zero, which is the source of the problem.

**Comment by veillette** [comment]
Although the problem was easily identified, it took me a while to come to a solution. 
As as result of the commit above, the MAX_TILT in `CalculusGrapherConstants` is no longer an angle but a slope.
It turns out to be simpler to  calculate offsets based on difference in slopes rather than difference in angles.

**Comment by veillette** [comment]
I have tested it a bit and it works as expected.
The maximum slope that can be seen by manipulated the `Shift` and `Tilt` mode is the following. 
![image](https://user-images.githubusercontent.com/7633344/222838883-0774f0bc-3228-4426-82a7-c1c58067f863.png)

**Comment by veillette** [comment]
The commit for this issue can be found https://github.com/phetsims/calculus-grapher/commit/e9a2b4bde836940df291c48bb37abece0fb77c62

The previous implementation  limited the relative slope (measure by the added slope added by the user)  to be below a threshold. However, successive user manipulations would allow a user to create a slope that was nearly infinite.
The new approach is to determine the absolute slope of the curve and ensure that it is never above a threshold (currently set to 3).
Assigning to @pixelzoom to review and close if appropriate.

**Comment by pixelzoom** [comment]
Looks and behaves reasonably to me! Closing.
