### ISSUE TITLE
Add "Reference Line" text to checkbox

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#247]
From 3/6/2023 design meeting to review interview results (@amanda-phet @catherinecarter @kathy-phet @veillette @pixelzoom)

Add a "Reference Line" label to the reference line checkbox.  Because some interviewees did not know its purpose, and didn't have language to refer to it.

**Comment by pixelzoom** [comment]
Done, see screenshots below.  I'm not crazy about double-line labels on controls.  But it doesn't look as awful as I thought it would.  @amanda-phet please review, close if OK.

<img width="1012" alt="screenshot_2352" src="https://user-images.githubusercontent.com/3046552/223203330-91719187-3d66-42fc-ad58-9b17909f2226.png">

<img width="1010" alt="screenshot_2353" src="https://user-images.githubusercontent.com/3046552/223203343-613c9a82-c3ed-45a9-82df-0549ab192f82.png">

**Comment by catherinecarter** [comment]
Looks great to me, and the long text doesn't bother me, either. I also looked in PhET Test to see the look for the Advanced and Lab screens and they also look good to me. I like the consistency of the draggable handles being near each other, and the line above the scrubbers makes it much more clear they're draggable. I feel like the proximity also will make the scrubbers more visible, but I'd be interested to see if this is true in an interview.

**Comment by amanda-phet** [comment]
Since we have a tall icon, and "area under the curve" can't be shorter, I think it's fine that the label is on two lines.
