### ISSUE TITLE
Change the initial position of the reference line to x=5.5

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#248]
From 3/6/2023 design meeting to review interview results (@amanda-phet @catherinecarter @kathy-phet @veillette @pixelzoom)

Change the initial position of the reference line to x=5.5

**Comment by pixelzoom** [comment]
Done. Screenshot below show initial state with "Values" preference on.  @amanda-phet please review, close if OK.

<img width="709" alt="screenshot_2350" src="https://user-images.githubusercontent.com/3046552/223199579-0b7f3b32-bfb0-4b0a-aa02-d188967a0424.png">

**Comment by catherinecarter** [comment]
I like that the default reference line position doesn't interfere with the cueing arrows. And I actually think that it being off-center draws attention to it (in a good way) where students might want it in the middle, so they'll move it if they want.

**Comment by amanda-phet** [comment]
Looks good to me. Thanks!
