### ISSUE TITLE
Move the "Tangent" and "Area Under Curve" checkboxes out of the control panel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#249]
From 3/6/2023 design meeting to review interview results (@amanda-phet @catherinecarter @kathy-phet @veillette @pixelzoom)

Move the "Tangent" and "Area Under Curve" checkboxes out of the control panel, and group them with the other checkboxes.

Order is:

Tanget
Reference Line
Grid

Area Under Curve
Reference Line
Grid

**Comment by pixelzoom** [comment]
Done, see screenshots below, where "Predict" in so that all controls are visible. @amanda-phet please review, close if OK.

<img width="1012" alt="screenshot_2352" src="https://user-images.githubusercontent.com/3046552/223202505-c2f91613-9ce7-43d8-8153-d8eeaa80a11a.png">

<img width="1010" alt="screenshot_2353" src="https://user-images.githubusercontent.com/3046552/223202772-7c159b18-015d-4817-b451-fac335b78390.png">

**Comment by catherinecarter** [comment]
Seems much easier to find those checkboxes.

**Comment by amanda-phet** [comment]
This change seems like it's doing what we want. Thanks!
