### ISSUE TITLE
Change the default graph set for the Advanced screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#250]
From 3/6/2023 design meeting to review interview results (@amanda-phet @catherinecarter @kathy-phet @veillette @pixelzoom)

Change the default graph set for the Advanced screen to f(x) + f'(x).

**Comment by pixelzoom** [comment]
Done. Screenshot below shows the initial state of the Advanced screen.

@amanda-phet please review, close if OK.
<img width="702" alt="screenshot_2351" src="https://user-images.githubusercontent.com/3046552/223201138-cd8179de-6080-4a1f-aea0-f989520a9cb3.png">

**Comment by amanda-phet** [comment]
Thanks!
