### ISSUE TITLE
"Freeform" icon

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#251]
From 3/6/2023 design meeting to review interview results (@amanda-phet @catherinecarter @kathy-phet @veillette @pixelzoom)

We'd like to have an icon for "freeform" that looks a little different than the other modes. @amanda-phet and @catherinecarter will mock something up.

**Comment by amanda-phet** [comment]
is this feasible, @pixelzoom ? (Obviously the stroke should be a consistent width, I just took a screenshot and stretched it for the purposes of starting a discussion) 
![image](https://user-images.githubusercontent.com/7852916/223547002-10ea8928-5e01-4af2-94f6-e8e0697533eb.png)

It's not showing up great in this patched mockup because it's partially a stretched screenshot... but I can try to make it a true mockup so we get a more accurate view. 
![image](https://user-images.githubusercontent.com/7852916/223547314-18cc0ed5-43fb-4653-89f4-330049ae5629.png)

**Comment by pixelzoom** [comment]
Looks like this was intended to be assigned to me.

Yes, that's possible, I'll give it a try.  I'm going to use the FontAwesome pencil icon, which has the same orientation as what you've shown in your mockup:

<img width="56" alt="screenshot_2410" src="https://user-images.githubusercontent.com/3046552/224516858-a9864a60-a6bf-4eb3-a0f4-4c323e5a6642.png">

**Comment by veillette** [comment]
Here is the current model form the freeform icon.

```js
  public freeformIconCurve( yMin: number, yMax: number ): void {

    // Convenience variables
    const xLength = this.xRange.getLength();
    const xMin = this.xRange.getMin();
    const width = xLength / 4;

    this.createHillAt( width, xMin + xLength / 5, yMin );
    this.saveCurrentPoints();
    this.createTriangleAt( width, xMin + 2 * xLength / 5, yMax );
    this.saveCurrentPoints();
    this.createParabolaAt( width, xMin + 3 * xLength / 5, yMin );
    this.saveCurrentPoints();
    this.createPedestalAt( width, xMin + 4 * xLength / 5, yMax );
  }
```

but you can really go to town with it. You can also add explicit discontinuities if you would like to.

**Comment by pixelzoom** [comment]
Thanks. Something to work on during my flight tomorrow :)

**Comment by pixelzoom** [comment]
As I'm working on this issue, I have to say that I'm not really satisfied with any of these icons.   They are wide, and not very tall, which makes it difficult to clearly differentiate between the shapes.  I realize that they are like this because the radio buttons are arranged in a vertical layout.  But what if the buttons were in a 2-column grid, so that the icons could be taller? 
Derivative and Integral screens would have a 2x2 grid. Advanced and Lab screens would have a 4x2 grid.

@amanda-phet @veillette thoughts?

**Comment by pixelzoom** [comment]
On hold until we discuss https://github.com/phetsims/calculus-grapher/issues/286.

**Comment by amanda-phet** [comment]
@pixelzoom over to you to close just in case you are still making commits to this issue.

**Comment by pixelzoom** [comment]
One more refinement... In the above commit, I made the pencil icon `rgb( 50, 50, 50 )` instead of 'black'.  See screenshot below, and compare it to the screenshot above.  When it was 'black', it felt like it was competing with (maybe even overpowering) the black stroke for the seleted radio button.  

@amanda-phet let's review this when we meet this morning.

<img width="206" alt="screenshot_2435" src="https://user-images.githubusercontent.com/3046552/225640629-076efab0-f6b2-498b-a440-337d10fa41ed.png">

**Comment by pixelzoom** [comment]
@amanda-phet and I reviewed this on Zoom, and agreed that this looks good and can be closed.
