### ISSUE TITLE
Move "Predict" to the bottom of the Simulation tab in Preferences

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#252]
From 3/6/2023 design meeting to review interview results (@amanda-phet @catherinecarter @kathy-phet @veillette @pixelzoom)

Move "Predict" to the bottom of the Simulation tab in Preferences

**Comment by pixelzoom** [comment]
Done, see screenshot below. @amanda-phet please review, close if OK.

<img width="700" alt="screenshot_2356" src="https://user-images.githubusercontent.com/3046552/223204149-df96f0d6-26d9-43cc-b1b2-3e955cf687d2.png">

**Comment by amanda-phet** [comment]
Looks good. Thanks.
