### ISSUE TITLE
Add arrow heads to the x and y axes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#253]
From 3/6/2023 design meeting to review interview results (@amanda-phet @catherinecarter @kathy-phet @veillette @pixelzoom)

Add arrow heads to the x and y axes, pointing in the positive direction. No arrows in the negative direction.

**Comment by pixelzoom** [comment]
Done, see screenshots below.  Ready for @amanda-phet to review, close if OK.

These are the default bamboo arrow heads. We can customize them if you want. Here are the defaults (from AxisArrowNode.ts), let me know what you'd prefer.

```
      headHeight: 10,
      headWidth: 10,
      tailWidth: 2
```

<img width="1004" alt="screenshot_2361" src="https://user-images.githubusercontent.com/3046552/223207557-e27d26ca-7735-44bf-940f-dfaebe24ccef.png">

**Comment by catherinecarter** [comment]
I like arrows at the end of the axes. I'm wondering if the axes thickness and darkness are a bit much. Here's a not-so-complicated screenshot, and it feels like the graphs get a little lost among the dark/thick axes. Did they get thicker? I don't remember what they looked like before... 
<img width="812" alt="image" src="https://user-images.githubusercontent.com/109630002/223229391-c823fe4b-073b-446b-8cce-8b9a430ead2a.png">

**Comment by pixelzoom** [comment]
I did not intentionally increase the thickness of the axes, and was using the same line width. But apparently bamboo adds a stroke, which effectively doubled the thickness (from 2 to 4).   I turned off the stroke, see screenshot below. Better?


<img width="1005" alt="screenshot_2369" src="https://user-images.githubusercontent.com/3046552/223231420-b1acd205-ecda-4038-8260-8799d8e3aec7.png">

**Comment by amanda-phet** [comment]
I agree it was a bit too thick with the change. Thanks for making it thinner again. The y-axis is really clear now which is nice. I can't look right now, but the thing I'd want to check is how the new y-axis looks when values are turned on. I'll check when I'm back at my computer.

**Comment by pixelzoom** [comment]
Screenshot with "Values" on:

<img width="1006" alt="screenshot_2371" src="https://user-images.githubusercontent.com/3046552/223260997-18b250e6-e32b-48fc-a7f9-f1c1325d6606.png">

**Comment by catherinecarter** [comment]
Thanks for changing the thickness back, sounds like Bamboo thinks it can think for itself. I think it's really nice, in both cases when the values are on and off. Agree the y-axis is much easier to identify, and I think it's lovely.

**Comment by kathy-phet** [comment]
Looks nice to me, too!

**Comment by amanda-phet** [comment]
I was wondering if the arrow would point straight into a tick mark and look like it's pointing to a wall, but it looks ok to me. Thanks. Closing.
