### ISSUE TITLE
Make the icons for "Tangent" and "Area Under Curve" checkbox look like the Reference Line icon

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#254]
From 3/6/2023 design meeting to review interview results (@amanda-phet @catherinecarter @kathy-phet @veillette @pixelzoom)

Make the icons for "Tangent" and "Area Under Curve" checkbox look like the Reference Line icon.  That is, add a short vertical line.

**Comment by pixelzoom** [comment]
Done, see screenshots below.   Note that I did not use a dashed line for the tangent and area icons -- it looked pretty awful. @amanda-phet please review, close if OK.

<img width="158" alt="screenshot_2355" src="https://user-images.githubusercontent.com/3046552/223203751-3f3d6fe3-46e2-4a24-8b77-3949ba1ec706.png">

<img width="169" alt="screenshot_2354" src="https://user-images.githubusercontent.com/3046552/223203763-7dff6cc9-6ddb-40c9-bc77-888bb5d1ec25.png">

**Comment by amanda-phet** [comment]
Looks great to me. I can see why dashed would be weird with it so short.

**Comment by kathy-phet** [comment]
Looks good!
