### ISSUE TITLE
How to label the graphs

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#255]
From 3/6/2023 design meeting to review interview results (@amanda-phet @catherinecarter @kathy-phet @veillette @pixelzoom)

@kathy-phet suggested adding more verbose labels to the graphs in the first couple of screens.  Like:

* function: f(x)
* derivative: f'(x)

We discussed this further after @kathy-phet left the meeting and identified some issues with this proposal:

* Doing this only for some screens complicates the code and the Studio tree.
* f''(x) only appears on the Lab screen.
* Is f'(x) labeled as "derivative" or "first derivative"?  If we have to change based on whether f''(x) is present, that's going to be a mess.
* These labels will get very long.  "second derivative: f''(x)" will span ~40% of the graph.
* There will be much more overlapping of labels and curves, creating visual noise.

@amanda-phet suggested maybe adding a 3rd choice to the "Notation" preferences that uses only the word "derivative", etc. Will anyone use this? Is it worth the effort?

This issue requires more discussion.

**Comment by pixelzoom** [comment]
> @amanda-phet suggested maybe adding a 3rd choice to the "Notation" preferences that uses only the word "derivative", etc. Will anyone use this? Is it worth the effort?

There's a fundamental problem with this.  If we switch the graph labels to use "words", then what do the icons show? They can't use words, there no space.  And which notation do they use?  Their notation depends on the Notation preference setting.

**Comment by amanda-phet** [comment]
@kathy-phet this needs to be resolved this week for us to meet our milestones. 

My inclination is to not support adding to or changing labels on graphs. There are a lot of complications associated with it, and it seems like students will build vocabulary by playing with the first two screens.

**Comment by kathy-phet** [comment]
@amanda-phet - I'm not sure they build the language with the first two screens, because the only place the word is is in the screen name, which is not tied to the graph it needs to name. I have time 8:30-10 tomorrow - if that works for some brainstorming.

**Comment by pixelzoom** [comment]
How about a title bar on each graph?  Something like the screenshots shown below.  I've turned on Values, the grid, and scrubber, so you can see how those are affected.  

Notes:
* I hacked this together in ~20 minutes. It will take 1-2 hours to do it right.
* This reduces the height of each graph by 20 pixels.
* Grid cells are still square
* Vertical lines for the scrubbers are in front of all title bars except the top one
* The highlight for the _f(x)_ graph encloses the title bar.
* I started with a black title bar, but it felt too heavy, so I switch to gray. Easy to change.
* "First Derivative" is used on all screens.


<img width="1187" alt="screenshot_2389" src="https://user-images.githubusercontent.com/3046552/223742656-a0f9ac4e-43ab-41e9-b5d3-973c588cc8fe.png">
<img width="1191" alt="screenshot_2390" src="https://user-images.githubusercontent.com/3046552/223742676-74bc225c-a173-489b-b804-96e8d5966c0c.png">

**Comment by pixelzoom** [comment]
> * Grid cells are still square

Oops... This makes the grid cells non-square in the Lab screen.  Do we need to revisit the graph ranges?

<img width="1191" alt="screenshot_2391" src="https://user-images.githubusercontent.com/3046552/223746734-8b9de675-b04f-47cb-8115-bae20c0087f6.png">

**Comment by pixelzoom** [comment]
3/8/2023 design meeting: @amanda-phet @catherinecarter @kathy-phet @veillette @pixelzoom

We decided not to change anything. Closing.
