### ISSUE TITLE
Polish width slider

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#257]
From 3/6/2023 design meeting to review interview results (@amanda-phet @catherinecarter @kathy-phet @veillette @pixelzoom)

For the width slider, make the minor tick marks a bit more subtle.

**Comment by pixelzoom** [comment]
Before and after shown in the screenshots below.  Minor ticks are now `lineWidth: 0.5` and `stroke: 'rgb( 120, 120, 120 )'`.

@amanda-phet please review, close if OK.

<img width="185" alt="screenshot_2357" src="https://user-images.githubusercontent.com/3046552/223205163-41a7ecfa-49de-486f-99c7-ff88840f10da.png">

<img width="185" alt="screenshot_2359" src="https://user-images.githubusercontent.com/3046552/223205285-b9403e4a-5b38-47bd-8c2d-e50497ff799d.png">

**Comment by catherinecarter** [comment]
Lighter minor tick marks looks good to me. Sort of draws my attention to the ends and the middle - not sure if this is a good, bad, or indifferent thing, but that's what it's doing for me.

**Comment by amanda-phet** [comment]
I agree @catherinecarter . Not sure this is doing much for me, and seems to accentuate the middle and ends. Should all of the tick marks get a thinner stroke? Or maybe the intermediate tick marks should just be shorter?

**Comment by amanda-phet** [comment]
Assigning back to @pixelzoom to comment and possibly try other tweaks. Maybe just keep them back and not change the stroke to gray?

**Comment by pixelzoom** [comment]
It's very typical to emphasize "major" marking and deemphasize "minor" markings.  We're doing it with the graph grid lines. And I was hoping to tone down the "lots of vertical lines" look that this sim suffers from.   But now I'm kind of sorry that I mentioned this, because the cost has now exceeded any imaginable benefit.

> Or maybe the intermediate tick marks should just be shorter?
If by "intermediate" you mean the minor tick marks... All tick marks need to be long enough to stick out above/below the slider thumb.  So making the minor ticks shorter is not an option.

> Maybe just keep them back and not change the stroke to gray?

I'm assuming you mean "black".  I'll do this.

**Comment by catherinecarter** [comment]
What if every other line were greyed out and middle tick mark is the same size as the others? Just a thought.

**Comment by amanda-phet** [comment]
I like them all black, but whichever you prefer @pixelzoom is fine with me. Please feel free to switch them to gray again, or leave as black and close this issue.

**Comment by pixelzoom** [comment]
I'm good with black. It's 1 less line of code :)

Closing.
