### ISSUE TITLE
Increase size of tangent arrow heads

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#258]
From 3/6/2023 design meeting to review interview results (@amanda-phet @catherinecarter @kathy-phet @veillette @pixelzoom)

Increase size of the tangent line's arrow heads slightly.  Do not increase the width of the arrow shaft.

**Comment by pixelzoom** [comment]
Increased arrow heads from 8x8 to 10x10, screenshot below.  @amanda-phet please review, close if OK.

<img width="1235" alt="screenshot_2367" src="https://user-images.githubusercontent.com/3046552/223222490-fb6fa23b-21d9-4e3c-a1be-35bea923d26d.png">

**Comment by amanda-phet** [comment]
This looks good to me.

**Comment by amanda-phet** [comment]
Thanks! Closing.
