### ISSUE TITLE
Solutions to avoid infinite tilting

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/calculus-grapher#26]
In #25, I said that I believe my assertions were failing since the user was tilting the curve near the origin, which resulted in vertical curves.

<details><summary>Here is a sample:</summary>

![*](https://user-images.githubusercontent.com/42391580/87070931-be69fa80-c1d6-11ea-9173-4f1c97fa4056.gif)
</details>

----

@amanda-phet how should we ensure that the user doesn't encounter this?

I have a couple of ideas (prefer 1):
   1. Keep track of the 'angle' of the curve and add some sort of drag-bounds (say -45 to 45 degrees) so that the user can only set the angle of the curve to an angle that is inside that range. It's likely that the curve will need to track an 'angle' anyways due to #3.
   2. Change the anchor position depending on where the user's pointer is. If the user drags the curve closer to the origin, the anchor is the rightmost extreme of the curve (and vise versa).

**Comment by amanda-phet** [comment]
I think option (1) sounds great. There is no reason to adjust the tilt really dramatically. The learning goal of that control is to see how the derivative and integrals change, and that is done while doing the tilt, so once you understand the principle you don't need to go very far. We might want more than 45, but absolutely don't need to go to 90.

**Comment by brandonLi8** [comment]
Done in the commits above. I also added the `?maxTilt` query parameter (defaults to 45) for adjustment down the road. Closing.
