### ISSUE TITLE
Is integral expression correct? 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#260]
Noticed by @veillette.  We're not sure if the integral expression is correct. It's currently:

<img width="103" alt="screenshot_2373" src="https://user-images.githubusercontent.com/3046552/223522038-a97664e0-25ad-4544-b918-4586170c445f.png">

... where _x_ may be replace by _t_ via Preferences.

@veillette recalls that the symbol use in the bounds (0, _x_) is sometimes different than the symbol in used in the integrand (`f(x) dx`).  For example `x'` (x prime).

@amanda-phet can you verify what's correct, and whether we need to change anything?

**Comment by amanda-phet** [comment]
Good catch! That is incorrect. Some point between dev4 and dev 5 that notation got changed. It is supposed to be integral from 0 --> x of f(t) dt. For the reason @veillette brings up. 

Now, since we have the choice to use x or t in the preferences... we will need to do something else here, because that seems too confusing to use that notation at this point. 

We also decided the prime notation isn't a good fit for calculus classes, because shorthand for derivatives is often f' or g', and while we wouldn't normally name a function x, it is still not a great choice to use x'. 

I think we should change the integral bounds to be from 0 to x_0. 
![image](https://user-images.githubusercontent.com/7852916/223534845-b54b722f-7861-44c5-9c34-130d55e37436.png)

@catherinecarter does this sound good to you, too?

**Comment by catherinecarter** [comment]
I looked in some textbooks and saw the bounds on the integral where any of the following:
1. bounds unknown: 
- <img width="91" alt="image" src="https://user-images.githubusercontent.com/109630002/223552866-74fa0588-b263-476d-8a07-2dfaf8741851.png">
2. lower bound known but across t: 
<img width="89" alt="image" src="https://user-images.githubusercontent.com/109630002/223552957-e92bf3f1-7d2d-46b0-8abc-65fadc17de6c.png">
3. no bounds at all:
<img width="88" alt="image" src="https://user-images.githubusercontent.com/109630002/223553053-239937a1-080a-475c-b37f-f85d948a8b47.png">

My concern with <img width="30" alt="image" src="https://user-images.githubusercontent.com/109630002/223553101-78da5295-f307-4026-bc67-1a50f842e301.png"> is that <img width="30" alt="image" src="https://user-images.githubusercontent.com/109630002/223553154-e471c6f3-0870-4bf6-92f3-41dc7ca1ab41.png"> is usually the symbol for the starting x-value in a Riemann sum rather the end x-value of the sum. If a subscript is the preferred option, I think changing it to x-sub1 would be a little more clear (over x-sub0).

This brings up a question for me: If the letter x and t are dynamic according to the user's preferences, could the upper bound also be dynamic and follow the x-value _if_ the values are turned on in preferences? If so, that would be pretty cool to help students notice that the area is being accumulated from 0 to whatever x their scrubber is on. If not, I'd probably vote for either #1 (from 0 to b) or #3 (no bounds at all).

Thoughts?

**Comment by pixelzoom** [comment]
> This brings up a question for me: If the letter x and t are dynamic according to the user's preferences, could the upper bound also be dynamic and follow the x-value if the values are turned on in preferences?

What do you mean by "follow the x-value"?  Do you mean that if "Values" is turned on in preferences, then the bounds should change to 0 to 10?   Is the really desirable or necessary?  Would the student even notice?

**Comment by amanda-phet** [comment]
>My concern with image is that image is usually the symbol for the starting x-value in a Riemann sum rather the end x-value of the sum. If a subscript is the preferred option, I think changing it to x-sub1 would be a little more clear (over x-sub0).

Good point about x_0. x_1 would achieve the same result. 

>If not, I'd probably vote for either choice 1 (from 0 to b) or choice 3 (no bounds at all).

Can we have it with no bounds? Maybe @veillette would know, but my understanding was that we did need to have bounds, since the sim is integrating over a very certain domain (even if that value isn't shown to students). 

We do know one of the bounds is 0, so a to b doesn't make sense to me. Does 0 to b make sense? why b? If you think 0 to b is clear, then that works for me.

**Comment by pixelzoom** [comment]
> We do know one of the bounds is 0, so a to b doesn't make sense to me. Does 0 to b make sense? why b? If you think 0 to b is clear, then that works for me.

That's true if you assume that the y-axis is at x=0.  When "Values" is off, we are not shown any x-axis labels, including 0.  So wouldn't it be more correct to show no range when "Values" is off?

**Comment by catherinecarter** [comment]
`What do you mean by "follow the x-value"? `
@pixelzoom - I meant if the values were turned on, wherever the scrubber was, say x = 4.2, then that would be the upper bound. The lower bound would stay zero. 

> We do know one of the bounds is 0, so a to b doesn't make sense to me. Does 0 to b make sense? why b? If you think 0 to b is clear, then that works for me.

@amanda-phet - I was thinking that if students were used to seeing a to b, but a is always zero, it would make sense to have 0 to b. But I suspect that may be confusing, so probably x-sub1 will suffice. I do think it would cool, though, for the upper bound to dynamically reflect the x-value if the values are turned on. But I don't know if that's feasible or desirable.

**Comment by veillette** [comment]
The mathematically correct answer is 

![image](https://user-images.githubusercontent.com/7633344/223557147-1a36cabf-dca2-4da0-8de9-1bc2bba15a9d.png)

as we deal with a definite integral. Mathematically the `a` is a dummy variable, in other words, it could be anything.

The bounds of the integral defines the variable of the new function, so therefore the upper bound would need to be a function of x.

This what we did in flash.
![image](https://user-images.githubusercontent.com/7633344/223558539-aec721d0-63f9-4148-ba4a-51b7ae4d5990.png)
but used x' instead. Again it could be anything.

However, I don't think we should be too much swayed by mathematically correctness. Only pedantic math professors would be offended.

**Comment by pixelzoom** [comment]
> > What do you mean by "follow the x-value"?

> @pixelzoom - I meant if the values were turned on, wherever the scrubber was, say x = 4.2, then that would be the upper bound. The lower bound would stay zero.

There is no area scrubber in the Lab screen.  We need to do something that works generally for all screens.

**Comment by veillette** [comment]
I'm still biased toward using x as our dummy variable, but last time we discussed it, it was not a popular opinion.

**Comment by catherinecarter** [comment]
It doesn't really matter to me what's there. I'd be interested to hear from teachers to see if they notice or have a preference about it. If we leave as is, the integral will go from 0 to x, and depending on what variable is used in preferences, it will be 
<img width="166" alt="image" src="https://user-images.githubusercontent.com/109630002/223563537-29f172cb-6937-49e2-a960-d7999a2841a6.png">?

**Comment by pixelzoom** [comment]
Not sure where you got those screenshot @catherinecarter -- I'm guessing not from the sim, since they do not have a blue background.  But if we leave it as is, then the upper bound also changes to match the Variable selected in Preferences:

<img width="82" alt="screenshot_2380" src="https://user-images.githubusercontent.com/3046552/223565973-8a1e3513-6f45-4fd9-ab63-69865a2486b3.png">

<img width="80" alt="screenshot_2379" src="https://user-images.githubusercontent.com/3046552/223565985-c227f613-3ac5-45b9-94eb-6ea3978bd5ab.png">

**Comment by veillette** [comment]
Sorry @catherinecarter  for the confusion. I would propose what @pixelzoom  suggested above, (which is to do nothing).

**Comment by veillette** [comment]
But @amanda-phet was proposing/suggesting when using the `x` variable

```math
\int_0^x f(a) da
```
and, when using the `t` variable

```math
\int_0^t f(a) da
```

**Comment by veillette** [comment]
By the way, I just found how to write mathematical equation in github comment:  https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions

**Comment by pixelzoom** [comment]
Cool! Wouldn't it be nice if we could do that in PhET sims, instead of having to cobble together mathematical expressions and equations?

**Comment by catherinecarter** [comment]
Ah, I see. Thanks for the clarification @pixelzoom and @veillette. Yes, the screenshots I put into this conversation were from a Google doc. I think @amanda-phet's suggestion is great. The upper bound correctly and clearly shows the variable being used on the x-axis, and the dummy variable, _a_ is nice and neutral.

**Comment by catherinecarter** [comment]
@veillette - curious where your bias comes from for the dummy variable being _x_?

**Comment by pixelzoom** [comment]
I'm concerned about using "f(a) da".  I think that's going to cause confusion.

See "Terminology and Notation" in https://en.wikipedia.org/wiki/Integral:

> In general, the integral of a [real-valued function](https://en.wikipedia.org/wiki/Real-valued_function) f(x) with respect to a real variable x on an interval [a, b] is written as
> 
```math
\int_a^b f(x) dx
```
> 
> When the limits are omitted, as in

```math
\int_a^b f(x) dx
```

> the integral is called an indefinite integral, which represents a class of functions (the [antiderivative](https://en.wikipedia.org/wiki/Antiderivative)) whose derivative is the integrand.[[](https://en.wikipedia.org/wiki/Integral#cite_note-19)

So my vote is for:

```math
\int_a^b f(x) dx
```
```math
\int_a^b f(t) dt
```

**Comment by pixelzoom** [comment]
I'm concerned about using "f(a) da", when "f(x)" is used everywhere else.  I think that's going to cause confusion.

See "Terminology and Notation" in https://en.wikipedia.org/wiki/Integral:

> In general, the integral of a [real-valued function](https://en.wikipedia.org/wiki/Real-valued_function) f(x) with respect to a real variable x on an interval [a, b] is written as
> 
```math
\int_a^b f(x) dx
```
> ... The function f(x) is called the integrand, the points a and b are called the limits (or bounds) of integration, and the integral is said to be over the interval [a, b], called the interval of integration.
>
> When the limits are omitted, as in

```math
\int f(x) dx
```

> the integral is called an indefinite integral, which represents a class of functions (the [antiderivative](https://en.wikipedia.org/wiki/Antiderivative)) whose derivative is the integrand.[[](https://en.wikipedia.org/wiki/Integral#cite_note-19)

So my vote is for:

```math
\int_a^b f(x) dx
```
```math
\int_a^b f(t) dt
```

**Comment by pixelzoom** [comment]
.... and I'd be OK with replacing "a" and "b" with "0" and "10" respectively when "Values" is turned on.  But I question whether anyone will notice, and whether it's worth the effort.

**Comment by pixelzoom** [comment]
3/8/2023 design meeting: @amanda-phet @catherinecarter @kathy-phet @veillette @pixelzoom 

Decided to leave it as is:

```math
\int_0^x f(x) dx
```
```math
\int_0^t f(t) dt
```
