### ISSUE TITLE
Should we make hill and pedestal affect the curve more locally?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#261]
For the hill and pedestal, using these modified affects the entire curve, not limited to any width (sigma).  

For example, supposed I set up a situation like this.  I've selected the "hill" radio button, set the width to its minimum.  Then I draw a hill at the far left:

<img width="787" alt="screenshot_2375" src="https://user-images.githubusercontent.com/3046552/223529618-4fbb3280-1317-443e-ad50-91d731427056.png">

Turning on the reference line tool, moving it to the far RIGHT, in Studio I can see that the value of `yOriginalProperty` is a very small non-zero value:

<img width="768" alt="screenshot_2376" src="https://user-images.githubusercontent.com/3046552/223530533-2a9986b7-1ed6-4241-9886-75fb0b399201.png">

Should we make hill and pedestal affect the curve more locally, similar to triangle, parabola, etc.?  @amanda-phet thoughts?

**Comment by amanda-phet** [comment]
Can it still be "smooth" for the entire curve? I think it's reasonable for the curve to eventually be 0 when using the hill and pedestal, as long as this doesn't introduce a cusp (which is what the triangle and parabola have).

**Comment by veillette** [comment]
In essence, we should only update the pedestal and hill function if their weight is above a threshold.
````js
  /**
   * Update pointValue with appropriate weight, but if weight is very small leave as is.
   * (see https://github.com/phetsims/calculus-grapher/issues/261)
   */
  private updatePointValue( point: CurvePoint, weight: number, peakY: number ): void {

    assert && assert( weight >= 0 && weight <= 1, `weight must range between 0 and 1: ${weight}` );

    // If the weight is very small, we are practically ignoring the new function. Let's explicitly replace it by the lastSavedY instead.
    point.y = ( weight > LOWER_WEIGHT ) ? weight * peakY + ( 1 - weight ) * point.lastSavedY : point.lastSavedY;
  }
````

I picked `LOWER_WEIGHT` to be 1e-8. I needs to be a fairly small number as the second derivative is sensitive to sudden a drop off. I checked that it did not generate any visual artefacts in the second derivative. 

In practice it means that beyond about about four value of "sigma" width, the function is zero. See below in studio for an example.
 
![image](https://user-images.githubusercontent.com/7633344/224513079-5e62af69-f221-40c6-8c4a-cdf36992b75f.png)

**Comment by veillette** [comment]
Assigning to @pixelzoom to review, and check that it behaves as expected in studio.

**Comment by pixelzoom** [comment]
Code looks excellent, and it's behaving nicely in Studio. This is a very nice improvement. 

I did add one assertion in TransformedCurve:

```ts
assert && assert( LOWER_WEIGHT < UPPER_WEIGHT, 'LOWER_WEIGHT must be < UPPER_WEIGHT' );
```

I suspect that this is done and can be closed, but I'm not certain.  So back to @veillette.

**Comment by veillette** [comment]
our work is done here. We can close.
