### ISSUE TITLE
model.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#263]
For https://github.com/phetsims/calculus-grapher/issues/262

Link: https://github.com/phetsims/calculus-grapher/blob/master/doc/model.md

We'll need to complete this before publication, because it's linked into the PhET-iO materials that are delivered to clients.  

It would be nice to have before official code review, but not essential.

**Comment by pixelzoom** [comment]
I made a couple changes for proof reading in the above commits.

**Comment by veillette** [comment]
I added a section called  "## Approximations, Limitations and Implementation Details" where I explained some internal details of  our  implementations without going too much into the weeds.

**Comment by veillette** [comment]
One aspect that is not included is a description of the mathematical transformation associated with each curve manipulation mode. Since there are many of them, it will be a long passage, but maybe that should be included. @amanda-phet, what do you think?

**Comment by pixelzoom** [comment]
@veillette and I discussed.  I think it would be useful to have a section that briefly enumerates the curve manipulation modes, and includes:

* their names (hill, pedestal, ...)
* identify which ones are relevant for "width"
* a brief description of the curve that they draw

**Comment by amanda-phet** [comment]
I made three edits. I'm not sure if I worded the 3rd one correct, but it had a typo (mentioning tangent line in the area under the curve section). 

@veillette please review and if it looks good I think this can be closed.

**Comment by veillette** [comment]
Good catch @amanda-phet ! I think we can close then.
