### ISSUE TITLE
implementation-notes.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#264]
For https://github.com/phetsims/calculus-grapher/issues/262.

Link: https://github.com/phetsims/calculus-grapher/blob/master/doc/implementation-notes.md

This would be nice to have before official code review, but not essential. Certainly we should have it done before @veillette's sabbatical ends.

**Comment by veillette** [comment]
I'll assign this one to myself.

**Comment by veillette** [comment]
Assigning to @pixelzoom as well.

**Comment by pixelzoom** [comment]
The section titled [Query Parameters](https://github.com/phetsims/calculus-grapher/blob/master/doc/implementation-notes.md#query-parameters) duplicated the information in CalculusGrapherQueryParameters.ts, and would be likely to get out of sync.  Since dev and QA are used to reading query-parameter schemas, I replaced that section with a link to CalculusGrapherQueryParameters.ts.

**Comment by pixelzoom** [comment]
I added a **Termninology** section that needs to be fleshed out.  I think we can keep this very brief.  No need to include general math terminology, only sim-specific terms that might not be obvious, and would help someone reading the code.

**Comment by veillette** [comment]
I added a section about PHET-IO with a short stub. Assigning to @pixelzoom who be able to add something more cogent/relevant.

**Comment by pixelzoom** [comment]
implementation-notes.md is not delivered with a release.  So we can continue to make changes after the release branch is published, and there's no need to cherry-pick to the release branch.

**Comment by veillette** [comment]
I went over the implementations-notes. It is a good description and if we compare it to other sim's implementations-notes,  we are raising the bar. Closing.
