### ISSUE TITLE
Discontinuity inconsistent for some graphs

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/calculus-grapher#269]
I have noticed that some of the graphs that I would expect to consistently produce a discontinuity, don't. 

e.g. This function can look like this: 
![image](https://user-images.githubusercontent.com/5096804/223779221-42587a3e-c7b3-45f3-b2f1-c64837297d92.png)

or like this: 
![image](https://user-images.githubusercontent.com/5096804/223779354-a4d59c04-7ada-4c08-94ec-ce59bfc1618f.png)

or like this: 
![image](https://user-images.githubusercontent.com/5096804/223779446-0c5b7004-a25a-49c8-9a21-d100649d92e7.png)

In the interview, it was a bit confusing to the student as to why it sometimes was discontinuous and why other times it was not. 

Note that this is ALL on the setting of open points.

**Comment by pixelzoom** [comment]
This is in @veillette's wheelhouse, so unassigning myself.

**Comment by veillette** [comment]
Yes, we discussed a new approach in our 3/7 meeting on how to better addressed to detect cusps (see #208).  Finding a  better way to detect cusps in f(x) allows us to more easily tag the discontinuities for the derivatives.

**Comment by kathy-phet** [comment]
OK, great. Feel free to close, if this is a duplicate.

**Comment by veillette** [comment]
Let's close. we are tracking this in #208
