### ISSUE TITLE
Gets the y coordinate of the top of the top-most ChartRectangle but providing x values

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#271]
I'm not sure how that even works.

```
  /**
   * Gets the y coordinate of the top of the top-most ChartRectangle.
   */
  private getChartRectanglesTop(): number {
    return this.graphSetNode.x;
  }
```

**Comment by veillette** [comment]
console.log tells me that the x and y  values are both zero, which explains why it did not affect the layout.

**Comment by pixelzoom** [comment]
Also embarrasing that WebStorm has been shouting at me about this, and I've been ignoring it:

<img width="560" alt="screenshot_2404" src="https://user-images.githubusercontent.com/3046552/224108338-bdd25d45-9d3a-4eff-bd66-837f60a15242.png">

**Comment by pixelzoom** [comment]
Fixed in the above commit, closing.
