### ISSUE TITLE
A bit of cleanup related to Undo feature

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#273]
Related to #262 (self code review)

One area that I thought could benefit from some renaming is the stuff related to the "Undo" feature.  There are names like `PointState`, `savedState`, `undoToLastSave`, etc. that could be a bit clearer.   And I think it's important to state that the 'undo' data structure is a stack (last-in, first-out).

I'll take a stab at this, then have @veillette review.

**Comment by pixelzoom** [comment]
I changed the names of 3 things, all in CurvePoint.ts:

* `type PointState` => `type CurvePointState`
* `savedStates` => `undoStack`
* `undoToLastSave()` => `undo()`

And I added this documentation to `undoStack`:

```ts
  // An array of this CurvePoint's saved states, for the Undo feature. This is used as a stack (last in, first out).
  // When save() is called, the current state of this CurvePoint is pushed onto the end of the stack.
  // When undo() is called, the last state that was pushed to the stack is popped off, and used to restore
  // the state of this CurvePoint. Note that this field is not serialized as part of PhET-iO state, see
  // https://github.com/phetsims/calculus-grapher/issues/65
  private readonly undoStack: CurvePointState[];
```

@veillette is this OK with you? If you were attached to some of the old names, I can revert.

**Comment by veillette** [comment]
That looks good to me. CLosing
