### ISSUE TITLE
PresetFunctions

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#274]
In #208, we have modified our approach to identify the CurvePointType: 'smooth, cusp, discontinuous'. The approach is very different than our algorithmic way to identify curvePointType based on the shave of the Curve. Instead, we decided CurvePointType are associated with CurveManipulationMode. 

PresetFunctions includes a set of mathematical functions (presets) and a KeyboardEvent listener for cycling
through those presets when the left/right arrow keys are pressed. PresetFunctions was used internally to test our curvePoint algorithm, but can no longer be used for this purpose with our new approach.

This bring the question: What should we do with PresetFunctions?
I see three way forward with PresetFunctions:
- leave as is. It could find a use in the future to navigate through presetFunctions for pedagogical purposes
- repurpose it to test our new approach by adding segments of curveManipulationModes.
- remove it altogether. It comes with a lot of baggage.

**Comment by veillette** [comment]
@pixelzoom: do you have any thoughts?

**Comment by pixelzoom** [comment]
It was useful and served a purpose. But it sounds like there's no current need, only potential/hypothetical future needs.  So I would remove it altogether.  If there's a need for it in the future, it can be resurrected from git history

**Comment by veillette** [comment]
I'll try to make a clean git surgery, and tag it in this issue for posterity.

**Comment by veillette** [comment]
Assigning to @pixelzoom to review. Feel free to close.

**Comment by pixelzoom** [comment]
Looks great. I don't see anything missed. Closing.
