### ISSUE TITLE
Redundant calls to `curveChangedEmitter.emit`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#278]
In Curve.ts, I see two mentions of `positionPropertyReadOnly`:

```ts
  // The collection of points that describe the curve. This is an array of CurvePoint instances that are typically
  // mutated in place, so that we have acceptable performance. If Curve was instantiated with positionPropertyReadOnly:true,
  // then it is possible to set pointsProperty via PhET-iO.
  private readonly pointsProperty: Property<CurvePoint[]>;
...
    // For Curve instances created with positionPropertyReadOnly:true, pointsProperty may be set via PhET-iO.
    // If that happens, notify listeners.
    this.pointsProperty.link( ( newPoints, oldPoints ) => {
```

But option `positionPropertyReadOnly` does not exist anywhere.  Did its name change? Is this documentation still relevant?

**Comment by veillette** [comment]
The only thing that comes to my mind is that we have many curves but only original curves and predict curves should be settable, the other should only be read only.   I think positionPropertyReadonly could be related to it.

**Comment by pixelzoom** [comment]
This code in Curve.ts is supposed to handle setting points via Studio:

```ts
    // Use this to short-circuit reentrant behavior where curveChangedEmitter and pointsProperty listeners (below)
    // call each other.
    let notifyListeners = true;

    // This is needed to notify Studio that pointsProperty has effectively changed.
    this.curveChangedEmitter.addListener( () => {
      if ( notifyListeners ) {
        this.pointsProperty.notifyListenersStatic();
      }
    } );

    // For Curve instances created with positionPropertyReadOnly:true, pointsProperty may be set via PhET-iO.
    // If that happens, notify listeners.
    this.pointsProperty.link( ( newPoints, oldPoints ) => {
      if ( newPoints !== oldPoints ) {
        notifyListeners = false;
        this.curveChangedEmitter.emit();
        notifyListeners = true;
      }
    } );
```

If I add a `console.log` to `this.pointsProperty` listener, and click in the _f(x)_ graph on the Derivative screen, I see the console output 8x.  It shouldn't be firing at all.   So it looks like we have a lot of calls to `curveChangedEmitter.emit` that should not be occurring, and are resulting in redundant work during curve manipulation.

**Comment by pixelzoom** [comment]
Checking git history for "positionPropertyReadOnly" points to https://github.com/phetsims/calculus-grapher/issues/90.

**Comment by pixelzoom** [comment]
Code commments are incorrectly referring to "positionPropertyReadOnly", it should be "pointsPropertyReadOnly".  In Curve.ts SelfOptions:

```ts
  // For PhET-IO, is pointsProperty read-only?
  pointsPropertyReadOnly?: boolean;
```

Fixed in the above commit. 

Now I need to figure out why `this.pointsProperty` listener is being notified while the curve is being manipulated.

**Comment by pixelzoom** [comment]
The problem is that this is firing every time the curve is manipulated, because `notifyListeners` is true.

```ts
     // This is needed to notify Studio that pointsProperty has effectively changed.
    this.curveChangedEmitter.addListener( () => {
      if ( notifyListeners ) {
        this.pointsProperty.notifyListenersStatic();
      }
    } );
```

**Comment by pixelzoom** [comment]
Another fix to the `pointPropertyReadOnly` doc in the above commit. The comments say that points are settable via Studio if  `pointsPropertyReadOnly:true`.  That's incorrect; they must be `pointsPropertyReadOnly:false` to be settable, otherwise they are read-only.

**Comment by pixelzoom** [comment]
In the above commit, I put `if ( !options.pointsPropertyReadOnly ) { ... }` around the code that I identified in https://github.com/phetsims/calculus-grapher/issues/278#issuecomment-1464780487.  When clicking in originalGraphNode on the Derivative screen, this reduces the number of times that pointsProperty listener fires from 8x to 2x.  That's better, but it should fire 0x, so this is not quite solved.

And I confirmed that `originalCurve.pointsProperty` is still settable from Studio.

**Comment by pixelzoom** [comment]
I now understand what's going on here, and improved the documentation significantly so that others (including my future self) won't be so mystified if this needs to be revisited.   

The code that is PhET-iO specific is now surrounded with `if ( Tandem.PHET_IO_ENABLED ) {...}` so that it does not impact brand=phet.   And for brand=phet-io, a `pointsProperty` listener is only registered for `originalCurve` and `predictCurve`. 

@veillette if you want to have a look, I suggest skipping the above commits, and just looking at Curve.ts lines 115-144 (the very end of the constructor).  Let me know if you want to discuss, or feel free to close.

**Comment by pixelzoom** [comment]
In brand=phet, this eliminate 7 redundant calls to `curveChangedEmitter.emit` for every manipulation of the curve. For brand=phet, it eliminated 6 redundant calls.  SDo performance should be improved all around.

**Comment by veillette** [comment]
I see that you (1) made it conditional with 'if ( Tandem.PHET_IO_ENABLED ) {...}' and ` if ( !options.pointsPropertyReadOnly ) `, which I think are the two important aspects that remove redundant calls. 
To be honest, although I see that it saved a lot of unnecessary calls, I don't fully understand the math behind the 7 and 6 calls. In any case, it feels tangibly snappier for sure and Studio is updating correctly. I'm glad that you found this redundant calls.

**Comment by veillette** [comment]
Closing

**Comment by pixelzoom** [comment]
> ...  I don't fully understand the math behind the 7 and 6 calls ...

These numbers with observed, via `console.log` statements. Though I tried to understand these specific number, I never succeeded, and I gave up when it was consuming too much time.
