### ISSUE TITLE
Document a few methods in TransformedCurve

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#279]
Related to https://github.com/phetsims/calculus-grapher/issues/262 ...

There are a handful of methods in TransformedCurve.ts that are missing documentation:

- [x] manipulateCurve
- [x] iterateFunctionOverPoints
- [x] freeformIconCurve

**Comment by veillette** [comment]
I added some documentation to the three methods that had no documentation. 
Assigning to @pixelzoom for review

**Comment by pixelzoom** [comment]
Looks good.  I added some missing punctuation in the above commit, to prove that I actually read it :)

Closing.
