### ISSUE TITLE
Two remaining PhET-iO requests 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/calculus-grapher#281]
As part of https://github.com/phetsims/calculus-grapher/issues/224 I discovered two features that @kathy-phet and I were hoping to have in studio that I can't find (documented in the PhET-iO design doc user stories). 

(1) Tangent and Area Under Curve features: Hide the movable point
(2) Derived property that calculates the total area under the curve (this is available as the last point of the integrated curve, but make it a nice name for a single point derived property) as an actual value

For (1), I couldn't find the ability to do this. I would say even enabledProperty would be fine if we can't do visibleProperty for that scrubber handle. @pixelzoom is this possible? 

For (2) The y-value of the integral does this, but there was a request for a nicely named derived property. @kathy-phet is this still necessary? I'm wondering if we can just include this in examples.md.

**Comment by veillette** [comment]
@amanda-phet : Regarding your second request, we currently have, under `areaUnderCurveScrubber`, an `areaUnderCurveProperty' (which merely points to `yIntegralProperty`. CM and I added this in case someone may be confused about the naming convention.
 
Is it sufficient? or do you want a different name for the property, or a different location in tree structure.

![image](https://user-images.githubusercontent.com/7633344/224788419-a10ba81f-da77-4507-9d74-11e397765e6c.png)

**Comment by amanda-phet** [comment]
Regarding (2) I found the linked property, and @kathy-phet and I discussed and think that's fine.

**Comment by veillette** [comment]
For the first request, you are right that it is not instrumented. We need to instrument the visibilityProperty of PlottedPoint.
```js
  /**
   * Adds a PlottedPoint to this GraphNode.
   */
  public addPlottedPoint( curvePointProperty: TReadOnlyProperty<CurvePoint>,
                          fill: TColor, visibleProperty: TReadOnlyProperty<boolean>,
                          tandemName: string ): PlottedPoint {
    const plottedPoint = new PlottedPoint( curvePointProperty, this.chartTransform, {
      visibleProperty: visibleProperty,
      fill: fill,
      tandem: this.tandem.createTandem( tandemName )
    } );
    this.curveLayer.addChild( plottedPoint );
    return plottedPoint;
  }
```

I think this is more in @pixelzoom wheelhouse.

**Comment by amanda-phet** [comment]
Is plottedPoint the scrubber handle? Because what we want to achieve here is that the vertical line is visible, but not movable. So, that could be achieved by hiding the scrubber handle or making it not enabled.

**Comment by veillette** [comment]
No, thanks for clarification. I thought you meant the small dotted point that appears on the derivative or integral graph. I now understand the request.

**Comment by pixelzoom** [comment]
Re:
> (1) Tangent and Area Under Curve features: Hide the movable point

So we've established that "movable point" means the scrubber handle.  

Scrubber handles are currently opting out of `visibleProperty` instrumentation.  In ScrubberNode.ts:

```
     phetioVisiblePropertyInstrumented: false
```

I did this intentionally because the scrubber handles are shown in the checkbox icons, and we do not instrument icons (let alone pieces of icons).  So if we allow the scrubber handles to be hidden, we have a problem with the icons.

I recommend that we not do this until someone asks for it.  @amanda-phet thoughts?

**Comment by pixelzoom** [comment]
As a compromise, we could instrument `tangentScrubber.handleNode.inputEnabledProperty` and `areaUnderCurveScrubber.handleNode.inputEnabledProperty`, which would allow the client to disable input, so that the scrubbers can't be moved.  I hestitate to even suggest this, and recommend to wait until someone asks for it.

**Comment by pixelzoom** [comment]
We could also instrument `tangentScrubber.handleNode.visibleProperty` and `areaUnderCurveScrubber.handleNode.visibleProperty`, then live with the checkbox icons being incorrect.  The screenshot below show how this would look for tangent scrubber.  I can't say that I like this.

<img width="750" alt="screenshot_2418" src="https://user-images.githubusercontent.com/3046552/224874932-c8b2abb3-ffff-459b-93aa-8a7a7df34c84.png">

**Comment by pixelzoom** [comment]
Another option would be to instrument these Properties for scrubbers:

```
tangentScrubber.handleNode.visibleProperty
areaUnderCurveScrubber.handleNode.visibleProperty
```

... and these Properties for the associated checkboxes:

```
tangentCheckbox.icon.visibleProperty
areaUnderCurveCheckbox.icon.visibleProperty
```

And make the client responsibile for hiding the scrubber handles and checkbox icons separately (to be noted in examples.md).

And I'm still not sure how this issue aligns with this statement that PhET recently adopted:

>  Our PhET-iO Design philosophy centers around reducing the time to production, largely through avoiding overly specific, “nit-picky” work that yields disproportionate value. Above all we focus on client-driven needs and feedback.

**Comment by amanda-phet** [comment]
Looks great! Since we discussed including these in examples.md, can you also feature `tangentScrubberNode.handleNode.visibleProperty` and `areaUnderCurveScrubberNode.handleNode.visibleProperty`?

**Comment by pixelzoom** [comment]
Done, back to @amanda-phet for review.  Search in Studio for  `handleNode.visibleProperty`.  You'll find 2 instances, and they are both featured.

**Comment by amanda-phet** [comment]
Looks great. Thanks!
