### ISSUE TITLE
CurveManipulationWidthSlider PointerArea along track seems too small

### ISSUE THREAD

**Issue by marlitas** [phetsims/calculus-grapher#282]
For https://github.com/phetsims/calculus-grapher/issues/268, I was examining the sim with `showPointerAreas` and noticed that I received a pointer along a very narrow portion of the track, so narrow that it would rapidly flip between cursor and pointer. This seems buggy, and may be a problem with Slider, as I did not see code in CurveManipulationWidthSlider that dictated pointer area. 

https://user-images.githubusercontent.com/42476338/224839893-5f7ba058-1383-4bae-8b50-9eafe62c5915.mov

**Comment by pixelzoom** [comment]
The default Slider track is sized via `SliderOptions.trackSize`, and the cursor changes only when it's over the track. There's currently no option for dilating the default track's pointer area.

CurveManipulationWidthSlider.ts is setting a very narrow `trackSize`, which explains the behavior that you're seeing:

```ts
      trackSize: new Dimension2( 100, 1 ),
```

If I make this change:

```diff
-      trackSize: new Dimension2( 100, 1 ),
+      trackSize: new Dimension2( 100, 3 ),
+      trackFillEnabled: 'black',
```

then the track looks too "heavy":

<img width="202" alt="screenshot_2417" src="https://user-images.githubusercontent.com/3046552/224868945-a0823f0e-599a-4c34-8347-85bc17346948.png">

I'll investigate adding options for dilation of track pointer areas to SliderOptions.  But I'm hesitant to add more complexity to Slider, especially for a feature like this that I suspect is seldom used/discovered.

**Comment by pixelzoom** [comment]
Adding options to Slider is not going to happen, see gory details in https://github.com/phetsims/sun/issues/836.

My recommendation is "won't fix" for Calculus Grapher. But I'll let @amanda-phet make the final call. To summarize:

* The slider track in Calculus Grapher is very narrow, but looks good.  But that means that's it difficult to click in the track.
* Making the slider track wider makes it look too heavy, and is not really much of an improvement on being able to click in the track.
* Adding options to Slider to adjust the tracks pointer areas is a major project, so it's not going to happen for Calculus Grapher.
