### ISSUE TITLE
Checkbox text labels handling large dynamic strings differently

### ISSUE THREAD

**Issue by marlitas** [phetsims/calculus-grapher#283]
From https://github.com/phetsims/calculus-grapher/issues/268.

One seems to be limiting based on a maxTextWidth and another seems to be using multiple lines in Rich Text to overflow the large string. This is probably due to the fact that "Reference Line" has a space in the string which allows it to be added onto a new line.

 I'm unsure how frequently we would run into this situation, but it seemed visually bizarre enough to create an issue to put eyes on it.

<img width="203" alt="Screenshot 2023-03-13 at 2 56 34 PM" src="https://user-images.githubusercontent.com/42476338/224841825-f738103c-d181-4af2-9575-29fe0d50f31e.png">

**Comment by marlitas** [comment]
In the advanced and lab screens I also noticed the grid checkbox icon is colliding into the menu bar.

<img width="665" alt="Screenshot 2023-03-13 at 3 11 19 PM" src="https://user-images.githubusercontent.com/42476338/224843718-43acd2cb-8f3f-4965-8bda-6519cf9d1751.png">

**Comment by pixelzoom** [comment]
TangentLineCheckbox, AreaUnderCurveCheckbox, and ReferenceLineCheckbox are in fact handling their strings identically -- they all use RichText, and allow the client to use whatever markup they want.  If you were to check "Tangent" to "Tangent<br>Line" in calculus-grapher-strings_en.json, you'd see that it behaves the same as the other checkboxes:
 
<img width="208" alt="screenshot_2414" src="https://user-images.githubusercontent.com/3046552/224865190-44eeb25a-fd46-4f5b-8bb0-6665dc0bfd00.png">

Or change "Reference<br>Line" to "Reference Line", and you'll see:

<img width="214" alt="screenshot_2415" src="https://user-images.githubusercontent.com/3046552/224865287-450110b9-61b7-494f-9978-f14a37f4eed7.png">

Using RichText anywhere in a sim does bring up the possibililty that the string height (not just its width) may become problematic.  Maybe it's a bad assumption, but we assume that translators tests their work, and would notice a case like https://github.com/phetsims/calculus-grapher/issues/283#issuecomment-1467039462.  But as a bit of defensive programming, I've added `maxHeight` to the RichText checkbox labels in the above commits.

Back to @marlitas for review, close if OK.

**Comment by marlitas** [comment]
Looks much better and feels like a better safe guard. Closing!
