### ISSUE TITLE
"Smooth" button does not adjust width with dynamic strings

### ISSUE THREAD

**Issue by marlitas** [phetsims/calculus-grapher#284]
For https://github.com/phetsims/calculus-grapher/issues/268

In the advanced and lab screens, the smooth button does not dynamically size with the width of the string. It seems the text should also get a maxWidth as it creates other layout issues when the string becomes too long. 

<img width="793" alt="Screenshot 2023-03-13 at 3 09 44 PM" src="https://user-images.githubusercontent.com/42476338/224843336-cfb25ccd-360e-481d-ab0c-791b3c7276fe.png">

**Comment by pixelzoom** [comment]
Fixed in the above commit, screenshot below with `?stringTest=dynamic`.  Back to @marlitas to review, close if OK.

<img width="164" alt="screenshot_2413" src="https://user-images.githubusercontent.com/3046552/224864302-992fa968-7638-4830-93a0-eb1a129d1e31.png">

**Comment by marlitas** [comment]
looks good. Closing!
