### ISSUE TITLE
Improve icons and layout for curve-manipulation radio buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#286]
While working on #251, I have to say that I'm not really satisfied with the curve-manipulation icons that appear on the radio buttons.  It's difficult to clearly differentiate between the shapes, so they are not as usable as they could be.  And this is because the icons are wide, and not very tall,  For example, the difference between "hill" and "triangle" (top 2 buttons) is not crystal clear, and 2/3 of each icon is a horizontal line:

<img width="128" alt="screenshot_2419" src="https://user-images.githubusercontent.com/3046552/224878455-b1a79ec4-db5e-4fb0-b977-640302d07bdb.png">

I realize that the icons are shaped like this because the radio buttons are arranged in a vertical layout.  What if the buttons were in a 2-column grid, so that the icons could be taller, and you could really see how their shapes differ?  Here's a sketch of what I had in mind for the Advanced and Lab screens.  The icons here are intentionally caricatures, so they clearly tell the user what they do. Compare them to the icons in the screenshot above - which do you think are clearer?

<img width="299" alt="screenshot_2420" src="https://user-images.githubusercontent.com/3046552/224879718-4c578d55-0a8b-4749-99aa-4bea95ae5c10.png">

@amanda-phet @veillette thoughts?

**Comment by pixelzoom** [comment]
There is precedence for arranging radio buttons in a grid.  See Vector Addition:

<img width="261" alt="screenshot_2421" src="https://user-images.githubusercontent.com/3046552/224880917-89011773-b641-4b07-89c5-239ee9511fb1.png">

**Comment by veillette** [comment]
The flash version of calculus grapher had a grid layout.

**Comment by pixelzoom** [comment]
Thanks for pointing that our @veillette.  I played with the Flash version -- those icons are so much more effective.

**Comment by pixelzoom** [comment]
Thinking more about why I haven't been satisfied wtih the current icons...  Good icons consisely sumarize what they represent, without extraneous/redundant information.  And for radio buttons, icons emphasize the differences between choices.  In the screenshot below, I've put a red rectangle around the portion of the current icons that meets those criteria.  Rr the top 4 radio buttons (hill, triangle,...) about 2/3 of the icon is not relevant to how that mode differs from other modes.  So we're not making good use of the space on our buttons, because most of the information is not useful.  The Flash version is much more effective, and meets the criteria for good icons.

<img width="212" alt="screenshot_2423" src="https://user-images.githubusercontent.com/3046552/225026314-e280b2b7-d213-4f99-9729-9adddc9fa3b7.png">

**Comment by pixelzoom** [comment]
Thanks for the context @amanda-phet, understood.  I'll get to work on the grid layout.

**Comment by pixelzoom** [comment]
We'll need to decide how the grid layout should change when the PhET-iO client makes one or more radio buttons invisibile. @amanda-phet if you have thoughts on this, please comment.  Otherwise I'll proceed with what I think is best -- which is to keep all cells in the grid populated, and populate those cells in row-major order (left-to-right, top-to-bottom).

**Comment by amanda-phet** [comment]
>Otherwise I'll proceed with what I think is best -- which is to keep all cells in the grid populated, and populate those cells in row-major order (left-to-right, top-to-bottom).

That's what I would say to do, too. Thanks!

**Comment by pixelzoom** [comment]
This was pretty easy to change -- well done @veillette for making this so flexible!

There's one thing that I could use @veillette's assistance with.  I can't seem to vertically center the icons for sinusoid, tilt, and shift -- they are a bit below center.  See screenshot below. @veillette ideas?

<img width="215" alt="screenshot_2426" src="https://user-images.githubusercontent.com/3046552/225160470-dabe2768-39c6-44d0-93f8-ab7cc1d73a1f.png">

**Comment by pixelzoom** [comment]
Making this temporary change in CurveManipulationIconNode.ts:

```diff
-    const chartRectangle = new ChartRectangle( chartTransform );
+    const chartRectangle = new ChartRectangle( chartTransform, {
+      stroke: 'red'
+    } );
```

... I see what the problem is.  It's the unstroked/unfilled ChartRectangle that is contributing to the bounds:

<img width="197" alt="screenshot_2428" src="https://user-images.githubusercontent.com/3046552/225162012-bd1e4f9a-d681-49da-b9af-6a9d4d982fe7.png">

**Comment by pixelzoom** [comment]
@veillette assisted me with getting the icons centered.  Here's end the result:

<img width="1200" alt="screenshot_2429" src="https://user-images.githubusercontent.com/3046552/225179805-a98b8fc2-24d0-4ad4-8608-5643d085fe6d.png">

I have tested with Studio, and verified that the grid's layout updates dynmically when the visibleProperty of radio buttons is changed.

I really like this, it feels like a huge usability improvement.  I will still be addressing the 'freeform' icon in #251.  But this is otherwise ready for @amanda-phet to review.

**Comment by pixelzoom** [comment]
Radio buttons are now a bit taller, and they are the same size on all screens.  The screenshot below shows the worst case, the Lab screen with "Predict" preference turned on.  @amanda-phet back to you for review, OK to close.

<img width="1129" alt="screenshot_2438" src="https://user-images.githubusercontent.com/3046552/225686247-feb14afa-f305-47a0-9cec-8082b42a421a.png">

**Comment by amanda-phet** [comment]
These look great! Thanks for making this change.
