### ISSUE TITLE
Implement sine manipulation

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/calculus-grapher#29]
All curve manipulation models have been implemented except for sine.

As of now, there are lots of changes to the behavior of sine for the html5 version. See #3, #4, #5, #8. Because of this, I don't think I will start with the flash implementation of the sine manipulation model.

**Comment by veillette** [comment]
Although there are some issues with the flash implementation, we can use it as a starting point.

**Comment by veillette** [comment]
Tracking the sine implementation in #85. Closing
