### ISSUE TITLE
GraphNode.hasDefaultCurveNode REVIEW comment

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#291]
Related to #288, for discussion about this REVIEW comment in GraphNode.ts:

```ts
  // REVIEW: This naming is a bit confusing, and I first thought a GraphNode had a default curveNode
  // REVIEW: in addition to something else that was provided. Not in place of. It's unclear that the default is
  // REVIEW: a non-interactive curve, rather than a curve which also happens to be non-interactive.
  // REVIEW: perhaps just `hasInteractiveCurveNode`?
  // Whether to create the default CurveNode, which is not interactive
  hasDefaultCurveNode?: boolean;
```

Whether the curve is interactive is really irrelevant in GraphNode; it has no notion of "interaction". What we're trying to describe by this option is whether GraphNode should create the CurveNode that is typically created for a Curve.   Would it help to rename `hasDefaultCurveNode`  to `createCurveNode`, and delete the "which is not interactive" comment, like this?

```ts
  // Whether to create the default CurveNode for the provided Curve
  createCurveNode?: boolean;
```

**Comment by pixelzoom** [comment]
In the above commit, I went ahead and made the change that I suggested above.

Summary, from GraphNode.ts:

```ts
  // Whether to create a CurveNode for the provided Curve.
  createCurveNode?: boolean;
...
  // Optional Node that plots the provided Curve, see SelfOptions.createCurveNode
  private readonly curveNode?: CurveNode;
...
    // Create CurveNode for the provided Curve.
    if ( options.createCurveNode ) {
      this.curveNode = new CurveNode( curve, this.chartTransform, {
...
```

@marlitas if this looks OK to you, please close. Otherwise let's discuss.

**Comment by marlitas** [comment]
Yes, this is much clearer! Thank you. Closing :-)
