### ISSUE TITLE
Inform QA about important queryParameters for dev Test

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#292]
This issue is to remind us to let the QA team to be on the look out for some particular kind of behaviors that were problematic during the development of the simulation. In addition, we would like to inform them of queryParameters that are useful to test and unearth problematic behaviors.

**Comment by veillette** [comment]
An important concept to understand ,for testing purposes, in this simulation,  is a cusp: A cusp or corner in a curve is a sharp turning point. FYI, the concept of cusp is not important for students, and therefore we do not explicitly exposed  cusps to student.
 
The cusps can be highlighted in this simulation through a private QueryParameters: `cuspPoints`.
The are visible as green circles on the f(x) curve below.

![Calculus Grapher screenshot (44)](https://user-images.githubusercontent.com/7633344/225396055-5f33e148-05c4-403e-b209-4c45657cbd90.png)

If the sim code fails to correctly identify cuspPoints, it leads to a failure in the calculation of the derivative. For instance: 
<img src="https://user-images.githubusercontent.com/7633344/225397023-6f091ff9-e63e-4945-9801-17b8827ae5db.png" width =500>

**Comment by veillette** [comment]
A useful queryParameter is `numberOfPoints=400`, where one can put whatever numberOfPoints is deemed appropriate.
By default the sim has 1251.

Testing with a small numberOfPoints can allow the QA team more control over the curve, for testing corner cases.
For instance, the team may want to put the cusps or discontinuities right over the edge of the curve.
![Calculus Grapher screenshot (45)](https://user-images.githubusercontent.com/7633344/225399775-1c63f996-53ad-43c3-bfda-b9088702b9d1.png)

Clearly, decreasing the numberOfPoints increases the discretization of the curve, which is a known side effect.  However, reducing the numberOfPoints has proved to be useful in identifying shortcomings of the simulation.

**Comment by pixelzoom** [comment]
Since dev test was completed, I'm going to close this issue.
