### ISSUE TITLE
Eraser and Undo Buttons have different sizes.

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#296]
![image](https://user-images.githubusercontent.com/7633344/225939292-f6303bc1-f4e5-4ee6-a195-377a83841fb3.png)

**Comment by veillette** [comment]
The height of the eraser is noticeably smaller than the undo button.

**Comment by pixelzoom** [comment]
I'll take this. HBox needs some layout options.

**Comment by veillette** [comment]
I was curious how to fix that. I imagined something much more complicated  
That was an easy fix.
