### ISSUE TITLE
Left and right slopes terminology.

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#298]
In order to calculate the derivative, we introduce the concept of right and left slopes. It is very intuitive what it means but webstorm flags the names are possible bug because it means attaching a right/ left quantity to a y-value. We should refactor the usages of  leftSlope and rightSlope to the mathematically well established idea of forward and backward differences

**Comment by veillette** [comment]
The code inspection on WebStorm no longer flags the variable as a probable bugs. In the documentation , I still refer to the point to the right and left, which would help  established a relationship between forward and backwardSlope.s. 

```js
    // Slope to the left of a point. It may not exist if the point is at the beginning of our curve range
    let backwardSlope: number | null;

    // Slope to the right of a point. It may not exist if the point is at the end of the curve range
    let forwardSlope: number | null;
```

**Comment by veillette** [comment]
Assigning to @pixelzoom to review. Feel free to close if OK.

**Comment by pixelzoom** [comment]
Looks like a nice change to me. Closing.
