### ISSUE TITLE
Sine function overrides tilt

### ISSUE THREAD

**Issue by bryo5363** [phetsims/calculus-grapher#3]
Steps to reproduce
1) open sim
2) click tilt
3) tilt the graph upwards
4) click the sine function
5)click on the line and drag downwards. Notice that there is no more tilt to the function

**Comment by amanda-phet** [comment]
Unassigning and putting on hold until this sim is ported.

**Comment by brandonLi8** [comment]
@amanda-phet is the desired functionality to 'tilt' the sine wave as well? (ie.
![image](https://user-images.githubusercontent.com/42391580/87339075-4ae02a00-c503-11ea-830c-555d0e9dbe17.png)

**Comment by amanda-phet** [comment]
>@amanda-phet is the desired functionality to 'tilt' the sine wave as well? (ie.

Yes. 

When the function gets tilted, some will be out of view. Is that going to work ok? Since we have a boundary around the function, the right side will end up hiding a bit until it is tilted back.

**Comment by brandonLi8** [comment]
> When the function gets tilted, some will be out of view. Is that going to work ok? Since we have a boundary around the function, the right side will end up hiding a bit until it is tilted back.

Sounds good. Doing (attempting) this now.

**Comment by brandonLi8** [comment]
Discussed this at design meeting 7/23/20.

Consensus was to change the functionality of the 'sine' curve to only show 1 or 2 revolutions of sine. The sine curve would act similar to the parabola/triangle curves, where it would add a sine function based on the "width" and then taper off (introduce a sharp point).

We also discussed the tilting of the sine curve and the consensus was to first make the sine curve consistent with the other curves where it would be drawn "upright" then jump upwards/downwards to the rest of the curve.

**Comment by veillette** [comment]
We will implement the behavior agreed upon above. Tracking in #85.
