### ISSUE TITLE
Widening of shape for PEDESTAL and HILL modes

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/calculus-grapher#301]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/921
If you click on a line multiple times, the bump created gets wider each time.
**Steps to reproduce**
1. On the first screen, choose either the bump or square bump option
2. Click above the line to create a bump
3. Click in the same spot again, several times

**Visuals**
![s1](https://user-images.githubusercontent.com/41024075/226459148-cdecc59b-7649-41bf-8234-1a67187f52fe.png)
![s2](https://user-images.githubusercontent.com/41024075/226459158-d096aafe-f524-4033-8dbf-4cdf88be7b69.png)
![s3](https://user-images.githubusercontent.com/41024075/226459166-b7b8b2cb-8aa8-4149-b646-dc84fb355002.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Calculus Grapher‬
URL: https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.25/phet/calculus-grapher_all_phet.html
Version: 1.0.0-dev.25 2023-03-20 03:37:03 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language: en-US
Window: 1536x714
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
@veillette I think we need to communicate the names of the curve manipulation modes to QA.  Maybe via a labeled screenshot?  I think I know what "bump" and "square bump" mean, but it would be preferrable if we all used the same terminology.

**Comment by pixelzoom** [comment]
As for this report... I'm not sure whether this behavior is correct or not.  So I'll defer to @veillette, and possibly @amanda-phet.

**Comment by veillette** [comment]
I added some terminology in  https://github.com/phetsims/qa/issues/921#issuecomment-1476955029

**Comment by KatieWoe** [comment]
Hill and Pedestal is what I meant. Sorry.

**Comment by veillette** [comment]
This is a side effect of putting the listener on the chart rather than the curve. See for instance the old behavior  [version 8](https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.8/phet/calculus-grapher_en_phet.html ) versus the new one [version 9](https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.9/phet/calculus-grapher_en_phet.html) where we can widen the shape.

I think we are all in about putting the listener on the chart rectangle. but I think what I am hearing is that we would still like to have some of the previous functionalities.

**Comment by veillette** [comment]
I stand corrected, this behavior was always present, but beforehand you had to select the curve and release it multiple times, whereas now you can merely click on a point on the chart multiple times, which is much easier to do.
