### ISSUE TITLE
Reference Line's x value should snap to 1 decimal place

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#305]
For https://github.com/phetsims/qa/issues/921 ...

While working on other issues, I noticed that with "Value" preference on, the Reference Line displays only 1 decimal place for the x value. For example:

<img width="194" alt="screenshot_2462" src="https://user-images.githubusercontent.com/3046552/226922588-ae579f4e-340f-4870-86bf-75a45a46305c.png">

But inspecting `tools.referenceLine.xProperty` in Studio, the value is actually `5.496479633520075`.  

So much like sliders, I believe that we should be snapping to 1 decimal place at the end of a drag cycle.  I'm going to go ahead and do this, and confirm later during review. 

Other scrubbers (tangent, area) do not need to be snapped, because they do not display the x coordinate.

**Comment by veillette** [comment]
@amanda-phet stated:
> Yes, I agree the change is a good one (the lack of precision's of the line actually came up in a meeting I was in Friday!) 
> ... I think it is a good change.

**Comment by veillette** [comment]
Unassigning @amanda-phet, I'll test that it is working properly in Studio.

**Comment by veillette** [comment]
I can confirm that the xProperty in Studio snaps to 1 decimal place when the Reference Line scrubber is released.

**Comment by veillette** [comment]
I realized that one downside to this behavior is that the snapping is present even when `values` are not on. As a result, it is not possible to put the reference line at particular point of interest. 

A typical usage of the reference line would be to create a curve, and align the reference line at the maximum of f(x) and observe that derivative curve is zero at this point. The maximum of f(x) is unlikely to be at multiplies of 0.1, so it is slightly off the maximum. (see below where  one cannot quite get the maximum of the integral ). 
![image](https://user-images.githubusercontent.com/7633344/228070526-da82532e-8455-4666-b8f7-ef263915434e.png)

I see two options
- (1) Leave as is. It is a very small offset, barely noticeable.
- (2) Make the snapping conditional: It only snaps the reference line if values are present.

I would vote for two, but I am happy to be outvoted.

**Comment by veillette** [comment]
I thought it would be an easy issue to review and close 😞. Reassigning to @amanda-phet for input.

**Comment by pixelzoom** [comment]
In today's standup meeting, @amanda-phet and @catherinecarter said that they'd like to revert the snapping, and that it's OK that the displayed value and Property value may be slightly different.  I've done that in the above commit.

**Comment by pixelzoom** [comment]
Option (3) is done, closing.  Feel free to have a look in master.
