### ISSUE TITLE
Labeled Points don't stay on line in launched sim

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/calculus-grapher#307]
**Device**
Dell
**OS**
Win 11
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/qa/issues/921
If you turn on Labeled Points in studio, the point stays on your line as you create curves. However, if you launch the sim the point is on the y=0 line no matter where the curve is.
**Steps to Reproduce**
1. Add a point with `model.tools.labeledPoints`
2. Add a curve to the line so that the point is at y /= 0
3. Launch the sim

**Visuals**
![Calculus Grapher screenshot](https://user-images.githubusercontent.com/41024075/227012892-655cccb3-2480-42d2-b37f-6a4206de2a7e.png)

**Comment by veillette** [comment]
Good find.

**Comment by veillette** [comment]
It is worth noting that after launching the sim, if  one moves the original curve, the point D does not update its position, but its label does. The label stays within the vicinity of the point so somehow, it knows about the derivative of the curve, but not the original function.

**Comment by veillette** [comment]
![test](https://user-images.githubusercontent.com/7633344/227037988-76b05b8d-959a-4af0-8ed8-f42fbe58ef49.gif)

**Comment by veillette** [comment]
I don't know if the presence/absence of motion of the labels themselves is a red herring. In all cases, the points themselves stay on the y=0 curve.

**Comment by pixelzoom** [comment]
I haven't investigated yet. But I have a bad feeling about this one.   

Our entire architecture is built on reusing CurvePoint instances, then having `curveChangedEmitter` fire when the user completes an interaction.  But when PhET-iO state is restored, there is no interaction, and therefore no calls to `curveChangedEmitter`.

Furthermore, the order in which state is restored is not something that we control.  And it's often restored in a much different order than would normally occur when using the sim.  I suspect that if we look at other tools, we'll find that their Property values are also not correct.

**Comment by pixelzoom** [comment]
@veillette noted:
> It is worth noting that after launching the sim, on the integral screen, if one moves the original curve, the point C does not update its position, but its label does. The label stays within the vicinity of the point so somehow, it knows about the derivative of the curve, but not the original function.

This is because LabeledPointNode handles the position of the point and its label separately.  Subcomponent PlottedPoint is responsible for updating the point's position, and is not getting notified.   LabeldPointNode is responsible for the label position via `updateLabelPosition`, which is called via a Multilink that is firing properly as the derivative changes at the point.

**Comment by pixelzoom** [comment]
Fixed in the above commit. As I suspected, this issue and https://github.com/phetsims/calculus-grapher/issues/310 were the same underlying problem, shared by all tools. Great find @Nancy-Salpepi! Please verify in master.

**Comment by KatieWoe** [comment]
Looks good in master
