### ISSUE TITLE
Tangent can return to default position in launched sim

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/calculus-grapher#310]
**Test device**
MacBook Air M1 chip

**Operating System**
13.2.1

**Browser**
Safari/FF/Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/921, on the Derivative Screen, after creating a curve on the left side of the graph and turning on Tangent, the Tangent line will be along the curve and not on the x-axis. When I launch the sim, the Tangent is in its default position along the x-axis. 

**Steps to reproduce**
1. On the Derivative Screen, create a curve so that the Tangent, when turned on, will be on the curve.
2. Check the Tangent checkbox.
3. Launch the sim. 

**Visuals**

https://user-images.githubusercontent.com/87318828/227216078-81751452-258d-42ee-8856-d84809c81727.mp4

**Comment by pixelzoom** [comment]
I'll have a look. This is similar to #307 -- a tool that is in the wrong initial position when state is restored.

**Comment by veillette** [comment]
I was able to reproduce. Atter setting the state, I'll note that modifying the curve does not  update the  position of the tangent arrow. However, as soon as one modifies the x-position of the scrubber the tangent arrow updates itself to the correct position.

**Comment by veillette** [comment]
And we can observe the same bug with the phet-io-wrapper.
![image](https://user-images.githubusercontent.com/7633344/227240529-5764e26b-c76e-49c7-8197-0fd9226dc13d.png)

**Comment by pixelzoom** [comment]
Fixed in the above commit. As I suspected, this issue and #307 were the same underlying problem, shared by all tools.  Great find @Nancy-Salpepi!  Please verify in master.

**Comment by Nancy-Salpepi** [comment]
Thanks @pixelzoom! 
This looks good in master now.

**Comment by pixelzoom** [comment]
👍🏻 closing.
