### ISSUE TITLE
Convert Curve `deltaX` from getter to field

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#311]
In Curve.ts:

```ts
  protected get deltaX(): number {
    return this.xRange.getLength() / ( this.numberOfPoints - 1 );
  }
```

Both of the quantities used to compute deltaX are constants, so deltaX is a constant.  So it's preferrable to convert deltaX to `protected readonly deltaX: number` and compute it once in the constructor.   

It's unlikely to make a noticable performance difference.  But `deltaX` is used in loops, like this one in TransformedCurve `smooth`:

```ts
      for ( let dx = this.deltaX; dx <= numberOfStandardDeviations * STANDARD_DEVIATION;
            dx += this.deltaX ) {
```

@veillette any reason why I shouldn't do this?

**Comment by veillette** [comment]
No go ahead.

**Comment by pixelzoom** [comment]
This was relatively trivial, so I'lll go ahead and close.  But @veillette feel free to have a look.
