### ISSUE TITLE
State Wrapper: still currently setting last state, skipping this update (setState) call.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#312]
For https://github.com/phetsims/qa/issues/921 ...

When I run Calculus Graph in the State Wrapper, this console output appears repeatedly, even when not interacting with the sim:

> still currently setting last state, skipping this update (setState) call.

<img width="385" alt="screenshot_2465" src="https://user-images.githubusercontent.com/3046552/227249072-3a11cd2a-c53c-4c46-a2d2-a02a8214b29a.png">

To reproduce:

1. Go to phetmarks
2. Run calculus-grapher in "state" mode
3. Do not interact with the sim. Watch the console, and the above output with begin to be printed to the console repeatedly, at what seems like a regular interval.

This does not occur in built versions https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.25/phet-io/wrappers/state/ or https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.26/phet-io/wrappers/state/.

I also tried a couple of other sims (GAO, CCK-DC) and I don't see this occurring.

**Comment by pixelzoom** [comment]
This message is coming from phet-io-wrappers/state/index.html, and was added by @zepumph in https://github.com/phetsims/phet-io-wrappers/commit/3a0b509860c4888abb4000d3055c865450550036.

**Comment by zepumph** [comment]
You can always trigger this, for example, by setting the "set state rate" down to 10ms. But this "limit" is based on the computer performance, specific sim, etc.

**Comment by zepumph** [comment]
Yeah good questions thanks. I think it has to do with the performance of setting the curves. Isn't it quite extensive to plot the whole thing?

With this patch you can see the "standard" time it takes to set the state of CG:

```diff
Subject: [PATCH] add hasListenerOrderDependencies, https://github.com/phetsims/center-and-variability/issues/143
---
Index: state/index.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/state/index.html b/state/index.html
--- a/state/index.html	(revision 097eea6359a123699ac08e1003f2af1ee0ab3b16)
+++ b/state/index.html	(date 1679599040779)
@@ -182,9 +182,11 @@
     const featuredPhetioIDs = await sourceClient.invokeAsync( 'phetioEngine', 'getFeaturedPhetioIDs', [] );
     const state = await sourceClient.invokeAsync( 'phetioEngine', 'getState', [] );
 
+    const startTime = Date.now();
     // set the state from the source to the destination
     destinationClient.invoke( 'phetioEngine', 'setState', [ state ], () => {
       currentlySettingState = false;
+      console.log( ( Date.now() - startTime ) / 1000, 'seconds to set the state' );
     } );
 
     // update the text with the desired state
```

Without output from me like:
```
2.63 'seconds to set the state'
2.871 'seconds to set the state'
3.012 'seconds to set the state'
2.862 'seconds to set the state'
2.545 'seconds to set the state'
2.699 'seconds to set the state'
2.856 'seconds to set the state'
```

I was getting an average of >2.5 seconds, but the default interval for "how often the upstream sim should be applied to the downstream sim" in the state wrapper is 1 second (the slider control in the state wrapper).


It isn't clear to me that this is something to work on. I think our previously "worst-case" state time was with hundreds of bunnies in NS. Here is the same stat with `introPopulation=700&labPopulation=400`

```
4.057 'seconds to set the state'
3.776 'seconds to set the state'
3.726 'seconds to set the state'
3.428 'seconds to set the state'
3.817 'seconds to set the state'
3.767 'seconds to set the state'
```

**Comment by pixelzoom** [comment]
> It isn't clear to me what could be done to optimize this, or if it should. @pixelzoom can you comment on an idea or two at making this faster?

It looks like we have some very big performance problems that are going to require some redesign.  See https://github.com/phetsims/calculus-grapher/issues/309#issuecomment-1482971390

**Comment by pixelzoom** [comment]
In #309 I made a major performance improvement that makes the sim more responsive and greatly reduces the amount of information in the data stream.  But I'm still seeing this console output.

In https://github.com/phetsims/calculus-grapher/issues/312#issuecomment-1481756846, I asked:
> Questions:
>
> (1) Why is it "still currently setting last state" when the sim is not doing anything, sitting idle? What is "the last state" in this context?
> 
> (2) Why is it doing this over and over? Presumably it should finish setting the "last state" at some point.
> 
> (3) Why is it doing this when Calculus Grapher is idle, but not other sims?

In https://github.com/phetsims/calculus-grapher/issues/312#issuecomment-1481776137, @zepumph replied:
> Yeah good questions thanks. ...

Then he answered (3), but not (1) and (2).   So while I'll likely end up just closing this issue, I'd like @zepumph to answer questions (1) and (2) above, if only to improve my undestanding of PhET-iO and the State Wrapper.

**Comment by pixelzoom** [comment]
@samreid @zepumph @veillette and I discussed remaining questions on Zoom.  We now have a better understanding of the State Wrapper. And we made some improvements to console output in the above commits, which should be useful for PhET and client developers. 

Closing.
