### ISSUE TITLE
Investigate breaking up TransformedCurve into smaller components.

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#317]
Discussed with @pixelzoom on 3/24. `TransformedCurve` is by far the largest class in CG. It is a bit tedious to navigate through some many methods. We should investigate: 
- Can we break into smaller components?
- Can we identify group of components that fit together in a meaningful way. 

Overall, we would like to lessen the cognitive overload and  improve code readability.

**Comment by pixelzoom** [comment]
I messed around with breaking up TransformedCurve.ts, and I think that I'm on to something.  I'm not quite done yet, so haven't commited anything -- and I probably won't until I consult with @veillette.

The basic idea is to factor each out the methods that operate on TransformedCurve.ts into separate "operations" files.   This reduces the size of TransformedCurve.ts to a nice 305 lines.  Here are the files for the operations, and their lines-of-code:

```
      25 ./shift.ts
      27 ./hill.ts
      36 ./parabola.ts
      39 ./triangle.ts
      46 ./tilt.ts
      59 ./pedestal.ts
      77 ./smooth.ts
     133 ./sinusoid.ts
     245 ./freeform.ts
```

This feels very nice to me, and more maintainable.  For example, I can go to freeform.ts and be confident that I'm making changes that only affect the freeform mode.

More to come...

**Comment by pixelzoom** [comment]
I ultimately decided against factoring out "operations" files like I described in https://github.com/phetsims/calculus-grapher/issues/317#issuecomment-1483854099.   

There are a lot of commits above, and most of them are just minor cleanup or documentation.  

To summarize the important changes:

* Renamed manipulation methods to simpler names: `createHillAt` to `hill`, `createTriangleAt` to `triangle`, etc.
* Made all of the  manipulation methods public, and used them directly in CurveManipulationIconNode and CurveManipulationDisplayNode
* Deleted TransformedCurve's `widthManipulationCurve` methods, and called the manipulation methods directly. I understand the intent of `widthManipulationCurve`, and calling directly requires more `if-then-else` clauses, but it reads better I think. 

@veillette if you have questions/concerns, let's discuss on Monday 3/27.  If not, feel free to close.

**Comment by pixelzoom** [comment]
I should note that all of the above only reduced TransformedCurve.ts from 875 to 845 lines.  But I think it was worthwhile, and it feels easier to navigate (for me anyway :)

**Comment by veillette** [comment]
I reviewed the changes above. I like the more iconic name for the methods. I'm fine with not breaking up the operations  into their own class. Closing
