### ISSUE TITLE
`wasManipulatedProperty` is updated prematurely

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#318]
Noticed while working on #317...

In TransformedCurve.ts, `wasManipulatedProperty` is being set prematurely, before the curve has actually been changed. This is not currently a problem, but could be a problem in the future for a listener added to `wasManipulatedProperty`. 

Relevant code:

```ts
public manipulateCurve( ... ) {

    this.wasManipulatedProperty.value = true;

    // ... code that manipulates the curve

    this.curveChangedEmitter.emit();
}
```

This can be addressed by relocating the `wasManipulatedProperty.value` assignment to just before the call to `curveChangedEmitter.emit`.

**Comment by pixelzoom** [comment]
Done in the above commit. @veillette please review, close if OK.

**Comment by veillette** [comment]
Some good defensive programming.  Closing
