### ISSUE TITLE
Revisit the display for "shift" mode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#319]
When you select the "shift" mode, the control panel looks like this:

<img width="169" alt="screenshot_2474" src="https://user-images.githubusercontent.com/3046552/227785872-404539a4-ff7c-479c-ac43-d87bd112bd4f.png">

The amount of empty space here has always bothered me a bit.  An easy change would be:

<img width="172" alt="screenshot_2473" src="https://user-images.githubusercontent.com/3046552/227785897-888aea0b-d330-419f-9d70-17a5b06081c6.png">

But maybe there's a pedagogical reason for why the icon is the way that it currently is. @amanda-phet @veillette your opinion?

**Comment by pixelzoom** [comment]
If we do want to change this, the change is in CurveManipulationDisplayNode.ts:

```diff
        else if ( mode === CurveManipulationMode.SHIFT ) {
-         curve.shift( xMax, yMax );
+         curve.shift( xMax, yMin );
        }
```

**Comment by veillette** [comment]
I think it was an oversight. Given that the slider disappears in SHIFT mode, it looks better at the yMin position.

**Comment by amanda-phet** [comment]
this looks better to me, to make this change.

**Comment by veillette** [comment]
Done in the commit above. Here is the new look! (Ignore the red outline, I was using the ?dev queryParameter)

 ![image](https://user-images.githubusercontent.com/7633344/227997774-5b89a86d-1ec5-4c74-88dc-9ce270cc71df.png)

Assigning to @pixelzoom  to review. Feel free to close.
