### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#321]
We'll need screenshots before we can publish 1.0.0.   The screenshots will need to be committed to master, then cherry-picked to calculus-grapher 1.0 branch.

**Comment by veillette** [comment]
We should wait until #333, #332 issues are resolved (as they affect the look of the sim) as well as knowing if we change the preference icon changes before we take the screenshots.

**Comment by veillette** [comment]
The issues #332 and #333 have been addressed. The commits for the two issues are on master and have been cherry-picked for the RC branch.

At this point, we are only awaiting for the decision about changing the preference icon/ tab dialogue order in JOIST.

**Comment by veillette** [comment]
The cog icon was updated in joist ( https://github.com/phetsims/joist/issues/919) in master. There is nothing holding back this issue.

**Comment by veillette** [comment]
The commit was cherry picked for the RC 1.0  branch.

**Comment by veillette** [comment]
Sorry QA, but there is really nothing to check as the screenshots are not bundled in the simulation.

**Comment by Nancy-Salpepi** [comment]
There are 4 png files. 
Closing
