### ISSUE TITLE
Create dev versions for Preferences interviews

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#324]
In Slack#calculus-grapher, @amanda-phet wrote:

For our mini-sprint on preferences, @catherinecarter and I need 6 versions of CG :scream: Our plan is to do guerrilla interviews on campus Monday so we can get the results back to the team asap.

* Preferences icon is [user-gear](https://fontawesome.com/icons/user-gear?f=classic&s=solid) (current icon, so we could use RC.1)
* Preferences icon is [gear](https://fontawesome.com/icons/gear?f=classic&s=solid)
* Preferences icon is [wrench](https://fontawesome.com/icons/wrench?f=classic&s=solid)
* Preferences icon is [user-gear](https://fontawesome.com/icons/user-gear?f=classic&s=solid), Preferences dialog is open to the Simulation tab
* Preferences icon is [gear](https://fontawesome.com/icons/gear?f=classic&s=solid), Preferences dialog is open to the Simulation tab
* Preferences icon is [wrench](https://fontawesome.com/icons/wrench?f=classic&s=solid), Preferences dialog is open to the Simulation tab

There isn’t a rush on this since we won’t use this until Monday (4/3/23), so by end of Friday (3/31/23) would be great!

**Comment by pixelzoom** [comment]
@amanda-phet How would you feel about 1 dev version, with 2 query parameters  — for selecting the icon and initial tab.  Something like: `?icon=wrench&tab=sim`

**Comment by pixelzoom** [comment]
For joist, I'd like to add something permanent to PreferencesModel that allows sims to specify the initial tab (default to 'Overview'), then use that in calculus-grapher.

**Comment by amanda-phet** [comment]
>@amanda-phet How would you feel about 1 dev version, with 2 query parameters — for selecting the icon and initial tab. Something like: ?icon=wrench&tab=sim

Query parameters sound great! Much better than lots of dev versions. 

>For joist, I'd like to add something permanent to PreferencesModel that allows sims to specify the initial tab (default to 'Overview'), then use that in calculus-grapher.

That sounds perfect. I think others have already talked about wanting this option.

**Comment by pixelzoom** [comment]
Here's another way to temporarily set the initial tab to Preferences:

```diff
Subject: [PATCH] lint fix
---
Index: js/preferences/PreferencesDialog.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/preferences/PreferencesDialog.ts b/js/preferences/PreferencesDialog.ts
--- a/js/preferences/PreferencesDialog.ts	(revision 994b74079bd91e46ebf226898b6be70153a9f9be)
+++ b/js/preferences/PreferencesDialog.ts	(date 1680117891191)
@@ -87,8 +87,10 @@
     preferencesModel.supportsLocalizationPreferences() && supportedTabs.push( PreferencesType.LOCALIZATION );
     assert && assert( supportedTabs.length > 0, 'Trying to create a PreferencesDialog with no tabs, check PreferencesModel' );
 
+    const initialTab = supportedTabs.includes( PreferencesType.SIMULATION ) ? PreferencesType.SIMULATION : PreferencesType.OVERVIEW;
+
     // the selected PreferencesType, indicating which tab is visible in the Dialog
-    const selectedTabProperty = new EnumerationProperty( PreferencesType.OVERVIEW, {
+    const selectedTabProperty = new EnumerationProperty( initialTab, {
       validValues: supportedTabs,
       tandem: options.tandem.createTandem( 'selectedTabProperty' )
     } );
```

**Comment by pixelzoom** [comment]
The links that @amanda-phet provided in https://github.com/phetsims/calculus-grapher/issues/324#issue-1646359595 are to icons in FontAwesome 6.4.0.   PhET has version 5.15.2.   It looks like 6.4.0 uses "gear", while 5.15 used "cog".  So the query parameter values are going to be different, to correspond to the fontawesome file names.

icon = 'userCog' (default) or 'cog' or 'wrench'
tab = 'overview' (default) or 'sim'

**Comment by pixelzoom** [comment]
@amanda-phet and I reviewed via Zoom before I committed.  The 'cog' icon feels a little heavy, but it's what we have, and it's acceptable for interviews.  And if the 'cog' is what we settle on, we can certainly create our own cog icon, as PhET has done for some of the other buttons in the navigation bar. 

In the above commits, I made the changes, published a dev version, then reverted the changes.

Published in [1.1.0-dev.1](https://phet-dev.colorado.edu/html/calculus-grapher/1.1.0-dev.1/phet/calculus-grapher_all_phet.html), ready for review by @amanda-phet @catherinecarter.

**Comment by pixelzoom** [comment]
@amanda-phet and @catherinecarter are planning to do interviews on Wednesday 4/5.

**Comment by catherinecarter** [comment]
It's ok with me to close. We'll discuss interview results after Wednesday.

**Comment by amanda-phet** [comment]
OK to close this, yes. We will be sharing results with Taliesin and Brett on Monday 4/10/23 and will make issue(s) in Joist.
