### ISSUE TITLE
`pointsProperty` needs a warning in examples.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#326]
For https://github.com/phetsims/qa/issues/924 ... 

While working on #325, I remembered something important that we did not add to examples.md.  In the **Load premade curve into a wrapper** subsection, we need a warning that goes something likes this:

> **NOTE!** When setting the value of `pointsProperty`, (1) use only a value that you got using the "Get Value" button in Studio, and (2) do not edit/change the value that you got using the "Get Value" button.  If you violate these conditons, the simulation may behave incorrectly. 

@amanda-phet may I add this to examples.md?  Or would you like to wordsmith? 

@veillette FYI.

**Comment by pixelzoom** [comment]
@amanda-phet would like to wordsmith.  Please make changes directly to example.md in master. Then assign back to me to cherry-pick to the 1.0 branch.

**Comment by amanda-phet** [comment]
I think the documentation in the phetioDocumentation gets the point across that these values shouldn't be editable (by saying they are not intended to be human-readable). 

Here's what I am thinking of adding to the examples.md doc: 

>Note: When setting the value of pointsProperty, (1) use only a value that you got using the "Get Value" button in Studio, and (2) do not edit/change the value that you got using the "Get Value" button. The value of `pointsProperty` is very large and not intended to be human-readable. Manually creating or editing the value may cause the simulation may behave incorrectly.

**Comment by pixelzoom** [comment]
There's some bad grammar in this sentence:

> Manually creating or editing the value may cause the simulation may behave incorrectly.

**Comment by amanda-phet** [comment]
That is a typo. How is this? 

>Note: When setting the value of pointsProperty, (1) use only a value that you got using the "Get Value" button in Studio, and (2) do not edit/change the value that you got using the "Get Value" button. The value of pointsProperty is very large and not intended to be human-readable. Manually creating or editing the value may cause the simulation to behave incorrectly.

**Comment by pixelzoom** [comment]
That looks good to me. @amanda-phet would you like to add to example.md, or would you like me to do it?  If you'd like me to do it, where would you like me to insert it?

**Comment by pixelzoom** [comment]
Cherry-pick was done in the above commits. Ready for verification in the next RC.  

To verify:

1. Go to the Index Wrapper
2. Click on the "Examples" link
3. Verify that that the section titled **Load premade curve into a wrapper** ends with this paragraph:

```
Note: When setting the value of pointsProperty, (1) use only a value that you got using the "Get Value" button in Studio, and (2) do not edit/change the value that you got using the "Get Value" button. The value of `pointsProperty` is very large and not intended to be human-readable. Manually creating or editing the value may cause the simulation to behave incorrectly.
```

**Comment by Nancy-Salpepi** [comment]
This looks good in the examples.md doc! Closing.
