### ISSUE TITLE
Document the absence of curve instrumentation in  CurveManipulationIconNodes and CurveManipulationDisplayNode

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#328]
One concern that I can bring is the amount of Curves and TransformedCurves that we currently have.  The curve display above the slider as well as the curve icons create instances of TransformedCurves (see `CurveManipulationIconNodes` and `CurveManipulationDisplayNode`. Currently, we explicitly OPT_OUT of instrumenting these curve models.

However, if in a future, a designer would request to instrument, say the icons, to create a different set of icons, this would have very consequential performance implications, which may not be apparent at first sight. (see #312 and #309)

We should have some very explicit documentation about the instrumentation of `TransformedCurve` in  `CurveManipulationIconNodes` and `CurveManipulationDisplayNode`

**Comment by pixelzoom** [comment]
Add doc in CurveManipulationDisplayNode.ts and CurveManipulationIconNode.ts:

```
// If you decided to instrument in the future, be aware that it has performance implications. Proceed with caution!
tandem: Tandem.OPT_OUT
```

**Comment by pixelzoom** [comment]
Pushed to master, cherry-picked to 1.0 in the above commits. Inspected the commit in the 1.0 branch in GitHub. Since this was exclusively code comments, there's nothing else to verify. Closing.
