### ISSUE TITLE
Patch memory leak in Disposable.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#330]
For https://github.com/phetsims/qa/issues/924

While reviewing https://github.com/phetsims/scenery-phet/issues/769, @zepumph and I discovered a relatively serious memory leak in Disposable, which is the base class for (among other things) PhetioObject.

From https://github.com/phetsims/scenery-phet/issues/769#issuecomment-1495060141, the line added in this diff is missing, so `disposeEmitter` listeners are not freed.

```diff
  public dispose(): void {
    assert && assert( !this.isDisposed, 'Disposable can only be disposed once' );
    this._disposeEmitter.emit();
+   this._disposeEmitter.dispose();
    this.isDisposed = true;
  }
```

In calculus-grapher, we use `disposeEmitter` througout GraphTypeLabelNode, which appears as labels for the Notation radio buttons appears in the Preferences dialog: _f'(x)_, _f'(t)_, _df/dx_, _df/dt_.  An example from GraphTypeLabelNode is:

```ts
  label.disposeEmitter.addListener( () => {
    labelStringProperty.dispose();
  } );
```

In Slack#DM, I asked @zepumph about the above example:
> There’s no handle to the listener function, but` labelStringProperty` is included by closure. Is this going to be a leak? Should we patch in calculus-grapher 1.0 ? 

... and he replied:

> Patching the Branch seems prudent.

So I'm going to proceed with patching calculus-grapher 1.0, to be tested in the next RC.

@veillette @amanda-phet FYI.

**Comment by zepumph** [comment]
The commit to cherry pick is https://github.com/phetsims/axon/commit/022433795034acf606ba510330a7495d1d56702a

**Comment by pixelzoom** [comment]
Cherry-picked and patches into axon's 'calculus-grapher-1.0' branch.

To verify in the next RC, repeat memory testing and compare to the results for the previous RC that are shown in https://github.com/phetsims/qa/issues/924#issuecomment-1487547110.

**Comment by KatieWoe** [comment]
Memory looks ok to me.
<img width="335" alt="cgmem" src="https://user-images.githubusercontent.com/41024075/232162691-46974018-3c31-46e6-bb48-0e7f52cf1f97.png">
