### ISSUE TITLE
Sinusoid Icon 

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#333]
We have made some changes to the sinusoid mode in the most recent devs (see #302).  As a result, the sine function has now a much wider width than it used to. We have not updated the icon to reflect this change.

![image](https://user-images.githubusercontent.com/7633344/229933711-0f4f244d-5572-4f4b-b448-ca5da7ffd823.png)

I would propose to make the sinusoid icon more iconic by showing the classic sine function with one full wavelength.

**Comment by veillette** [comment]
I created a patch for my suggestion.
<details>
<summary> Patch for sine icon </summary>

````js
Subject: [PATCH] maintain aspect ratio of CurveManipulationDisplayNode (see #332)
---
Index: js/common/view/CurveManipulationIconNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/CurveManipulationIconNode.ts b/js/common/view/CurveManipulationIconNode.ts
--- a/js/common/view/CurveManipulationIconNode.ts	(revision bfc57fb9a751928743dafd9d53939ff7ccc218d7)
+++ b/js/common/view/CurveManipulationIconNode.ts	(date 1680647276276)
@@ -86,10 +86,10 @@
     else if ( mode === CurveManipulationMode.SINUSOID ) {
 
       // Ad hoc variables to create sine function
-      const sinusoidWidth = 0.08 * xLength;
+      const sinusoidWidth =
+        CalculusGrapherConstants.CURVE_MANIPULATION_WIDTH_RANGE.defaultValue * xLength / ( 2 * Math.PI );
       const y = 0.5 * yMax;
-      solidCurve.sinusoid( sinusoidWidth, xCenter, y );
-      solidCurve.save();
+      solidCurve.sinusoid( sinusoidWidth, xLength / 4, y );
       solidCurve.shift( xMin, yCenter );
     }
     else if ( mode === CurveManipulationMode.FREEFORM ) {

````
</details>

It would look like below. It is a little bit less busy and more in line with the other icons. The periodicity of the sine function is no longer apparent in the icon, but students should recognize a sine function with only one period.

<img src="https://user-images.githubusercontent.com/7633344/229936662-dde0b212-c6be-479e-8880-906195bc0a1a.png" width=200>

**Comment by pixelzoom** [comment]
This looks great.  I think it would be a nice improvement.

**Comment by veillette** [comment]
Assigning to @amanda-phet to decide if this is worth implementing.

**Comment by veillette** [comment]
Raising the priority. @amanda-phet it would be to know if we should cherry-pick this as for CG, or you have objections/suggestions to this proposal.

**Comment by amanda-phet** [comment]
This looks great to me, too! And is related to a question @KatieWoe asked me about, so I like it.

**Comment by veillette** [comment]
Thanks @amanda-phet. I'll commit the patch to  master then.

**Comment by veillette** [comment]
The patch was committed to master.

**Comment by veillette** [comment]
Above, the commit on master was cherry-picked on the RC branch 1.0.

**Comment by veillette** [comment]
To verify in the next RC:

In PhET brand, verify that:

- [ ] There is a single wavelength for the sinusoid icon on the third and fourth screen.

**Comment by Nancy-Salpepi** [comment]
Looks nice in rc.2! Closing
