### ISSUE TITLE
Cherry pick JOIST change of COG for 1.0 branch.

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#334]
Commits are complete over in https://github.com/phetsims/joist/issues/919. We just need to cherry pick:

https://github.com/phetsims/joist/commit/2eda3a488258038df60b6e7d3e4c933b5e1ff0e1

**Comment by veillette** [comment]
I talked to @samreid about the fact that the dependencies file for the RC includes
```diff
"axon": {
    "sha": "d32f61ce72b42cc86083b997d592136038c09ad0",
-    "branch": "calculus-grapher-1.0"
+    "branch": "HEAD"
  },
```

We were not clear about why cherry-picking something in JOIST should lead to a change in AXON.


@samreid pointed out that the SHA in AXON remains the same, and therefore was not too worry about the change of branch. 
He suggested I seek a second opinion.

@chrisklus who is currently doing the same process for Number-play was also puzzled but also concurred with @samreid. As a sanity check, he found out that the dependencies of number play point to the Head branch as well even for repos that had been cherry picked.   So that seems part of the standard process.

**Comment by veillette** [comment]
For the RC spot check, please check that  the cog icon on the preference menu shows up correctly.
Test the following platforms:
- [ ] chrome
- [ ] safari
- [ ] firefox

**Comment by Nancy-Salpepi** [comment]
This looks good with:
mac + safari/chrome
Win10 + chrome/FF
iPad + safari

Closing
