### ISSUE TITLE
Calculus Grapher postmortem

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#336]
For Calculus Grapher postmortem, occurring on 5/17/2023.

 - [x]  **1. Schedule the meeting**
 - Require the entire sim team to participate, and optionally anyone else who had a significant involvement. Have the meeting as soon as possible after the sim is released, so that experiences are still fresh in everyone's mind. Allow sufficient time for the meeting, 1.5-2 hours.

 - [x]  **2. Enlist a meeting moderator**
 - The moderator's job is to make sure the meeting runs efficiently, stays on point, and focuses on constructive (but
   not overly negative) criticism. The moderator can be someone not on the sim team, or in many cases the Development Coordinator. The moderator also documents the important points of the meeting.

> @marlitas 

 - [x]  **3. Create github postmortem issue and postmortem google doc**
 - Create a github issue in the repository of the sim for which the postmortem is occurring. This checklist will should be copied into the issue.
 - Create a postmortem google doc for the sim and set phethelp as the owner. This google doc should live within the appropriate sim folder on google drive.
 > https://docs.google.com/document/d/1aMAv6QI5lI6f_H6DnV7utVgPs3NgXmKSnDTpC6tXaqg/edit#

 - [x]  **4. Two successes and two improvements**
 - Require participants to bring a list of no more than 2 items that were done well during the project and no more than 2 items that could be improved upon. Limiting to 2 requires people to think critically about their experience.

 - [ ]  **5. Identifying the top five**
 - At the meeting, start by having each person present their items (successes, then improvements). Make a list of these items, and note duplicates. Based on popularity, identify the top 5 success items and the top 5 items that need improvement.
  * Discuss the 5 success items first. Identify specific things that can be applied to future sims. Celebrate, pat each other on the back. Then move on to the harder part.
  * Discuss the 5 improvement items. Try to avoid getting personal. Discuss what was learned, and identify specific things that can be done to prevent these problems in the future. If anything needs more investigation, assign to specific individuals.

 - [ ]  **6. Modifications to Look & Feel** 
 - Identify modifications to the PhET Look-&-Feel Guidelines. If applicable, based on what we learned during development of this sim, suggest revisions to the guidelines.
  * [HTML5 Look and Feel](https://docs.google.com/document/d/1Fg4E6VNMsnId7CjsyqHKnZeIoQ4N-5ezM9PTkj7N3PM/edit)
  * [HTML5 Visual Sim Design Elements
](https://docs.google.com/document/d/1rpp0vT7-bGUs_5tZP_77-HM8PnaGbIDQ5DGNygX5CBo/edit)

- [ ]  **7. Sim checklist** 
- Review the [Sim Checklist](https://github.com/phetsims/phet-info/blob/master/checklists/sim-checklist.md) 

- [ ]  **8. Action items** 
- Note important items in the postmortem github issue, and create issues for any tasks the require action (such as updating documents, leftover "todo's", etc. 

- [ ]  **9. Take home messages** 
- From the top 5 successes/improvements, decide what are the "take home messages" that would be useful to note in the future, and add these to the [HTML5 Postmortem Take Home Messages](https://docs.google.com/document/d/1hayLX0FbhYqGao-5xizAFU9kVBzqrW_RVX88Wk_C_Lc/edit#heading=h.krbf2d24bpav) google doc
- Report out at status meeting

**Comment by amanda-phet** [comment]
Here is the google doc for notes: https://docs.google.com/document/d/1aMAv6QI5lI6f_H6DnV7utVgPs3NgXmKSnDTpC6tXaqg/edit#

**Comment by marlitas** [comment]
The full document can be found above, but here is a summary of the overall discussion:
### Successes:

1. Effective Pairing Experience: CM and MV had successful pairing sessions with efficient work division and valuable knowledge sharing. They came prepared with agendas, resulting in productive outcomes.

2. Improved Communication and Collaboration: Informal design meetings and increased communication through Slack and impromptu meetings helped move the project forward. Collaboration between physics and math educators contributed to ideation and added functionality to the simulation.

3. Focus Time and Iterations: The introduction of focus time and iterations increased efficiency and collaboration, allowing for quicker decision-making and meeting deadlines.

### Improvements:

1. Consideration of Alternative Input: The team neglected to consider alternative input in the design, which made it challenging to incorporate later. It is suggested to include alternative input from the beginning and document it in the design template.

2. Clarify Roles and Ownership: Clearer delineation of roles and ownership, especially when new developers join the project, would help improve coordination and avoid confusion.

3. Settled Design Prior to Development: It is important to have a more settled design before starting development to prevent shifting requirements and challenges during implementation. This would improve the development process and save time.

### Action Items:

Modifications to look and feel? 
- Nothing sim specific here.

Modifications to sim design process? 
- Considering all features we would like to include from the beginning (PhET-iO, alternative input, UI Sound).
  - Timeline makes this a bit complex, but ensuring that the final timeline includes these considerations.
  - Addressing it could be: “We’re not going to do this.”

Modifications to sim checklist? 
- Modify checklist to state which items may not be relevant
  - CM: I strike through or delete the ones that are not relevant.
  - MV: However, that comes with some experience.

Modifications to project process?
- Explicit conversations at outset as to what expectations, milestones, ownership, and work styles are.
  - CM: Perhaps this applies to team creation in iteration by iteration.
  - CC: A discussion on milestones and timeline responsibilities at the beginning. 

Messages to share at status? 
- Sharing the explicit conversations point: “Explicit conversations at outset as to what expectations, milestones, ownership, and work styles are.”
- It is important to communicate this at the outset of teams. 
- As more people work on projects this becomes more and more important.

Closing this issue as completed. Thanks all!
