### ISSUE TITLE
Calculus Grapher - Publish 1.0

### ISSUE THREAD

**Issue by markgammon** [phetsims/calculus-grapher#35]
Publish Calculus Grapher 3.0. 

- [ ] https://github.com/phetsims/calculus-grapher/issues/1

**Comment by pixelzoom** [comment]
Dev testing started on 3/20/23:

* https://github.com/phetsims/qa/issues/921

**Comment by pixelzoom** [comment]
RC1 was published on 3/28/23:

* https://github.com/phetsims/qa/issues/924

**Comment by veillette** [comment]
RC2 was published on  13/4/2023
- [ ] https://github.com/phetsims/qa/issues/933

**Comment by veillette** [comment]
The sim was published on 4/17/2023

**Comment by veillette** [comment]
Done. Closing
