### ISSUE TITLE
Consider implementing boundaries for respective functions

### ISSUE THREAD

**Issue by bryo5363** [phetsims/calculus-grapher#4]
This simulation can get messy very quickly. May want to implement boundaries for each function so you don't end up w/ something like this

![untitled](https://cloud.githubusercontent.com/assets/7717368/7752203/6852b8ba-ff9b-11e4-9bbb-f327a28f21da.png)

**Comment by amanda-phet** [comment]
Unassigning and putting on hold until this sim is ported.

**Comment by veillette** [comment]
This is being tracked in #55.
