### ISSUE TITLE
Design questions (general & PhET-iO)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#49]
@veillette and I had a meeting to review the [HTML5 design document](https://docs.google.com/document/d/1yt4ykdjF8EYAv9GdxmM3Y-_9kYeudW7gKth-nEleygk/edit?pli=1).  Here are some questions for our next design meeting. @veillette feel free to add anything that I missed, or anything else that occurs to you.

## General design questions

- [x] Milestones: please provide significant dates.

- [x] Showing discontinuities in the derivatives is a challenging problem. Verify that this requirement is necessary, discuss the challenges.
_See https://github.com/phetsims/calculus-grapher/issues/18._ 

- [x] How should curve manipulators behave as a curve is built up using multiple manipulators?  The Flash version has some unusual/inconsistent behavior. 
_See https://github.com/phetsims/calculus-grapher/issues/77._

- [x] Undo feature:  Is infinite undo really necessary? Is Undo history cleared when Reset All button is pressed? 
_See https://github.com/phetsims/calculus-grapher/issues/64_

- [x] Intro screen:  The mockups show the integral checkbox on this screen. Is that correct? Or is this screen only supposed to include f(x) and df/dx?

- [x] Integral Lab screen: The design doc says:
> The lab screen has an additional “scene selection” button that displays the second derivative as well as additional drawing tools.

I see no “scene selection” buttons, which are typically radio buttons. Do you mean checkboxes?  And shouldn’t this be “displays the integral”?
_See https://github.com/phetsims/calculus-grapher/issues/63, no longer relevant._

- [x] Is it OK that this design provides no way to compare the integral and d2f/dx2?

- [x] Should there be a way to hide f(x), for prediction?

- [x] What do you want the behavior to be when a curve exceeds the y-axis range of its graph?  Should we consider auto-scaling the y axis, ala Fourier?

- [x] There are mentions of f(t) in some of screenshots of the design document. Should we support a toggle between f(x), df/dx and x(t), v(t) etc.  

- [x]  Do we want f(x) to ever be non-differentiable? 

- [x] Wish list features that should be included ? (slope indicator?, area integrator, numerical value?, indicators for max/min)
 
## PhET-iO design questions

- [x] Are there any non-standard PhET-iO requirements that we need to know about? Query parameters, special features, etc.

- [x] Should we have support for f(x) curves created through PhET-iO that cannot be created by mouse/touch interactions (ege. f(x) curves with discontinuities).
_See https://github.com/phetsims/calculus-grapher/issues/52._

- [x] Should curves that are derived from f(x) be present in the Studio tree? Because they are derived, they do not need to be instrumented in order to save/restore state.

- [x] One way to implement the sim is to have a single model that contains all 4 curves. Screens would simply ignore the curves that they don't use. Would that be acceptable for the Studio tree?  Or does the Studio tree need to contain only relevant curves for each screen?

- [x] Should Undo history be saved with PhET-iO state? It seems undesirable as part of initial state; what does it mean for the student to “Undo” what was set up by the instructional designer?  Is it needed for record/playback?
_See https://github.com/phetsims/calculus-grapher/issues/65_

**Comment by pixelzoom** [comment]
9/22/2022 design meeting

> Is it OK that this design provides no way to compare the integral and d2f/dx2?

Yes.

**Comment by pixelzoom** [comment]
We will continue discussing the remaining items at our next meeting, the week of Oct 3.

**Comment by veillette** [comment]
> - [] Do we want f(x) to ever be non-differentiable?
yes, it is an important goal to have a step function

**Comment by pixelzoom** [comment]
> - [ ] Wish list features that should be included ? (slope indicator?, area integrator, numerical value?, indicators for max/min)

To be discussed by @veillette and @catherinecarter in https://github.com/phetsims/calculus-grapher/issues/62.

**Comment by pixelzoom** [comment]
> - [ ] Should there be a way to hide f(x), for prediction?

We should be able to hide f(x) via PhET-iO, but not via the sim's UI.

**Comment by pixelzoom** [comment]
> - [ ]  Integral Lab screen: The design doc says: ...

No longer relevant, since the screens have been redesigned in #63.

**Comment by pixelzoom** [comment]
> - [ ] Should we have support for f(x) curves created through PhET-iO that cannot be created by mouse/touch interactions (ege. f(x) curves with discontinuities).

Moved to https://github.com/phetsims/calculus-grapher/issues/52.

**Comment by pixelzoom** [comment]
> - [ ]  How should curve manipulators behave as a curve is built up using multiple manipulators? The Flash version has some unusual/inconsistent behavior.

Moved to https://github.com/phetsims/calculus-grapher/issues/77.

**Comment by pixelzoom** [comment]
All design questions have been addressed or moved to their own issues.  So I'm going to close this issue.
