### ISSUE TITLE
Weird behavior with sine function

### ISSUE THREAD

**Issue by bryo5363** [phetsims/calculus-grapher#5]
I assume I observe strange behavior w/ the sine function because it is continuous but here is a strange issue. Essentially the sine function will not initially be repetitious until a certain boundary is passed

1) open sim
2) select "Hill" option, draw a peak (or trough)
3) click sine function. drag the line upwards. Note that the sine function is not repeating, it is merely one peak
4) drag the line towards the left. There will be a certain location where the sine function becomes repetitious.

**Comment by phet-steele** [comment]
Drawing a peak versus a trough in step 2, I see different behavior. The trough behavior is what is described in steps 3 and 4, but a peak behaves as such (ignore that stuff on the right):

![calcgra](https://cloud.githubusercontent.com/assets/5863899/7752620/ab17e3b2-ff9d-11e4-86be-b08c87ef4e68.gif)

**Comment by bryo5363** [comment]
Noticed this w/ a pedestal

![calculusgrapher](https://cloud.githubusercontent.com/assets/7717368/7754492/33ee24d8-ffaa-11e4-91df-79734f43f004.gif)

**Comment by amanda-phet** [comment]
I've noticed this before, too. It seems that if you drag *up* first with the pedestal, hill, etc. and then drag down with the sine curve, it overrides the rest of the graph. This does not happen if you drag *down* first with the pedestal, hill, etc.

**Comment by amanda-phet** [comment]
Unassigning and putting on hold until this sim is ported.

**Comment by veillette** [comment]
We are addressing this issue in #85.
Closing
