### ISSUE TITLE
Remove Calculus Grapher from phet-io-state-unsupported

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#50]
We have added calculus-grapher to phet-io-state-unsupported.  We should remove it  in the long run as we wish to instrument this simulation (#48). This issue will ensure that we remove it from the list prior. to publication

**Comment by pixelzoom** [comment]
12/6/2022 @veillette and I considered whether to enabled this yet. Decided to wait until the sim is close to feature complete, and after we've had a chance to do a thorough review of the PhET-iO instrumentation.

**Comment by pixelzoom** [comment]
I moved this task to https://github.com/phetsims/calculus-grapher/issues/209 (PhET-iO post-review checklist).  Closing.
