### ISSUE TITLE
Design for clipped Graph. 

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#55]
Although there is no explicit mention of clipped graph in the design document, I see that the df/dx graph in the design document is clipped.

![image](https://user-images.githubusercontent.com/7633344/192338238-cb9b398c-d320-436c-aea1-5cad17637440.png)

There is no clipping in the flash simulation.

Clipping the graphs brings a handful of design questions that we should addressed.

Should we indicate to the user that the graph is being clipped.

The model bounds of the graph change according to the number of graphs that are visible. In addition, for f(x),  our drag Listener is attached to the curve., which means that a drag can only be started by initially touching the curve. By clipping the graph, we can easily imagine a scenario where a portion of the curve (or even the entire curve)  is pushed out of sight and the user can no longer manipulate the curve.

**Comment by amanda-phet** [comment]
In the HTML5 version of this sim, we want graphs "clipped" and staying within the bounds of their grid area. 

Regarding the bounds changing, that is still being figured out, so I think we can address that concern once we have finalized the size and number of graphs per screen.

**Comment by veillette** [comment]
In light of the previous change in the design document, where the height of the graphs is now static, this is no longer a design problem, rendering this issue.  

The details to clip the curves have already been implemented. 
Closing.
