### ISSUE TITLE
Migrating Buttons

### ISSUE THREAD

**Issue by phet-steele** [phetsims/calculus-grapher#6]
Continuously down clicking on a button, but then up clicking off the button causes them to move. This is after many repetitions:

![living buttons](https://cloud.githubusercontent.com/assets/5863899/7752384/60f0bcb0-ff9c-11e4-9c76-8c3da1006659.PNG)

Tested on Win 8.1 FF

**Comment by bryo5363** [comment]
This is a pretty familiar issue; it was observed on arithmetic and fraction matcher. I believe @jbphet has dealt with this issue before.

**Comment by amanda-phet** [comment]
Unassigning and putting on hold until this sim is ported.

**Comment by brandonLi8** [comment]
The hmtl5 version of the sim shouldn't (and doesn't) have this problem (no issues of moving buttons in sun). Closing.
