### ISSUE TITLE
Identify possible "value added" features for the design

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#62]
10/3/2022 design meeting

@catherinecarter will review the current design, with an eye towards "value added" features that would be nice to have.  She'll discuss with @veillette. (Feel free to loop in @pixelzoom too, if you think it would be helpful.)

Ideally meet up in the next 7-10 days, brainstorm, and bring back ideas to the larger group.

Cut-off for completing design is 10/28/2022.

**Comment by catherinecarter** [comment]
@veillette and I met with @matthew-blackman to discuss value added features. We added some notes in the [Calculus Grapher design document](https://docs.google.com/document/d/1yt4ykdjF8EYAv9GdxmM3Y-_9kYeudW7gKth-nEleygk/edit#heading=h.wua4hb1dax3q) with things MV will investigate how long each added value feature might take, with the goal of not pushing the timeline back. Also included is a "wishlist" of features not considered for this version, but perhaps a future version.

**Comment by pixelzoom** [comment]
@veillette caught me up on proposed "value added" features, and I reviewed the 10/13 meeting note in the design doc.  A few thoughts...

> Points to be places on line labeled A, B, C, etc., with a spinner to choose the number of desired points - PhET-iO

Consider alternatives to text labels, unless text is important to show in equations or activities.  Using color (or something else) to differentiate the points may be preferrable. 

> Toggle for prime notation vs df/dx = f’(x) (consider i18n and l10n)

Changing the notation (Lebniz vs Newton?) seems appropriate as a sim-specific Preference, with a query parameter to set the initial value, and a Property that can be changed via the Preferences choice and/or PhET-iO.

> Eyeball icon to hide or show each of the three curves

See scenery-phet EyeToggleButton.

> A non-connected “predictor horizontal curve” for students (in a different color) to drag a curve to predict any of the three graphs when the eyeball is toggled hidden (something will need to happen so students/teachers know this is an option)

Drawing a prediction curve will be very difficult when the graphs have different scales. So I'm wondering how useful/usable this feature will be in practice.

When sims have a prediction feature, we typically want to see both the "prediction" and the "actual" at some point, so that students can compare.  Has that been considered?  What is described in this issue and the design doc (for far) makes me think not.

The prediction feature makes having a single "Smooth" and "Reset" button problematic.  If this feature is added, then those buttons need to be per-graph. Consider iconic buttons on the graphs (for example in the lower-right corner) whenever the curve for that graph is editable.

From the 10/13 meeting notes in the design doc:
> Two calculus teachers CC spoke with prefer to not have the dotted connecting lines between piecewise graphs 

Perhaps we also need a "Discontinuities" preference, where the user can switch between 2 (or more?) representations for how discontinuities are graphed.

Finally... Reminder that the milestone for completing the design is 10/31/2022, which is in 13 days.  There are a lot of new features here.  It's unlikely that all of them can be designed in the remaining time.  Should we should either prioritize/drop some features quickly, or extend the design deadline (which would be unfortunate).

**Comment by pixelzoom** [comment]
11/10/2022 design meeting:

The milestone for completing the general design is moved from 10/31/2022 to 11/16/2022.

**Comment by amanda-phet** [comment]
I believe this issue is complete, since we've discussed all additional features now.
