### ISSUE TITLE
Revisit how the sim is organized into screens

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#63]
From 10/3/2022 design meeting...

The sim currently has 3 screens: Intro, Integral Lab, Derivative Lab.

The Intro and Integral Lab screens are the same, but the latter has more operations. This isn't obvious from the screen titles. Multiple people have asked about this, and we seem to have to keep reminding ourselves about this aspect. So that might be a cue that there's a problem here.

@catherinecarter pointed out that derivative is typically taught before integral, so the order intially seems a bit odd.

@amanda-phet and @kathy-phet had some idea about using "scene" buttons to switch between "f(x) + 1st derivative + 2nd derivation" and "f(x) + 1st derivative + integral" configurations.

@veillette @ariel-phet FYI.

**Comment by veillette** [comment]
Amanda cemented how the sim is organized in the 10/19 meeting. The info is in the design document.

**Comment by veillette** [comment]
We can safely closed this issue and refer to the design document.

**Comment by amanda-phet** [comment]
I think it wouldn't hurt to paste the decision here. We decided on four screens: 

Derivative (simple function types, maybe a tangent line tool)
![image](https://user-images.githubusercontent.com/7852916/196973227-0161b1fa-febf-4b38-ab3e-83fb6a1ce761.png)

Integral (simple function types, maybe an area under the curve tool) 
![image](https://user-images.githubusercontent.com/7852916/196973280-f7456455-a1ac-42dd-a970-3ece7993c28f.png)

Advanced (includes derivative and integral options, and advanced function types)
![image](https://user-images.githubusercontent.com/7852916/196973337-a0f5e233-3a81-470b-81d4-4dee8d55e53a.png)

Lab (includes derivative, integral, and 2nd derivative options, and advanced function types) 
![image](https://user-images.githubusercontent.com/7852916/196973383-0892cf02-5b31-45c2-b385-c29c0742bd95.png)

**Comment by veillette** [comment]
In the previous commit, I created the four screens with the appropriate names. 

The derivative and integral screens are functionally up to date with the design doc.

The Advanced  screen still need pushButton whereas the the lab screens needs a toggle switch. 
In the meantime, I have left the old checkbox as a placeholder.

**Comment by veillette** [comment]
I noticed that the Lab has a placeholder over the ABswitch. 
@amanda-phet , should the ABswitch be replaced by rectangular radio buttons as on the Advanced screen?

**Comment by amanda-phet** [comment]
I'm not sure what UI component makes sense on that screen. I suppose it controls whether integral or second derivative is shown, so we might want a similar control to what is on the Advanced screen. But I think some design details are still being worked out, especially on that Advanced screen.

**Comment by amanda-phet** [comment]
I believe this is worked out now, and you already have this reflected in the latest version. But just to have it documented, let's use this control on the left to switch between which graphs are in view. 

Advanced screen: 
![image](https://user-images.githubusercontent.com/7852916/201392266-35606522-b8be-4f8f-a136-7bc0b52afd6e.png)

Lab screen: 
![image](https://user-images.githubusercontent.com/7852916/201392324-097eedd8-752d-4837-9951-e669ec443957.png)

**Comment by veillette** [comment]
The graphSet Buttons are tracked in #103 and #106. We can close this issue at this point.
