### ISSUE TITLE
Should Undo history be included in PhET-iO state?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#65]
This sim has an Undo feature.  It saves the state before each user operation on f(x), and allows the user to Undo previous operations.  (In https://github.com/phetsims/calculus-grapher/issues/64, we're discussing whether Undo is unlimited, or some large number of operations.)

Should Undo history be stateful?

For initial state, restoring Undo history seems undesirable. The instructional designer is going to perform some operations to put the sim in an initial state. Why would we want the student to have that Undo history as part of their initial state? They are not operations that the student performed. Shouldn't the student start with empty Undo history?

Is Undo history needed for record/playback?

In addition to designers @amanda-phet and @kathy-phet, we'd like to hear from the PhET-iO team @samreid and @zepumph.  @veillette FYI.

**Comment by kathy-phet** [comment]
I also feel undo should not be captured in state.

**Comment by amanda-phet** [comment]
>Should Undo history be stateful?

I agree with what others have said here (so I think the answer is 'no'). I would not want someone to save the state of the sim in studio, then open the sim and be able to undo whatever the instructional designer did to create the curve on the screen.

**Comment by pixelzoom** [comment]
I agree with all of the above.  So unless we determine otherwise, Undo history will be omitted from the PhET-iO state.

@veillette let's leave this issue open, and make sure we document this decision at an appropriate location in the code, with a link to this issue.

**Comment by veillette** [comment]
I added a comment about savedYvalue and why it is not in the state object in  CurvePoint. I also added a link referencing this issue. Our work is done. Closing
