### ISSUE TITLE
Color profile

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#68]
Not too long ago, PhET decided that all new sims should have a "color profile".  A color profile is a collection of ProfileColorProperty instances.  For example, see GOColors.ts.  The reason for this is three-fold:

(1) Color profile is how PhET implements 'projector mode'.
(2) Even if your sim doesn't currently require 'projector mode', it puts the sim in a good position to support other color profiles in the future.
(3) It makes it easier for PhET designers to experiment with adjusting colors, for example when addressing color blindness issues.

When running a sim from phetmarks, you can edit a sim's ProfileColorProperty instances by choosing the "Color Editor" mode:

<img width="489" alt="screenshot_1917" src="https://user-images.githubusercontent.com/3046552/194372782-a4dbd24c-df14-4454-b305-c36a6fd69580.png">

Here's an example of what the Color Editor looks like, for Geometric Optics:

<img width="1535" alt="screenshot_1918" src="https://user-images.githubusercontent.com/3046552/194372886-d5fb6a30-89b1-41a6-8e68-668bd371d3fb.png">

In this sim, you'll want to change CalculusGrapherColors to use ProfileColorProperty instead of static string/Color constants.  Some guidelines:

* Use ProfileColorProperty for colors that you think designers would like to experiment with.
* It's still OK to use static string/Color for things that you don't think will need to change, or that would not be different in (for example) a projector mode
* ProfileColorProperty instances do not need to be instrumented for PhET-iO.  If a PhET designer decides that a color should be editable via PhET-iO/Studio, they'll let you know.

**Comment by veillette** [comment]
Thanks for all the info, that made the conversion process easier.

**Comment by veillette** [comment]
The color profile was added. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Looks great.  I see CalculusGrapherColors.ORIGINAL_CHART_BACKGROUND is unused.  Should it be delete or relocated?  Then feel free to close.

**Comment by veillette** [comment]
Oops, I forgot to delete the unused variables. Done in the commit above. Closing
