### ISSUE TITLE
Grid Layering

### ISSUE THREAD

**Issue by phet-steele** [phetsims/calculus-grapher#7]
The fully zoomed out grid for f(x) is layered in front of the integral graph:

![graph cover](https://cloud.githubusercontent.com/assets/5863899/7752791/c08c61fe-ff9e-11e4-9840-7bd7aef6c053.PNG)

Tested on Win 8.1 FF

**Comment by phet-steele** [comment]
It also covers the derivative graph.

**Comment by amanda-phet** [comment]
Unassigning and putting on hold until this sim is ported.

**Comment by veillette** [comment]
In #55, we discussed clipping the graphs.  We have implemented clipping in master. There are a few user interactions about how to deal with curve in clipped graph but it resolves the layering issue so we can close it
