### ISSUE TITLE
Rendering math symbols

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#70]
In general for PhET math sims:
* symbols that could serve as operands in an equation (x, y,...) should be translatable
* symbols for operators (=,+,...) are not translatable

In this sim, it looks like your translatable symbols are "f", "x", and "d".  They should be added to  calculus-grapher-strings_en.json.

In Fourier, we had a large number of symbols, and an entire issue was devoted to specifying how to render them, see https://github.com/phetsims/fourier-making-waves/issues/15.  But for Calculus Grapher, I think you'll be fine using italic MathSymbolFont for all of the above symbols, because they are shown that way in the design-doc mockups, for example:

<img width="32" alt="screenshot_1919" src="https://user-images.githubusercontent.com/3046552/194379120-cbc91a8a-aa41-4a2b-84e1-575f598aea43.png">

To render symbols, you'll use MathSymbolFont and RichText, keeping in mind that the translated symbols are string Properties.  See GOSymbols.ts for an example of how to generate the markup that will be passed to RichText.  CalculusGrapherSymbols will probably be something like:

```typescript
const CalculsGrapherSymbols = {
  fStringProperty: MathSymbolFont.createDerivedProperty( CalculusGrapherStrings.fStringProperty ),
  lStringProperty: MathSymbolFont.createDerivedProperty( CalculusGrapherStrings.xStringProperty ),
  mStringProperty: MathSymbolFont.createDerivedProperty( CalculusGrapherStrings.dStringProperty ),
};
```

You could also have DerivedProperty instances for `dfStringProperty`, `dxStringProperty`, etc.

To render the standard "numerator over denominator" format for expressions like "df/dx", use scenery layout features, something like this, adjusting HSeparator options as needed:

```
const dfdxNode = new VBox( {

  // numerator
  new RichText( CalculsGrapherSymbols.dfStringProperty ),

  // horizontal line between numerator and denominator, resized automatically by VBox
  new HSeparator( {
    stroke: 'black',
    lineWidth: 0.5
  } ),

  // demonimator
  new RichText( CalculsGrapherSymbols.dxStringProperty )
} );
```

**Comment by veillette** [comment]
Also related to #24, where the possibility of reversing (LTR -> RTL) the math notation was broached.

**Comment by veillette** [comment]
I gave it my college try, but there are a lot of pitfalls. 

It is not clear what are the translatable units in this case. The minimum set is  f  and x.
However,  however I also included d, even though it is an operator. 

For each three string properties, a derived mathSymbolFont string property was generated.

These strings  properties were then assembled to generate the appropriate expressions:
 df, dx, d^2f, dx^2,  f(x), \int f(x) dx 
This is all a bit tedious as one must operate on the properties to generate new strings, so it is a bit contrived.

The superscript were generated by leveraging RichText, but RichText is not an mathematical engine and doesn't understand the spacing and sizing. Small thinspace were added and the fontsize and the font family where chosen appropriately to give a natural look to the equation.

![image](https://user-images.githubusercontent.com/7633344/194540846-cedff80b-9263-4f47-b83f-637b8ceaf208.png)

I like the look but it would fail the RTL to LTR test, as explained in #24. 

However I truly failed when it comes to the integral

![image](https://user-images.githubusercontent.com/7633344/194541030-9516d496-0b12-4ea2-a6ae-cc8b4616bab8.png)

There is no easy way to attach subscript and superscript to the integral sign.


For reference, here is what it should look like

![image](https://user-images.githubusercontent.com/7633344/194536558-0826b8da-515a-4afb-8c5c-17d5e6e2276c.png)

**Comment by pixelzoom** [comment]
Yes indeed, you're running into the same problems that I've encountered in every math-related sim. PhET does not have a good solution for rendering math equations and expressions.  It usually comes down to manual layout, lots of magic-number offsets, and lots of tweaking until the designers approve the look.

For the integral, you'll will indeed need to manually add the range and handl the layout. It will be something like the summation that appears in the first screen of Fourier (set the "Equation" combo box in the control panel to something other than "Hidden"):

<img width="252" alt="screenshot_1928" src="https://user-images.githubusercontent.com/3046552/194583772-dd82ae81-ed18-4153-bf3f-0171cd90abe9.png">

As of the RLT translation issue in https://github.com/phetsims/calculus-grapher/issues/24.  We have never handled this in a PhET math sim, and we are not equipped to handle this.  It will be a huge amount of work.  So before spending time on this, we should confirm the requirements.

**Comment by pixelzoom** [comment]
Yes indeed, you're running into the same problems that I've encountered in every math-related PhET sim. PhET does not have a good solution for rendering math equations and expressions, and it's a long-standing problem. The way that we workaround this deficiency is to do the best we can with the tools available (which I've described above). This usually comes down to using manual layout, lots of magic-number offsets, and lots of tweaking until the designers approve the look.

For the integral, you'll will indeed need to manually add the range and handl the layout. It will be something like the summation that appears in the first screen of Fourier (set the "Equation" combo box in the control panel to something other than "Hidden"):

<img width="257" alt="screenshot_1929" src="https://user-images.githubusercontent.com/3046552/194584580-6b6a588b-0999-4983-8c2f-bdf11f9ee9da.png">

As of the RLT translation issue in https://github.com/phetsims/calculus-grapher/issues/24.  We have never handled this in a PhET math sim, and we are not equipped to handle this.  It will be a huge amount of work.  So before spending time on this, we should confirm the requirements.

@amanda-phet @kathy-phet FYI.

**Comment by pixelzoom** [comment]
A couple more note on the integral...

See fourier-making-waves SumSymbolNode.js for the summation symbol that I mentioned above.  It also supports an integral symbol, shown in Fourier _Wave Packet_ screen when the numer of wave components is infinite.  To see this in Fourier:

1. Go to Wave Packet screen
2. Set "Component Spacing" slider to '0'
3. The "Sum" graph will have an equation like this above it:

<img width="248" alt="screenshot_1930" src="https://user-images.githubusercontent.com/3046552/194590228-9a8ffb26-7efc-4284-ae32-94bd995936b9.png">

Not in close to perfect, but it was acceptable for Fourier.  I mention it in case you want to try reusing bits of SumSymbolNode.js.

**Comment by pixelzoom** [comment]
@veillette said:
> ... however I also included d, even though it is an operator.

Right you are.  There are exceptions to the "In general" guidelines that I mentioned in https://github.com/phetsims/calculus-grapher/issues/70#issue-1400062430.

In the case of "dx", it looks like both symbols are typically rendered in italic font.  See a Google Image search for "df/dx".  So I think that's the way to do.

**Comment by kathy-phet** [comment]
> @veillette I've asked for clarification on the LTR/RTL issue in https://github.com/phetsims/calculus-grapher/issues/24#issuecomment-1271725367.

I commented. I think addressing RTL and LTR switch is beyond the scope of what we can do here.

**Comment by veillette** [comment]
I did not  not tackle the RTL /LTR switch.

In fact, I used a similar approach as SumSymbolNode for laying out the integral. It is a lot of small tweaks to lay out all the nodes properly.  I have also laid out the upper and lower bounds of the integral to the right of the integral symbol. 

Assigning to @amanda-phet for review.

![image](https://user-images.githubusercontent.com/7633344/195632329-86d5236d-f47d-4c8c-8211-dd706f5d3b4a.png)

**Comment by amanda-phet** [comment]
@veillette for f(x) and f(t), can you use Times (or whatever the PhET math font is) for the parentheses? That might help with the spacing between f and the open parenthetical. I also think it would look better. If they are still touching, we might want to add a space.

**Comment by veillette** [comment]
In general, parentheses ( as well as brackets, operators  and numbers) are not italicized in math, which is why I'm not using Math font the parenthesis.

I added a hair space between the f and the parenthesis to address the issue.
![image](https://user-images.githubusercontent.com/7633344/201685015-16bb83ef-e9d0-49c8-9b38-cba58190b210.png)

**Comment by veillette** [comment]
Assigning back to @amanda-phet to review.

**Comment by amanda-phet** [comment]
Thank you, this is much better! 

Can this be closed now?

**Comment by veillette** [comment]
We can close this issue. Closing.
