### ISSUE TITLE
Should we create a rich enumeration for the type of curves?

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#71]
There are four type of curves in this simulation.
 - derivative
 - second derivative
 - original function
 - integral

Each curve have their own label, own model, prefixes for tandem. Some of the curve have different colors based on the type of graph.
We need to iterate over the type graphs to create the GraphNode and end up with onerous code like  the following lines. 

````
    this.integralGraphNode = new GraphNode( model.integralCurve,
      visibleProperties.gridVisibleProperty,
      this.graphHeightProperty,
      {
        visibleProperty: visibleProperties.integralGraphNodeVisibleProperty,
        tandem: options.tandem.createTandem( 'integralGraphNode' )
      } );


    this.originalGraphNode = new OriginalGraphNode( model.originalCurve,
      visibleProperties.gridVisibleProperty,
      this.graphHeightProperty,
      {
        visibleProperty: visibleProperties.originalGraphNodeVisibleProperty,
        tandem: options.tandem.createTandem( 'originalGraphNode' )
      } );

    this.derivativeGraphNode = new GraphNode( model.derivativeCurve,
      visibleProperties.gridVisibleProperty,
      this.graphHeightProperty,
      {
        visibleProperty: visibleProperties.derivativeGraphNodeVisibleProperty,
        tandem: options.tandem.createTandem( 'derivativeGraphNode' )
      } );

    this.secondDerivativeGraphNode = new GraphNode( model.secondDerivativeCurve,
      visibleProperties.gridVisibleProperty,
      this.graphHeightProperty,
      {
        visibleProperty: visibleProperties.secondDerivativeGraphNodeVisibleProperty,
        tandem: options.tandem.createTandem( 'secondDerivativeGraphNode' )
      } );
````

There are two more instance of this pattern when we create the checkboxes and for the creation of curve models.

The questions 
- Would an rich enumeration be advantageous in this cases? what would be the drawbacks.
- Is there another approach that could be used instead.

**Comment by pixelzoom** [comment]
I don't think you need an enumeration in this case. 

Add `tandemName` and any other properties (title, icon, etc.) that you need to Curve. Then something like:

```typescript
// in the model:
this.curves = [ integralCurve, originalCurve, derivativeCurve, secondDerivativeCurve ];

// in the view:
const curveNodes = model.curves.forEach( curve => new GraphNode( curve, 
  visibleProperties.gridVisibleProperty,
  this.graphHeightProperty, {
    visibleProperty: visibleProperties.integralGraphNodeVisibleProperty,
    tandem: options.tandem.createTandem( curve.tandemName )
} );
```

Would that meet the needs that you have in mind?

**Comment by pixelzoom** [comment]
The above of course will not work if you need specific GraphNode subclasses for specific models. For example, if `originalCurve` required `OriginalGraphNode extends GraphNode`.   If that's the case, I don't have a problem with the creating the Nodes for the curves as you've shown in https://github.com/phetsims/calculus-grapher/issues/71#issue-1400362461.

**Comment by veillette** [comment]
The  https://github.com/phetsims/calculus-grapher/issues/71#issuecomment-1270814321 shows that we could do a lot without creating a rich enumeration.  In any case, the fact that OriginalGraphNode extends GraphNode makes it moot either way.

Closing
