### ISSUE TITLE
Pointer areas for interactive curves

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#74]
In #59 and #54, we have created a CurveNode that relies on the Bamboo library. Since the originalCurve is usercontrolled, we have added a dragListener to it but we then realized that it wouldn't respond without creating custom pointerAreas.

To summarize, a dragListener is added OriginalCurveNode, which extends CurveNode. CurveNode creates many scenery node, the most important being the continuousLinePlot. The continuousLinePlot is a scenery/path constructed from kite/shape. The shape is a series of connected points. 

My understanding is that because the kite/shape is not closed, it doesn't have a surface to hit, and the dragListener does not have anything to answer to. 

To get around this fact, we created  customs touchArea, mouseArea that are closed shapes based on the series of points. Although it is working, it is an ugly hack.

```js
 /**
   * set the touch/mouse area of this node
   */
  public override setPointerAreas(): void {

    const pathShape = this.getDilatedCurveShape();
    this.touchArea = pathShape;
    this.mouseArea = pathShape;
  }


  /**
   * Creates a (rough) dilated shape for a Curve.
   * TODO simplify: Talk to JO about why this is necessary in the first place.
   */
  private getDilatedCurveShape(): Shape {

    // in view coordinates
    const CURVE_DRAG_DILATION = 5;

    const pathShape = new Shape();

    const point = this.chartTransform.modelToViewXY( this.curve.points[ 0 ].x, this.curve.points[ 0 ].y );

    pathShape.moveToPoint( point );

    // Draw the curve shape slightly BELOW the true y-value.
    this.curve.points.forEach( point => {
      if ( point.exists ) {
        const viewPoint = this.chartTransform.modelToViewXY( point.x, point.y );

        pathShape.lineToPoint( viewPoint.addXY( 0, CURVE_DRAG_DILATION ) );
      }
    } );

    // Draw the curve shape slightly ABOVE the true y-value.
    _.forEachRight( this.curve.points, point => {
      if ( point.exists ) {
        const viewPoint = this.chartTransform.modelToViewXY( point.x, point.y );

        pathShape.lineToPoint( viewPoint.addXY( 0, -CURVE_DRAG_DILATION ) );

      }
    } );

    return pathShape.close().makeImmutable();
  }
```

Ideally, we should be able to avoid creating custom touch and mouse Areas.  At the very least, these pointerAreas could be obtained directly from the initially shape (but dilated/expanded).

**Comment by veillette** [comment]
Assigning to @jonathanolson for help on this issue.

**Comment by pixelzoom** [comment]
@veillette do you still need @jonathanolson's assistance on this?

**Comment by veillette** [comment]
Yes we do need him to assess if there is an easier to set the pointerAreas.

**Comment by veillette** [comment]
With the help of @jonathanolson, we were able to set the PointerAreas by finding a dilated version of the shape using getStrokeShape.

```js
  /**
   * Sets the touch/mouse area of the drag Handler
   */
  public override setPointerAreas(): void {

    // create a dilated shape based on the continuous line plot shape
    const lineStyles = new LineStyles( { lineWidth: 10 } );
    const dilatedCurveShape = this.continuousLinePlot.shape!.getStrokedShape( lineStyles );

    this.continuousLinePlot.touchArea = dilatedCurveShape;
    this.continuousLinePlot.mouseArea = dilatedCurveShape;
  }
```
As you can see below, the pointerAreas show the correct bounds for the curve, with the advantage that it does not require a custom method to determine the dilated shape of the curve.

![image](https://user-images.githubusercontent.com/7633344/214732886-6c5e9b96-1bf0-49b3-ae1d-b0119d36aef9.png)

Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Looks good.  In the above commit I factored out:

```typescript
const LINE_STYLES = new LineStyles( { lineWidth: 10 } );
```

... so that we're not allocating one of these everytime that `setPointerAreas` -- which is critical code, since it's called everytime the curve is changed.

I can't tell if this affected performance positively or negatively, because I didn't run with `?profiler` before the change.  But responsiveness of manipulating the curve seems qualitatively about the same.

Back to @veillette in case there's anything else to do here.  You might want to mention to @jonathanolson that this occurs while the user is manipulating the curve, to see if he any performance concerns or tips.

**Comment by veillette** [comment]
@pixelzoom : factoring out the LinseStyles is a good step.
As far as performance is concerns I did not run a before/after test. However, casually, I did not see a performance improvement or degradation.  
I'll note that the responsiveness of the predictCurve is significantly better than the originalCurve. Since both curves have dragHandlers, it suggests that the bottleneck does lie in the setting of pointerAreas.

But since we are here: @jonathanolson do you have any concerns about performance from this change?

For comparison: You can see how we used to set the pointerAreas in https://github.com/phetsims/calculus-grapher/issues/74#issue-1415303875 

versus

```js
  /**
   * Forwards response to super-class
   */
  public override updateCurveNode(): void {
    super.updateCurveNode();
    this.setPointerAreas();
  }

  /**
   * Sets the pointer areas for manipulating the curve.
   */
  public override setPointerAreas(): void {

    // create a dilated shape based on the continuous line plot shape
    const dilatedCurveShape = this.continuousLinePlot.shape!.getStrokedShape( LINE_STYLES );

    this.continuousLinePlot.touchArea = dilatedCurveShape;
    this.continuousLinePlot.mouseArea = dilatedCurveShape;
  }
```

**Comment by pixelzoom** [comment]
@veillette can we remove this TODO in OriginalGraphNode.ts?  This now seems like a reasonable thing to do in when `yZoomLevelProperty` changes.
 
```typescript
    this.yZoomLevelProperty.link( () => {

      // TODO: find a way to update touch/mouse area without resorting to this: https://github.com/phetsims/calculus-grapher/issues/74
      this.setCurvePointerAreas();
    } );
```

**Comment by veillette** [comment]
Yes, agree, the TODO is unwarranted.

**Comment by pixelzoom** [comment]
@jonathanolson please reply to https://github.com/phetsims/calculus-grapher/issues/74#issuecomment-1405147932.

To summarize...  TransformedCurveNode `setPointerAreas` calls Shape `getStrokedShape` to create the Shape for pointer areas.  This is called in critical code -- while the user is dragging the curve.  Do you have any performance/responsivenes concerns about doing this in critical code?

**Comment by jonathanolson** [comment]
That could be a problem for performance, depending on the path size. Is it showing up as a problem on lower-performance devices, or in profiling?

Also unless the curve is set to pickable:false WHILE dragging, presumably any lazy approaches wouldn't work (since hit testing would actually test to see if the pointer is still over the curve).

**Comment by pixelzoom** [comment]
In Slack, @jonathanolson said:
> Let me know if I should look into potential alternatives that might be better for performance (probably depends on the specific use case here, I don't know how the curve can change)

The curve changes when the user drags it. See `new DragListener` in TransformedCurveNode.ts.

It feels sluggish even on my 2019 MacBook Pro, which is a relatively fast device. With `?profile`, I'm seeing 16-22fps while dragging.  So yes, I think we need to investigate how to improve this.

If I comment out this call to `setPointerAreas` in TransformedCurveNode:

```typescript
  protected override updateCurveNode(): void {
    super.updateCurveNode();
    // this.setPointerAreas();
  }
```

... then I can still grab the curve initially, and it still feels sluggish.  So it's possible that Shape `getStrokedShape` is not the primary/only contributor to the sluggishness.

**Comment by pixelzoom** [comment]
We should test the responsiveness of a built version, to see if assertions in critical code are impacting responsiveness.

**Comment by pixelzoom** [comment]
Over in https://github.com/phetsims/calculus-grapher/issues/210#issuecomment-1414362321, we decided to take an entirely different approach.  There will no longer be a pointer area that is matched to the curve shape.  So closing this issue.
