### ISSUE TITLE
Add private query parameter to set the edgeSlopeFactor to PEDESTAL curveManipulationMode

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#75]
The pedestal mode creates a smooth and continuous trapezoidal-shaped curve with rounded corners.
The rounded corners are set by a constant called edgeSlopeFactor.

Following the PhET Brand Design meeting, on 10/19, it would be useful to easily set different values to the rounded corner.
We will add a private query parameter, such that the designers can choose an optimal value.

**Comment by veillette** [comment]
For reference, here is the algorithm to set the pedestal

````
  /**
   * Creates a smooth and continuous trapezoidal-shaped curve with rounded corners.
   */
  public createPedestalAt( peak: Vector2 ): void {

    // width of the hill
    const width = this.curveManipulationWidth;

    const closestPoint = this.getClosestPointAt( peak.x );
    
    this.points.forEach( point => {
      let P;

      if ( Math.abs( point.x - closestPoint.x ) < width / 2 ) {
        P = 1;
      }
      else if ( point.x <= closestPoint.x ) {

        // use the square of a gaussian in order to have a very symmetric derivative at the edges
        P = Math.exp( -Math.pow( ( point.x - ( closestPoint.x - width / 2 ) ) / ( EDGE_SLOPE_FACTOR ), 4 ) );
      }
      else {
        P = Math.exp( -Math.pow( ( point.x - ( closestPoint.x + width / 2 ) ) / ( EDGE_SLOPE_FACTOR ), 4 ) );
      }

      point.y = P * peak.y + ( 1 - P ) * point.lastSavedY;
    } );

    // Signal that this Curve has changed.
    this.curveChangedEmitter.emit();
  }
````

**Comment by veillette** [comment]
The query parameter for the pedestal mode was added. 
Assigning to @amanda-phet and @kathy-phet to make you aware of the existence of this query parameter.

**Comment by pixelzoom** [comment]
One of the things that @amanda-phet @kathy-phet should consider is whether this should be a public query parameter (`public: true` in schema).  It's currently private, for internal use only.   My recommendation is to keep query parameters private unless they are requested, or unless they are related to a specifically-designed feature that you intended to be public.

**Comment by pixelzoom** [comment]
👍🏻 Great, sounds like you've already discuss public vs private.

**Comment by pixelzoom** [comment]
I think that @amanda-phet and @kathy-phet have had enough time to familiarize themselves with this query parameter ( > 1 month), so I'm going to close this issue.
