### ISSUE TITLE
How should curve manipulators behave as a curve is built up?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#77]
From https://github.com/phetsims/calculus-grapher/issues/49:

> - [ ] How should curve manipulators behave as a curve is built up using multiple manipulators? The Flash version has some unusual/inconsistent behavior.

@veillette FYI.

**Comment by amanda-phet** [comment]
This was discussed in the 10/10/22 design meeting, so I think we clarified it (especially in regards to the sine curve behavior). 

@veillette could you specify any open questions that are remaining for this issue?

**Comment by pixelzoom** [comment]
@veillette do you need any more info here? Or was this addressed sufficiently at design meeting?

**Comment by veillette** [comment]
We can close the issue. The last standing issue is with the Sine Function which is tracked in #85.  Closing
