### ISSUE TITLE
ExpandCollapse buttons for graphs

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#79]
I cant recall if we came to a conclusion about the expandCollapse buttons. 

The graphs take quite a bit of real estate such that the sim looks broken when two graphs are collapsed.
![Calculus Grapher screenshot (2)](https://user-images.githubusercontent.com/7633344/197810408-e628e374-5281-4d3a-b3d4-3844828bbc4d.png)

@amanda-phet 
Given that the we have an eye toggle for the curves, we perhaps can remove the expandCollapse buttons ?

**Comment by pixelzoom** [comment]
I like the idea of removing the expand/collapse buttons, and would start there, see how it feels. But if we do keep them, there should be a label to the right of each button when collapsed, to indicate the name of the graph that will be shown when "+" is pressed.

**Comment by amanda-phet** [comment]
We decided to try removing them, since as you say, we have the toggle button for the curves. And @pixelzoom is right that if we do use the expandCollapeButtons there would be a title when collapsed.

**Comment by veillette** [comment]
The expandCollapse button was removed in the previous commit.

**Comment by veillette** [comment]
In the process of removing the expand collapse button, I removed the graphContent node that the expand collapse button controlled. All the children can be directly attached to the GraphNode. Overall, this simplify the logic, and the meaning of GraphNode as a node with a graph is restored. CLosing
