### ISSUE TITLE
Reset for DerivativeCurve and IntegralCurve

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#82]
SInce DerivativeCurve and IntegralCurve are subordinate to the baseCurve, they should not have their own reset property.

**Comment by veillette** [comment]
The derivative and integral curve  classes throw an error when attempting to reset these classes. Closing.

**Comment by pixelzoom** [comment]
Reopening. I think I have a better idea.

1. Delete `reset` from Curve, DerivativeCurve, IntegralCurve

2. Change the implementation of OriginalCurve `reset` to:

```
  public override reset(): void {

    // Reset every CurvePoint to its initial state.
    this.points.forEach( point => {
      point.reset();
    } );

    // Signal once that this Curve has changed.
    this.curveChangedEmitter.emit();

    this.curveManipulationModeProperty.reset();
    this.curveManipulationWidthProperty.reset();
  }
```

**Comment by pixelzoom** [comment]
I would also consider factoring out `resetCurvePoints` in OriginalCurve, like this:

```  
private void resetCurvePoints() {

// Reset every CurvePoint to its initial state.
    this.points.forEach( point => {
      point.reset();
    } );

    // Signal once that this Curve has changed.
    this.curveChangedEmitter.emit();
}

public override reset(): void {
    this.resetCurvePoints();
    this.curveManipulationModeProperty.reset();
    this.curveManipulationWidthProperty.reset();
  }
```

**Comment by veillette** [comment]
The previous commit is unrelated to the above comments. I had mistakenly removed the calls for reset on the derivativeGraphNode, etc, instead of the model. The call for reset functions on the graphNode have been restored but removed from the calculusGrapherModel

```
  /**
   * Reset all
   */
  public reset(): void {
    this.originalCurve.reset();
  }
```

**Comment by veillette** [comment]
@pixelzoom : I agree with your comment. This is an improvement over our previous approach. 

I removed the reset functions from Curve, DerivativeCurve and OriginalCurve classes.  The originalCurve is the only class with a reset method.

```
   /**
   * Resets the OriginalCurve.
   * Called when the reset-all button is pressed.
   */
  public reset(): void {

    this.resetCurvePoints();

    this.curveManipulationModeProperty.reset();
    this.curveManipulationWidthProperty.reset();
  }


  // reset the curve points to their initial values
  private resetCurvePoints(): void {

    // Reset every CurvePoint to its initial state.
    this.points.forEach( point => point.reset() );

    // Signal once that this Curve has changed.
    this.curveChangedEmitter.emit();
  }

```

**Comment by veillette** [comment]
II think the work is done here. Closing.
