### ISSUE TITLE
PhET-iO: color of curves and studio tree

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#83]
The color of the curve strokes have been instrumented.

As you can see, all the colors of the curves appears under global/view/colorProfile .

![image](https://user-images.githubusercontent.com/7633344/198007882-1e82b8fc-6383-4f07-baad-b73a95b302e0.png)

While discussing the color profile with @pixelzoom, it occurred to us that it may be preferable to have a different hierarchy and link each color in studio under their respective curveNode.

On one hand, it may be more natural for the user to have a color directly under its curveNode, on the other hand it is convenient to have all the colors in the color profile, if you would like to retouch all of them.
 
Assigning to @amanda-phet.

**Comment by veillette** [comment]
Code snippet for myself in case we need to change the studio tree
````
// CurveNode.ts
const continuousLinePlotStrokeProperty = options.continuousLinePlotOptions.stroke as ProfileColorProperty;
assert && assert( continuousLinePlotStrokeProperty instanceof ProfileColorProperty );
this.addLinkedElement( continuousLinePlotStrokeProperty, {
  tandem: options.tandem.createTandem( 'continuousLinePlotStrokeProperty' )
} );
```

**Comment by amanda-phet** [comment]
Linked right there at derivativeScreen.view.graphsNode.integralGraphNode.curveNode seems perfect to me.

**Comment by veillette** [comment]
In the commit below I linked the colors linked to the curves in Studio in the view. In the studio hierarchy, they appear under their respective CurveNode.
![image](https://user-images.githubusercontent.com/7633344/205935378-f895194d-9b2c-4b38-a22b-dcf4f1fad67e.png)

**Comment by veillette** [comment]
Assigning to @amanda-phet to review and close if appropriate.

**Comment by amanda-phet** [comment]
Looks good to me.
