### ISSUE TITLE
Create content for "Simulation" tab of Preferences dialog

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#86]
We will need  to create a preference menu for CG.
We need to create a view node in CalculusGrapherPreferencesNode and, as a model counterpart, CalculusGrapherPreferences

The two will be invoked  in calculus-grapher-main.ts, as options to Sim:

```
    preferencesModel: {
      simulationOptions: {
        customPreferences: [ {
          createContent: tandem => new CalculusGrapherPreferencesNode( {
            tandem: tandem.createTandem( 'simPreferences' )
          } ),
          modelLinkables: [
            { property: CalculusGrapherPreferences.XXXProperty },
            { property: CalculusGrapherPreferences.XXXProperty }
          ]
        } ]
      }
    }
````

see GeometricOptics for an example.

**Comment by veillette** [comment]
As a first pass , we can will make numericalLabels public facing, and an option in preferences. 
it will show numerical labels based on a toggle button.

**Comment by pixelzoom** [comment]
This is not technically a menu.  It's content for the "Simulation" tab of the Preferences dialog. So I'll modify the title of this issue to prevent any confusion.

**Comment by pixelzoom** [comment]
> see GeometricOptics for an example.

Specifically, see GOPreferences.ts (model), GOPreferencesNode.ts (view), and `preferencesModel` in GOSim.ts.

**Comment by veillette** [comment]
The CG preferencesNode and its associated model have been created. At this point, it is pretty barebone, but it shows a onOffToggle switch that display the numericalLabels.

**Comment by pixelzoom** [comment]
@veillette this issue can likely be closed. Now that you have CalculusGrapherPreferences.ts and CalculusGrapherPreferencesNode.ts, futher work on Preferences will involve adding to those classes (and to CalculusGrapherQueryParameters.ts).

**Comment by veillette** [comment]
Closing this issue.
