### ISSUE TITLE
Numerical Values on x-axis

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#87]
MV currently has a query parameter (numericalLabels=true) to show some values on the graph. It currently adds tick mark values to the x and y axes. 
![Calculus Grapher screenshot (8)](https://user-images.githubusercontent.com/7633344/199331579-60539f95-c53b-4c9c-b928-0da8bd88fa47.png)

From the design document, it states that  Y-values need to move over to the y-axis.

For the x axis, the labels are on the y=0 line. 
- Do we want them at the bottom of the graph, like Fourier Transform?
- Do we want the x-labels on all the graphs, or just f(x)?

**Comment by amanda-phet** [comment]
> For the x axis, the labels are on the y=0 line.
> 
> Do we want them at the bottom of the graph, like Fourier Transform?

No. On the x-axis looks great to me. 

> Do we want the x-labels on all the graphs, or just f(x)?

All graphs is fine, since the provide a reference if someone isn't using the reference line.

**Comment by veillette** [comment]
The simulation stays as is. We can close this issue.
