### ISSUE TITLE
CT Assertion failed: cannot initialize twice

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#88]
```calculus-grapher : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667649902782/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1667649902782%22%2C%22timestamp%22%3A1667653408434%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: cannot initialize twice
Error: Assertion failed: cannot initialize twice
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667649902782/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:232:14)
at initializePhetioObject (Node.ts:6324:10)
at initializePhetioObject (Node.ts:6314:9)
at mutate (GraphNode.ts:240:9)
at (GraphsNode.ts:48:30)
at (CalculusGrapherScreenView.ts:77:22)
at (DerivativeScreenView.ts:29:4)
at (DerivativeScreen.ts:28:53)
at createView (Screen.ts:298:22)
id: Bayes Puppeteer
Snapshot from 11/5/2022, 8:05:02 AM
```

**Comment by pixelzoom** [comment]
This is one of the common pitfalls of using `mutate`.  In GraphNode.ts, you're processing options twice -- once via `super( options )`, once via `this.mutate( options )`.   And that causes `initializePhetioObject` to be called twice.

Relevant code in GraphNode.ts:

export default class GraphNode extends Node {
...
  public constructor( ... ) {
...
    super( options );
...
    this.mutate( options );
  }

**Comment by pixelzoom** [comment]
So... If you need to use `mutate`, take care to call `super()` instead of `super( options )`.   I generally prefer to avoid `mutate`, as most uses of it are unnecessary and inefficient (as you and I discussed recently).

**Comment by veillette** [comment]
I addressed the CT issue by removing the duplicate `this.mutate( options )`.
We discussed during our yesterday meeting the tradeoffs of using `super()` followed by `this.mutate(options)`  vs
`super(options)`

In this case, the instances of GraphNode are created and then layed out later, so there is no need to mutate their options field.  

We can close this since CT is now quiet.
