### ISSUE TITLE
Control Panel

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#89]
The control panel of the simulation has been mostly completed. The icons, slider and curveDisplay have been implemented.
I have yet to add the checkbox for the derivative and integral screens.

https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.3/phet/calculus-grapher_en_phet.html
In the meantime, can you take a look at the dev above and let me know if you have any comments 
about the look, behavior, or design of the control panel.

Assigning to @amanda-phet

**Comment by amanda-phet** [comment]
It is looking great! We will probably want to come back later and polish it, but one easy polish is to provide more space above the curve so it doesn't get clipped. Notice the top of this parabola isn't totally visible: 
![image](https://user-images.githubusercontent.com/7852916/200677612-4bb25102-0c8f-4d88-9fc6-df055a3d5a27.png)
It also looks like the bottom is getting clipped a bit:
![image](https://user-images.githubusercontent.com/7852916/200677950-1fdfdedc-a799-4621-bdc0-85cb83f052f2.png)


Once we have everything that will exist on the right-hand side of the screen we might want to adjust alignments and spacing. For example,I might want a little more spacing between the radio buttons, and the yellow buttons could also be a little smaller. 

Finally, could you left-align the grid and reference line checkboxes with the left edge of the control panel?

**Comment by veillette** [comment]
Thanks @amanda-phet .
There are several small changes here, most notably the maxY, minY value of the curve points, is smaller than the chartTransform, ensuring that the displayed curve is not clipped. 

Other changes are 
- left-align the grid and reference line checkboxes with the left edge
- make push buttons smaller
- make spacing between radio buttons larger 

Here is a screenshot.
![image](https://user-images.githubusercontent.com/7633344/200894719-56ba6db7-5472-446f-9eb4-d252929a6ec6.png)

One can check/test the (non) clipping behavior on master.

**Comment by amanda-phet** [comment]
Looks great! Thanks!

**Comment by amanda-phet** [comment]
I'll close this, since I think any future polishes can be done in another issue or in a meeting.
