### ISSUE TITLE
Numerical labels and zoom and eye toggle buttons

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#93]
![image](https://user-images.githubusercontent.com/7633344/201199025-1c7aed83-5b52-4d2a-b88c-41eea621aad4.png)

How should we align the zoom and eye toggle buttons when Numerical labels is turned on?

Three possibilities:
- The eye toggle and zoom buttons sit always at a fixed distance from the graphs,, allowing enough place to numerical labels (when visible) 
- The eye toggle and zoom buttons shift to the left when the visibility of the numerical labels is turned on.
- Other

**Comment by veillette** [comment]
We want the zoom and eye toggle to adjust depending on the presence/absence of numerical labels.

**Comment by veillette** [comment]
In the previous commit,  we have made the zoom button and eye toggle button move according to the setting of numerical Labels. 
Assigning to @amanda-phet  to review.

**Comment by amanda-phet** [comment]
This is working well for me.
