### ISSUE TITLE
Update colors

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/calculus-grapher#94]
@veillette can you update the colors to match these: 
![image](https://user-images.githubusercontent.com/7852916/201388350-7115c843-082f-464e-9d74-ed6a0675af0c.png)

background: F3FCFE
integral curve: 009245
f(x) curve: 0000FF
1st derivative curve: FF0000
2nd derivative curve: 662D91

I reviewed these for color-blindness and they are all working well to my eyes.

**Comment by veillette** [comment]
OK will do.

background: F3FCFE ->  rgb(243, 252, 254)
integral curve: 009245 -> rgb(0, 146, 69)
f(x) curve: 0000FF -> rgb(0, 0, 255)
1st derivative curve: FF0000 _> rgb(255, 0, 0)
2nd derivative curve: 662D91 -> rgb(102, 45, 145)

and #808080 -> rgb(128, 128, 128)

**Comment by pixelzoom** [comment]
@veillette note that you can use hex colors if you'd like, they are supported by scenery.

**Comment by veillette** [comment]
Thanks @pixelzoom .
 I updated the colors with rgb, but that's good to know that it is not necessary.

**Comment by veillette** [comment]
@amanda-phet 
I updated the colors for the curve strokes and background. 
I replaced the circle on the referenceLine by a blue shadedSphere 

I am not sure what you meant by the picture of the undoButton.
For your information, in CG,  the yellow buttons are using PhetColorScheme.BUTTON_YELLOW  which is Color( 254, 225, 5 ).
Let me know what color you would prefer to use.

**Comment by amanda-phet** [comment]
The undo button is fine, it is only there because I was putting all of the sim colors in one place. 

The rest of the colors look great, thank you!

**Comment by veillette** [comment]
Reopening, the predictCurveStroke has not been added yet.

**Comment by veillette** [comment]
I committed  the missing predict color stroke above and we will leverage it in #100. Closing.
