### ISSUE TITLE
Change width of graphs (model and view)

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#96]
The x Range for the model of the graphs should be from 0 to 36 instead of 0 to 40, as decided on the 11/10 design meeting. The view should scale accordingly.

**Comment by veillette** [comment]
Here is a screenshot of the result. The issue with #93 has not been addressed yet, but you can see that it gives us more leeway for the layout of the graph buttons.

![Calculus Grapher screenshot (12)](https://user-images.githubusercontent.com/7633344/201408884-7ed882da-75e6-459d-9aa0-eec7abda2f9f.png)

**Comment by veillette** [comment]
In the meantime, I addressed #93, so the layout of the buttons should be fixed as well. 

Assigning to @amanda-phet to review. Feel free to close.

**Comment by amanda-phet** [comment]
Looks good. Thanks!
