### ISSUE TITLE
New Feature: Tangent Line on Derivative Screen

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#97]
- Toggle to show tangent line on First Screen 
- Show a “scrubber” that could be dragged horizontally that moves the point of tangency 

![image](https://user-images.githubusercontent.com/7633344/201934440-66064721-46d5-4b88-bcc4-4f142a4a74f0.png)

Discussion: 

We like having a tangent line that is a set length, and discussed possibilities of curve (and tangent) being outside the graphing window 
The “slope of tangent” meter is nice for qualitative assessment of the tangent line, and even shows the point of inflection! 
Discussed color-coding options, and like having all things derivative-related, since each curve has an associate color. 

Should the “slope of tangent” meter be in an accordion box? 
Could be nice to hide this

Start the scrubber at the “center” of f(x) - whatever the middle x-value is

**Comment by veillette** [comment]
The work on the tangent line has been completed. Assigning to @amanda-phet  to review. 
FYI, I ended up changing the initial position of the scrubber to be slightly off center since it gets a bit busy if the cueing arrows are still visible in the center of the graph.

**Comment by amanda-phet** [comment]
This looks great to me! 

Should we use this issue to polish the accordion box? Or make a new one? 
![image](https://user-images.githubusercontent.com/7852916/210280111-fed0cb62-8ef9-424d-8107-0379d9bce040.png)

**Comment by veillette** [comment]
Since the accordion applies to both the Area Under the curve and the Tangent, I suggest that you open a new issue instead.

**Comment by amanda-phet** [comment]
Since this feature is in and working well, I think we can close it.
