### ISSUE TITLE
New Feature: Area under Curve for Integral Screen

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#99]
We will track the issue of are under the curve here.

![image](https://user-images.githubusercontent.com/7633344/201941629-5414a9c6-81ff-4caf-87e1-0a75c3921197.png)

![image](https://user-images.githubusercontent.com/7633344/201941738-c1f35dde-b137-4896-9dee-5ca8fab4270f.png)

The scrubber should start at zero.

**Comment by veillette** [comment]
All the work for this feature has been done in the previous commit.

![Calculus Grapher screenshot (20)](https://user-images.githubusercontent.com/7633344/209216574-d5b1314c-cf84-488f-ba58-a2215499d3b9.png)

At this point it would be useful if @amanda-phet could take look and give us some feedback on this feature.

**Comment by amanda-phet** [comment]
This seems to be functioning really well. I am wondering if the positive/negative measure bar (in the accordion box) could have a slightly larger range. Without doing much to the curve (in my opinion) I maxed out the positive area under the curve fairly easily. Hopefully that makes sense, what I am asking for!

**Comment by veillette** [comment]
Yes it make sense.  For the Area under the curve, the range of the barometer is  
```
      barometerModelYRange: new Range( -100, 100 )
```
To give you a context about the value,  If the original curve is at the maximum but yet visible, then its y-value i y=10, and since the range goes from 0 to 50, the "maximum" area would be 500.


I increased it by a factor of 3, in the commit below.
```
      barometerModelYRange: new Range( -300, 300 )
```

**Comment by veillette** [comment]
Assigning back to @amanda-phet (we may have to iterate a few times to find the sweet spot)

**Comment by veillette** [comment]
The barometer range was changed to -200, 200 following a request by @amanda-phet

**Comment by veillette** [comment]
@catherinecarter and @amanda-phet requested that the position of the Barometer be positioned relative to the original graph.
It should match at the top of original graph and have the same height as the graph.

**Comment by veillette** [comment]
In the previous commit, the scrubber line is set to have a linewidth of two. and opacity was added the shaded areas on original graph node.

In another commit (not tagged), the barometer top position was set to match the top of the original graph. It is a little bit difficult to set the height of the accordionBox to match the graph height in a robust way. Because of i18n, the  height of the title of the accordion box may vary, one cannot easily predict the actual height of the accordionBox. However, it is set to currently match the height of the graph for the English title.

**Comment by veillette** [comment]
I'll close this issue as the design team is familiar enough with this new feature. We can open separate issue (such as #175) on specific matter of Area under Curve.
